### ISSUE TITLE
Deploying on GlassFish Server

### ISSUE THREAD

**Issue by jduke99** [OHDSI/WebAPI#1]
I had a hard time getting this to deploy from NetBeans using the GlassFish server.   Looks like some conflicts with Jersey, according to this:

http://stackoverflow.com/questions/19868843/cant-deploy-war-to-glassfish-4

Are you using Tomcat to deploy I assume?

**Comment by fdefalco** [comment]
Yes, I'm deploying on Tomcat and honestly haven't the foggiest about deploying on GlassFish.  I'll close for now and if we get folks who want to deploy on GlassFish we can look into it further.
