### ISSUE TITLE
Connection timeout downloading maven dependencies

### ISSUE THREAD

**Issue by sprajapati86** [OHDSI/WebAPI#100]
I am trying to set up WebAPI through IntelliJ and getting below error while compiling.

[ERROR] Failed to execute goal on project WebAPI: Could not resolve dependencies for project org.ohdsi:WebAPI:war:1.0.0-SNAPSHOT: Failed to collect dependencies for [org.springframework.boot:spring-boot-starter:jar:1.2.1.RELEASE (compile), org.springframework.boot:spring-boot-starter-log4j:jar:1.2.1.RELEASE (compile), org.springframework.boot:spring-boot-starter-web:jar:1.2.1.RELEASE (compile), org.springframework.boot:spring-boot-starter-tomcat:jar:1.2.1.RELEASE (provided), org.springframework.batch:spring-batch-core:jar:3.0.3.RELEASE (compile), org.springframework.boot:spring-boot-starter-jdbc:jar:1.2.1.RELEASE (compile), org.springframework.boot:spring-boot-starter-jersey:jar:1.2.1.RELEASE (compile), org.springframework.boot:spring-boot-starter-data-jpa:jar:1.2.1.RELEASE (compile), javax.servlet:javax.servlet-api:jar:3.1.0 (provided), org.ohdsi.sql:SqlRender:jar:1.0.0-SNAPSHOT (compile), commons-dbutils:commons-dbutils:jar:1.6 (compile), commons-io:commons-io:jar:2.4 (compile), org.springframework.boot:spring-boot-starter-test:jar:1.2.1.RELEASE (test), org.apache.commons:commons-lang3:jar:3.3.2 (compile), org.flywaydb:flyway-core:jar:3.1 (compile), org.apache.httpcomponents:httpclient:jar:4.3.6 (compile), commons-httpclient:commons-httpclient:jar:3.1 (compile), org.springframework.batch:spring-batch-admin-manager:jar:2.0.0.M1 (compile), org.postgresql:postgresql:jar:9.4-1201-jdbc41 (compile)]: Failed to read artifact descriptor for org.ohdsi.sql:SqlRender:jar:1.0.0-SNAPSHOT: Could not transfer artifact org.ohdsi.sql:SqlRender:pom:1.0.0-SNAPSHOT from/to ohdsi (http://repo.ohdsi.org:8085/nexus/content/repositories/releases): Connect to repo.ohdsi.org:8085 [repo.ohdsi.org/52.0.148.6] failed: Connection timed out: connect -> [Help 1]

Is there any settings I need to do?

**Comment by chrisknoll** [comment]
I believe you experienced a possible system outage?  I went to the above URL directly and got a response. Could you try to open that link in your browser and see if you get a response?  If so, but your IDE still fails, it might be a proxy setting that you need to set (if you are behind a firewall)

**Comment by sprajapati86** [comment]
yes it's proxy issue. Thanks. It is resolved now.
