### ISSUE TITLE
Cohort 'Quick Reports' Condition Era returns no data for ageAtFirstDiagnosis, prevalenceByGenderAgeYear, prevalenceByMonth

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#1004]
### Expected Results
Clicking on a row form the Condition Era report that shows a prevalence of condition should display report data for age at first diagnosis, prevalence by gender-age-year and prevalence by month.

### Actual Results
Those collections in the results are empty arrays, causing the report data to show no data.

Screen capture of request:
![image](https://user-images.githubusercontent.com/6818777/55340393-938ce480-5472-11e9-9d16-fd1c1ab339fc.png)

Note that the prevalence shows 1,506 people (33%) have this condition, but there is no data in the aforementioned collections.

### Steps to reproduce
1. Create a cohort that will contain people, and generate.
2. On reporting tab, do a 'Quick Analysis'
3. Open condition Era report
4. Observe, table view shows condition eras with prevalence. Select one with > 10%
5. Observe the results from the /cohortResults endpoint for the concept ID yields no data in those fields.

**Comment by anthonysena** [comment]
@chrisknoll - I'm closing this as I believe it was addressed as part of https://github.com/OHDSI/Atlas/pull/1892 in the 2.7.2 release. If this persists, let's re-open and investigate. Thanks!
