### ISSUE TITLE
Generation of Utilization report failed for Netezza

### ISSUE THREAD

**Issue by spbima** [OHDSI/WebAPI#1014]
Generation of Utilization report failed for Netezza

![util-netezza-1](https://user-images.githubusercontent.com/804934/55470619-a5a48980-5610-11e9-987e-312eb2321f4f.jpg)

In Jobs list:
HERACLES_COHORT_28_Netezza53 | FAILED | mikhail.ivanko@odysseusinc.com | 04/03/2019 12:56 PM | 04/03/2019 12:59 PM

In log I see:
_nested exception is org.netezza.error.NzSQLException: ERROR:  Attribute 'CST1.PERSON_ID' not found_

Full log: [log-netezza.txt](https://github.com/OHDSI/WebAPI/files/3038076/log-netezza.txt)

**Comment by ssuvorov-fls** [comment]
database structure does not match current ddl-script from CommonDatamodel project
