### ISSUE TITLE
Documentation is missing figures

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/WebAPI#103]
I am trying to follow the instructions on how to setup PostgreSQL to deploy WebAPI

https://github.com/OHDSI/WebAPI/wiki/PostgreSQL-Installation-Guide

However all the figures are missing.

**Comment by chrisknoll** [comment]
These are just screenshots of the tools which I'd need to locate and update.  The detailed instructions, however, should give you the commands you need. In any case i'll make sure that these figures get uploaded, this is definitely an issue!

Thanks!

**Comment by jmbanda** [comment]
Hello,

I still continue to find the documentation lacking, as these steps are not really clear or point to non-existing fodlers/files. 

1) There is no settings_postgresql.xml file
2) Is the folder /WebAPIConfig/ supposed to be there or created by the user?
3) mvn clean package -s /WebAPIConfig/settings.xml fails since the /WebAPIConfig/settings.xml does not exist.

**Comment by chrisknoll** [comment]
Hi, @jmbanda ,
 Sorry for the shoddy state of the documentation.  It's an area that could use a lot of help from the community.  Your experience is very helpful to reveal those gaps so that improvements can be made.

To your points:
1) The section https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide#postgresql is misleading, calling for a modificaton of a 'settigns_postgresql.xml.  Instead, we should title this secton  'Create settings.xml file' and then it will be clear that the sample XML below belongs in a new file, and this file will be saved in /WebAPIConfig/ which is later referenced in the mvn build command.

I think clarifying 1 above makes 2 and 3 make more sense:  you create the settings.xml file, store it in a separate folder (the example is /WebAPIConfig/) and refer to the path to that file in the mvn command.

I'll make these changes to the documentation now.

**Comment by jmbanda** [comment]
Thanks for the changes!
I figured it out by reading through the pom.xml file. So I created the settings.xml file on a separate folder. I am taking notes on all my steps and will gladly contribute them for the instruction manual :)

Is this normal?

[INFO] MireDot: Completed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.848 s
[INFO] Finished at: 2016-05-19T10:17:40-07:00
[INFO] Final Memory: 66M/1727M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "{webapi-postgresql}" could not be activated because it does not exist.

I am going over the steps to get tomcat installed to deploy the built war file.

Thanks for the help!

**Comment by chrisknoll** [comment]
Hi, @jmbanda ,
  That warning is something that you should look into.  There's 2 places where the profile {webapi-postgresql} is referenced:
In pom.xml here:
https://github.com/OHDSI/WebAPI/blob/master/pom.xml#L385

This sets up the proper maven dependencies on the driver that should be used to connect to the database (for deployment purposes).  

In your custom-made settings.xml file (from the sample in the installation guide, the sample xml starts with this:
~~~ xml
<settings>
  <profiles>
    <profile>
      <id>webapi-postgresql</id>
      <properties>
...
      </properties> 
    </profile>  
  </profiles>
</settings>
~~~~

Finally, the mvn command refers to this profile ID that should exist in both the pom.xml and your settings.xml:
~~~
mvn clean package -s /WebAPIConfig/settings.xml -P {profile id}
~~~

Note: {profile id} is a placeholder, in your case it should be set to webapi-posgresql.

-Chris

**Comment by chrisknoll** [comment]
I would like to also add that the reason we made the instructions to create a settings.xml file in a different folder location is that you do not want to accidentally commit/push/make pull request your environment specific settings (with sekret pazzwords) into git.

**Comment by jmbanda** [comment]
So, should I change the pom.xml file in this section:

    <profile>
      <id>webapi-postgresql</id>
      <properties>
        <datasource.driverClassName>org.postgresql.Driver</datasource.driverClassName>
        <datasource.url>jdbc:postgresql://54.209.111.128:5432/vocabularyv5</datasource.url>
        <datasource.username>USER</datasource.username>
        <datasource.password>PASS</datasource.password>
        <datasource.dialect>postgresql</datasource.dialect>
        <datasource.ohdsi.schema>ohdsi</datasource.ohdsi.schema>
        <flyway.datasource.driverClassName>${datasource.driverClassName}</flyway.datasource.driverClassName>
        <flyway.datasource.url>${datasource.url}</flyway.datasource.url>
        <flyway.datasource.username>userWithWritesToOhdsiSchema</flyway.datasource.username>
        <flyway.datasource.password>PASS</flyway.datasource.password>
        <flyway.locations>classpath:db/migration/postgresql</flyway.locations>
      </properties>
    </profile>


To reflect my settings? i have the settings.xml file now with the proper settings, but it is still giving me the same warning.

**Comment by chrisknoll** [comment]
no, the pom.xml should be left unchanged.  All the settings you see in the pom.xml should have overriden values in your own settings.xml file. I'm not sure why it would say the requested profile does not exist. can you provide the exact mvn command you're executing?  I think it's critical that the spelling/case-sensitive of the profile ID must match exactly what's in pom.xml and your custom settings.xml.

**Comment by jmbanda** [comment]
Here is the maven command (and outputs)

[jmbanda@shahlab-dev3 WebAPI]$ mvn clean package -s ./WebAPIConfig/settings.xml -P {webapi-postgresql}
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building WebAPI 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ WebAPI ---
[INFO] Deleting /home/jmbanda/OHDSI/WebAPI/target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ WebAPI ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 256 resources
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ WebAPI ---
[INFO] Compiling 227 source files to /home/jmbanda/OHDSI/WebAPI/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ WebAPI ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ WebAPI ---
[INFO] Compiling 7 source files to /home/jmbanda/OHDSI/WebAPI/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.18.1:test (default-test) @ WebAPI ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-war-plugin:2.2:war (default-war) @ WebAPI ---
[INFO] Packaging webapp
[INFO] Assembling webapp [WebAPI] in [/home/jmbanda/OHDSI/WebAPI/target/WebAPI]
[INFO] Processing war project
[INFO] Copying webapp resources [/home/jmbanda/OHDSI/WebAPI/src/main/webapp]
[INFO] Webapp assembled in [6569 msecs]
[INFO] Building war: /home/jmbanda/OHDSI/WebAPI/target/WebAPI.war
[INFO]
[INFO] --- miredot-plugin:1.5.1:restdoc (default) @ WebAPI ---
[WARNING] Miredot is unable to document the status codes of rest interfaces, unless a statusCodes-block is specified in pom.xml
[INFO] Building reflective model of API and reading annotations...
[WARNING] Unknown annotation on service method: skipped @javax.transaction.Transactional(value=REQUIRED, rollbackOn=[], dontRollbackOn=[])
[WARNING] Unknown annotation on service method: skipped @javax.transaction.Transactional(value=REQUIRED, rollbackOn=[], dontRollbackOn=[])
[WARNING] Unknown annotation on service method: skipped @javax.annotation.PostConstruct()
[WARNING] Unknown annotation on service method: skipped @org.springframework.transaction.annotation.Transactional(rollbackFor=[], noRollbackFor=[], readOnly=true, rollbackForClassName=[], noRollbackForClassName=[], isolation=DEFAULT, value=, propagation=REQUIRED, timeout=-1)
[WARNING] Unknown annotation on service method: skipped @org.springframework.transaction.annotation.Transactional(rollbackFor=[], noRollbackFor=[], readOnly=false, rollbackForClassName=[], noRollbackForClassName=[], isolation=DEFAULT, value=, propagation=REQUIRED, timeout=-1)
[WARNING] Unknown annotation on service method: skipped @org.springframework.transaction.annotation.Transactional(rollbackFor=[], noRollbackFor=[], readOnly=false, rollbackForClassName=[], noRollbackForClassName=[], isolation=DEFAULT, value=, propagation=REQUIRED, timeout=-1)
[WARNING] Unknown annotation on service method: skipped @org.springframework.transaction.annotation.Transactional(rollbackFor=[], noRollbackFor=[], readOnly=true, rollbackForClassName=[], noRollbackForClassName=[], isolation=DEFAULT, value=, propagation=REQUIRED, timeout=-1)
[WARNING] Unknown annotation on service method: skipped @org.springframework.transaction.annotation.Transactional(rollbackFor=[], noRollbackFor=[], readOnly=false, rollbackForClassName=[], noRollbackForClassName=[], isolation=DEFAULT, value=, propagation=REQUIRED, timeout=-1)
[WARNING] Unknown annotation on service method: skipped @org.springframework.transaction.annotation.Transactional(rollbackFor=[], noRollbackFor=[], readOnly=false, rollbackForClassName=[], noRollbackForClassName=[], isolation=DEFAULT, value=, propagation=REQUIRED, timeout=-1)
[WARNING] Unknown annotation on service method: skipped @javax.transaction.Transactional(value=REQUIRED, rollbackOn=[], dontRollbackOn=[])
[WARNING] Unknown annotation on service method: skipped @javax.transaction.Transactional(value=REQUIRED, rollbackOn=[], dontRollbackOn=[])
[INFO] Built.
[INFO] Reading javadoc comments from sourcefiles...
[INFO] Read.
[INFO] Merging reflective and javadoc models...
[INFO] Merged.
[INFO] Performing issue analysis...
[INFO] Analysis done.
[INFO] Constructing Html documentation
[WARNING] Could not find html intro file file: miredot.htmlintro.html
[INFO] MireDot: Completed
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.808 s
[INFO] Finished at: 2016-05-19T10:44:35-07:00
[INFO] Final Memory: 51M/968M
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "{webapi-postgresql}" could not be activated because it does not exist.

Here is my settings.xml file contents:
<settings>
  <profiles>
    <profile>
      <id>webapi-postgresql</id>
      <properties>
        <datasource.driverClassName>org.postgresql.Driver</datasource.driverClassName>
        <datasource.url>jdbc:postgresql://localhost:5432/jmbanda</datasource.url>
        <datasource.username>*********</datasource.username>
        <datasource.password>*********</datasource.password>
        <datasource.dialect>postgresql</datasource.dialect>
        <datasource.ohdsi.schema>webapi</datasource.ohdsi.schema>
        <flyway.datasource.driverClassName>${datasource.driverClassName}</flyway.datasource.driverClassName>
        <flyway.datasource.url>${datasource.url}</flyway.datasource.url>
        <flyway.datasource.username>**********</flyway.datasource.username>
        <flyway.datasource.password>***********</flyway.datasource.password>
        <flyway.locations>classpath:db/migration/postgresql</flyway.locations>
      </properties>
    </profile>
  </profiles>
</settings>

**Comment by chrisknoll** [comment]
Yes, looks like you have {webapi-postgresql} on the command line when it should simply be webapi-postgresql (without curly braces).

**Comment by jmbanda** [comment]
Ok, got it to compile with no errors and warnings and it deploys properly. I have a question about this part of the instructions:

Configuration

Once the source code is built and the resulting libraries are deployed to your web environment the web.xml file needs to be updated for your specific environment

database.driver : this parameter specifies the class name of the driver for your database environment (ie com.microsoft.sqlserver.jdbc.SQLServerDriver)

database.url : this parameter specifies the connection string for your database environment

database.dialect this parameter specifies the dialect of your database environment and is used by the SQLRender library to translate the embedded templated queries to one of the supported dialects (SQL Server, Oracle, PostgreSQL, Amazon RedShift)
Testing

Is this needed? I seem to be able to get proper results get I do:

http://localhost:8080/WebAPI/source/sources

But for: 

http://localhost:8080/WebAPI/vocabulary/concept/0

I get a bunch of crap:
{"payload":{"cause":null,"stackTrace":[{"methodName":"run","fileName":"ServerRuntime.java","lineNumber":268,"className":"org.glassfish.jersey.server.ServerRuntime$1","nativeMethod":false},{"methodName":"call","fileName":"Errors.java","lineNumber":271,"className":"org.glassfish.jersey.internal.Errors$1","nativeMethod":false},{"methodName":"call","fileName":"Errors.java","lineNumber":267,"className":"org.glassfish.jersey.internal.Errors$1","nativeMethod":false},{"methodName":"process","fileName":"Errors.java","lineNumber":315,"className":"org.glassfish.jersey.internal.Errors","nativeMethod":false},{"methodName":"process","fileName":"Errors.java","lineNumber":297,"className":"org.glassfish.jersey.internal.Errors","nativeMethod":false},{"methodName":"process","fileName":"Errors.java","lineNumber":267,"className":"org.glassfish.jersey.internal.Errors","nativeMethod":false},{"methodName":"runInScope","fileName":"RequestScope.java","lineNumber":297,"className":"org.glassfish.jersey.process.internal.RequestScope","nativeMethod":false},{"methodName":"process","fileName":"ServerRuntime.java","lineNumber":254,"className":"org.glassfish.jersey.server.ServerRuntime","nativeMethod":false},{"methodName":"handle","fileName":"ApplicationHandler.java","lineNumber":1030,"className":"org.glassfish.jersey.server.ApplicationHandler","nativeMethod":false},{"methodName":"service","fileName":"WebComponent.java","lineNumber":377,"className":"org.glassfish.jersey.servlet.WebComponent","nativeMethod":false},{"methodName":"service","fileName":"ServletContainer.java","lineNumber":381,"className":"org.glassfish.jersey.servlet.ServletContainer","nativeMethod":false},{"methodName":"service","fileName":"ServletContainer.java","lineNumber":344,"className":"org.glassfish.jersey.servlet.ServletContainer","nativeMethod":false},{"methodName":"service","fileName":"ServletContainer.java","lineNumber":221,"className":"org.glassfish.jersey.servlet.ServletContainer","nativeMethod":false},{"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":292,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":207,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilter","fileName":"WsFilter.java","lineNumber":52,"className":"org.apache.tomcat.websocket.server.WsFilter","nativeMethod":false},{"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":240,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":207,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilterInternal","fileName":"HiddenHttpMethodFilter.java","lineNumber":77,"className":"org.springframework.web.filter.HiddenHttpMethodFilter","nativeMethod":false},{"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":107,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":240,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":207,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilterInternal","fileName":"RequestContextFilter.java","lineNumber":98,"className":"org.springframework.web.filter.RequestContextFilter","nativeMethod":false},{"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":107,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":240,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":207,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilterInternal","fileName":"CharacterEncodingFilter.java","lineNumber":88,"className":"org.springframework.web.filter.CharacterEncodingFilter","nativeMethod":false},{"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":107,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":240,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":207,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilter","fileName":"ErrorPageFilter.java","lineNumber":108,"className":"org.springframework.boot.context.web.ErrorPageFilter","nativeMethod":false},{"methodName":"access$000","fileName":"ErrorPageFilter.java","lineNumber":59,"className":"org.springframework.boot.context.web.ErrorPageFilter","nativeMethod":false},{"methodName":"doFilterInternal","fileName":"ErrorPageFilter.java","lineNumber":88,"className":"org.springframework.boot.context.web.ErrorPageFilter$1","nativeMethod":false},{"methodName":"doFilter","fileName":"OncePerRequestFilter.java","lineNumber":107,"className":"org.springframework.web.filter.OncePerRequestFilter","nativeMethod":false},{"methodName":"doFilter","fileName":"ErrorPageFilter.java","lineNumber":101,"className":"org.springframework.boot.context.web.ErrorPageFilter","nativeMethod":false},{"methodName":"internalDoFilter","fileName":"ApplicationFilterChain.java","lineNumber":240,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"doFilter","fileName":"ApplicationFilterChain.java","lineNumber":207,"className":"org.apache.catalina.core.ApplicationFilterChain","nativeMethod":false},{"methodName":"invoke","fileName":"StandardWrapperValve.java","lineNumber":212,"className":"org.apache.catalina.core.StandardWrapperValve","nativeMethod":false},{"methodName":"invoke","fileName":"StandardContextValve.java","lineNumber":106,"className":"org.apache.catalina.core.StandardContextValve","nativeMethod":false},{"methodName":"invoke","fileName":"AuthenticatorBase.java","lineNumber":502,"className":"org.apache.catalina.authenticator.AuthenticatorBase","nativeMethod":false},{"methodName":"invoke","fileName":"StandardHostValve.java","lineNumber":141,"className":"org.apache.catalina.core.StandardHostValve","nativeMethod":false},{"methodName":"invoke","fileName":"ErrorReportValve.java","lineNumber":79,"className":"org.apache.catalina.valves.ErrorReportValve","nativeMethod":false},{"methodName":"invoke","fileName":"AbstractAccessLogValve.java","lineNumber":616,"className":"org.apache.catalina.valves.AbstractAccessLogValve","nativeMethod":false},{"methodName":"invoke","fileName":"StandardEngineValve.java","lineNumber":88,"className":"org.apache.catalina.core.StandardEngineValve","nativeMethod":false},{"methodName":"service","fileName":"CoyoteAdapter.java","lineNumber":528,"className":"org.apache.catalina.connector.CoyoteAdapter","nativeMethod":false},{"methodName":"process","fileName":"AbstractHttp11Processor.java","lineNumber":1099,"className":"org.apache.coyote.http11.AbstractHttp11Processor","nativeMethod":false},{"methodName":"process","fileName":"AbstractProtocol.java","lineNumber":672,"className":"org.apache.coyote.AbstractProtocol$AbstractConnectionHandler","nativeMethod":false},{"methodName":"doRun","fileName":"NioEndpoint.java","lineNumber":1520,"className":"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor","nativeMethod":false},{"methodName":"run","fileName":"NioEndpoint.java","lineNumber":1476,"className":"org.apache.tomcat.util.net.NioEndpoint$SocketProcessor","nativeMethod":false},{"methodName":"runWorker","fileName":"ThreadPoolExecutor.java","lineNumber":1145,"className":"java.util.concurrent.ThreadPoolExecutor","nativeMethod":false},{"methodName":"run","fileName":"ThreadPoolExecutor.java","lineNumber":615,"className":"java.util.concurrent.ThreadPoolExecutor$Worker","nativeMethod":false},{"methodName":"run","fileName":"TaskThread.java","lineNumber":61,"className":"org.apache.tomcat.util.threads.TaskThread$WrappingRunnable","nativeMethod":false},{"methodName":"run","fileName":"Thread.java","lineNumber":745,"className":"java.lang.Thread","nativeMethod":false}],"response":{"context":{"headers":{},"entity":null,"entityType":null,"entityAnnotations":[],"entityStream":{"closed":false,"committed":false},"requestCookies":{},"acceptableLanguages":["*"],"responseCookies":{},"entityClass":null,"stringHeaders":{},"links":[],"allowedMethods":[],"entityTag":null,"acceptableMediaTypes":[{"type":"*","subtype":"*","parameters":{},"quality":1000,"wildcardType":true,"wildcardSubtype":true}],"mediaType":null,"date":null,"lastModified":null,"committed":false,"length":-1,"language":null,"location":null},"status":404,"stringHeaders":{},"metadata":{},"statusInfo":"NOT_FOUND","links":[],"allowedMethods":[],"entityTag":null,"entity":null,"mediaType":null,"date":null,"lastModified":null,"cookies":{},"length":-1,"language":null,"location":null,"headers":{}},"message":"HTTP 404 Not Found","localizedMessage":"HTTP 404 Not Found","suppressed":[]},"headers":{"timestamp":1463698184945,"id":"bfdc0b89-292d-82de-1444-ebe22cea3d84"}}

The same when I run Atlas, I can't seem to be able to get the vocabulary version correctly for any of my databases. (but this might be a different issue).

**Comment by chrisknoll** [comment]
Hi,
  No the main instructions on the readme.md should be cleaned up to remove those instructions since they are covered in the installation guide.  If you're up and running, you're up and running.

If this URL is coming back with results:
~~~
http://localhost:8080/WebAPI/source/sources
~~~

Then you can do a vocabulary lookup using one of the {sourceKey} from the above results like this:

````
http://localhost:8080/WebAPI/{sourceKey}/vocabulary/concept/0
````

The reason for this is that you could have multiple versions of a vocabulary set up, and this let's you choose which registered source with a vocabulary that you'd like to use.

**Comment by jmbanda** [comment]
Awesome! Thanks! 

I have it finally fully running. I added a small note in the documentation about the jdbc structure for postgresql servers which gave me the last headaches of the day.  Let me know if you want me to add/change any of the other steps I took, or make a separate forum post about it. 

Thanks!

**Comment by chrisknoll** [comment]
You can just post any amendments to the documentation here, i wish there was an easy way for people to contribute changes to the wiki pages. but I'll have to merge it in manually.

**Comment by chrisknoll** [comment]
Ah looks like you found the ways to edit wikis?  EZ-PZ.

**Comment by anthonysena** [comment]
Closing this issue noting that the WebAPI wiki content is now located here: https://github.com/OHDSI/WebAPI/wiki.
