### ISSUE TITLE
Can't delete or save changes cohort after import CC

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/WebAPI#1036]
## Expected behavior
After CC import, it is possible to modify / delete created cohort

## Actual behavior
After CC import, it is impossible to modify / delete generated cohort

## Steps to reproduce behavior
1. Create Characterization 
2. import json code

**Comment by anthonysena** [comment]
@NEONKID - this should be fixed with [WebAPI v2.7.2](https://github.com/OHDSI/WebAPI/releases/tag/v2.7.2). I'm going to close this out but please re-open if you see this issue persisting.
