### ISSUE TITLE
Invalid object name

### ISSUE THREAD

**Issue by pgallins** [OHDSI/WebAPI#1038]
I installed OHDSI/WebAPI using Microsoft SQL Server.   I can see table names like "dbo.cc_cohort" under the "OHDSI" database, but the tables are empty.

I am also having trouble running the Achilles analysis. I have these two R commands:

connectionDetails <- createConnectionDetails(dbms="sql server", server="localhost", user="ohdsi_app_user", password="app1", schema="OHDSI")

achilles(connectionDetails, cdmDatabaseSchema="OHDSI.dbo", cdmVersion=5)

I am getting this error:
ERROR Error: Error executing SQL:
com.microsoft.sqlserver.jdbc.SQLServerException: Invalid object name 'OHDSI.dbo.person'.

**Comment by chrisknoll** [comment]
Sorry for the confusion with the WebAPI database containing 'results schema' tables.

They were used as example tables and are not to be used.  What you would use to create your 'results' schema is found in /WebAPI/ddl/results.  Just access that URL and you will get the result scema.

Please see the wiki: https://github.com/OHDSI/WebAPI/wiki for configuration.

Re: achilles error:  is your CDM tables in a dtabase named 'OHDSI' and a schema of 'dbo'?

**Comment by pgallins** [comment]
Hey Chris,

Thank you for replying to my Github post.  I am really just hoping to
access the datasets used in this OHDSI paper.  How can I access them?

Thanks,
Paul

**Comment by chrisknoll** [comment]
Hi, @pgallins,  

This repo just contains the Java code that provides the Web Services for a few of the OHDSI tools.  Therea re no data-sets contained in this repo.
