### ISSUE TITLE
Request compressed results from Execution Engine

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#1043]
- Send request for execution with header `arachne-compressed` = `true`
- Expect zip file in a callback from EE and handle it properly

Branch out from 2.7.1 - I will move the tag after we merge it.

**Comment by chrisknoll** [comment]
Why not 2.7.2?

**Comment by pavgra** [comment]
This seems like a showstopper for PLE & PLP execution over big datasets: results are sent in a plain form which leads to both huge payload and the increasing possibility of facing web servers' limitations. Since this is the only critical issue which we discovered now in 2.7.1 and we'd like to get the official fix ASAP, I thought of moving the tag.
