### ISSUE TITLE
cohort-specfic report fails to show visualization on the Atlas reporting page

### ISSUE THREAD

**Issue by leeevans** [OHDSI/WebAPI#106]
This is because the table qualifier "@ohdsi_database_schema." is missing from the first reference to heracles_table in this SQL:

https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cohortresults/sql/cohortSpecific/personsInCohortFromCohortStartToEnd.sql

**Comment by chrisknoll** [comment]
Thanks for pointing this out, Lee. I pushed a fix to master, and will be part of the next official release.

**Comment by leeevans** [comment]
Thanks Chris!
