### ISSUE TITLE
OpenSSL and WebAPI, 401 unauthorized

### ISSUE THREAD

**Issue by ambuj369** [OHDSI/WebAPI#1085]
Hello,

I am trying to add security to OHDSI applications using OpenSSL method and using self signed certificate for the same.Tomcat homepage gets open without issues, but WebAPI/source/sources shows error, however, WebAPI/ddl/results shows the ddl for results schema.
I am attaching the settings.xml for WebAPI and screenshot with the errors.

Please confirm if there is something which is missed or wrong with my configuration. 

Feel free to ask if I missed anything here.
![Screenshot from 2019-05-13 13-03-28](https://user-images.githubusercontent.com/47858365/57603505-8a1d8e80-757f-11e9-9062-485496957061.png)
![Screenshot from 2019-05-13 13-07-06](https://user-images.githubusercontent.com/47858365/57603707-fe583200-757f-11e9-89be-e71777362682.png)
![Screenshot from 2019-05-13 15-08-32](https://user-images.githubusercontent.com/47858365/57611647-f6ed5480-7590-11e9-85d2-5bf4e804e2a6.png)

**Comment by fgiesen** [comment]
Hi, 

We had the same issue while deploying. This could be solved by clearing your browser data.

Hope it helps,
Florence

**Comment by ambuj369** [comment]
Hi Florence,

I figured it out ; in settings.xml, I used <security.provider> as DisabledSecurity as I was only using it for SSL connection and not for advance security set up for Active Directory/LDAP.

I will be doing that in next phase and I will post further if any issue comes up.

-Ambuj
