### ISSUE TITLE
Broken import of PLP, PLE, CC, Pathway

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/WebAPI#1100]
Steps to reproduce:
try to import PLP from attached file

Expected result:
PLP is imported

Actual result:
![image](https://user-images.githubusercontent.com/38942654/58020578-2eb84700-7b11-11e9-9775-aa6cc0984ae2.png)

the reason is -- lack of db migration which updates `CohortExpression` according to appearance `cdmVersionRange` field
hashcodes of persisted `CohortExpression` and incoming one are different, so `DesignImportService#findCohortByExpressionHashcodeAndPredicate` can't find already existing entity
[broken PLP.txt](https://github.com/OHDSI/WebAPI/files/3197830/broken.PLP.txt)

**Comment by chrisknoll** [comment]
Question for you:

If the imported cohort definition hashes differently from the existing cohort definition (since the imported cohort definition will hash based on the `cdmVersionRange`, while the existing one did not) why doesn't that just result in a new cohort definition being imported?  And why does this result in a duplicate name error (from your screenshot)?

**Comment by pavgra** [comment]
> why doesn't that just result in a new cohort definition being imported

Because there is already a cohort definition in DB having the same name as the imported cohort

**Comment by chrisknoll** [comment]
> Because there is already a cohort definition in DB having the same name as the imported cohort

Ok, so if you have 2 different characterizations containing cohorts that have the same names (let's say, CC1 and CC2 both have a cohort called 'Cancer' but cancer is defined differently (ie: different hash)), will there be a problem importing CC1 (where the cohort is new and Cancer doesn't exist yet) and CC2 is imported (where now there is an existing cohort named 'Cancer' but has a different hash)?

**Comment by aklochkova** [comment]
@chrisknoll yes, there will be a problem in this case because we will not find the 'Cancer' cohort with different hash and when we try to add this cohort the unique name constraint will raise

**Comment by pavgra** [comment]
Since the hash is calculated based on the design field (so the cohorts actually differ) it would be reasonable to alter the name of the imported cohort to avoid clashes, e.g. "Cancer" -> "Cancer (1)"

**Comment by chrisknoll** [comment]
Yes, that's what I'm getting at: I believe the original problem was that the import resulted in a clash, which needs to be resolved (find a unique cohort name).  I don't think the hash DB migration is actually necessary to fix this issue: the cohort should have been imported with a new name (since it didn't match any existing cohort definition hashes).  However, the DB migration will allow newly imported designs to match to existing cohorts because the import 'injects' a `cdmVersionRange` value into the payload.

I strongly feel that the serialize/desalinize operation leading to an injection of values into the payload is problematic:  it is not obvious in the code that serialization would lead to a change in the serialized data.  If you looked at the raw expression that was imported in the import, and compared it to the raw expression that was saved in the database, you would expect that they would match each other. But because serialize injects a cdmVersionRange, it leads to confusion.

**Comment by anthonysena** [comment]
I'm re-opening this issue - the PR that closed this didn't fully address the problem from my testing.

While the migration handles the inclusion of the `cdmVersionRange`, we are still faced with the problem that if we attempt to import the same asset, with the same name again, things fail. I've attached this 
[ple-example-for-import.txt](https://github.com/OHDSI/WebAPI/files/3204066/ple-example-for-import.txt). 

Here are the steps to recreate the problem:

1. Import the PLE study. Assuming that works...
2. Import it again. In my environment, I get the following error:

```
2019-05-21 15:04:49.521 WARN http-nio-8080-exec-4 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - SQL Error: 0, SQLState: 23505
2019-05-21 15:04:49.522 ERROR http-nio-8080-exec-4 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - ERROR: duplicate key value violates unique constraint "uq_cs_name"
  Detail: Key (concept_set_name)=(Negative controls for hypertension drugs) already exists.
```

The import process will need to ensure a unique name for concept sets, cohort definitions, feature analyses, pathways, prediction and estimation designs to avoid this problem.

**Comment by aklochkova** [comment]
@anthonysena I forgot to warn that I haven't finished the PR (https://github.com/OHDSI/WebAPI/pull/1103) yet

**Comment by anthonysena** [comment]
@aklochkova - my apologies. I'll check with you and @pavgra next time before merging in changes like that. Hope this doesn't cause extra work.

**Comment by aklochkova** [comment]
@anthonysena don't worry, thank you : )

**Comment by aklochkova** [comment]
I checked the following test cases:

entity = Concept Set / Cohort Definition / CC / Pathway / IR / Estimation / Prediction

**1. Warning about name uniqueness**
1) create entity with name "New test entity"
2) create entity with the same name as in p.1
   ER: warning about name uniqueness is raised

**2. Usual copy**
1) create entity with name "New test entity"
2) create copy of it
   ER: entity wih suffix "COPY OF:" is created

**3. Copy of copy**
1) create entity with name "New test entity"
2) create copy of it
3) create copy of entity from p.2
   ER: entity with suffix "COPY OF: COPY OF:" is created

**4. Several copies of original entity**
1) create entity with name "New test entity"
2) create copy of it
3) create copy of entity from p.1
   ER: entity with suffix "COPY OF:" is created
       entity with suffix "COPY OF:" and postfix "(1)" is created

**5. Import with the same name**
1) create entity with name "New test entity"
2) export it and import
3) export entity from p.1 and import
   ER: entity with name "New test entity (1)" is created
       entity with name "New test entity (2)" is created

**6. Import when entity with this name already exists**
1) create entity with name "New test entity"
2) create entity with name "New test entity (1)"
3) export entity from p.1 and import it
4) create entity with name "New test entity (1) (1) (1)"
5) export entity from p.4 and import it
   ER: entity with name "New test entity (2)" is created
       entity with name "New test entity (4)" is created

**7. Import PLE when hashcodes of nested CS's & CD's are different**
1) import Estimation entity "Comparative effectiveness of ACE inhibitors vs Thiazide diuretics as first-line monotherapy for hypertension" ([ple-example-for-import.txt](https://github.com/OHDSI/WebAPI/files/3227480/ple-example-for-import.txt))
2) change hashcodes of nested Cohort Definitions
3) import Estimation again
   ER: Estimation is imported with postfix (1);
       new Cohort Definitions & Concept Sets are created and nested

**8. Import with unique name**
1) import entity with unique name
   ER: entity is imported

**Comment by pavgra** [comment]
@aklochkova , the list of test cases look cool and, I think, it would be really awesome if we could transform it into a junit test class. That would be a nice example of how issues should be handled and would be a great step to the more solid Atlas. Would you mind doing this?

**Comment by aklochkova** [comment]
as a result of this task the following properties were added to `pom.xml`: 
`<skipUnitTests>true</skipUnitTests>`
`<skipITtests>true</skipITtests>`

All integration tests were fixed, unit tests are needed to be fixed in another task
