### ISSUE TITLE
Unique constraint application in SQL Server

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#1105]
Per @aklochkova's detailed comment here: https://github.com/OHDSI/WebAPI/pull/1073#issuecomment-493748843, the update made to the SQL Server migration script that enforces unique names for various entities in WebAPI can potentially fail.

The changes I made for SQL Server as part of that pull request stemmed from the fact that creating, executing and then dropping stored procedures on SQL 2012 was failing in our environment. Instead, I revised that migration to use a set of UPDATE statements which works with the exception that @aklochkova described. 

For simplicity: I'd propose we revise the script so that instead of attempt to rename entities with a sequence number (i.e. adding a "(1)", "(2)", etc to the end of the entity name), we instead use the primary key from the table as the suffix. While this doesn't completely address the edge-case that @aklochkova described, I would expect that this would allow things to work 99% of the time.

**Comment by anthonysena** [comment]
Closed via #1106.

**Comment by anthonysena** [comment]
After re-testing in our environment, there are still some fixes related to SQL Server that need to be applied. I'll put in a PR for this issue shortly.

**Comment by anthonysena** [comment]
Root cause of the issues I faced: inside of the stored procedures for SQL Server:

https://github.com/OHDSI/WebAPI/blob/v2.7.2-rc/src/main/resources/db/migration/sqlserver/V2.8.0.20190424150601__add-unique-name-constraint-to-entities.sql#L5

The `duplicate_name` declarations in this script are `varchar(100)` while the target tables name field uses a `varchar(255)`. What happens when the script executes is that it cannot create a unique name if the cohort name is greater than 100 characters and things get stuck in an infinite loop. I'm adjusting the SQL script to use varchar(255) and this fixes the issues in our environment.

Doing some additional digging on this, I noticed that the Oracle script also appears to use a varchar(100) approach:

https://github.com/OHDSI/WebAPI/blob/v2.7.2-rc/src/main/resources/db/migration/oracle/V2.8.0.20190424150601__add-unique-name-constraint-to-entities.sql#L5

I'm thinking this should also be adjusted but wanted to confirm with @aklochkova @pavgra before also modifying that script. Please let me know and I can make this change with the PR I'll be filing shortly. Thanks!

**Comment by chrisknoll** [comment]
Good catch, @anthonysena.  The field that captures the duplicate names should be at least the size of the column that stores the names of the entities that we are trying to de-dupe.  I worry about an edge case where if there are 2 cohorts that are same names that are 255 chars, we will run into an infinite loop where we are unable to put the postfix of 1..2..3 after the names (because the name is already 255 length).

Perhaps the solution is to `LEFT` up to 250 characters in the title and then de-dupe based on the first 250 characters (thus leaving 5 characters to add the postfix...and maybe 250 is generous, maybe we can read up to 253 and leave 2 chars for suffix (leaving up to 99 duplicate names of 253 length (probably very unlikely to happen).

-Chris

**Comment by pavgra** [comment]
@anthonysena , would be great if you could apply the same fix to Oracle

**Comment by aklochkova** [comment]
@anthonysena, hi, I approve

**Comment by anthonysena** [comment]
@pavgra and @aklochkova for confirming.

@chrisknoll you raise an excellent point - this is also an edge case that could bite us. Looking in our environment though, when I look at the entities with duplicate names, the maximum length I see is 171 characters. 

While I support the approach you proposed of using a `LEFT` operation on the entity name, I am not sure how easily this is done across the 3 dialects since this particular migration has slightly different approaches for each dialect. Also, I'm not sure how many people in the community will face this potential issue. Let me file a PR where I do not adopt the `LEFT` approach and perhaps we can further discuss it there?

Just want to note it in case others face a challenge with the `V2.8.0.20190424150601__add-unique-name-constraint-to-entities` migration stuck for a very long time.

**Comment by chrisknoll** [comment]
I agree, the odds that you have 2 cohorts with names exactly 255 chars long is really slim (unless someone forced the issue, at which point could be to modify the offending cohort names manually and then let the migration execute again).

So, put it under 'known limitation' but go with the main fix that the dupe_name column should be specified to be the same type (varchar(255)) as the entity names.

**Comment by anthonysena** [comment]
Fair enough - thanks @chrisknoll. I've filed that PR as mentioned earlier and let me make a note of this known limitation in the draft release notes. Thanks!
