### ISSUE TITLE
how to make WebApi use another SqlRender

### ISSUE THREAD

**Issue by hajarhomayouni** [OHDSI/WebAPI#111]
Hi,

I have implemented a sample SqlRender that supports other dbms, Now I want to make WebApi use mine instead of OHDSI's. How can I do this?

**Comment by chrisknoll** [comment]
You'll need to override the dependency on this line:
https://github.com/OHDSI/WebAPI/blob/master/pom.xml#L293

You'll have to look into maven and providing overrides to dependencies, as I've not done this myself.
