### ISSUE TITLE
Negative results in Cohort Characterisation

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1110]
Why do we use negative numbers for Cohort Characterization jobs?

![image](https://user-images.githubusercontent.com/4144173/58097976-43fca680-7be1-11e9-9c5f-aee2c3f9b8c9.png)

**Comment by chrisknoll** [comment]
I believe that is a hash value, we don't have any direct control over what the hash is generating, we just show the value (so you can reference it against other design executions and determine the difference). You're not able to know what the actual difference is based on the hash value, only that there is a difference between them.

**Comment by pavgra** [comment]
I suggest just prettifying the hashes to something more human-readable like `V1`, `V2`, etc. So to do the following transformation at UI:

333333 --> V4
123123 --> V1
789789 --> V3
456456 --> V2
123123 --> V1

**Comment by anthonysena** [comment]
@pavgra - this was closed for 2.7.2 but we have a PR open that is linked to this issue. So, I'm going to re-open this issue and note it for 2.8 but perhaps this warrants a separate issue for the remaining PR instead of linking to this one?
