### ISSUE TITLE
Reports - Dashboard fails in Impala

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1144]
`errorMessage:AnalysisException: Incompatible return types 'STRING' and 'SMALLINT' of exprs 'c1.concept_id' and '8507'.↵), Query: SELECT↵  c1.concept_id   AS conceptId,↵  c1.concept_name AS conceptName,↵  ar1.count_value AS countValue↵FROM omop_results.achilles_results ar1↵INNER JOIN↵_omop_20183.concept c1↵ON ar1.stratum_1 = CAST(c1.concept_id AS VARCHAR(255))↵WHERE ar1.analysis_id = 2↵AND c1.concept_id IN (8507, 8532)."`

1. Needs casts
2. Heracles needs fix too

**Comment by wivern** [comment]
Could not reproduce on our environment
![b9bd0bda-e5cc-4fc2-be92-8a8fb3a0f573](https://user-images.githubusercontent.com/1109753/58585415-528e3200-8261-11e9-91b7-73dfc9beac94.png)

**Comment by konstjar** [comment]
The issue related to wrong time of fields in CDM database. Closing
