### ISSUE TITLE
AD groups import fails

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1155]
We met a problem with AD groups mapping and users import process. When import job started, it fails with this error:
![image](https://user-images.githubusercontent.com/4144173/58710135-538ba480-83c4-11e9-8930-bff620e69680.png)

The proposal is to change type of the field like this:
alter table webapi.batch_job_execution_params alter string_val type VARCHAR;

**Comment by pavgra** [comment]
As discussed with @anthonysena and @chrisknoll , let's store AD import properties in a separate table as we do this for CC, Pathways, etc

**Comment by ssuvorov-fls** [comment]
pr to master was updated
pr to 2.7.2 was closed
new pr to 2.7.5 was created
