### ISSUE TITLE
Results DDL script generation for postgres ignoring parameters

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WebAPI#1167]
[These instructions](https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration#results-schema-setup) on the wiki mention several parameters for the results DDL:
`/ddl/results?dialect=<your_cdm_database_dialect>&vocab=<your_vocab_schema>&results=<your_results_schema>&initConceptHierarchy=true&tempSchema=<your_temp_schema>`

However, when I input for dialect `postgresql`, it ignores all the schema parameters and will just put `result` and `vocab` as schema. Snippet from the result:
```sql
CREATE TABLE IF NOT EXISTS results.cohort
 (COHORT_DEFINITION_ID int NOT NULL,
	SUBJECT_ID bigint NOT NULL,
	cohort_start_date date NOT NULL,
	cohort_end_date date NOT NULL
);


CREATE TABLE IF NOT EXISTS results.cohort_features
 (cohort_definition_id bigint,
  covariate_id bigint, 
....
```

**Comment by anthonysena** [comment]
Hi @MaximMoinat - sorry for the trouble there. I made a mistake when translating the query parameters from the underlying function call so I'll update the documentation. Instead, could you try:

`/ddl/results?dialect=<your_cdm_database_dialect>&schema=<your_results_schema>&vocabSchema=<your_vocab_schema>&tempSchema=<your_temp_schema>&initConceptHierarchy=true`

Not that in the current wiki docs, the parameter `vocab `should be `vocabSchema` while `results` should be `schema`.

**Comment by anthonysena** [comment]
We've updated the wiki to correct this error - thanks for catching that mistake!
