### ISSUE TITLE
Add support for sources using Hive LLAP

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#1168]
- New profile in POM to install required drivers
- New database type in Configuration -> Source
- New dialect tab in Cohort Definition
- All existing features should work properly for Source with DB type = Hive LLAP
- Add new cases into DataSourceDTOParserTest

**Comment by anthonysena** [comment]
Linking this to OHDSI/SqlRender#173 related to Hive support with SqlRender
