### ISSUE TITLE
mvn clean package -s /WebAPIConfig/settings.xml -P {profile id} returns an error

### ISSUE THREAD

**Issue by don-torok** [OHDSI/WebAPI#117]
Installation guide says to run 'mvn clean package -s /WebAPIConfig/settings.xml -P {profile id}'

returns The specified user settings file does not exist: C:\WebAPIConfig\settings.xml
and there is no explanation of where the profile id is suppose to be.

**Comment by t-abdul-basser** [comment]
{profile id} refers to one of the database-specific profiles mentioned in the WebAPI [installation docs](https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide): 'webapi-postgresql', 'webapi-mssql' or 'webapi-oracle'.

**Comment by don-torok** [comment]
Thanks, I missed that for the profile.  But if I use
-s/WebAPIConfig/settings.xml, per the documentation, I get an error that
the setting file does not exist.  But if run 'mvn clean package -P
webapi-postgresql' then the maven runs using the pom.xml file.  My
assumption is that the documentation is incorrect.


On Fri, Jul 29, 2016 at 5:36 PM, Taha Abdul-Basser <notifications@github.com

**Comment by chrisknoll** [comment]
Hi, @don-torok ,
  The documentation says to create a settings.xml file. Did you create this file?  The documentation further describes that the file created in the example will be saved in /WebAPIConfig/settings.xml and will be referred to in the "building the .war file section".  If you saved it in a different location, you will naturally need to change the path to the location that you saved the settings.xml file.

For clarity, could you briefly summarize which steps of the installation guide you've performed?

**Comment by chrisknoll** [comment]
@don-torok , I'm also trying to make sure that the documentation is clear, but I'm confused by your statement that "there is no explanation of where the profile id is supposed to be."  Immediately after the maven command you tried to execute is this text:

> mvn clean package -s /WebAPIConfig/settings.xml -P {profile id}
> This will create the file WebAPI.war in the target subfolder. Note: {profile id} is set to the value of the profile ID from the example configuration. The valid values for this are 'webapi-postgresql', 'webapi-mssql' or 'webapi-oracle'. Use the proper profile id for your database environment.
> 

Could you help me by offering a suggestion that would make the setting of {profile id} more clear?

**Comment by don-torok** [comment]
My error on the the profile id, for not reading instructions close enough.

As per the settings file, you might add the following

WebAPI Configuration

Each database platform will have their own JDBC driver class name and
connection string URL. *These database specific setting are recorded in the
/WebAPIConfig/settings.xml *  The following sections describes how the
settings files should be configured for PostgreSQL, MSSql and Oracle to
connect to the DB server.


You might also have a sample setting.xml file.  I went looking for the file
and not finding it, looked at the pom.xml file and saw a section with the
<id> webapi-postgresql </id>.  That made me think that the documentation
was incorrect and that those examples were referencing the various sections
in the pom file.  Also, the directory for the setting file, /WebAPIConfig,
it seem strange to create a top level directory for a single file.

I know it is difficult writing user documentation when your audience is so
varied and appreciate your effort.

**Comment by chrisknoll** [comment]
Thanks, @don-torok .  There's a reason the pom.xml elements you saw match the elements in the settings.xml file: the settings.xml file overrides those values in the POM.xml.  I think that I need to add some information that the purpose of creating the settings.xml file: to override the values found in the POM.xml, but these overriding values are in a separate file so that sensitive information (databaes usernames/passwords) are not stored in the POM.xml.  

Thanks for your feedback on this, you are right it's hard getting one document to fit everyone's needs but we're getting there!
