### ISSUE TITLE
Vocabulary endpoints for concept ancestor

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#1170]
Per @cgreich's advice here https://github.com/OHDSI/Atlas/issues/1752#issuecomment-497987657:

> A single level of separation could be constructed through a string of more than one CONCEPT_RELATIONSHIP record. That happens because only the standard concepts count. So, you can have a chain standard - relationship - non-standard - relationship - standard. In the CONCEPT_ANCESTOR, it would still make a single level of separation.
> 
> There are lateral relationships that don't increment the level of separation. That way, Clinical Drug and Branded Drug have levels of separation=0.
> 
> So, trust the CONCEPT_ANCESTOR logic. Don't try to double-guess it. If there is a mistake complain.

For the hierarchy functionality in ATLAS, it may be best to use solely the CONCEPT_ANCESTOR table as suggested which would require an additional REST end-point to query it. Likely the signature would be for a single concept ID, it would then query CONCEPT_ANCESTOR to determine all ancestors/descendants - similar to the subset of this query: [getRelatedConcepts.sql](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/vocabulary/sql/getRelatedConcepts.sql):

```
select ANCESTOR_CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, c.VOCABULARY_ID, 'Has ancestor of' , MIN_LEVELS_OF_SEPARATION RELATIONSHIP_DISTANCE  
    from @CDM_schema.concept_ancestor ca
    join @CDM_schema.concept c on c.CONCEPT_ID = ca.ANCESTOR_CONCEPT_ID
    where DESCENDANT_CONCEPT_ID = @id
    and ANCESTOR_CONCEPT_ID <> @id
union 
select DESCENDANT_CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, c.VOCABULARY_ID, 'Has descendant of' , MIN_LEVELS_OF_SEPARATION RELATIONSHIP_DISTANCE  
    from @CDM_schema.concept_ancestor ca
    join @CDM_schema.concept c on c.CONCEPT_ID = ca.DESCENDANT_CONCEPT_ID
    where ANCESTOR_CONCEPT_ID = @id
    and DESCENDANT_CONCEPT_ID <> @id
```

**Comment by anthonysena** [comment]
Linking to OHDSI/Atlas#2042 as it may be easiest to implement this new endpoint and then update tab behavior at the same time.

**Comment by KSadomtsev** [comment]
/WebAPI/vocabulary/*/concept/*/ancestorAndDescendant

Status Code: 200 

![image](https://user-images.githubusercontent.com/56290675/99247178-a1de6e80-2817-11eb-8c58-340303ba2567.png)

verified
