### ISSUE TITLE
getConceptRecordCount fails - exceeds max params for RDBMS

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#1176]
## Scenario

Attempt to get the record counts for a [large_list_of_concepts.txt](https://github.com/OHDSI/WebAPI/files/3262141/large_list_of_concepts.txt) (>5000) using the REST endpoint:

`WebAPI/cdmresults/<source_key>/conceptRecordCount`

### Expected result

The list is returned with record counts from the `<source_key>`

### Actual result

An exception is thrown:

`The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.`

### Analysis

Since the @conceptIdentifiers parameter in the query https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/getConceptRecordCount.sql is repeated twice, we'll need to properly chunk up the list of concepts to ensure we don't exceed the max DB limit.

**Comment by anthonysena** [comment]
Also worth noting: this occurred on a source where the record counts are not cached at startup.

**Comment by chrisknoll** [comment]
I'd like to suggest that in cases where we're doing in() clauses for paramaterization, we don't actually make individual prepared statement paramaters, and instead we do the sql-replacement.  This sounds like sql injection risk, but the in() clasues will be arrays of integers, and you can't sql inject from an array of integers, so it should be safe.

Chunking the query will work, but it's a solution that's very limited: if you had a query that looked like this:

```
select *
from Table1 t1
join table2 t2 on t1.a = t2.a
join table3 t3 on t1.b=t3.b
where t1.col1 in (...5000 params...)
and t2.col1 in (..another 5000 params...)
and t3.col1 in (...another 5000 params...)
```

I'm not sure how chunking can be done in the above query to ensure you will actually find all the records.  In the context of this issue, tho, the query is failry simple `select * from concept where concept_id in (....params...). This could be chunked and concatenated across multiple queries.

**Comment by anthonysena** [comment]
Thanks @chrisknoll for that point. Yes, I think in the example you have mentioned, chunking is not possible so my proposed solution of breaking up a single parameter would not work. Ideally we should avoid IN clauses wherever possible and in the case that you've illustrated here, we'd have to think about a SQL replacement approach instead.

For the purposes of this issue, my plan is to identify where we are doing this type of "chunking" to ensure that the underlying queries do not require further division of the list of parameters to ensure we remain under the RDBMS enforced parameter limit.
