### ISSUE TITLE
Error when calculating Estimation

### ISSUE THREAD

**Issue by wivern** [OHDSI/WebAPI#1184]
Not sure this is a bug, but Estimation failed with SQL error. Same error was when not concepts attached to cohort, but not this time. All cohorts included to Estimation analysis has at least one concept set attached.

Error message:
`Error executing query job. Message: Syntax error: Unexpected ")" at [4:32]`

[estimation.json.zip](https://github.com/OHDSI/WebAPI/files/3265848/estimation.json.zip)

**Comment by pavgra** [comment]
The actual issue is https://github.com/OHDSI/Atlas/issues/1846
