### ISSUE TITLE
Starving the batch job queue 

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#1219]
The characterization, pathways and incidence rate analyses supported by WebAPI create jobs using Spring Batch. These jobs perform 2 fundamental steps: 1) generating the cohorts used in the analysis and 2) performing the analysis on these cohorts.

When there is a lot of jobs like these passed to WebAPI for execution, it can starve itself of resources to clear the queue. For example, if one user is running a characterization with 5 cohorts (taking 6 queue spots) and another user generates several cohorts across several data sources, WebAPI may only have 1 active job slot to process the activity since the other jobs have to wait for their cohorts to completely generate.

Some ideas I'll leave here:

- Spring batch supports providing a priority for jobs: https://stackoverflow.com/questions/29678778/how-do-i-set-up-to-run-batch-jobs-based-on-priority. I'm not sure how feasible this is to implement but perhaps the parent job (characterization) could spawn the child cohort generation jobs with a higher priority so that the dependent cohort generations complete. This could still lead to a race condition amongst other jobs though.
- Run the cohort generations serially: instead of a characterization starting up separate jobs for each cohort generation, it could iterate through the generation process as part of it internal process. This way only a single job slot is taken while the operation completes. The downside is that we aren't taking advantage of running the generations in parallel.

**Comment by pavgra** [comment]
Although we execute the nested cohort generations as Steps of a single pipeline, Spring Batch treats them as the separate job runs. Your point is very valid: we need to revisit this mechanism. I'll do some researches and proposals when we get to 2.8.0 planning & development.

**Comment by anemniugin** [comment]
Situation, when I click generate button (on my test environment) if generating in the same time more then 2 reports( e.g. for cohort characterizations, or cohort pathways, etc) those jobs changed the status to "Starting", but Generate button is active again. I think we should show that job will be start later, and button "Generate" have to get the same behavior like with status "Started" (change button to red color and text "Cancel").

**Comment by anthonysena** [comment]
Having some discussions with @gowthamrao on this topic and wanted to add a few more thoughts here to get feedback:

Having each analysis run fully encapsulated ensures that nothing changes the underlying data during the execution. The upside here is that each analysis is self-contained and makes no assumptions about the current state of a cohort's generation status. The downside to this approach is that it is inefficient - if a cohort is used in multiple analyses, it is always generated.

In general, the workflow when working with a cohort is: define a cohort, generate it on a source to make sure it has people. Then, use that cohort definition as part of a cohort characterization, pathways and IR analysis. Again, each analysis will then generate the cohort in a temporary location, run the analysis and then discard the temporary table. If we adjust the analysis (i.e. add a new feature to a characterization), the whole process starts over: generate the cohort temporarily, characterize the features, discard the temporary cohort.

Ideally, we'd like to generate a cohort once and then use it for the analyses. The challenge is knowing that the contents of the cohort table in the results schema match up to the current cohort definition. I'm wondering if we could store the `cohort_definition_details.hash_code` in the results schema which would enable us to check to see if the cohort has been generated using the same expression that matches the hash? In that case, we could potentially prevent users from generating that cohort on ATLAS until the other analyses have completed. 

I only mention it on this thread since it seems like an improvement that would be sensible to do while making these changes and has the potential to really optimize the performance of the system. That said, it is adding a lot of complexity so I want to see if we can find the right balance here.

Tagging @pavgra @chrisknoll for thoughts and comments.

**Comment by pavgra** [comment]
@anthonysena , I believe you are talking about the same thing, are't you?
https://github.com/OHDSI/WebAPI/issues/1088

**Comment by gowthamrao** [comment]
A solution that allows us to reuse and not have to regenerate cohorts (when not necessary) - would be a fantastic optimization!

**Comment by anthonysena** [comment]
@pavgra indeed I am - thanks for linking these items together.
