### ISSUE TITLE
Distribution of a field values in Cohort Characterization

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#1220]
Today Criteria Feature Analyses in CC display distribution of records and not the distribution of some field's values. E.g. we can see the distribution of the number of measurements but cannot see the distribution of measurement's value_as_number. The latter has originally been [planned](https://github.com/OHDSI/WebAPI/issues/495) but was covered by dust and forgotten as we moved forward. The proposal is to revisit the item and bring it to life since there are real-life use-cases requiring it.

Tagging @pbr6cornell

**Comment by chrisknoll** [comment]
Described here: https://github.com/OHDSI/WebAPI/issues/495#issuecomment-431905691
