### ISSUE TITLE
Add possibility to disable redundant authProviders

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1227]
Currently WebAPI supports different auth providers. When application starts it tries to connect to all auth providers. 
In case of AD auth provider configuration we get a problem that WebAPI hangs for about a 1 minute trying to connect to some PostgreSQL host using authDatabase provider and then fails. 
It's good to have options to enable/disable needed authProviders

**Comment by chrisknoll** [comment]
Going to add this to 2.8 milestone because this isn't a bugfix, but rather a feature/enhancement that probably will require configuration changes or some sort of refactoring to allow enable/disable of providers.
