### ISSUE TITLE
Documentation for testing outdated? 

### ISSUE THREAD

**Issue by rtmill** [OHDSI/WebAPI#123]
I ran into some trouble trying to deploy the WebAPI. Turns out the application was running fine but the URL used for testing was incorrect. 

Documentation suggests: 
http://{YOUR SERVER}/WebAPI/vocabulary/concept/0

Where I believe it should be: 
http://{YOUR SERVER}/WebAPI/{SOURCE_KEY}/vocabulary/concept/0

**Comment by fdefalco** [comment]
You are correct.  We are in the process of migrating all documentation to the OHDSI wiki site:

http://www.ohdsi.org/web/wiki/doku.php

The WebAPI documentation will be moving here:

http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi

We will update the documentation to correct this issue with the migration.

**Comment by anthonysena** [comment]
Closing this noting that the wiki has moved to https://github.com/OHDSI/WebAPI/wiki
