### ISSUE TITLE
Exporting IR analysis results leads to net::ERR_CONTENT_DECODING_FAILED 500

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#1232]
Expected Result:
After generating an IR analysis, yous hould be albe to export the results as CSV.

Actual Results:
Clicking export button begins to export the data, but Chrome reports net::ERR_CONTENT_DECODING_FAILED 500.

Googling this error turns up that the encoding of the response doesn't match the type specified in the response.

The rest endpoint that handled /{id}/export has `@Produces(MediaType.APPLICATION_JSON)`, which I beleive should be @Produces(MediaType.APPLICATION_OCTET_STREAM), since the response is an octet stream.

What is interesting about this is that while I can reliably reproduce this on our current production env (2.7.2), I'm unable to reproduce this problem (even with the apparently wrong MediType.APPLICATION_JSON) working off the 2.7.3 RC branch.  I'll have to dig into the logs on the prod server to see exactly what is going on.

**Comment by YaroslavTir** [comment]
@chrisknoll You are right, it should not be an application-json media type. I guess the reason why it works is that we set this type programmatically in the method:
```
      response = Response
        .ok(baos)
        .type(MediaType.APPLICATION_OCTET_STREAM)
```
tbh I even can not reproduce this issue for version 2.7.2. I would remove this annotation, or put there correct type.
