### ISSUE TITLE
Lack of Client Cache Directives

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1234]
Lack of Client Cache Directives
Overview
The Atlas application does not utilize client control directives to control the caching of sensitive information, potentially exposing sensitive information to unauthorized users.

When no cache directives are provided by a web application, the user’s browser may choose to cache received content to the user’s local cache, potentially exposing sensitive information to any user who has access to the local file store. For example, the Atlas application was found to be sending full application credentials to requesting administrators, which may be cached to the user’s local file system and retrieved by an unauthorized user later. The following server response shows the lack of cache directives in combination with these sensitive details: 

HTTP/1.1 200 
Access-Control-Allow-Origin: https://..... 
Access-Control-Allow-Credentials: true 
Access-Control-Expose-Headers: Bearer,x-auth-error 
Set-Cookie: rememberMe=deleteMe; Path=/WebAPI; Max-Age=0; 
Expires=Tue, 30-Apr-2019 20:31:04 GMT 
Vary: Accept-Encoding 
Content-Type: application/json 
Date: Wed, 01 May 2019 20:31:04 GMT 
Alt-Svc: clear 
Connection: close 
Content-Length: 694 

{"sourceId":5,"sourceName":"Optum 2018/08","sourceDialect":"postgresql",
"sourceKey":"OPTUM","daimons":[{"sourceDaimonId":6,"daimonType":"CDM",
"tableQualifier":"cdm_53","priority":0},
{"sourceDaimonId":7,"daimonType":"Vocabulary","tableQualifier":"cdm_53",
"priority":0},{"sourceDaimonId":8,"daimonType":"Results",
"tableQualifier":"cdm_53_results","priority":0}],
"connectionString":"jdbc:postgresql://...........","username":"atlas","password":"ATLAS_<redacted>",
"krbAuthMethod":"password","keytabName":null,"krbAdminServer":null}

Sensitive Service Response without Cache-Control Directives

Recommendation(s)The Atlas application should include the following cache directives when sending sensitive content to application users: 

Cache-control: no-store 
Pragma: no-cache

ReferencesCWE-524: Information Exposure Through Caching: https://cwe.mitre.org/data/definitions/524.html

**Comment by anthonysena** [comment]
This was closed with the 2.7.3 release.
