### ISSUE TITLE
Unable to delete cohort definition

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#1239]
In version 2.7.2, attempting to delete the cohort definition results in a hanging (pending) request to the delete endpoint.

#### Steps to Reproduce

1. Create cohort Definition
2. Add cohort definition to Characterization (not sure if this is required, but it is the case in our internal enviornment)
3. Generate cohorts and characterizations
4. Try to delete the cohort definition. We observed this in chrome:

![image](https://user-images.githubusercontent.com/6818777/61467562-d3a4a400-a949-11e9-8b29-5b9628fe44a6.png)

The request was stuck in 'pending' state for over 5 minutes.

**Comment by pavgra** [comment]
@chrisknoll , do you have any additional details on this like logs from the server? Maybe you could connect to the running instance of Atlas with remote debug and check what's going on from inside? - Neither I nor other Odysseus team members were able to reproduce this

**Comment by chrisknoll** [comment]
Restart of WebAPI resovled this.  My guess is that there was a lock on the cohort definition table which was preventing the thread from deleting.
