### ISSUE TITLE
Cannot add Place of Service Location filter to Visit occurrence initial criteria

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#1263]
1. Create cohort definition with Visit occurrence initial criterion
2. Save
3. Add Place of Service location filter and select concept set
4. Save

Results in 500 - `User-defined CDM range (>=5.0.0) does not include derived CDM range (>=6.1.0)`

**Comment by chrisknoll** [comment]
We should remove the range check during saving. It should be valid to save a cohort definition even with invalid use of certain expression features.  Instead, we should have checks during generation that can fast-fail with the indicated error if a person attempts to generate a definition with invalid specification.  In addition, we should add warnings/error messages to the UI (leveraging the same validation framework we have today for other errors) to indicate to the user which feature is outside the version range.
