### ISSUE TITLE
Error adding source using the Source Management web interface in v2.7.2

### ISSUE THREAD

**Issue by JamesSWiggins** [OHDSI/WebAPI#1295]
I receive the following pop-up error when trying to add a new source through the Atlas web interface:

The Source was not saved. A different object with the same identifier value was already associated with the session : [org.ohdsi.webapi.source.SourceDaimon#6]

The JSON POST'd to source/ is below:
{"name":"MyNewSource",
"key":"test1",
"dialect":"redshift",
"connectionString":"jdbc:redshift:/redshiftclusterurl.us-east-1.redshift.amazonaws.com:5439/mycdm?user=user&password=password",
"krbAuthMethod":"password",
"krbAdminServer":null,
"username":"user",
"password":"password",
"daimons":[
    {"tableQualifier":"CMSDESynPUF100k1",
    "priority":0,"sourceDaimonId":null,
    "daimonType":"CDM"},

    {"tableQualifier":"CMSDESynPUF100k1",
    "priority":0,
    "sourceDaimonId":null,
    "daimonType":"Vocabulary"},

    {"tableQualifier":"CMSDESynPUF100kresults",
    "priority":0,"sourceDaimonId":null,
    "daimonType":"Results"}
    ]
}

When this error happens, I also get the following output in my Tomcat catalina.out log file:

Aug 13, 2019 1:27:46 PM org.ohdsi.webapi.shiro.filters.ProcessResponseContentFilter processResponseContent
SEVERE: Failed to process response content: Json node 'sourceId' is null

**Comment by pavgra** [comment]
@JamesSWiggins , have you tried https://github.com/OHDSI/WebAPI/releases/tag/v2.7.3-RC1?

**Comment by JamesSWiggins** [comment]
No I haven't.  I'll give this a shot.

**Comment by anthonysena** [comment]
@JamesSWiggins - I'm noting this for myself so that we can confirm this is closed via v2.7.4 and v2.8. If you happen to have tested this against v2.7.4, we can close this out. Thanks!

**Comment by anthonysena** [comment]
Closing this out since I can no long reproduce this error on 2.8/master.
