### ISSUE TITLE
WebAPI Tables Not Being Created in Windows 10

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/WebAPI#1299]
Since nobody appears to be responding to my issue on the forums, I am posting it here.  **Any ideas why the tables are not being created?**  Much appreciated.

[https://forums.ohdsi.org/t/webapi-tables-not-being-created-in-windows-10/7716](url)

**Comment by chrisknoll** [comment]
Hi, @anonymous34 ,
  The log file  seems incomplete. There doesn't seem to be any error information in the log file.  

When the WebAPI first starts off, it will log the sql updates being applied to the database (shortly after the logg message: localhost-startStop-1 org.flywaydb.core.internal.util.VersionPrinter - - Flyway 4.2.0 by Boxfuse.

Please attach a more complete error log with the error messages in it, and we'll be able to determine the problem.

In addition please specify version of webapi you are running.

**Comment by anonymous34** [comment]
Hello @chrisknoll  

Thank you for getting back to me.  I think the issue was I did not have the SQL Server JDBC driver installed.  Silly me.  Anyway, 149 tables were created after this fix.  Web API version is 2.7.3.  Now there seems to be some issues accessing http://localhost:8080/WebAPI/source/sources.  When I go to this link, I get [].  In the log, it seems I have a 404 and 405 java exception when trying to access these urls.  I posted the updated log on the forum post because github is not letting me upload text files. You can see the exceptions starting here in the log file:

`2019-08-20 16:28:30.284 INFO taskScheduler-5 org.ohdsi.webapi.executionengine.service.ScriptExecutionServiceImpl -  - Invalidating execution engine based analyses
2019-08-20 16:29:52.038 ERROR http-nio-8080-exec-6 org.ohdsi.webapi.util.GenericExceptionMapper -  - javax.ws.rs.NotFoundException: HTTP 404 Not Found`

Also, I recreated the empty OHDSI database because I realized the app user login had failed.  I fixed this and I stopped/started catalina.bat.

**Comment by chrisknoll** [comment]
Ok, since there's not an actual bug here, let's continue the configuration questions on the ohdsi forums, where more people will be able to shed light on your specific configuration.
