### ISSUE TITLE
/cache/clear endpoint cannot be accessed in secure mode

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#1303]
No migrations were created which would define new permission and grant it to Atlas user role. Therefore, it is impossible to access the endpoint with enabled auth

**Comment by chrisknoll** [comment]
This should be unsecured, similar to /info.  I don't think there's any reason to restrict this endpoint to any role.

**Comment by pavgra** [comment]
The presence of cache directly affects the performance of the application and workload of the hosting server. Which, in its turn, affects all Atlas users. So, I do not agree with the statement. It's administrator's responsibility to do app maintenance.

**Comment by pavgra** [comment]
While `/info` is doing nothing. Just prints some metadata about the application without changing any app state or affecting it anyhow. Totally different beasts

**Comment by chrisknoll** [comment]
Not totally different.  Often those 2 functions are accessed the same way: you just open a browser to the endpoint to get some information/result.  The reason why it was exposed as an endpoint was so that you could invoke cache clear without even having atlas being installed or logging in.  

Under your proposal, how would someone perform a cache clear without a UI to direct them to log in?

**Comment by chrisknoll** [comment]
> It's administrator's responsibility to do app maintenance.

We can agree to disagree here that clearing a cache is 'app maintenance' on the same level as datasource configuration or security role updates....

**Comment by pavgra** [comment]
> Under your proposal, how would someone perform a cache clear without a UI to direct them to log in?

Same as with all other URLs in secure mode: by attaching `Authorization` header to the request.

Anyway, currently, you cannot even call the endpoint with enabled security since the endpoint is marked as protected and requires appropriate permission from a user but such permission has never been added into the database. So the migration which adds the permissions is required, there are no options. As soon as you add permission, you need to link it to some role, otherwise, the permission is meaningless - you won't be able to grant it to anyone. Linking it to Public vs Admin role may be debatable but my vision is that it's better to provide a more secure approach by default (so to allow calling the endpoint by admins only) and then anyone who wants can go into Admin panel and re-assign the permission from Admin role to Atlas user role.

**Comment by chrisknoll** [comment]
> Same as with all other URLs in secure mode: by attaching Authorization header to the request.

How do you add an Authorization header manually in Chrome?

Anyway, the endpoint should not have been marked as protected (I thought endpoints would be marked as 'unprotected' by default'.  If you can point me to the documentation that describes how to mark an endpoint unprotected, I'll make a PR to make that change.
