### ISSUE TITLE
Record count caching optimization

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#1308]
In speaking with @leeevans, we've noted that it takes a while for WebAPI to completely start up since there are jobs that run to cache record counts through this query: https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/loadConceptRecordCountCache.sql. We'd like to see if this is something that we could potentially do as part of running Achilles and have it store these results in a stand-alone table so that the ConceptRecordCountCache.sql could be a simple SELECT from that table which would help improve startup time.

**Comment by ssuvorov-fls** [comment]
Add to Release Notes: parameter "optimizeAtlasCache" with default value FALSE was added to achilles

**Comment by anthonysena** [comment]
@ssuvorov-fls - I think the changes made for Achilles are good. Now we'll need to update WebAPI to make use of the new `@resultsDatabaseSchema.achilles_result_concept_count` as part of the WebAPI startup. Also, I'm unsure how the changes proposed in https://github.com/OHDSI/Atlas/pull/2119 relate to this issue?

**Comment by ssuvorov-fls** [comment]
@anthonysena 
I could not get correct state of warming cache job for this issue due to wrong behaviour of notifications during startup so i decided to fix it in OHDSI/Atlas#2119
