### ISSUE TITLE
Results schema script - adding vocabulary table index

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#1327]
I'm facing an issue while applying the results schema script via the `ddl/results` endpoint. Specifically this statement fails on PDW:

````
CREATE INDEX idx_concept_id_varchar ON dbo.concept (CAST(concept_id AS VARCHAR));
````

Tracing through the git history lead me to this issue & corresponding changes: _Heracles performance issue when joining strata to concept_ #1068. In thinking about this, my opinion is that this type of index creation would be more appropriate to store in the CommonDataModel repo as that is where indicies are applied for the vocabulary tables. For example: https://github.com/OHDSI/CommonDataModel/blob/master/PostgreSQL/OMOP%20CDM%20postgresql%20pk%20indexes.txt#L189. I do not thing that the WebAPI should direct changes to the vocabulary tables as was done here. 

Tagging @pavgra @chrisknoll for thoughts on this.

**Comment by chrisknoll** [comment]
Agreed, we shouldn't have indexes for the CDM schema in the ddl for the results schema.

**Comment by anthonysena** [comment]
Linking to https://github.com/OHDSI/CommonDataModel/issues/313 and noting here that the change required here is to remove the `CREATE INDEX` statement from the results schema DDL.
