### ISSUE TITLE
impossible to create a copy of PLP

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1364]
1) Try to copy any plp(prediction)

expected:The copy has been created

actual:
front:
![image](https://user-images.githubusercontent.com/56290675/69413241-7d91a400-0d21-11ea-9dee-bf383cf0006a.png)

 back:
WebAPI/prediction/{id}/copyRequest Method: GETStatus Code: 500{"payload":{"cause":null,"stackTrace":[],"message":"An exception ocurred: org.springframework.core.convert.ConversionFailedException","localizedMessage":"An exception ocurred: org.springframework.core.convert.ConversionFailedException","suppressed":[]},"headers":{"id":"249a112a-4afe-32c3-1543-b30a203dac25","timestamp":1573718841739}}

as a result - the copy has been created, but it's unable for editing

**Comment by anthonysena** [comment]
@ssuvorov-fls presumably this is a problem on v2.7.4?

**Comment by ssuvorov-fls** [comment]
@anthonysena yes, it will be fixed in 2.7.5 and 2.8
