### ISSUE TITLE
pom.xml issue for net.lingala.zip4j

### ISSUE THREAD

**Issue by billudada78** [OHDSI/WebAPI#1367]
From a vanilla installation of the latest Java JDK and Maven, I repeatedly had issues with:

[ERROR] /C:/GIT/OHDSI/WebAPI/src/main/java/org/ohdsi/webapi/executionengine/service/AnalysisResultFileContentSensitiveInfoServiceImpl.java:[4,30] package net.lingala.zip4j.core does not exist

I needed to add zip4j explicitly to the pom.xml file to resolve this:

<dependency>
        <groupId>net.lingala</groupId>
        <artifactId>zip4j</artifactId>
        <version>1.3.3</version>
    </dependency>

**Comment by billudada78** [comment]
![image](https://user-images.githubusercontent.com/48965882/69409966-4c59a980-0d0a-11ea-8cb0-62174a4da18f.png)

**Comment by anthonysena** [comment]
Thanks for reporting this @billudada78. I think that the zip4j reference may be coming from a different OHDSI library but to your point, I see references to zip4j in the code and if you are facing issues on a fresh install, it seems like a configuration issue.

Tagging @pavgra - #1315 mentions this and it is noted in that issue: _dependency itself was upgraded in the common library, here I just fixed code._ zip4j is referenced in ArachneCommons: https://github.com/OHDSI/ArachneCommons/search?q=zip4j&unscoped_q=zip4j but in the `execution-engine-commons` project. Perhaps it should be promoted to the arachne-commons reference used by WebAPI instead?

**Comment by YaroslavTir** [comment]
The zip4j library was upgraded in the ArachneCommons: https://github.com/OHDSI/ArachneCommons/pull/200/
and then upgraded in the WebApi
https://github.com/OHDSI/WebAPI/pull/1314
and then merged to the WebApi 2.7.3 
https://github.com/OHDSI/WebAPI/compare/v2.7.3...isssue-1315
