### ISSUE TITLE
WebAPI "FAIL - Application at context path [/WebAPI] could not be started"

### ISSUE THREAD

**Issue by billudada78** [OHDSI/WebAPI#1369]
I have rebuilt the Maven project for the war file for a postgres build multiple times.  I have connectivity to the SQL database using SQL Workbench and have used the same URL and user account details in the settings.xml file.  My webapi schema shows all of the new tables created as part of the Tomcat connection.  I can reach the Tomcat server and login as manager (I have used 8081 to avoid conflict with my Achilles server).  The WebAPI is deployed but when I start the service I get a failure message.  I cannot navigate to the WebAPI page.  My Catalina log and WebAPI logs are attached:

[webapi.log](https://github.com/OHDSI/WebAPI/files/3879705/webapi.log)

[catalina.2019-11-22.log](https://github.com/OHDSI/WebAPI/files/3879707/catalina.2019-11-22.log)

Any guidance on next steps or obvious issues in my install would be greatly appreciated!

**Comment by anthonysena** [comment]
@billudada78 - thanks for sharing this info - it looks like the error is:

`Circular placeholder reference 'webapi.version' in property definitions`

Can you also post up the settings.xml used to create the WebAPI.war? Please remove any sensitive info when posting.

**Comment by billudada78** [comment]
Thanks @anthonysena, it is possible that the circular reference comes from my attempt to fix the pom file in my other issue flag https://github.com/OHDSI/WebAPI/issues/1367j .  

Here is the settings.xml (with .txt appended for uploading to Github, the working file has only .xml):
[settings.xml.txt](https://github.com/OHDSI/WebAPI/files/3879970/settings.xml.txt)

Here is my poor attempt to correct the POM.  The maven build complains that I have included multiple references to zip4j.  I am only running a postgres database but I left a mention within each SQL database section.  I am not sure how to use the "\exception" syntax to do this in the proper way.  I mention this in case it is the source of the circular references.
[pom.xml.txt](https://github.com/OHDSI/WebAPI/files/3879978/pom.xml.txt)

**Comment by anthonysena** [comment]
Hi @billudada78 - thanks for sharing those files and for the reference to #1367. I'd suggest rolling back the changes to your pom.xml as I'm fairly certain that your zip4j reference should resolve now that it is in your local maven repository.

One other thing I noticed from your logs: it looks like you are running Tomcat 9. Could you give it a try on Tomcat 8 instead? That is a recommendation from the wiki here: https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide#software.

**Comment by billudada78** [comment]
Thanks @anthonysena !  I have a working WebAPI now.  I didn't realize my zip4j hack would create a permanent addition to my local maven repository.  I have also rolled back Tomcat to version 8.
