### ISSUE TITLE
Startup Failure when running unit tests: operator does not exist: boolean = integer

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#1370]
Possibly related to the embedded Postgresql instance that WebAPI uses for unit tests, however, I am intermittently seeing the folliwing error in the log:

```
Hibernate: select userimport0_.id as id1_54_0_, rolegroupm1_.id as id1_48_1_, userimport0_.cron as cron2_54_0_, userimport0_.is_enabled as is_enabl3_54_0_, userimport0_.executed_times as executed4_54_0_, 
  userimport0_.frequency as frequenc5_54_0_, userimport0_.is_closed as is_close6_54_0_, userimport0_.last_executed_at as last_exe7_54_0_, userimport0_.recurring_times as recurrin8_54_0_, userimport0_.recurring_until_date as recurrin9_54_0_, userimport0_.start_date as start_d10_54_0_, userimport0_.preserve_roles as preserv11_54_0_, userimport0_.provider_type as provide12_54_0_, 
  rolegroupm1_.group_dn as group_dn2_48_1_, rolegroupm1_.group_name as group_na3_48_1_, rolegroupm1_.provider as provider4_48_1_, rolegroupm1_.role_id as role_id5_48_1_, rolegroupm1_.job_id as job_id6_48_1_, rolegroupm1_.job_id as job_id6_48_0__, rolegroupm1_.id as id1_48_0__ 
from public.user_import_job userimport0_ 
left outer join public.sec_role_group rolegroupm1_ on userimport0_.id=rolegroupm1_.job_id 
where userimport0_.is_enabled=1 and userimport0_.is_closed=0
2019-11-22 22:43:17.831 WARN main org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - SQL Error: 0, SQLState: 42883
2019-11-22 22:43:17.831 ERROR main org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - ERROR: operator does not exist: boolean = integer
```

I'm guessing that in the user import tables, there's a boolean for is_enabled or is_closed that is defined as a boolean, but it's using integers to check the flag (0 or 1).

Other times, I am able to execute the tests without issue. So it's a strange, almost race-condition feeling issue.  However, if it does get tripped, the application context fails to initialize, and the unit tests fail to run.

**Comment by ssuvorov-fls** [comment]
@chrisknoll Hi, I've tried to execute some tests and got another sql 
`2019-11-27 13:59:19.996 DEBUG main org.hibernate.SQL -  - select userimport0_.id as id1_54_0_, rolegroupm1_.id as id1_48_1_, userimport0_.cron as cron2_54_0_, userimport0_.is_enabled as is_enabl3_54_0_, userimport0_.executed_times as executed4_54_0_, userimport0_.frequency as frequenc5_54_0_, userimport0_.is_closed as is_close6_54_0_, userimport0_.last_executed_at as last_exe7_54_0_, userimport0_.recurring_times as recurrin8_54_0_, userimport0_.recurring_until_date as recurrin9_54_0_, userimport0_.start_date as start_d10_54_0_, userimport0_.preserve_roles as preserv11_54_0_, userimport0_.provider_type as provide12_54_0_, rolegroupm1_.group_dn as group_dn2_48_1_, rolegroupm1_.group_name as group_na3_48_1_, rolegroupm1_.provider as provider4_48_1_, rolegroupm1_.role_id as role_id5_48_1_, rolegroupm1_.job_id as job_id6_48_1_, rolegroupm1_.job_id as job_id6_48_0__, rolegroupm1_.id as id1_48_0__ from ohdsi.user_import_job userimport0_ left outer join ohdsi.sec_role_group rolegroupm1_ on userimport0_.id=rolegroupm1_.job_id where userimport0_.is_enabled=true and userimport0_.is_closed=false`
what tests have you tried?

**Comment by chrisknoll** [comment]
Ah, maybe the issue is related to the Redshit driver:  is the redshift driver installed in your env?  As discussed in #592, if you have both the redshift driver and Postgresql driver installed, you could have the redshift driver pick up the jdbc connection to `jdbc:postgresql`.  Is that possible?

The fix on this is to specify a `OpenSourceSubProtocolOverride=true` in the JDBC connection string, but for the tests, we don't use a connection string to get the connection, thre's a `getInstance()` method that returns the datasource....not sure what to do here...

I will say, tho, that for that 'isClosed' and 'isEnabled', are defined as different data types on oracle, sqlserver an postgresql, and I think this leads to a risk that the JDBC driver won't translate the value correctly...maybe the fix is to ensure that we use datatypes consistently across platforms.

**Comment by ssuvorov-fls** [comment]
@chrisknoll what test is running when you get this error?

'isClosed' and 'isEnabled', are defined as different data types on oracle, sqlserver an postgresql because sql server and oracle don't have type 'boolean' and using different data types for them is common way to emulate boolean data type

**Comment by chrisknoll** [comment]
No test...or rather...any test. This is the Spring Container initializing and starting up all the Beans.  One of them is the userImport job scheduler, and I believe that bean is started by default.

**Comment by ssuvorov-fls** [comment]
@chrisknoll are you running tests during maven execution or you just run test class itself without maven?

**Comment by chrisknoll** [comment]
I got this by running 'debug test' in vs.code.

**Comment by ssuvorov-fls** [comment]
@chrisknoll 
> But, to answer your question, this was happening when I was testing the caching updates in my PR #1337.
Do you mean GenerationCacheTest?

**Comment by chrisknoll** [comment]
@ssuvorov-fls : correction on referenced PR, it was #1337 

Yes, GenerationCacheTest.

I set up VS.code to append -Pwebapi-mssql but, I'm not sure how the applicaiton.properties from `@TestPropertySource(locations = "/in-memory-webapi.properties")` defined for this test case takes precedence. I'm pretty sure it will just use the `in-memory-webapi.properties` file regardless of which profile the build was done, right?
