### ISSUE TITLE
Update postgresql jdbc version in POM.XML

### ISSUE THREAD

**Issue by ambuj369** [OHDSI/WebAPI#1375]
Hello,

I was building WebAPI.war on RHEL7 operating system using Postgres as database. While deploying it to Apache Tomcat I encountered an error and the tomcat log says (see screenshot):
I checked the JDBC version on RHEL and it was "42.2.8" and POM.XMl have "9.4-1201-jdbc41". So, I changed  the <versionId> from "9.4-1201-jdbc41" to "42.2.8" in pom.xml and recompiled the build which deployed successfully.
Please update it in POM.XML for WebAPI 2.7.4 and upcoming versions to dynamically pick up the JDBC version from operating system itself to avoid any manual intervention to standard code files.

Thank you
![Error_tomcat](https://user-images.githubusercontent.com/47858365/69853747-a5e34a80-12ad-11ea-9cf2-1a31cc9c80c1.JPG)

**Comment by anthonysena** [comment]
Thanks @ambuj369 for pointing this out. Just curious: is the machine where you are doing this work connected to the Internet? I would have expected that this driver would have downloaded from the Maven repository.

**Comment by ambuj369** [comment]
@anthonysena 
Yes, it was connected to internet. 

Unfortunately, it didn't happen.

I had to manually update the version in POM.xml I tried today as well without any changes and got the same error which got resolved by updating version in POM.

**Comment by anthonysena** [comment]
Related to #1125 - we can make the defaults for each DBMS part of the application.properties and allow overriding as described here: https://vladmihalcea.com/jdbc-driver-maven-dependency/.

**Comment by anthonysena** [comment]
Closing this in favor of #1125.
