### ISSUE TITLE
Characterization Error in oracle

### ISSUE THREAD

**Issue by ParkChanghHyun** [OHDSI/WebAPI#1402]
When I implement "Characterizations" FUNCTION,, it didint work!

[Didn't woks page]
![image](https://user-images.githubusercontent.com/45930454/71714441-47336280-2e51-11ea-949b-b3da5c228e33.png)

[Error Log]
![image](https://user-images.githubusercontent.com/45930454/71714507-82359600-2e51-11ea-94fd-96d821da520b.png)

.
.
.
![image](https://user-images.githubusercontent.com/45930454/71714552-ac875380-2e51-11ea-9edd-a09707de32db.png)

When I look the Error QUERY. The checked line occurred Error. Because Oracle didn't have CONCAT FUNCTION( in oracle use "||" ). 
![image](https://user-images.githubusercontent.com/45930454/71714759-6da5cd80-2e52-11ea-9ddb-425c031055cb.png)

So!! I need Where can I fix the "Characterizations" FUNCTION. 
I want to know source code directory in WebAPI.

**Comment by anthonysena** [comment]
@ParkChanghHyun - can you send the full WebAPI logs for this error? The query you've highlighted above looks like a query that would execute against the WebAPI DB and that SQL translation is done using the Hibernate library.

**Comment by ParkChanghHyun** [comment]
Thanks @chrisknoll and @anthonysena !
Now it is well working :)

**Comment by chrisknoll** [comment]
Let's leave this open until the PR gets merged into master so we don't loose track of it.
