### ISSUE TITLE
Temp tables aren't cleaned up

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/WebAPI#1409]
Example for BigQuery:
after IR cancellation there is a bunch of temp tables

For Impala: after Heracles generation temp tables are left

need to check other databases

**Comment by KSadomtsev** [comment]
![image](https://user-images.githubusercontent.com/56290675/75690229-89431e00-5cb3-11ea-95cc-b05363fbb9b7.png)
can see the same problem for IMPALA (PLP, PLE)

**Comment by olga-ganina** [comment]
Original request and issue was about Netezza.
Do not have any reported problems for other database for now, so closing this one.
