### ISSUE TITLE
com.sun tools-1.60.jar file does not exist

### ISSUE THREAD

**Issue by kelly2848** [OHDSI/WebAPI#1431]

**Comment by blootsvoets** [comment]
I've had the same when compiling with Java 11, if I recall correctly in the Miredot package. Reverting to Java 8 solved the issue for me.

**Comment by kelly2848** [comment]
Thanks for the quick response. Now that Java 13 is out not sure I can even get back to Java 8. I noticed some workarounds that I will also try.

**Comment by MaximMoinat** [comment]
For future reference, another option is to change the miredot version to one not requireing Java 8. e.g.:
<version>2.2-Java9</version>

For other Java versions see: https://mvnrepository.com/artifact/com.qmino/miredot-plugin?repo=qmino-miredot
