### ISSUE TITLE
Altas in "Data source" Dashboard didn't work in oracle

### ISSUE THREAD

**Issue by ParkChanghHyun** [OHDSI/WebAPI#1447]
Hi I'm park.

When I try to "Data source"->"Dashboard" function. 
It didn't work.
So I need a that’s query directory.Where can I find it?

`Like bellow added image.
`

![image](https://user-images.githubusercontent.com/45930454/73713322-5bb89280-4750-11ea-8d8d-8c376c63f4f8.png)

`It is error log.`
![에러로그](https://user-images.githubusercontent.com/45930454/73526652-02511a80-4455-11ea-91a1-deee4de4419e.PNG)

`And I think It is a solution like this image. Where can I find out that's query.
`
![에러 쿼리](https://user-images.githubusercontent.com/45930454/73526765-3debe480-4455-11ea-8211-c068f7963087.PNG)

**Comment by ParkChanghHyun** [comment]
`-1.When you before build "WebAPI.war" files in maven,chage bellow file.`

That is because it need alias in "oracle" syntax.


"\src\main\resources\resources\cdmresults\sql\report\observationperiod\cumulativeduration.sql"
                   &
"\src\main\resources\resources\cohortresults\sql\observationperiod\cumulativeduration.sql"
 
![수정 1번](https://user-images.githubusercontent.com/45930454/73706936-45550b80-473d-11ea-8a63-1ca9f573b31e.PNG)
![수정 2번](https://user-images.githubusercontent.com/45930454/73706938-45550b80-473d-11ea-8240-6f72e01f7253.PNG)

**Comment by Andreyyiv** [comment]
@anthonysena @olga-ganina Please include this fix into the main code. Thanks

**Comment by anthonysena** [comment]
@Andreyyiv or @ParkChanghHyun can you contribute a PR with these fixes?

**Comment by Andreyyiv** [comment]
@anthonysena sure

**Comment by anthonysena** [comment]
Thanks @Andreyyiv then I'll close this out since both fixes have been applied. Let me know if I've missed something here.
