### ISSUE TITLE
WebApI 2.7.6 Setup Failing on PostgreSql 11.0

### ISSUE THREAD

**Issue by bradanton** [OHDSI/WebAPI#1472]
- WebAPI 2.7.6
- Windows
- PostgreSql 11.0

When I tried to start WebAPI, the tomcat message showed:
FAIL - Application at context path /WebAPI could not be started
FAIL - Encountered exception org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/WebAPI]]

Here is part of the log from catalina.out:
`Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'shiroFilter' defined in class path resource [org/ohdsi/webapi/ShiroConfiguration.class]: Unsatisfied dependency expressed through method 'shiroFilter' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/ohdsi/webapi/FlywayConfig.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.dbsupport.FlywaySqlException: 
Error restoring current schema to its original setting`

The error is caused by following script:
[https://github.com/OHDSI/WebAPI/blob/aa203243b6ca340e4b2fd54a16c2d44a1e6d44fe/src/main/resources/db/migration/postgresql/V2.7.0.20190304162609__standardize-permissions-ir.sql](url)

flowing query from the V2.7.0.20190304162609__standardize-permissions-ir.sql:

`delete from ${ohdsiSchema}.sec_permission where
  value in ('ir:*:info');`  

causes the PostgreSQL database to enter recovery mode. Only on PostgreSql 11.0.

The issue related with PostgreSql 11.0 bug.
[https://www.postgresql.org/message-id/flat/E1gKAr3-0004nH-Jv%40gemulon.postgresql.org](url)
[https://www.postgresql.org/message-id/flat/20181101140216.GA2954%40hermes.hilbert.loc](url)

Upgrading to version 11.1 and higher will fix the issue.

**Comment by bradanton** [comment]
Hi @anthonysena - I have updated the link, it was misprint.

Yep, >= PG 11.1, It can help someone.

Thanks!

**Comment by anthonysena** [comment]
Thanks @bradanton - just to confirm: upgrading from PG 11.0 to 11.1 addressed this issue then? I can note it for the documentation as this will certainly help others in the community. Thanks!

**Comment by chrisknoll** [comment]
@anthonysena , I am reading it as an issue with PG 11.0, and antying > 11.0 will work, we can make a note of that in our documentation.
