### ISSUE TITLE
ATLAS cohort pathways producing Duplicate treatment pathways 

### ISSUE THREAD

**Issue by mayakamay** [OHDSI/WebAPI#1476]
Hi, I was trying to generate cohort pathways using ATLAS version 2.7.5, sunburst plot produced duplicate treatment pathways. See screenshots below.

Any idea why this is happening? 
![image](https://user-images.githubusercontent.com/35781399/76055141-bfcbb200-5fad-11ea-8955-9a8ddcdfc1f3.png)

Treatment Pathways are set up as following:
![image](https://user-images.githubusercontent.com/35781399/76055255-15a05a00-5fae-11ea-809a-3684bea492a1.png)

**Comment by anthonysena** [comment]
Hi - I'm not sure what happened there. If you go to the "Executions" Tab on the pathways analysis in Atlas, can you export the design that produced this result and share it here? That may shed some light into what happened.

**Comment by mayakamay** [comment]
hi Anthony, should I export the SQL code for generating the cohort pathways? I tried to paste it here but it was too long

**Comment by anthonysena** [comment]
I'd suggest passing along the JSON design for the analysis. You can find this by clicking on the number next to the "Design":

![image](https://user-images.githubusercontent.com/12902366/78248706-24016900-74bb-11ea-9bf9-efb3c2a624cf.png)

This will reveal the JSON used for that particular execution. If you copy/paste it into a text file, you can then attach it to this issue and we can take a look. Please keep in mind that this will share out the cohort definitions, etc. used in the study so if that's a concern, please let me know.

**Comment by mayakamay** [comment]
[cohort pathway.txt](https://github.com/OHDSI/WebAPI/files/4507462/cohort.pathway.txt)

**Comment by mayakamay** [comment]
Thanks Anthony

**Comment by anthonysena** [comment]
Tagging @chrisknoll since I think this is related to #1518 and this example is helpful in tracking down the details. Thank you for sharing it @mayakamay
