### ISSUE TITLE
V2.7.6: Vocabulary search issue

### ISSUE THREAD

**Issue by ChavanShweta** [OHDSI/WebAPI#1484]
### Expected behavior
searching vocabulary yields nothing.
### Actual behavior
Atlas - V2.7.6
![Screen Shot 2020-03-04 at 1 37 57 PM](https://user-images.githubusercontent.com/20832191/75911836-3043c900-5e1e-11ea-9e86-78b9d7a408fc.png)

Adding source gives following errors:
![Screen Shot 2020-03-06 at 8 22 58 PM](https://user-images.githubusercontent.com/20832191/76133864-78aee280-5fe8-11ea-94f4-a73bed21da68.png)

So I tried Atlas - V2.7.5 works fine WebAPI V2.7.5 has following errors
![Screen Shot 2020-03-06 at 8 28 37 PM](https://user-images.githubusercontent.com/20832191/76134024-62eded00-5fe9-11ea-9367-19041e5929b3.png)

So I tried deploying Atlas - V2.7.1
![Screen Shot 2020-03-06 at 8 33 33 PM](https://user-images.githubusercontent.com/20832191/76134092-ce37bf00-5fe9-11ea-9a8f-a264f2bedff6.png)

I am pulling these from Release tab/Assets
Should I pull it from master and git reset to specific tag?

**Comment by anthonysena** [comment]
V2.7.5 may be having issues related to https://github.com/OHDSI/WebAPI/issues/1432. 

For the V2.7.6 problem mentioned here: do you have a vocabulary daimon set up for your data source?

**Comment by anthonysena** [comment]
@ChavanShweta - let us know if you still face an issue here and we can re-open. Thanks!
