### ISSUE TITLE
Role "atlas user" lacks rights to create incidence rates

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#1488]
We need to add a flyway script to add the following permission to the "atlas user" role:

insert into ${ohdsiSchema}.sec_role_permission (role_id, permission_id)
select 10, id
from ${ohdsiSchema}.sec_permission p
where p.value = 'ir:*:put'
;

**Comment by anton-abushkevich** [comment]
Reopening. Q.v. OHDSI/Atlas#2220
Permission to create incidence rates is "ir:post". We need to rollback #1503 migrations and check if "ir:post" is enough to create IR.
