### ISSUE TITLE
CAST(concept_id AS VARCHAR) causes Results DDL to fail when runs against SQL Server DBs  

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/WebAPI#1500]
**Expected**

[TBC]

**Experienced**

The following statement in Results DDL fails when run against SQL Server database

`CREATE INDEX idx_concept_id_varchar ON dbo.concept (CAST(concept_id AS VARCHAR));`

**Steps**

[TBC]

**Comment by anthonysena** [comment]
@t-abdul-basser - this has been addressed as part of https://github.com/OHDSI/WebAPI/pull/1434. I'd suggest commenting out that problematic SQL as a work around for now.
