### ISSUE TITLE
source id should be larger than 0

### ISSUE THREAD

**Issue by Geunhae-Lee** [OHDSI/WebAPI#1505]
source_id in source table should NOT be zero. If so Incedence Rate Generation will fail on CDM whose source id were 0.

I've tested on version 2.7.6. 

Code should detect invalid setting in source table or DDL should have constraints to have positive value.

**Comment by anthonysena** [comment]
@Geunhae-Lee - the wiki doesn't explicitly state that you must use a source_id > 0 so I think it would be good for us to add that to https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration. Additionally the query used to initialize the source table should use the sequence in the WebAPI vs hard-coding the ID to use.

**Comment by anthonysena** [comment]
Wiki updated to reflect this information.
