### ISSUE TITLE
Miredot license Issue

### ISSUE THREAD

**Issue by chankch** [OHDSI/WebAPI#1507]
![WebAPI Miredot License](https://user-images.githubusercontent.com/37068413/79191532-c5949d00-7e61-11ea-84c6-9e2324ff4368.PNG)

### **> [ERROR] License key expired on 31 3 2020**

When building the WebAPI .war file using Maven, an error has occurred

**Comment by anthonysena** [comment]
For reference, this was solved by contacting miredot's support via email and requesting a new key.
