### ISSUE TITLE
Prevent trailing white spaces in asset names?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/WebAPI#1510]
Asset names (like cohort definition names, concept set names) currently allow trailing (and leading) white spaces. This is maybe not very pretty, and also can [lead to trouble downstream](https://github.com/OHDSI/CohortDiagnostics/issues/39#issuecomment-613944951).

Maybe trim asset names before storing them?

**Comment by olga-ganina** [comment]
Atlas PR is done, WebAPI will be added
