### ISSUE TITLE
Google OAuth couldn't be used for new projects due to legacy API still in use

### ISSUE THREAD

**Issue by wivern** [OHDSI/WebAPI#1511]
Google OAuth authentication in the WebAPI uses Legacy People API to retreive info about person who has logged in.
But this API is [deprecated](https://developers.google.com/people/legacy) since March 7, 2019 and cannot be used in new projects. This means none is able to deploy new WebAPI istance with Google OAuth authentication.
Google recommends migrate to the new People API.

**Comment by anthonysena** [comment]
Looks like this has been fixed for 2.7.7 - can you make a PR for 2.8.0? Also, it appears that this closed out #1502 as well?

**Comment by chrisknoll** [comment]
Does this update require JDK 11?

**Comment by anthonysena** [comment]
@chrisknoll - just checked this on my side and for me the 2.7.7 build used opensaml-saml-api 3.2.0 which is JDK8 compatible.

**Comment by chrisknoll** [comment]
odd...I pulled the commits from the 2.7.7 branch which led to that error I reported, so...I don't know how that happened.
