### ISSUE TITLE
Invalid combo_IDs being generated in pathway analysis (leading to duplicates)

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#1518]
### Expected Results
Only one event cohort should appear in the pathway analysis combo_id's set where `is_combo == true`.

### Actual Results
Event cohorts are being duplicated. Looking at the `pathwy_analysis_codes` results, we observe combo_ids where `is_combo == 0`. but the combo ID is not a perfect power of 2 (as all non-combos should be individual cohorts, where the combo_id = pow(2,index)).

### Steps to reproduce

I'm having difficulty determining the exact way to reproduce this, but some errors I am seeing are:

- In a analysis with 11 event cohorts (indexed, 0..10), the max combo ID should be pow(2,11)-1 = 2047.  However, I'm seeing comboIDs of 2116, 2306, etc.  This would indicate that there are duplicated event cohort rows that are causing the same event cohorts to be counted together, leading to cases where we add the same cobo_id more than once, which breaks the binary addition at the core of the pathway analysis process.

**Comment by mayakamay** [comment]
[RunPathwayAnalysis.txt](https://github.com/OHDSI/WebAPI/files/4549064/RunPathwayAnalysis.txt)

**Comment by mayakamay** [comment]
hi Chris, this might be helpful in solving the problem, one of our collaborator found out the issues and fixed it in the sql code.

**Comment by chrisknoll** [comment]
Hi, @mayakamay, 
  The modification to use DISTINCT works in only certain cases.  I have a commit [here](https://github.com/OHDSI/WebAPI/commit/7c11efbf04547860a4b9b505c433d264792fc1f9) that creates eras out of the individual event cohort episodes (which is required to prevent duplicate overlapping episodes after the collapse logic is applied).  As an added benefit, the change also will only do the additional work of collapsing the dates (and finding date replacments) if the gap_window paramater is set (ie: > 0).
