### ISSUE TITLE
Different display of the number of files for old and new results PLP/PLE

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1529]
For new executions(238 filles, there may be a misunderstanding from user side):
![image](https://user-images.githubusercontent.com/56290675/81302462-17a49900-9083-11ea-872a-4aa270d3f79d.png)
archive:
![image](https://user-images.githubusercontent.com/56290675/81302519-2a1ed280-9083-11ea-8385-91d2b5b2932e.png)

For previous executions(which were made on lower version WebApi):
![image](https://user-images.githubusercontent.com/56290675/81302979-c6e17000-9083-11ea-8e5e-6721672ccbd3.png)
archive:
![image](https://user-images.githubusercontent.com/56290675/81303125-f98b6880-9083-11ea-9b9d-24489c73434b.png)

**Comment by YaroslavTir** [comment]
there is such an issue, this related to the fact that in the database we still store one archive file, and a correct number of files can be calculated only in analyzes execution time, so all analysis that runs against execut_engine of version 1.16.0 would have the wrong number of files(2 or 3). we can fix it by running a script to calculate the file amount, but this script is going to be slow and can take a lot of time.

**Comment by YaroslavTir** [comment]
after discussion 
![image](https://user-images.githubusercontent.com/3305166/81306044-50db0a00-907f-11ea-85c9-44c021b01361.png)
