### ISSUE TITLE
Unauthenticated Message Even Though Security is Disabled

### ISSUE THREAD

**Issue by CartWill** [OHDSI/WebAPI#1531]
Trying to setup a testing sandbox without security but get a message that I don't have access on Search.  Security is disabled in Atlas site and in security.provider in settings.xml is set to DisabledSecurity

`<security.provider>DisabledSecurity</security.provider>`

Opened this on the Atlas project but maybe it's a backend issue. 
 https://github.com/OHDSI/Atlas/issues/2197

**Comment by anthonysena** [comment]
Hi @CartWill - I think this may be due to the 'priority' setting you have on your vocabulary and results `source_daimon` entries. Can you try to set these to 1 or higher and see if that resolves the issue?

**Comment by CartWill** [comment]
That's worked.  Thank you @anthonysena!
