### ISSUE TITLE
Characterization import skips features

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#1538]
### Expected behavior

When importing a characterization design, all associated elements of the design (including custom features) are imported.

### Actual behavior

Under certain circumstances (see below) features are not imported nor are any warnings/errors thrown.

### Steps to reproduce the problem

[This design file](https://github.com/OHDSI/WebAPI/files/4624072/cc-features-not-imported.zip) has 9 features that were defined as part of the study. When it is imported, it only imports 2 of the 9 features.

Tracing through the code, [the importAnalyses](https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java#L979) attempts to prevent duplicate features during the import. At the moment, it only considers the feature's `design` property. In the attached design, you'll see that the features share a common design but differ in what concept sets are used. 

As a suggestion for this issue: we should consider the design but also the concept sets. We should also consider the domain and stat type since those could differ based on how the user would like to see that feature in the results.

**Comment by aklochkova** [comment]
a version of circe-be should be raised to `1.8.6` after the merge of  https://github.com/OHDSI/circe-be/pull/125

**Comment by KSadomtsev** [comment]
![image](https://user-images.githubusercontent.com/56290675/88906357-06bd8b00-d260-11ea-9635-7a0a017116e3.png)
Tested
