### ISSUE TITLE
When I build the WebAPI i get a License key expired ERROR?

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/WebAPI#1549]
[INFO] Building war: D:\Github\WebAPI\target\WebAPI.war
[INFO] Packaging classes
[INFO] Building jar: D:\Github\WebAPI\target\WebAPI-classes.jar
[INFO]
[INFO] --- miredot-plugin:2.1.2:restdoc

......

[ERROR] License key expired on 31 Mar 2020
[WARNING] Rest Framework not explicitly set, using JAX-RS by default.

WebAPI.war is generated correctly.

**Comment by chrisknoll** [comment]
This is in master, you can copy from [this commit](https://github.com/OHDSI/WebAPI/commit/db05136ff685758d8247b56b98d2f9711260a007) into your local env and rebuild.
