### ISSUE TITLE
ACHILLES reports and caching

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1551]
Every time when opening Achilles reports it takes minutes to load it for the first time.
It should already be cached and cache shared across users and sessions.

**Comment by chrisknoll** [comment]
Just FYI: there is some level of caching in effect for the top-level reports under Data Sources (aka: Achilles).  Example [here](https://github.com/OHDSI/WebAPI/blob/d6e010c0e1573c01c9df03e3966ba38be2bfed0e/src/main/java/org/ohdsi/webapi/service/CDMResultsService.java#L279).  If we want to expand on caching, that is a good idea, but please don't ignore the current functionality.

Also, it appears that we do cache the drilldowns...I wonder if caching is enabled for you (there should be default settings for that).  I'm also wondering why it would be taking 'minutes', these queries are simple reads from the DB (possibly a join to a vocabulary table to resolve the concept names?) Is there possibly a problem with your environment?

**Comment by konstjar** [comment]
I found this problem:
Yesterday - I opened all reports and wait all of the were loaded. Next attempts to open show that data is taken from cache.
Today - I open reports again and it takes time to load them. So the data is not taken from cache.
Does it mean cache logic or system makes clean up?

**Comment by chrisknoll** [comment]
that's correct there's a timeout on the cache, defined [here](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/config/ehcache.xml).

**Comment by konstjar** [comment]
@chrisknoll Thank you for detailed feedback. I'm trying to figure out if there is advantage of this. 
Our use case - reports are visited occasionally, let's say once a week. Every time users needs to wait for about 1-10 minutes report to be opened. Is there an option to disable this timeout and let's say refresh the cache with "refresh" button on Configuration screen?

**Comment by gklebanov** [comment]
When caching for ACHILLES was suggested some time ago, I had the following in my head:

 - do an application level caching vs. session level one so that cache can be shared across all users and save some server resources
 - populate cache when ATLAS is starting vs. when user is hitting a report for the first time. The issue is that users might be hitting this report just to look something up one time and caching "first time use" approach just defeats the whole purpose. And this is definitely what I am seeing today
- refresh cache only as data set or ACHILLES changes. No need to invalidate cache every X minutes or even days unless there is a change in data
- have an ability in admin interface to invalidate and reload ACHILLES reports

how was it actually implemented? Do you agree with the bullet points above?

**Comment by chrisknoll** [comment]
@konstjar , the origional PR #1070, I asked if there was a mechanism to override cache settings via settings.xml, and I can't recall if I received an answer to this offline, or via some other thread.  But, the idea on using a external .xml file to store this configuration was specifically to allow site-specific implementation configuration to override these settings.  I'm feeling like I was misled if this isn't something that is actually possible.  Maybe we can change the default timeout options for these to never time out.  There is an endpoint to [clear the cache](https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/cache/CacheService.java#L55) , so it's possible to specify an infinite timeout on the cache for datasoures, and rely on the cache/clear endpoint for resetting the data-source data.

@gklebanov : 
application level vs. session level: what were you suggesting, one or the other, or supporting some level of both?
startup cache: We could have data write records into the ehcache subystem during startup, it would just involve creating a Spring bean that runs once during startup.
refresh cache: right, we can set no timeout and depend on the cache/clear endpoint to remove dirty data.
admin interface:  it's just an endpoint to WebAPI, so I assume that it would be simple to add a button somewhere where admins could clear the cache.

**Comment by gklebanov** [comment]
@chrisknoll  - sorry, my comment was confusing

> "application level vs. session level: what were you suggesting, one or the other, or supporting some level of both?"


I was suggesting we should be using the application level cache that is shared across all users.

**Comment by chrisknoll** [comment]
Ok, that's what we are doing...ehcache is a server-side cache that is managed by Spring.
