### ISSUE TITLE
Result schema for IMPALA is built incorrectly

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1553]
steps:
1) open /WebAPI/ddl/results?schema=results&dialect=impala&vocabSchema=cdm
2) Find part "Populate the hierarchy lookup table per treemap"

**expected**:
 snomed.concept_id,
    CAST(snomed.concept_name AS VARCHAR(400)) AS snomed_concept_name,
	CAST('Condition' AS VARCHAR(20)) AS treemap,
	CAST(pt_to_hlt.pt_concept_name AS VARCHAR(255)) AS pt_concept_name,
	CAST(hlt_to_hlgt.hlt_concept_name AS VARCHAR(255)) AS hlt_concept_name,
	CAST(hlgt_to_soc.hlgt_concept_name AS VARCHAR(255)) AS hlgt_concept_name,
	CAST(soc.concept_name AS VARCHAR(255)) AS soc_concept_name

**actual**:
 snomed.concept_id,
    snomed.concept_name AS snomed_concept_name,
	CAST('Condition' AS VARCHAR(20)) AS treemap,
	pt_to_hlt.pt_concept_name,
	hlt_to_hlgt.hlt_concept_name,
	hlgt_to_soc.hlgt_concept_name,
	soc.concept_name AS soc_concept_name

**Comment by wivern** [comment]
@KSadomtsev Just to clarify, why field casts, not string literals, is expected?

**Comment by konstjar** [comment]
![image](https://user-images.githubusercontent.com/4144173/84130905-25638a80-aa44-11ea-9b2a-0abc21c04d4f.png)
+ multiple same issues

**Comment by konstjar** [comment]
Todo: investigate the reason please
