### ISSUE TITLE
concept_hierarchy does not exist error

### ISSUE THREAD

**Issue by SungJun9212** [OHDSI/WebAPI#1555]
The error occurred in the in data source/Drug in Atlas, and I checked the tomcat log.

-------------------------------
SELECT
  concept_hierarchy.concept_id                        AS concept_id,
  CONCAT(
    COALESCE(concept_hierarchy.level4_concept_name,'NA'), '||',
    COALESCE(concept_hierarchy.level3_concept_name,'NA'), '||',
    COALESCE(concept_hierarchy.level2_concept_name,'NA'), '||',
    COALESCE(concept_hierarchy.level1_concept_name,'NA'), '||',
    concept_hierarchy.concept_name
  ) AS concept_path,
  ar1.count_value                                     AS num_persons,
  ROUND(CAST(1.0 * ar1.count_value / denom.count_value AS NUMERIC),5) AS percent_persons,
  ROUND(CAST(1.0 * ar2.count_value / ar1.count_value AS NUMERIC),5)   AS records_per_person
FROM (SELECT *
      FROM webapi.ACHILLES_results WHERE analysis_id = 700) ar1
  INNER JOIN
  (SELECT *
   FROM webapi.ACHILLES_results WHERE analysis_id = 701) ar2
    ON ar1.stratum_1 = ar2.stratum_1
  INNER JOIN
  webapi.concept_hierarchy concept_hierarchy
    ON CAST(ar1.stratum_1 AS INT) = concept_hierarchy.concept_id
  AND concept_hierarchy.treemap='Drug'
  ,
  (SELECT count_value
   FROM webapi.ACHILLES_results WHERE analysis_id = 1) denom

ORDER BY ar1.count_value DESC
---------------------------------

'webapi' is result schema.

And this is my result_schema tables.

i'm used postgresql 10.

After deploying the WebAPI.war file.
This is the result of the query 

=======================
SELECT * FROM pg_catalog.pg_tables where schemaname='webapi' order by tablename;
=======================
"achilles_analysis"
"achilles_heel_results"
"achilles_results"
"achilles_results_derived"
"achilles_results_dist"
"analysis_execution"
"analysis_generation_info"
"batch_job_execution"
"batch_job_execution_context"
"batch_job_execution_params"
"batch_job_instance"
"batch_step_execution"
"batch_step_execution_context"
"cc_analysis"
"cc_cohort"
"cc_param"
"cca"
"cca_execution"
"cca_execution_ext"
"cohort"
"cohort_analysis_gen_info"
"cohort_analysis_list_xref"
"cohort_characterization"
"cohort_concept_map"
"cohort_definition"
"cohort_definition_details"
"cohort_features"
"cohort_features_analysis_ref"
"cohort_features_dist"
"cohort_features_ref"
"cohort_generation_info"
"cohort_inclusion"
"cohort_inclusion_result"
"cohort_inclusion_stats"
"cohort_study"
"cohort_summary_stats"
"concept_of_interest"
"concept_set"
"concept_set_generation_info"
"concept_set_item"
"concept_set_negative_controls"
"drug_hoi_evidence"
"drug_hoi_relationship"
"drug_labels"
"estimation"
"evidence_sources"
"exampleapp_widget"
"fe_analysis"
"fe_analysis_conceptset"
"fe_analysis_criteria"
"feas_study_generation_info"
"feas_study_inclusion_stats"
"feas_study_index_stats"
"feas_study_result"
"feasibility_inclusion"
"feasibility_study"
"heracles_analysis"
"heracles_heel_results"
"heracles_results"
"heracles_results_dist"
"heracles_visualization_data"
"input_files"
"ir_analysis"
"ir_analysis_details"
"ir_analysis_dist"
"ir_analysis_result"
"ir_analysis_strata_stats"
"ir_execution"
"ir_strata"
"laertes_summary"
"output_files"
"pathway_analysis"
"pathway_event_cohort"
"pathway_target_cohort"
"penelope_laertes_uni_pivot"
"penelope_laertes_universe"
"plp"
"prediction"
"schema_version"
"sec_permission"
"sec_role"
"sec_role_group"
"sec_role_permission"
"sec_user"
"sec_user_role"
"source"
"source_daimon"

**Comment by SungJun9212** [comment]
I need to manually run the results DDL?

**Comment by chrisknoll** [comment]
Yes.  Some references:

https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration
https://forums.ohdsi.org/t/ddl-scripts-for-results-achilles-results-derived-etc/9618/13
https://forums.ohdsi.org/t/how-can-i-excute-sql-file-in-the-webapi-ddl-resuls/9773/10
https://forums.ohdsi.org/t/cohort-generation-in-atlas-with-generation-status-failed/5690/25
https://forums.ohdsi.org/t/oracle-webapi-schema-not-created/4851/6
https://forums.ohdsi.org/t/webapi-source-source-daimon-configuration-for-postgresql/1631/7

Closing this thread, but please follow up if you have any other questions.
