### ISSUE TITLE
V2.8.0.20190531181956__alter_job-execution-params_string-val fails in Oracle

### ISSUE THREAD

**Issue by Andreyyiv** [OHDSI/WebAPI#1563]
The[ V2.8.0.20190531181956__alter_job-execution-params_string-val.sql migration script](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/db/migration/oracle/V2.8.0.20190531181956__alter_job-execution-params_string-val.sql) fails in Oracle due to the incorrect datatype:

`ALTER TABLE ${ohdsiSchema}.user_import_job ADD (user_roles VARCHAR);`

It should be

`ALTER TABLE ${ohdsiSchema}.user_import_job ADD (user_roles VARCHAR2(size) );`

We used `size` of 1000 as a database-safe value, but it is unclear if this length is enough for WebAPI. Currently the table is empty anyway.

**Comment by chrisknoll** [comment]
Fixed in d511384dee06d45e23dce4f1190be49fa71e49b9.
