### ISSUE TITLE
Losing events in patent profile for events that occur on same day but in different visits

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#158]
With @jswerdel, I discovered a problem with patient profiles where domain events that occur on the same day (but different visits) are lost in the patient profile view.

Example, the data in condition occurrence table looks like this:

|condition_occurrence_id|condition_concept_id|condition_start_date|visit_concept_id|
|----|----|----|----|
|1|12345|2006-08-01|9037|
|1|12345|2006-08-01|9038|

(Obviously these concept IDs are made up, but visit_concept id is IP and ER in the above example)

The problem is if you look at the tabular data in the patient profile, it looks like there's just one event of concept_id 12345 X number of days after the cohort start date.  It appears that the patient profile is doing a DISTINCT concept_id, start_date (or concept_id, days_from_index). If you create a cohort inclusion rule looking for at least 2 occurrences of 12345, a person is going to be chosen (the raw data has 2) but the profile only shows one.

Possible solution is to include the visit type in the profile table and use the visit_concept_id as part of the distinct clause so that it will not lose those events that occur on the same day in different visits.

**Comment by mpozhidaeva** [comment]
I had a attempt to reproduced the behavior:
source data for person_id = 5441
![source_data](https://user-images.githubusercontent.com/31308645/49008052-f812fc80-f17d-11e8-9177-39632e567077.png)
profile:
![profile](https://user-images.githubusercontent.com/31308645/49008160-37d9e400-f17e-11e8-9406-543677f9d2f2.png)

**Comment by mpozhidaeva** [comment]
@chrisknoll - could you review my attempt to reproduce the bug, please? Is it possible to add some details for reproducing or can I close the issue?

**Comment by chrisknoll** [comment]
It looks like you've reproduced the issue.  I think my initial post proposes a solution?  Why would you want to close this?

**Comment by mpozhidaeva** [comment]
Sorry for my misunderstanding - but in the profile (the second screenshot) I see both concepts (with a difference only in visit_occurrence_id) and nothing is lost

**Comment by chrisknoll** [comment]
I'm sorry, I also had a misunderstanding:  the original issue was that the DISTINCT was used (ignoring the visit_occurrence_id) thus dropping the appearance of a visit (the visualization was out of sync with the actual multiple visits).  But, when you showed me the screenshot, I thought the issue was duplicate rows (where we'd need to see visit_occurrence_id  to know that it was from 2 different visits) but that would be a different issue.

Yes, the original issue (of rows being lost) is resolved per your example. Thank you.

If we think that those rows need to be 'de-duped' by adding additional info such as the visit ocurrence ID, we can open that as a separate issue.
