### ISSUE TITLE
Application initialization failed for users without "Atlas users " role

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1584]
WebApi 2.7.7

Steps:
1)Login by any user with only "public" role

Expected:
Home page is available

Actual:
![image](https://user-images.githubusercontent.com/56290675/88166287-b327bd80-cc1f-11ea-98d9-df1ee06f0bf8.png)

**Comment by ssuvorov-fls** [comment]
Not reproduced in 2.7.8
Need to be retested after deploy

**Comment by KSadomtsev** [comment]
![image](https://user-images.githubusercontent.com/56290675/88381246-be5d2380-cdae-11ea-8090-f25b17130bda.png)
Tested

**Comment by KSadomtsev** [comment]
Tested
