### ISSUE TITLE
link to installation guide redirects back to repo

### ISSUE THREAD

**Issue by blm14** [OHDSI/WebAPI#159]
In the readme there is a link to a new installation guide and the URL given is: 

https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide

Clicking that links redirects back to the repo landing page. I want to install webAPI but without being able to access the wiki this will be difficult :)

**Comment by hirschf** [comment]
@blm14 Issue has been resolved, please see the README for installation instructions.
