### ISSUE TITLE
Impossible to delete Feature Analysis

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1596]
webApi 2.7.8 

1)Login by the user which has permissions for Feature Analysis 
2) Characterization -> Feature analysis -> new New Feature Analysis
3) Set name -> Set some description -> Set Analysis type -> Add Criteria Feature
4) Click save
5) Try to delete

Expected:
Feature Analysis is deleted

Actual:
button is disabled
![image](https://user-images.githubusercontent.com/56290675/89196422-d99c1000-d5b2-11ea-9431-e9b6167b8b45.png)

**Comment by wivern** [comment]
This affects not only Feature Analyses but for example Concept Sets too. Probably also some others.
