### ISSUE TITLE
The query processor ran out of stack space during query optimization. Please simplify the query.

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/WebAPI#1601]
Since the recent change in codesets query template - where all codesets are union'ed together - i have noticed this issue

https://github.com/OHDSI/CohortDiagnostics/issues/180

When there are more than 100 unions (which happens frequently) - the query fails as shown above. This has broken CohortDiagnostics run orphan concepts check - when running on a large number of cohorts

**Comment by anthonysena** [comment]
Appears to be CohortDiagnostics specific and closed via https://github.com/OHDSI/CohortDiagnostics/commit/9b85c08161999adb75b60993625743611dcca2fb
