### ISSUE TITLE
WebAPI 2.2.7 cant query from concept_hierarchy when using BigQuery

### ISSUE THREAD

**Issue by javier-gracia-tabuenca-tuni** [OHDSI/WebAPI#1611]
We are getting the attached error when intialising webAPI

[ohdsi_webapi_error_message.txt](https://github.com/OHDSI/WebAPI/files/5117269/ohdsi_webapi_error_message.txt)

SimbaJDBCDriverforGoogleBigQuery42_1.2.4.1007 
WebAPI 2.7.7
Atlas 2.7.7
Synpuf1k v5.3.1 
3 schemas in BigQuery 1:cdm+vocab 2:results 3:tmp

**Comment by konstjar** [comment]
Google BigQuery JDBC drive v1.2.4 works incorrectly. It was reported to Google and Simba.
Workaround is to use driver with older version 1.2.0-1.2.2

**Comment by braincow** [comment]
@konstjar thank you. this resolved the issue we were seeing.

**Comment by javier-gracia-tabuenca-tuni** [comment]
Thanks a lot,  @konstjar 

Should it be coded in the pom.xml file, so that any build forces such versions ??
