### ISSUE TITLE
Cohort definition status typo in status indicator

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1622]
webAPi version 2.8 and earlier

it should be COMPLETED
![image](https://user-images.githubusercontent.com/56290675/92583167-9d875980-f29a-11ea-9a12-8cece3274441.png)

status comes from backend:
[{“id”:{“cohortDefinitionId”:794,“sourceId”:10956},“startTime”:1598263077805,“executionDuration”:4340,“status”:“COMPLETE”,“isValid”:true,“isCanceled”:false,“includeFeatures”:false,“failMessage”:null,“personCount”:40303,“recordCount”:40303,“canceled”:false,“message”:null}]

**Comment by chrisknoll** [comment]
What are you basing this on? The status defined in the WebAPI are found here:
https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/GenerationStatus.java
And converted here:
https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/GenerationStatusConverter.java

Are you saying that from an aesthetic perspective it should be displayed differently, or are you calling for a change in the API to rename status codes?  The latter is a bit more involved and breaking than the former of just formatting the status code differently.

I'm not sure I understand the value of this issue in the first place...
