### ISSUE TITLE
info method calls during cohort creating

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1624]
ATLAS Version 2.8.0 DEV Release Notes
WebAPI Version 2.8.0 DEV Release Notes

steps:
1)Cohort definitions 
2)Click to create new cohort
3)Wait for a few seconds

Expected:
info method is not called until the cohort will be saved

Actual:
info method is called 
we get 500 error
![image](https://user-images.githubusercontent.com/56290675/92896154-ce939580-f424-11ea-9a83-4741111358f5.png)
":"An exception ocurred: java.lang.IllegalArgumentException","localizedMessage":"An exception ocurred: java.lang.IllegalArgumentException

**Comment by anton-abushkevich** [comment]
Related to OHDSI/Atlas#2312
