### ISSUE TITLE
Incidence rates performance drop

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1630]
WebAPI Version 2.8.0 DEV 
[diabetes.txt](https://github.com/OHDSI/WebAPI/files/5244715/diabetes.txt)

Steps:
1) Import analysis from file
2) Run analysis

Expected:
performance of analysis is quite the same as the previous versions(Screenshot from 2.7.8)
![image](https://user-images.githubusercontent.com/56290675/93583040-f8f8cc00-f9ab-11ea-9ce8-ae496ab31e6a.png)

Actual:
The duration was increased to one hour(Tried on few postgress data sources)
![image](https://user-images.githubusercontent.com/56290675/93583263-47a66600-f9ac-11ea-96ef-693b94a9d340.png)

**Comment by chrisknoll** [comment]
I can't remember any recent updates to the IR analysis job...do you know what may have changed there?
