### ISSUE TITLE
Impala SQLException(Impala does not support modifying a non-Kudu table)

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1631]
webApi 2.8

Steps:
1) Cohorts Definitions 
2) Run any cohort on IMPALA

Expected:
Successful running

Actual:
org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [DELETE FROM synpuf_53_test_results_280.cohort_inclusion WHERE cohort_definition_id = 46]; SQL state [HY000]; error code [500051]; [Cloudera][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AnalysisException: Impala does not support modifying a non-Kudu table:

**Comment by chrisknoll** [comment]
Is this a WebAPI issue, or simply a matter of setting up the results schema on impala using Kudu-based tables (so that they can be modified)?

**Comment by ssuvorov-fls** [comment]
@chrisknoll it's not a WebAPI issue. We had the same problem earlier, when we tried to modify non-Kudu table

**Comment by chrisknoll** [comment]
Ok, will close this out since it's not a WebAPI issue, but we may want to include additional information in documentation instructing the proper configuration of the results schema.

**Comment by ssuvorov-fls** [comment]
@Chris, sorry, I was wrong - it was a bug in WebAPI

**Comment by chrisknoll** [comment]
More like a bug in JDBCTemplate that we have to work around, but yes, I get your point. Thanks.
