### ISSUE TITLE
Expose whether or not security is enabled 

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/WebAPI#165]
Perhaps a SystemService or ConfigurationService that can expose the current security settings. This will allow clients to know whether or not they should expect authentication with the WebAPI to be possible / required during interaction.

**Comment by anthonysena** [comment]
As noted in #266, also consider adding in the uptime for the service to the /info endpoint.

**Comment by pavgra** [comment]
The proposed solution is to add "configuration" key into the JSON provided by `/info` endpoint where we could reflect whether certain features are enabled or how they are configured in the current Atlas instance or nor. E.g.:

```
/info

{
  "metadata": {
    "artifactVersion": "WebAPI 2.8.0-SNAPSHOT",
    "build": "NA",
    "timestamp": "Thu Aug 08 22:38:33 UTC 2019",
    "version":"2.8.0"
  },
  "configuration": {
    "security": { "enabled": true },
    "person": { "viewDates": false },
    "heracles": { "smallcellcount": 5 }
  }
}
```

**Comment by chrisknoll** [comment]
Let's try not to break backwards compatability with this interface. Adding a configuration map is ok, but redirecting the other elements under 'metadata' I think would remove where version is found.  How about we have 2 top level properties: configuratio, build, and put the build info under build....the version can be a top-level property, as well as uptime, etc.

**Comment by pavgra** [comment]
@chrisknoll , ok, that sounds reasonable
