### ISSUE TITLE
Cohort Analysis Missing Tables 

### ISSUE THREAD

**Issue by grisha1776** [OHDSI/WebAPI#1656]
Hi,
I have a question: after creating and generating cohort, I ran Analysis in "Report" tab, then I have a list of reports, but I do not see there reports on **Observation** and **Measurement** tables.
And if there are no such reports, how can I get/add them to the Heracles run?
Thanks in advance

**Comment by anthonysena** [comment]
I'd suggest using the cohort characterization module instead for observation and measurements. For more details, please see https://ohdsi.github.io/TheBookOfOhdsi/Characterization.html.
