### ISSUE TITLE
Update cdmresults service path

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#166]
The current format of the cdmresultsservice path is to prefix the route with a source key and then /cdmresults. The issue is that we must provide a source key to get to anything in this route, but there's cases where we'd want to get information at the webapi level that is not source specific.

For example, we might have a results statistic table that stores information about the sources which have generated results and information about when the run was executed (for all databases). This information would be store din the webAPI schema and read from the route /cdmresults.

Or: an external process may finish a cdm results and update this webAPI table and need to decache the stats, so a route like /cdmresults/refresh might be required.

The solution is to have the path to the cdm results service start as /cdmresults and then any source specific results are fetched via /cdmresults/{source}.

**Comment by anthonysena** [comment]
Closed via 6c3c7242e79a2810ec3fec28202e0001782b190d
