### ISSUE TITLE
[Geospatial] Not obvious the meaning of values from density

### ISSUE THREAD

**Issue by KSadomtsev** [OHDSI/WebAPI#1678]
WebAPi:2.8

Steps:
1)Generate any cohort on geo source
2)Load density

Exected:
Values are clear

Actual:
We get only one values(interval) for every area
![image](https://user-images.githubusercontent.com/56290675/98932327-3f703000-24f0-11eb-90d2-a58c6cd5be49.png)

https://testatlas.arachnenetwork.com/WebAPI/gis/cohort/245/density
`{"type":"FeatureCollection","features":[{"type":"Feature","id":0,"properties":{"level":"< 1e-08","min":-0.0,"max":1.0E-8},"geometry":{"type":"Polygon","coordinates":[...`

**Comment by ablack3** [comment]
I suggest that the density tooltip be removed since the actual density value is not very interpretable. In a future update you may consider using color to represent different density ranges as in the example here: http://bl.ocks.org/diegovalle/5166482
