### ISSUE TITLE
Oracle migrations failed

### ISSUE THREAD

**Issue by anton-abushkevich** [OHDSI/WebAPI#1680]
Application fails to start on Oracle DB (tested on 19c). Problem migrations:

V2.7.8.20200728164800__add_conceptset_permission.sql
V2.8.0.20200109100200__cohort_sample_tables.sql
V2.8.0.20200122173000__insert_cohort_sample_permissions.sql
V2.8.0.20201022120031__concept_ancestor_and_descendants.sql

**Comment by chrisknoll** [comment]
Any update on this?
