### ISSUE TITLE
Installation instruction diagram not showing in Wiki

### ISSUE THREAD

**Issue by schuemie** [OHDSI/WebAPI#1687]
[These instructions](https://github.com/OHDSI/WebAPI/wiki) are linked from the repo README:

![Capture](https://user-images.githubusercontent.com/6713328/99223571-0c29eb80-27e5-11eb-8aa2-37f42dc5445f.PNG)

**Comment by chrisknoll** [comment]
I'm not sure why, but I do see it when I go to the URL provided:
![image](https://user-images.githubusercontent.com/6818777/99271924-308dc400-27f5-11eb-8d67-f68cff8590cc.png)

@schuemie : can you go to your browser console, try to find the requested URL that returned a 404 (or some other error) for the image?

**Comment by schuemie** [comment]
That is so weird. It still doesn't show for me on my laptop, neither in Chrome nor in Edge (ruling out caching issues). But if I click 'Open image in a separate tab' the image shows. And if I go to the site on another machine, it also works fine. If its just my laptop, then I can live with it ;-)
