### ISSUE TITLE
Vulnerabilities in postgresql

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WebAPI#1698]
We found a number of vulnerabilities (identified by Snyk) in the WebApi. Most of which can be fixed easily by updating the dependencies.

## Issues
XML External Entity (XXE) Injection. Introduced through: org.postgresql:postgresql@9.4-1201-jdbc41
> The PgSQLXML class used for parsing was found to allow external entities and multiple doc types which could allow XXE attacks.

Man-in-the-Middle attack. Introduced through: org.postgresql:postgresql@9.4-1201-jdbc41
> It was possible to provide an SSL Factory and not check the host name if a host name verifier was not provided to the driver.

## Remediation
- Upgrade to org.postgresql:postgresql@42.2.13

**Comment by konstjar** [comment]
@MaximMoinat can you please clarify the usage of PG in this case? Is it system WebAPI DB or you use PG as data source DB?

**Comment by MaximMoinat** [comment]
We use it for both. This vulnerability concerns both as well, because the WebAPI queries from all the databases connected to it.
