### ISSUE TITLE
v2.8.0 regression for MS SQL CAST->TRY_CAST statement fix

### ISSUE THREAD

**Issue by scivm** [OHDSI/WebAPI#1723]
https://github.com/OHDSI/WebAPI/issues/819 opened by @anthonysena  that was fixed with pull request https://github.com/OHDSI/WebAPI/pull/820 in V2.7.0 was regressed in V2.8.0.

It fixes an issue in MS SQL for view cc_generation but I think same fix should be applied to all views since I am seeing same error in pathway_analysis_generation

The fix was to change CAST to TRY_CAST

File V2.8.0.20190531181956__alter_job-execution-params_string-val.sql regresses the previous fix.

This only affects MS SQL.

**Comment by chrisknoll** [comment]
Note, the fix here should not be to update the existing migratino script, we'll just introduce a new migration script wich drops and re-creates the views with the proper definition.  Thanks.
