### ISSUE TITLE
Missed table qualifier correction?

### ISSUE THREAD

**Issue by mark-velez** [OHDSI/WebAPI#173]
Should 

    String resultsTableQualifier = source.getTableQualifier(SourceDaimon.DaimonType.CDM);

[here](https://github.com/OHDSI/WebAPI/blob/0118f2897b5b1ecfd28a1887996211c9b764d17f/src/main/java/org/ohdsi/webapi/service/CohortResultsService.java#L1421) be changed to below?

    String resultsTableQualifier = source.getTableQualifier(SourceDaimon.DaimonType.Results);

**Comment by chrisknoll** [comment]
Definitely, the results table qualifier should be set to the DaimonType.Results qualifier and not the DaimonType.CDM. Good catch.  Let me know if you'd like me to follow up on this or if you'd like to take it.

**Comment by chrisknoll** [comment]
Actually I have an open branch that is tweaking this file so I can handle this. I'll put it into my next pull request.

**Comment by mark-velez** [comment]
Ok great, thanks @chrisknoll!
