### ISSUE TITLE
Maven Build Fail. When it just have java 1.8 version.

### ISSUE THREAD

**Issue by ParkChanghHyun** [OHDSI/WebAPI#1735]
It's my Environment.
-java 1.8
-Eclipse (2020-09)
.
.
.

When I try maven build ( in this commend line "mvn clean~~"), it occurred Error like bellow.
「Could not find arrifact com.sun:tools:jar:1.6.0 at specified path ~~~」

![image](https://user-images.githubusercontent.com/45930454/103990611-dd246a80-51d4-11eb-862a-bfec23a619d4.png)

NOW I SOLVED THIS ERROR. 
But I want to ask updating WebAPI. 

First of all in the wiki, recommend java version is 1.8.
But this error is about when it excute maven build , it need java(version1.6) in some part.

So in first commend "mvn clean ~", I builded WebAPI with java(1.6). => It surely faced other error.
And then change the java version(1.6->1.8).
Then It can pass this error.

I just wonder is it the best thing to avoid this error.
Can I have advice?

**Comment by chrisknoll** [comment]
You're not compiling this with JDK8, as indicated in your error message:  "Could not find artifact com.sun:tools:jar:1.6.0 at specified path C:\Program Files\java\ **jdk-14.0.2** \...lib\tools.jar".
