### ISSUE TITLE
Vulnerabilities in bouncycastle

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/WebAPI#1737]
## Issues
Deserialization of Untrusted Data
> https://owasp.org/www-community/vulnerabilities/Deserialization_of_untrusted_data

Information Exposure
> https://www.immuniweb.com/vulnerability/information-exposure.html

Insecure Encryption
> https://owasp.org/www-project-mobile-top-10/2016-risks/m5-insufficient-cryptography

## Remediation
- Upgrade to org.bouncycastle:bcprov-jdk15on@1.68

**Comment by chrisknoll** [comment]
Just remember, we're limited to jdk 8 until WebAPI 3.0 (where we can make platform-level changes). Do you know fi there's a secure dependency based on JDK8?

**Comment by ssuvorov-fls** [comment]
@chrisknoll I will raise only minor version of bouncycastle
