### ISSUE TITLE
Vulnerabilities in log4j

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/WebAPI#1741]
## Issues
Deserialization of Untrusted Data
> https://owasp.org/www-community/vulnerabilities/Deserialization_of_untrusted_data

## Remediation
- Upgrade to log4j 2

**Comment by ssuvorov-fls** [comment]
Raising of major version can cause problems with configuration and other unpredictable behavior

**Comment by anthonysena** [comment]
Closed via #1970.
