### ISSUE TITLE
Exporting Patient Profiles

### ISSUE THREAD

**Issue by jswerdel** [OHDSI/WebAPI#175]
It would be useful to be able to export a patient profile into a csv/excel file.  The export should only bring over the items that are in the selected list, i.e., if certain criteria are selected such as conditions, then only the conditions should be in the export.  It would be a nice to have to be able to select the file where the export is going to go to be able to combine into multiple tabs in an excel file.

**Comment by anthonysena** [comment]
@jswerdel closing this since it is out of scope for the purposes of WebAPI's functionality.
