### ISSUE TITLE
Should Not Limit WebAPI to Supporting Only Postgres Database

### ISSUE THREAD

**Issue by anonymous34** [OHDSI/WebAPI#1768]
Our organization is reluctant to adopt after finding out the webapi database will not be supported after Atlas v3.0  This is an issue for our organization because while we can use open source tools, our CDM is on MS sql server and the team seemed reluctant to set up webapi on an opensource database (postgres) that the organization does not have enterprise support and that our DBAs do not support.  We want to keep everything on a single server.  We would like to adopt,  but this is a very limiting factor.

Thanks.

**Comment by chrisknoll** [comment]
Hello, @anonymous34 ,
  The community will be able to contribute PRs to implement migration scripts for non-postgresql databases, but the burden on the development team has forced us to limit WebAPI support to a single, open source platform.  This does not impact any CDMs, just WebAPI (which is transactional in nature, has DB constraints/FK references which is not a concern of the analysis queries on CDMs).  Just to be clear, the OHDSI tools support for CDMs handles 9+ database dialects and that is not changing.
