### ISSUE TITLE
Unable to view the report of Characterization on Netezza/Impala (GenericExceptionMapper)

### ISSUE THREAD

**Issue by DKashenko** [OHDSI/WebAPI#1783]
WebApi 2.8.1

### Expected behavior

The report is shown

### Actual behavior
<img width="191" alt="netezza_cc_results" src="https://user-images.githubusercontent.com/77493858/107925337-59089400-6f85-11eb-983f-164bc253ebee.png">
WebAPI/cohort-characterization/generation/7858/result

Request Method: POST
Status Code: 500

{"payload":{"cause":null,"stackTrace":[],"message":"An exception occurred: java.lang.reflect.UndeclaredThrowableException","localizedMessage":"An exception occurred: java.lang.reflect.UndeclaredThrowableException","suppressed":[]},"headers":{"id":"93185d51-131c-3322-ff9f-5968ad0f3d3f","timestamp":1613378809545}}
[log.txt](https://github.com/OHDSI/WebAPI/files/5980576/log.txt)

### Steps to reproduce behavior

1. Login by a user who has access to Netezza DS/Impala
2. Characterizations -> Run any valid analysis on Netezza/Impala
3. Try to view the report

**Comment by KSadomtsev** [comment]
Was CDM issue
