### ISSUE TITLE
OMOP v6 compatibility

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/WebAPI#1792]
### Expected behavior
The web API should be compatible with OMOP v6 which was released more than 2 years ago.

### Actual behavior
According to the documentation, it's only compatible with v5.

**Comment by anthonysena** [comment]
That's correct - we don't currently have support for CDM V6 per: https://ohdsi.github.io/CommonDataModel/cdm60.html. I'll close this out since our focus remains on V5.x.
