### ISSUE TITLE
How to test correct database connectivity?

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/WebAPI#1802]
How can I easily test that the connectivity to my CDM database is working properly? **Preferably not using any R packages, just plain HTTP requests.** Are there some endpoints I can check?

**Comment by anthonysena** [comment]
Hi @sdebruyn - to (finally) answer your question, you can use the end-point: 

`https://<server>/WebAPI/source/connection/<source_key>`

Hoping this helps.
