### ISSUE TITLE
CI tests failing

### ISSUE THREAD

**Issue by blootsvoets** [OHDSI/WebAPI#1805]
Unit tests and integration tests are currently failing both on my local machine and on Github actions. https://github.com/OHDSI/WebAPI/pull/1799 will disable running the tests so that GitHub actions at least check that the code is compiling. It would be good to fix the unit tests or remove tests that are no longer deemed useful.

**Comment by anthonysena** [comment]
Closing since this should be fixed with the PR and latest release of code. Thanks @blootsvoets!
