### ISSUE TITLE
Incorrect prevalence Standard Mean Difference calculation 

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#1812]
### Expected behavior
Standard Mean Difference (SMD) should be based on Austin paper, which for prevalence stats, you get the same magnitude but opposite direction if you calculate the prevalnce and 'anti-prevalence' of the same population (ie: std diff between males or std diff between females).

### Actual behavior
WebAPI uses an alternate form which does not exhibit the same performance as the Austin formula.

### Steps to reproduce behavior
Check the [implementation here](https://github.com/OHDSI/WebAPI/blob/26d2c8d97805f0b22207a913e156e5a7ff143230/src/main/java/org/ohdsi/webapi/cohortcharacterization/report/PrevalenceItem.java#L42).  Note the Austin calculation is defined as:

![image](https://user-images.githubusercontent.com/6818777/110376028-b2ae2c80-8020-11eb-95c4-ff2f6f895835.png)

This formula is for dichotomous (binary) variables and p-hats are the prevalence of the variable within each population.

**Comment by anthonysena** [comment]
Just noting that this was also addressed in FeatureExtraction via https://github.com/OHDSI/FeatureExtraction/commit/948217e0fc7dece790a2c7d0eb0f4c30b7b70426

**Comment by chrisknoll** [comment]
I looked at the calcuation, and when you have a 100% / 0% split between the two populations, it denominator produces 0.  I'm trying to figure out the best way to handle this, I was thinking +/- infinity or NaN but I'm not sure how JSON would serialize that...so I may return just a very large number for those cases.  

If anyone has thoughts on that, please let me know.

**Comment by chrisknoll** [comment]
I'm returning +/- Infinity in the response, but the JS will format those values as empty string, so it won't look strange in the UI.
