### ISSUE TITLE
Concept IDs are Truncated in JSON files

### ISSUE THREAD

**Issue by mfernandezchas** [OHDSI/WebAPI#1823]
This is just an example, for the pre-coordinated concept 45757528 for influenza measurements and the same would apply to other concepts, as a result of the scientific notation representation. This concept is being rounded up to 45757530 in GitHub:

https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/blob/master/inst/cohorts/114.json
"id" : 14,
                      "name" : "Influenza positive measurements pre-coordinated",
                      "expression" : {
                             "items" : [
                                    {
                                           "concept" : {
                                                  "CONCEPT_ID" : **4.575753e+07**,
                                                  "CONCEPT_NAME" : "Influenza A virus present",
                                                  "STANDARD_CONCEPT" : "S",
                                                  "STANDARD_CONCEPT_CAPTION" : "Standard",
                                                  "INVALID_REASON" : "V",
                                                  "INVALID_REASON_CAPTION" : "Valid",
                                                  "CONCEPT_CODE" : "181000124108",
                                                  "DOMAIN_ID" : "Measurement",
                                                  "VOCABULARY_ID" : "SNOMED",
                                                  "CONCEPT_CLASS_ID" : "Clinical Finding"
                                           },
                                           "isExcluded" : false,
                                           "includeDescendants" : true,
                                           "includeMapped" : false
                                    },

In contrast, the number representation for this concept is correct in the OHDSI Atlas instance:
https://atlas.ohdsi.org/#/cohortdefinition/209/export

{
      "id": 14,
      "name": "Influenza positive measurements pre-coordinated",
      "expression": {
        "items": [
          {
            "concept": {
              "CONCEPT_CLASS_ID": "Clinical Finding",
              "CONCEPT_CODE": "181000124108",
              "CONCEPT_ID": **45757528**,
              "CONCEPT_NAME": "Influenza A virus present",
              "DOMAIN_ID": "Measurement",
              "INVALID_REASON": "V",
              "INVALID_REASON_CAPTION": "Valid",
              "STANDARD_CONCEPT": "S",
              "STANDARD_CONCEPT_CAPTION": "Standard",
              "VOCABULARY_ID": "SNOMED"
            },
            "includeDescendants": true
          },

**Comment by anthonysena** [comment]
Hi @mfernandezchas - I'm going to close this out as this problem is not related to WebAPI but rather with the way in which we captured the cohort json in Charybdis. This issue is being tracked in https://github.com/ohdsi-studies/Covid19CharacterizationCharybdis/issues/80 and was addressed in this issue https://github.com/OHDSI/ROhdsiWebApi/issues/152.
