### ISSUE TITLE
CDM results - data density query error

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#183]
The data density web service call is failing on OHDSI.org

http://api.ohdsi.org/WebAPI/cdmresults/1PCT/datadensity

Tracing the error a bit reveals: 

_ERROR: column \"series_name\" does not exist\n  Position: 1616_

Tagging @t-abdul-basser for awareness. This error does not happen on our SQL Server instances internally so it is likely a PostgreSQL related issue with the queries utilized in the report.

**Comment by chrisknoll** [comment]
I did some tests on my local postrgesql just to see if AS was supported and order by clauses.

This results in a column not found error:

```sql
select source_name as "some_Name" from webapi.source
order by some_Name
```

But this does work:
```sql
select source_name as "some_Name" from webapi.source
order by "some_Name"
```

I'm not sure we can rely on the quoted identifiers of columns to be equally respected across databases, but I think at the very least if you refer to a column as being quoted, you have to refer to it as quoted in all contexts.

**Comment by t-abdul-basser** [comment]
Thanks @chrisknoll for drilling down on this. My fault: I should have covered this in postgres unit tests better. I will look into this.

**Comment by PRijnbeek** [comment]
I can confirm we have the same issue on postgresql with the new webapi 2.0.0 and atlas 2.0.0
