### ISSUE TITLE
Nexus does not have public repos

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1844]
@leeevans http://repo.ohdsi.org:8085/nexus/ does not have public repos anymore. Is there a reason for this?

**Comment by leeevans** [comment]
Anonymous (public) browsing was disabled in the recent upgrade of the OHDSI Nexus. 
Public access to download artifacts from the repo is still enabled. 

This was done as a security measure to reduce the exposure for internet web site attacks. Access to the OHDSI nexus website itself cannot be disabled completely when anonymous downloading is allowed.
