### ISSUE TITLE
Documentation for CDMResults service

### ISSUE THREAD

**Issue by vojtechhuser** [OHDSI/WebAPI#185]
This is an exciting feature.

> Achilles summary statistics are now exposed through REST end-points in the CDMResults service 

So no more .JSON exports?

Where can I find any documentation (or source code) for the CDMResults service?

**Comment by t-abdul-basser** [comment]
The REST endpoints are (for now, sparsely) documented in the [Miredot docs](http://webapidoc.ohdsi.org/job/WebAPI/ws/target/miredot/index.html). The corresponding service endpoint is `/CDMResults`.

**Comment by vojtechhuser** [comment]
the link is not working.

![image](https://cloud.githubusercontent.com/assets/7526119/23770587/969ce036-04e1-11e7-96b9-78f103e2835c.png)

**Comment by t-abdul-basser** [comment]
There is apparently a licensing issue with Miredot that @fdefalco mentioned in today's Arch Group Mtg. I believe that @fdefalco, @chrisknoll, @anthonysena and co will attend to that. If you want to see the docs for the REST endpoints before this isfixed you can use the Java Enterprise tool window in IntelliJ.

**Comment by gowthamrao** [comment]
The current url for documentation seems to b [here](http://webapidoc.ohdsi.org/index.html)
