### ISSUE TITLE
Question: can the ID of an OMOP record change?

### ISSUE THREAD

**Issue by sdebruyn** [OHDSI/WebAPI#1854]
Is it okay if the ID of a record changes between 2 ELT runs?

E.g. Person X with ID 1 is replaced with a record with the same Person X data, but now with ID 999. This change would occur consistently so that every other record referring this person, would also be using the new ID. So every condition in condition_occurrence would have person_id set to 999 after the change.

I know this is not an issue for the CDM tables, DQD and Achilles.

So the remaining tool that might cause an issue would be this WebAPI and the SQL it generates to create the cohort tables.

**Do the cohort tables have references to specific records in the CDM?**

**Comment by chrisknoll** [comment]
we don't store IDs of records anywhere, but we do store person_IDs, so if you are updating person_ids in the cdm tables, you should sync those updates over to the results schema.

Closing this as not a particular issue with WebAPI, but feel free to continue discussion here (or in the forums).
