### ISSUE TITLE
Explicitly state GeneratedValue strategy for entity ID columns.

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#187]
When updating to the latest Spring libraries described in #186, the GeneratedValue annotation (defaults to AUTO) no longer uses the IDENTITY strategy on MSSQL Server, but instead defaults to a spring-global sequencer:
```
select next value for webapi.hibernate_sequence
```

This is the behavior on PostgreSQL and Oracle, but should be made explicit, and potentially have a dedicated sequencer for each entity.  The challenge is creating the DDL for these sequencers that are initialized based on a value from a select max (id) from EntityTable. I'm sure this is possible on MSSQL, but more challenging on oracle.  

Alternatively, we can adopt the 'table-based' strategy which is proven to be more cross-platform friendly, tho slow when doing bulk inserts into the identity column (which is not something we do in our current webAPI anyways, so perhaps not a large issue).  Further research is required.

**Comment by anthonysena** [comment]
Think we got this with #324 so closing out this issue.
