### ISSUE TITLE
[COHORT CACHE ERROR]When "CDM" data updated,  Generated cohort_result fail to Data consistency!!! 

### ISSUE THREAD

**Issue by ParkChanghHyun** [OHDSI/WebAPI#1874]
### After cohort generate.->update "CDM data"->  cohort regenerate
=>It's result note update, because cache.
.
.
.

My environment is "WebAPI 2.80"
.
.
.

### This is detail SAMPLE

It 's data of "SypuF 5% sample"

**1. create cohort with only "DEATH" in 'Cohort Entry Events'(Because it is the simplest cohort)**

![image](https://user-images.githubusercontent.com/45930454/116522764-845a1880-a910-11eb-8da2-e49f8e28df1e.png)

**2. And then Generate Cohort.** 

![image](https://user-images.githubusercontent.com/45930454/116522822-91770780-a910-11eb-8028-ef6dafcd5aff.png)

**3. DELETE data in "cdm.death" (CNT change: 6921->3426)**

![image](https://user-images.githubusercontent.com/45930454/116524332-39410500-a912-11eb-9436-a39a086a3a1e.png)

**4. And then regenerate Cohort.**
(Result should be changed but it is not)
![image](https://user-images.githubusercontent.com/45930454/116527448-a30ede00-a915-11eb-9306-cc99e8d8dc3f.png)

---------------------------------------------------------------------------------------------------------------------------------------

It is urgent ISSUE.
So it is a temporary solution to data consistency. ↓↓↓↓↓
After "CDM" updated "cohort_cache" table truncated, it  operate properly.

Should be check all the cache table like "COHORT_INCLUSION_RESULT_CACHE" table etc.

**Comment by chrisknoll** [comment]
The issue is that the caching assumes that the CDM does not change, and we don't have any checks to determine if there is an update to the CDM data (ie: checking COHORT_INCLUSION_RESULT_CACHE doesn't help us determine if data in cdm.DEATH has changed (or any other cdm table for that matter).  This is an interesting challenge because I'm not sure how we would be able to determine if any table in the CDM received an update in order to invalidate the cache....

What we might need to implement is to 'disable caching' if your CDM source is not read-only (ie static)

**Comment by ParkChanghHyun** [comment]
> The issue is that the caching assumes that the CDM does not change, and we don't have any checks to determine if there is an update to the CDM data (ie: checking COHORT_INCLUSION_RESULT_CACHE doesn't help us determine if data in cdm.DEATH has changed (or any other cdm table for that matter). This is an interesting challenge because I'm not sure how we would be able to determine if any table in the CDM received an update in order to invalidate the cache....
> 
> What we might need to implement is to 'disable caching' if your CDM source is not read-only (ie static)
> 
> Update:
> @ParkChanghHyun you can apply a trigger on your CDM tables which when updated will invoke a `TRUNCATE TABLE results.cohort`, which will make it so that if any CDM table gets updated, it will automatically truncate your cohort table, and then the cache will look 'dirty' when you generate the cohort next.

Thank you Chris. It is very useful
