### ISSUE TITLE
WebAPI 404 Not Found and Unable to connect to an instance of the WebAPI

### ISSUE THREAD

**Issue by gywlsdms123** [OHDSI/WebAPI#1879]
-- my environment --
ubuntu 20.04
tomcat 9
jdk 8
postgresql 12

![image](https://user-images.githubusercontent.com/51704606/118069908-fab24c80-b3df-11eb-98cc-23cecb79b30b.png)

success tomcat deploy (WebAPI & Atlas)

![image](https://user-images.githubusercontent.com/51704606/118070047-2d5c4500-b3e0-11eb-991c-3fc36487fd7e.png)

![image](https://user-images.githubusercontent.com/51704606/118070119-49f87d00-b3e0-11eb-9bec-ecca8750f0dc.png)

**Question 1. Is it correct to see this result in http://192.168.10.10:8080/WebAPI? (404 Not Found)** 

![image](https://user-images.githubusercontent.com/51704606/118070691-57623700-b3e1-11eb-976f-6b2499c62b71.png)

In WebAPI/source/sources, I succeeded in getting the results as webAPI document.

![image](https://user-images.githubusercontent.com/51704606/118070265-888e3780-b3e0-11eb-8f91-a7e599a6c136.png)
- Atlas page 

**Question 2. I don't know why Atlas is getting this error.**

I would appreciate your reply.

**Comment by chrisknoll** [comment]
For Q1: WebAPI doesn't respond to a 'bare' endpoint, so it is a correct response for a 404 when you aren't asking for anything specific :)  .  But, it is working for you, because when you asked for the list of sources, you got a response, so WebAPI is functioning!

For Q2: you are running into a CORS violation. CORS means Cross-Origin Resource Sharing which is a feature that is used to restrict access to WebAPI from other domains from browsers.  Could you try changing the URL you're accessing to use `localhost` instead of `192.168.10.10`?  I'm assuming that you are accessing localhost directly.

Othwerwise, I believe you need to set a value in your settings.xml file that you created to specify your local-environment settings.  In [this sample](https://github.com/OHDSI/WebAPI/blob/master/sample_settings.xml#L24), it shows setting the origin to `*` which should allow everything...do you want to try to set that in your settings.xml file and deploy a new build of WebAPI?  Unfortunately, you have to build the WAR to make the settings, so making that change will require you to deploy a new WAR.

**Comment by gywlsdms123** [comment]
> Q1의 경우 : WebAPI는 '베어'엔드 포인트에 응답하지 않으므로 특정 항목을 요구하지 않을 때 404에 대한 올바른 응답입니다. :). 그러나 소스 목록을 요청하면 응답을 받았으므로 WebAPI가 작동하기 때문에 작동합니다!
> 
> Q2 : CORS 위반이 발생했습니다. CORS는 브라우저의 다른 도메인에서 WebAPI에 대한 액세스를 제한하는 데 사용되는 기능인 Cross-Origin Resource Sharing을 의미합니다. `localhost`대신 사용하기 위해 액세스하는 URL을 변경해 주 `192.168.10.10`시겠습니까? 나는 당신이 localhost에 직접 액세스하고 있다고 가정하고 192.168.10.10은 실제 로컬 호스트입니다.
> 
> 그렇지 않으면 로컬 환경 설정을 지정하기 위해 만든 settings.xml 파일에 값을 설정해야한다고 생각합니다. [이 샘플](https://github.com/OHDSI/WebAPI/blob/master/sample_settings.xml#L24) 에서는 `*`모든 것을 허용해야하는 오리진을 설정하는 방법을 보여줍니다. settings.xml 파일에서이를 설정하고 WebAPI의 새 빌드를 배포 하시겠습니까? 안타깝게도 설정을하려면 WAR을 빌드해야하므로 변경하려면 새 WAR을 배포해야합니다.

thanks for answer. 

![image](https://user-images.githubusercontent.com/51704606/118077059-58e62c00-b3ee-11eb-9832-b6ac4bd12544.png)

I already set value settings.xml. 

I was able to find the problem with your hints, I don't understand < Could you try changing the URL you're accessing to use localhost instead of 192.168.10.10? I'm assuming that you are accessing localhost directly, and 192.168.10.10 is the actual local host. > this sentence. 
I searched for CORS errors, but I can't get a sense of it. Where can I change the URL? 

![image](https://user-images.githubusercontent.com/51704606/118077290-cc883900-b3ee-11eb-99c1-f2dfbebaeca7.png)
It is Atlas setting file. (config-local.js) Have you ever had a problem with this?

> For Q1: WebAPI doesn't respond to a 'bare' endpoint, so it is a correct response for a 404 when you aren't asking for anything specific :) . But, it is working for you, because when you asked for the list of sources, you got a response, so WebAPI is functioning!
> 
> For Q2: you are running into a CORS violation. CORS means Cross-Origin Resource Sharing which is a feature that is used to restrict access to WebAPI from other domains from browsers. Could you try changing the URL you're accessing to use `localhost` instead of `192.168.10.10`? I'm assuming that you are accessing localhost directly, and 192.168.10.10 is the actual local host.
> 
> Othwerwise, I believe you need to set a value in your settings.xml file that you created to specify your local-environment settings. In [this sample](https://github.com/OHDSI/WebAPI/blob/master/sample_settings.xml#L24), it shows setting the origin to `*` which should allow everything...do you want to try to set that in your settings.xml file and deploy a new build of WebAPI? Unfortunately, you have to build the WAR to make the settings, so making that change will require you to deploy a new WAR.

thanks for answer. 

![image](https://user-images.githubusercontent.com/51704606/118077059-58e62c00-b3ee-11eb-9832-b6ac4bd12544.png)

I already set value settings.xml. 

I was able to find the problem with your hints, I don't understand < Could you try changing the URL you're accessing to use localhost instead of 192.168.10.10? I'm assuming that you are accessing localhost directly, and 192.168.10.10 is the actual local host. > this sentence. 
I searched for CORS errors, but I can't get a sense of it. Where can I change the URL? 

![image](https://user-images.githubusercontent.com/51704606/118077290-cc883900-b3ee-11eb-99c1-f2dfbebaeca7.png)
It is Atlas setting file. (config-local.js) Have you ever had a problem with this?

**Comment by chrisknoll** [comment]
hmm, I thought origin of * would allow anything, but what I meant was:

![image](https://user-images.githubusercontent.com/6818777/118078978-35d36200-b385-11eb-8f7a-b092eb3b05db.png)


Change that URL in your browser address bar to say 'localhost' and not 192.168.10.10.

**Comment by gywlsdms123** [comment]
> hmm, I thought origin of * would allow anything, but what I meant was:
> 
> ![image](https://user-images.githubusercontent.com/6818777/118078978-35d36200-b385-11eb-8f7a-b092eb3b05db.png)
> 
> Change that URL in your browser address bar to say 'localhost' and not 192.168.10.10.
> 
> I also noticed that the setting:
> 
> ```
> <security.cors.enabled>true</security.cors.enabled>
> ```
> 
> You could try setting that value to `false`.

![image](https://user-images.githubusercontent.com/51704606/118080282-d90f9000-b3f4-11eb-8e9d-abacb96f8c9e.png)

`<security.cors.enabled>false</security.cors.enabled>`
I try setting this vaule.

After redeploying the war file, I accessed localhost:8080.
And this screen was displayed. How to solve this problem ?
also, i don't have config-gis.js file. where can I find this file?

**Comment by gywlsdms123** [comment]
> hmm, I thought origin of * would allow anything, but what I meant was:
> 
> ![image](https://user-images.githubusercontent.com/6818777/118078978-35d36200-b385-11eb-8f7a-b092eb3b05db.png)
> 
> Change that URL in your browser address bar to say 'localhost' and not 192.168.10.10.
> 
> I also noticed that the setting:
> 
> ```
> <security.cors.enabled>true</security.cors.enabled>
> ```
> 
> You could try setting that value to `false`.

![image](https://user-images.githubusercontent.com/51704606/118081708-df067080-b3f6-11eb-9505-a5f22c5c91d3.png)

I solved config-gis problem. 

`Less has finished and no sheets were loaded.
:8080/WebAPI/i18n/locales:1 Failed to load resource: the server responded with a status of 404 ()
main.js:57 App initialization failed undefined
(anonymous) @ main.js:57
`

![image](https://user-images.githubusercontent.com/51704606/118081882-2ab91a00-b3f7-11eb-9e06-188cf91ef533.png)

what is http://localhost:8080/WebAPI/i18n/locales?

**Comment by chrisknoll** [comment]
That's something that was introduced in version 2.9 (which has not been released yet).  Are you building WebAPI off of master branch in github?   You will need to pull down the master branch of Atlas if you want to use the master branch of WebAPI.

**Comment by gywlsdms123** [comment]
> That's something that was introduced in version 2.9 (which has not been released yet). Are you building WebAPI off of master branch in github? You will need to pull down the master branch of Atlas if you want to use the master branch of WebAPI.

oh...... I had build WebAPI version 2.8.0 & Atlas version 2.8.2 
I will try the same version again.

I 'm very grateful to you for all your help .

**Comment by chrisknoll** [comment]
Yes, 2.8.2 on both WebAPI and Atlas is our latest release.

**Comment by gywlsdms123** [comment]
> Yes, 2.8.2 on both WebAPI and Atlas is our latest release.

Thank you!! Atlas runs now. 

![image](https://user-images.githubusercontent.com/51704606/118207525-d3bb4f80-b49f-11eb-8123-df6801a71b75.png)

But it occured error. I think somthing wrong at webapi.
I tried running webapi by referring to [this page](http://webapidoc.ohdsi.org/index.html), 

A message such as `GET http://localhost:8080/WebAPI/cdmresults/synpuf5/dashboard 500` is shown.

How can I solve it?

**Comment by chrisknoll** [comment]
At this point, I'd say check your tomcat logs and look for errors. It could be an incorrect permission on the target schema. It could be a bad JDBC url in source... but please don't post an entire log to this thread, just find either 'Error' or 'Exception' in the logs to find out where you might get information about the core error.

**Comment by gywlsdms123** [comment]
> At this point, I'd say check your tomcat logs and look for errors. It could be an incorrect permission on the target schema. It could be a bad JDBC url in source... but please don't post an entire log to this thread, just find either 'Error' or 'Exception' in the logs to find out where you might get information about the core error.
> 
> Btw: the 'results' table qualifier of `OHDSI.webapi` looks wrong. The results shema is not your webapi schema. Each CDM should have their own results schema. Please refer to the [CDM configuration article](https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration) in the wiki.

![image](https://user-images.githubusercontent.com/51704606/118235912-552ad600-b4d0-11eb-89c3-af4bd6a4a2d2.png)

I refer to the [CDM configuration article](https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration) and complete to insert script in Database.

Hum... I checked tomcat log, but there were no special errors. There is no 'Error' or 'Exception', only 'WARNING' and 'INFO' exist.
Could you by any chance check my log file? Also, Where can I check JDBC url? I added the jdbc driver to tomcat referring [this page](https://tomcat.apache.org/tomcat-9.0-doc/jndi-datasource-examples-howto.html).

**Comment by gywlsdms123** [comment]
> At this point, I'd say check your tomcat logs and look for errors. It could be an incorrect permission on the target schema. It could be a bad JDBC url in source... but please don't post an entire log to this thread, just find either 'Error' or 'Exception' in the logs to find out where you might get information about the core error.
> 
> Btw: the 'results' table qualifier of `OHDSI.webapi` looks wrong. The results shema is not your webapi schema. Each CDM should have their own results schema. Please refer to the [CDM configuration article](https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration) in the wiki.

Hi, I installed achilles properly and it works fine.
Thank you for your help!
