### ISSUE TITLE
WebAPI does not accept results from Execution Engine if one of the files in results is bigger than 2Gb

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#1889]
### Expected behavior
WebAPI accepts and stores results from EE correctly

### Actual behavior
Application fails on this line 
https://github.com/OHDSI/WebAPI/blob/fd108571086fceea8513389fab426a6ea8101888/src/main/java/org/ohdsi/webapi/executionengine/service/AnalysisResultFileContentSensitiveInfoServiceImpl.java#L75

![image](https://user-images.githubusercontent.com/4144173/120319457-525a1e80-c2e1-11eb-9c5e-2a61702bce3b.png)

### Steps to reproduce behavior
Submit results with one of the files bigger that 2Gb in archive.

More info
https://stackoverflow.com/questions/43782158/java-reading-a-big-file-few-gb

**Comment by anton-abushkevich** [comment]
As discussed, we need to filter *.sqlite files from the result archive. I added filtration of files within zip-archives on EE side. See PR. 

Then, on the WebAPI side: add "*.sqlite" to the env variable executionengine.resultExclusions (comma-separated filename patterns).

```-Dexecutionengine.resultExclusions=*.sqlite```
