### ISSUE TITLE
Support Cohort Definition Revisions

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#189]
The current implementation of Cohort Definitions only supports a 'latest' cohort definition, and this leads to generation of cohort analysis (such as inclusion rule impact statistics) that may go out of sync if the definition is revised after the execution is made.

This issue request is to extend cohort definitions to allow revisions.  The vision of how this would work is as follows:
The existing cohort definition state would be considered a 'draft'.  Before a cohort can be generated, it must be marked as a specific revision number.  This allows incremental changes to a cohort definition (ie: mulitple saves) but only record a new revision when the user specifically requests it.

On the generation side, the user will choose the revision of the cohort definition (will default to the latest revision) and the datasource to execute against.

This could lead to results schema updates, as now results will be tied to a specific revision of a OHDSI asset (in this case cohort definition, but could also be extended for analysis results).

**Comment by anthonysena** [comment]
Addressed, in part, by #1923.
