### ISSUE TITLE
Issue with Launching WebAPI using Helm Charts

### ISSUE THREAD

**Issue by shreyanssethi** [OHDSI/WebAPI#1900]
### Expected behavior

Trying to launch the ohdsi-Webapi on a minikube cluster and  following the steps that are outlined here:
https://github.com/chgl/charts/tree/master/charts/ohdsi

The installation and update were successful but neither the atlas or webapi endpoint are working. Opening the minikube dashboard and going to the pods shows that all 3 pods (ohdsi-atlas, ohdsi-postgresql, and ohdsi-webapi) have errored with the falling error message:

"Failed to pull image "busybox:1.32": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.2:44156->192.168.64.1:53: i/o timeout"

Have tried deleting and reinstalling using Helm along with reinstalling Docker but neither has made any change.

### Actual behavior

Once helm install is run and the endpoints are given, the WebAPI and Atlas should be running

### Steps to reproduce behavior

https://github.com/chgl/charts/tree/master/charts/ohdsi
Follow the steps outlined here

**Comment by chrisknoll** [comment]
Shouldn't this be an issue raised on https://github.com/chgl/charts?

**Comment by chgl** [comment]
I think this can be closed. https://github.com/chgl/charts/issues/105
