### ISSUE TITLE
WebAPI build failure

### ISSUE THREAD

**Issue by ipscell** [OHDSI/WebAPI#1915]
I tried to build WebAPI 2.9.1 but could not build it with the error message below. Any helpful comments are appreciated. 
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/88561885/128574256-9147f6c9-29e8-4021-9ac7-f1e5d24e8fd5.png">

**Comment by ssuvorov-fls** [comment]
@ipscell Hello
What java version do you use?

**Comment by ipscell** [comment]
I use java 16.0.1. Thank you.

**Comment by ssuvorov-fls** [comment]
Please try java 8

**Comment by ipscell** [comment]
I could downgrade Java 16 to 8, and it seems to work well. Thank you!
However, I still could not build the WebAPI war file because of 2 test failures (see below). I doubted my DB settings, although I could confirm the connection with the database query tool. I have used pgAdmin 4 instead of 3. Thank you again for your help.

<img width="1329" alt="image" src="https://user-images.githubusercontent.com/88561885/129261454-e38cb4e6-7d42-42d8-a7d8-2cfbc0ad1163.png">

**Comment by chrisknoll** [comment]
Is this MacOS? If so, there seems to be some issue related to tests that write to a temp directory.  If you want to trust the tests are actually working, you can look in your pom.xml where there is `skipUnitTests` and `skipITtests`, and set those properties to `true`.

**Comment by anthonysena** [comment]
Closing this due to age. I'd suggest using the latest release of the code and if you are still facing an issue please re-open the issue. Thanks!
