### ISSUE TITLE
Error 403 after succesful login

### ISSUE THREAD

**Issue by alabarga** [OHDSI/WebAPI#1916]
I have configured AtlasRegularSecurity (Local DB security )as per the [wiki instructions](https://github.com/OHDSI/WebAPI/wiki/Basic-Security-Configuration)

I login and I can see 

`2021-08-10 13:17:20.130 INFO http-nio-8080-exec-8 com.odysseusinc.logging.LoggingService -  - User login = *******@iomed.es was logged in`

the `sec_user` table holds the login email used

id|login|name
--|----|------
1000|****@iomed.es|iomed

and the `sec_user_role` table assigns role admin ti my user (status is _null_ )

id|user_id|role_id|status
--|------|-------|------
1001|1000|2|

however,  Atlas application never let me in
 
![image](https://user-images.githubusercontent.com/166339/128874584-698ba54e-574a-4ccd-ae61-b353187b3ad1.png)

I can see an error

`Cannot retrieve user info`

in the browser console since the request to

 `http://localhost:9000/WebAPI/user/me` 

which is using the returned Bearer token, returns a 403 error

**Comment by alabarga** [comment]
I was missing the `public` role

id|user_id|role_id|status
--|------|-------|------
1001|1000|2|
1002|1000|1|

now, I can log into Atlas

**Comment by anthonysena** [comment]
@alabarga - thank you for posting this issue plus the solution! I've noted that this would be a useful contribution to the documentation you referenced since this is a gap.
