### ISSUE TITLE
Duplicate records can be created in postgresql tag_group table in Atlas. Lacks unique constraint.

### ISSUE THREAD

**Issue by Sathyaraos** [OHDSI/WebAPI#1938]
### Expected behavior
Duplicate records should not exists in postgresql tag_group table in Atlas. Upon trying to insert the same record to the tag_group table it should throw an error notifying the user that the record exists. 

### Actual behavior
Duplicate records can be created in postgresql tag_group table in Atlas. Since there is no unique constraint it lets you create duplicate records with same values. 

### Steps to reproduce behavior
You can run the same insert script multiple times to create a new record with same values and hence it creates duplicates as there is no unique constraint.

INSERT INTO .tag_group(tag_id, group_id)
	VALUES (?, ?); -- pass the tag_id and group_id 

SOLUTION, would be to create a unique constraint using column names tag_id and group_id. Hope this helps. 

@alondhe , @anton-abushkevich

**Comment by alondhe** [comment]
We think the sequences were corrupted. After resetting, it's working correctly now.
