### ISSUE TITLE
 Ldap authentication is not working in ATLAS

### ISSUE THREAD

**Issue by shailender1984** [OHDSI/WebAPI#1942]
Hi Team,
I have configured the Altas through docker-compose by using reference of below code. Everything is working but ldap is not working . Could you please help me to fix it

https://github.com/OHDSI/Broadsea
 kindly find the below docker-compose file and config.local.js file 
root@spdpaa0736-usw2:~/OHDSI/Broadsea/postgresql# cat docker-compose.yml
version: '2'

services:

  broadsea-methods-library:
    image: ohdsi/broadsea-methodslibrary
    ports:
      - "8787:8787"
      - "6311:6311"
    environment:
      - PASSWORD=mypass

  broadsea-webtools:
    image: ohdsi/broadsea-webtools
    ports:
      - "443:8443"
    volumes:
     - .:/tmp/drivers/:ro
     - ./config-local.js:/usr/local/tomcat/webapps/atlas/js/config-local.js:ro
     - ./cacerts:/usr/local/openjdk-8/jre/bin/cacerts:rw
     - ./create_keystore.sh:/usr/local/openjdk-8/jre/bin/create_keystore.sh:rw
     - ./atlas-keystore.jks:/usr/local/openjdk-8/sample/jmx/jmx-scandir/atlas-keystore.jks:rw
     - ./server.xml:/usr/local/tomcat/conf/server.xml:rw
    environment:
      - WEBAPI_URL=https://10.175.158.228:443
      - env=webapi-postgresql
      - security_enabled=true
      - security_cors_enabled=true
      - security_origin=*
      - datasource_driverClassName=org.postgresql.Driver
      - datasource_url=jdbc:postgresql://10.175.158.228:5432/OHDSI
      - datasource_ohdsi_schema=ohdsi
      - datasource_username=ohdsi_app_user
      - datasource_password=3547647f10f7484ad5a7003ffbb95570
      - spring_jpa_properties_hibernate_default_schema=ohdsi
      - spring_jpa_properties_hibernate_dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring_batch_repository_tableprefix=ohdsi.BATCH_
      - flyway_datasource_driverClassName=org.postgresql.Driver
      - flyway_datasource_url=jdbc:postgresql://10.175.158.228:5432/OHDSI
      - flyway_schemas=ohdsi
      - flyway_placeholders_ohdsiSchema=ohdsi
      - flyway_datasource_username=ohdsi_admin_user
      - flyway_datasource_password=3547647f10f7484ad5a7003ffbb95570
      - flyway_locations=classpath:db/migration/postgresql
      - security_provider=AtlasRegularSecurity
      - security_maxLoginAttempts=3
      - security_duration_initial=10
      - security_duration_increment=10
      - security_db_datasource_url=jdbc:postgresql://10.175.158.228:5432/Security
      - security_db_datasource_driverClassName=org.postgresql.Driver
      - security_db_datasource_schema=atlas_security
      - security_db_datasource_username=ohdsi_app_user
      - security_db_datasource_password=3547647f10f7484ad5a7003ffbb95570
      - security_db_datasource_authenticationQuery=select password from atlas_security.demo_security where username = ?
      - security_ssl_enabled=true
      - server_port=443
      - security_auth_ad_enabled=true
      - security.ad.url=ldaps://##############:636
      - security.ad_basedn='ou=internal,ou=Users,dc=science,dc=roche,dc=com'
      - security.ad.principalSuffix=@science.roche.com
      - security.ad.system.username=CN=SVC-phcaa-T1,OU=ServiceAccounts,DC=science,DC=roche,DC=com
      - security.ad.system.password=#########
      - security_ad_searchFilter="(&(objectClass=person)(uid=*))"

root@:~/OHDSI/Broadsea/postgresql# cat config-local.js
define([], function () {
        var configLocal = {};

        // clearing local storage otherwise source cache will obscure the override settings
        localStorage.clear();

        var getUrl = window.location;
        var baseUrl = getUrl.protocol + "//" + getUrl.host;

        // WebAPI
        configLocal.api = {
                name: 'OHDSI',
                url: 'https://10.175.158.228:443/WebAPI/'
        };

        configLocal.cohortComparisonResultsEnabled = false;
        configLocal.userAuthenticationEnabled = true;
        configLocal.plpResultsEnabled = false;

        configLocal.authProviders = [{
                        "name": "Local Security Test DB",
                        "url": "user/login/db",
                        "ajax": true,
                        "icon": "fa fa-database",
                        "isUseCredentialsForm": true
                      },
                     {
                        "name": "AD",
                        "url": "user/login/ad",
                        "ajax": true,
                        "icon": "fa fa-cubes",
                        "isUseCredentialsForm": true
                      }];
        return configLocal;
});

**Comment by anthonysena** [comment]
Hi - is your goal to use LDAP or AD? If you'd like to use LDAP, please try configuring using https://github.com/OHDSI/WebAPI/wiki/Security-Configuration#lightweight-directory-access-ldap. Additionally in your Atlas `config-local.js` you'll want to use the [LDAP Configuration](https://github.com/OHDSI/Atlas/blob/master/js/config/app.js#L65) block.

If you'd like to use AD, I believe your machine will need to be joined to the AD Domain. I'm not very familiar with how this is done with Docker so I'd have to defer to others. In the case that you use AD, your NT credentials will be used an no login is required.

**Comment by shailender1984** [comment]
Hi Anthonysena,

I have used the below ldap setting and changed my config-local.js according to ldap block but same issue.

- security.auth.ldap.enabled=true
- security.ldap.dn=CN=SVC-phcaa-T1,OU=ServiceAccounts,DC=science,DC=roche,DC=com
- security.ldap_uri=ldaps://###############:636
- security.ldap.baseDn=dc=science,dc=roche,dc=com
- security.ldap.system.username=SVC-phcaa-T1
- security.ldap.system.password=$$$$$$$$$$$$

**Comment by anthonysena** [comment]
Tagging @konstjar for some help on this as I'm not as familiar with troubleshooting the LDAP setup

**Comment by anthonysena** [comment]
@shailender1984 are there any entries in your WebAPI log that you can share that might help describe the problem? This may be hard to troubleshoot with out some specific error beyond the `401 unauthorized` message reported.

**Comment by shailender1984** [comment]
@anthonysena , I am able to see only below logs .

2021-10-01 07:22:40.583 INFO https-openssl-nio-8443-exec-4 com.odysseusinc.logging.LoggingService -  - Log in failed for user login = sings135
2021-10-01 07:22:40.591 INFO https-openssl-nio-8443-exec-4 audit -  - <110>1 2021-10-01T07:22:40.591Z 75d980ed9d87 Atlas - - - User login failed: sings135, remote-host = 10.37.112.110

**Comment by shailender1984** [comment]
@anthonysena, 
I have checked the dockerfile for  deploy the released OHDSI WebAPI war file. Could you please confirm if this WAR file have settings.xml ??

# set working directory to the Tomcat server webapps directory
WORKDIR /usr/local/tomcat/webapps

# deploy the released OHDSI WebAPI war file from the OHDSI CI Nexus repository
ENV WEBAPI_WAR_URL=https://repo.ohdsi.org/nexus/repository/releases/org/ohdsi/WebAPI/$WEBAPI_RELEASE/$WEBAPI_WAR
RUN wget $WEBAPI_WAR_URL \
    && mv /usr/local/tomcat/webapps/WebAPI*.war /usr/local/tomcat/webapps/WebAPI.war

**Comment by leeevans** [comment]
resolved in forum post
