### ISSUE TITLE
Select All Feature 

### ISSUE THREAD

**Issue by jonathanfogo** [OHDSI/WebAPI#1945]
Hello,

I am creating concept sets in Atlas where including/excluding large groups of concepts in necessary. In past versions of Atlas, there was a feature in the concept search and concept hierarchy that allowed multiple concepts to be selected at once. This feature still remains in the concept set expression view but is no longer available in the concept search or concept hierarchy view. 

Does the community have any suggestions about ways to select multiple concepts to include/exclude at once?

Thank you.

**Comment by anthonysena** [comment]
Hi @jonathanfogo - this issue has gone unnoticed (apologies). As of Atlas v2.10.0, we've added back the "select all" for concept selection so I'm going to close this out.
