### ISSUE TITLE
cohort reporting data (result distributions) export fails

### ISSUE THREAD

**Issue by leeevans** [OHDSI/WebAPI#195]
Error seen in Atlas running on postgres and redshift databases - I have not tested on other DBMSs

Steps to reproduce:
Navigate to URL:
http://www.ohdsi.org/web/atlas/#/cohortdefinition/155
click on reporting tab
click on export button under the synpuf1k column.

Error:

```
{"methodName":"run","fileName":"Thread.java","lineNumber":745,"className":"java.lang.Thread","nativeMethod":false}],"message":"org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar 
[select ROWCOUNT() OVER (ORDER BY tmp.analysis_id) as rn , *
FROM ( select *
        from ohdsi.heracles_results_dist
        where cohort_definition_id = 155 ) tmp
Where rn <= 100;

]; nested exception is org.postgresql.util.PSQLException: ERROR: function rowcount() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8","localizedMessage":"org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [select ROWCOUNT() OVER (ORDER BY tmp.analysis_id) as rn , *
FROM ( select *
        from ohdsi.heracles_results_dist
        where cohort_definition_id = 155 ) tmp
Where rn <= 100;

]; nested exception is org.postgresql.util.PSQLException: 
ERROR: function rowcount() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 8","suppressed":[]},"headers":{"id":"7ca06b4b-9390-49ad-5b8e-09cc559e328a","timestamp":1490040703886}}

```

Suggested fix:

Change
src/main/resources/resources/cohortresults/sql/raw/getAllResultDistributions.sql
to this:

```
select * from (
	select ROW_NUMBER() OVER (ORDER BY tmp.analysis_id) as rn, *
	FROM ( select *
		from @tableQualifier.heracles_results_dist
		where cohort_definition_id = @cohortDefinitionId 
	) tmp
) tmp2
where rn <= 100;
```

Is the exported file intended to contain only the top 100 cohort result distribution rows from the heracles_results_dist table for a cohort, or all the rows of data from that table, for a cohort? If top 100 what is the significance of only retrieving the first 100 rows?

It may be helpful to add a brief explanation of the cohort reporting export button in the cohort reporting section of the Atlas user manual here:
http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:atlas:cohorts

**Comment by JamesSWiggins** [comment]
Experiencing the same issue on Redshift.  I second this change.  You can update the SqlTranslate replacementValues.csv file to have the following replacement for Redshift:

redshift,ROWCOUNT(),ROW_NUMBER()

which solves the ROWCOUNT() error, but doesn't address the fact that neither Postgres nor Redshift support ALIASes ("as rn") referenced in the WHERE statement.  @leeevans proposed change fixes that.

**Comment by chrisknoll** [comment]
We definitely should fix this in the query and not make a mapping rule to translate rowcount() to row_number()...rowcount() doesn't actually exist as a window function.

I'll work on incorporating @leeevans  fix into a PR.
