### ISSUE TITLE
error in deploying WebAPI using Tomcat application manager

### ISSUE THREAD

**Issue by Aqsa-Mahmood** [OHDSI/WebAPI#1950]
when i deploy WebAPI using tomcat application manager and try to deploy .war file i got error msg "site cant be reached". plz guide how can i resolve this issue?

**Comment by anthonysena** [comment]
I'm closing this due to age. If you are still facing this issue, can you provide more details on your environment configuration so we can try to help? The "site cant be reached" is not enough information for us to help diagnose the problem you encountered. Thanks!
