### ISSUE TITLE
measurement Error loading report 

### ISSUE THREAD

**Issue by gywlsdms123** [OHDSI/WebAPI#1957]
`http://<server:port>/WebAPI/ddl/results?dialect=<your_cdm_database_dialect>&schema=<your_results_schema>&vocabSchema=<your_vocab_schema>&tempSchema=<your_temp_schema>&initConceptHierarchy=true
`
I ran this code, and created concept_hierarchy. 
The dashboard is displayed for data other than measurement.

![image](https://user-images.githubusercontent.com/51704606/141705619-81da93a4-0ef6-4f01-91c0-693c5513dc9b.png)
![image](https://user-images.githubusercontent.com/51704606/141705910-aec3b0b5-0507-43fb-a66e-db3c6a51f049.png)
![image](https://user-images.githubusercontent.com/51704606/141706471-59eee72f-0512-481a-b43f-77228102ff8f.png)

I made a new concept code for mapping to measurement, the numbers start at 40,000,000.
1) The corresponding code is inserted in the concept, vocabulary, concept_class table.

![image](https://user-images.githubusercontent.com/51704606/141706092-bf461239-cb20-47e2-bf56-d29163b2353a.png)
This is part of the results of concept_hierarchy. (concept_id Data Type is int8)

What's wrong with my measurement Table? 
Also, do I have to rerun Achilles for this?

**Comment by gywlsdms123** [comment]
![image](https://user-images.githubusercontent.com/51704606/141706719-78003d5a-cecd-4d31-bf09-1ab277d924f1.png)

add other error

**Comment by gywlsdms123** [comment]
@chrisknoll 
Hi, could i get help? 
`https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/report/measurement/treemap.sql`
Since the treemap was not created, this sql query was executed. 
I use postgresql


![image](https://user-images.githubusercontent.com/51704606/141873135-7520e4c6-6a63-4d3b-aa41-dd49eacdf7f9.png)
^ original 

![image](https://user-images.githubusercontent.com/51704606/141872635-ce4a56d3-3461-49e4-8a5d-4f9b4d569f06.png)
^ after update numeric -> int 8

I think the reason for the error in measurement is that concept_id is int8. function isnumeric does not accept int8.
 So I changed it to int8 and ran the query, and the result came out.

How can I display this value in a treemap?

**Comment by chrisknoll** [comment]
I don't think the error is that isnumeric does not accept int8, it's that the conceptID is too big to cast into an int.  An int8, btw, is an alias to 'bigint' which is a common datatype we use in sql.

Btw: I'm not finding any of these concept_ids in the standard vocabulary, so that might explain why I've never seen this type of error before.  What are these concept IDs?

**Comment by gywlsdms123** [comment]
we made a new concept code for mapping to measurement, the numbers start at 40,000,000. 
Do I have to specify the concept_id within the int4 range by any chance?

**Comment by chrisknoll** [comment]
Yep.

**Comment by gywlsdms123** [comment]
OMG... all for nothing, I'll have to rebuild the concept_id within the int4 range.
 Thank you for answer.

I have two more questions. 

1) Do I really need concept_ancestor to define new concept code? Our new code has no hierarchy.
2) It takes 15 hours to run Achilles of 1815 analysis. Is this normal activity? (The number of columns in the measurement table is about 150 million)

**Comment by chrisknoll** [comment]
You could try to modify the WebAPI code to cast to a bigint and see if the query works.

I looked up a few concepts in athena and it seems like there should be standard concepts to represent what you are creating there...why didn't you map to standard concepts?

As far as hierarchy, you don't need anything in concept_ancestor:  the concept_hierarchy builds the lookup table, but if the concepts aren't' found, then you'll get a NA as the parent hierarchy...which is fine for you.

I'm not sure what 1815 is doing internally, but if you want you can just pull out that query from Achilles, and run it, and use the 'show plan' function of postgresql to determine where the bottleneck is.  maybe it's a sorting (so set up a sorted key on yoru table) or some other operation that you'll have to see for yourself.

**Comment by gywlsdms123** [comment]
If the code is specified in the int4 range, the data output(measurement) is normally.

We try to standardize our code and use it.
it helped a lot. thanks for making a good source. thank you!!
