### ISSUE TITLE
User import jobs not revoking access

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#1959]
### Expected behavior
When using the scheduled import AD/LDAP job, users who have been removed from an AD/LDAP group should no longer have their Atlas mapped roles checked.

### Actual behavior
We've found this doesn't occur. We removed a user from an AD group, but the import process persisted their user roles.

### Steps to reproduce behavior
Enable authentication, scheduled import with mappings to AD groups. Remove a user from the AD group. Observe they keep their Atlas roles.

**Comment by anton-abushkevich** [comment]
#2146
