### ISSUE TITLE
What values ​​should @conceptIdentifiers contain?

### ISSUE THREAD

**Issue by gywlsdms123** [OHDSI/WebAPI#1962]
I'm studying the query from 
https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/getConceptRecordCount.sql 

What should be in @conceptIdentifiers to check the result in the database?

I think `select concept_id from concept` should be included, is this correct?

**Comment by ssuvorov-fls** [comment]
@gywlsdms123 
@conceptIdentifiers contains array of the concept ids, for whom we want to get record and descendant record counts
This script does not return counts for all concept in database

**Comment by gywlsdms123** [comment]
So, what should I refer to to to see the structure of the search function in atlas? 
I want to understand the structure of obtaining a record count using the query. To implement this, what coding should you do on @conceptin?

**Comment by konstjar** [comment]
@gywlsdms123 You should follow this instruction to setup results schema 
https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration#results-schema-setup

**Comment by gywlsdms123** [comment]
@konstjar 
Oh, I know this Process. 
What I'm curious about is what @conceptIdentifier inputs are? 

I want to run this script and produce results like the Atlas search results.

**Comment by chrisknoll** [comment]
I believe it's simply a comma delimited list of conceptIds.  It is used in atlas to fetch the counts for the conceptIds that were returned in the search query.

**Comment by gywlsdms123** [comment]
@chrisknoll 
I think so, too. 
The reason I want to do this:Trying to run the script by figuring out what goes into  @conceptIdentifier is to get a list of patients by record count.

Thank you!! have a nice day.

**Comment by chrisknoll** [comment]
Ok, but I don't think any of that query deals with any patient-level data, but I'm glad I could help! I'll close this out since it's not an issue, but if you want to post back later with additional info, that's fine.  But, you might get more traction asking these kind of questions on the ohdsi forums, because the git issue tracker is more for issues and enhancements.
