### ISSUE TITLE
LOG10 usage needs cast

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#198]
See issue https://github.com/OHDSI/SqlRender/issues/64.

Can we alter the usage of LOG10 in src/main/resources/resources/cohortresults/sql/raw/getCohortBreakdown.sql
and
src/main/resources/resources/cohortresults/sql/raw/getCohortBreakdownPeople.sql

to go from this:
`log10(abs(count(*) + 0.01))`

to this:
`log10(abs(cast(count(*) + 0.01 as real)))` ?

Reason is, in Redshift, the expression within the log function needs to have one variable type.

**Comment by chrisknoll** [comment]
Sure thing.  I'll put together a PR.

**Comment by schuemie** [comment]
This should now be fixed in SqlRender, so no need to add a cast here.

https://github.com/OHDSI/SqlRender/commit/b26b3e11e1c64535daab1ce2c3bf7bc2a01ebf18
