### ISSUE TITLE
Database Update - PostgreSQL Issue - maybe?

### ISSUE THREAD

**Issue by jmbanda** [OHDSI/WebAPI#199]
When updating to WebAPI 2.0, my current data sources did not update properly so I had considerably issues with ATLAS 2.0 debug logs saying that tables cohort_* , concept_* tables missing. I solved this by manually creating the cohort_* , concept_*, etc. for each of our data sources. This might be an issue when deploying the new WebAPI war file particular to PostgreSQL or a more general and broader issue. I can provide any additional details if need.

**Comment by chrisknoll** [comment]
Setting up multiple CDMs in a single WebAPI instance is a manual step. Details about which tables need to be created can be found here: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:multiple_datasets_configuration.

**Comment by jmbanda** [comment]
Thanks! I missed this from the documentation.
