### ISSUE TITLE
Running webapi on tomcat

### ISSUE THREAD

**Issue by mircom2** [OHDSI/WebAPI#200]
Web API Installation
Because I can not speak English very well, I write it using Google Translator.
Please help us.

Web API Installation Guide, but the following error occurs.

Below is the error log that occurs when running Tomcat on Webapi.

Severity: ContainerBase.addChild: start:
Org.apache.catalina.LifecycleException: Failed to start component [StandardEngine [Catalina] .StandardHost [localhost] .StandardContext [/ WebAPI]]
At org.apache.catalina.util.LifecycleBase.start (LifecycleBase.java:162)
At org.apache.catalina.core.ContainerBase.addChildInternal (ContainerBase.java:899)
At org.apache.catalina.core.ContainerBase.addChild (ContainerBase.java:875)
At org.apache.catalina.core.StandardHost.addChild (StandardHost.java:652)
At org.apache.catalina.startup.HostConfig.deployWAR (HostConfig.java:1092)
At org.apache.catalina.startup.HostConfig $ DeployWar.run (HostConfig.java:1984)
At java.util.concurrent.Executors $ RunnableAdapter.call (Unknown Source)
At java.util.concurrent.FutureTask.run (Unknown Source)
At java.util.concurrent.ThreadPoolExecutor.runWorker (Unknown Source)
At java.util.concurrent.ThreadPoolExecutor $ Worker.run (Unknown Source)
At java.lang.Thread.run (Unknown Source)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org / springframework / boot / autoconfigure / flyway / FlywayAutoConfiguration $ FlywayConfiguration.class]: Invocation of init method failed; Nested exception is org.flywaydb.core.api.FlywayException: Schema "OHDSI" contains a failed migration to version 1.0.0.9!
At org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean (AbstractAutowireCapableBeanFactory.java:1628)
At org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean (AbstractAutowireCapableBeanFactory.java:555)
At org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean (AbstractAutowireCapableBeanFactory.java:483)
At org.springframework.beans.factory.support.AbstractBeanFactory $ 1.getObject (AbstractBeanFactory.java:306)
At org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton (DefaultSingletonBeanRegistry.java:230)
At org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean (AbstractBeanFactory.java:302)
At org.springframework.beans.factory.support.AbstractBeanFactory.getBean (AbstractBeanFactory.java:197)
At org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons (DefaultListableBeanFactory.java:761)
At org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization (AbstractApplicationContext.java:866)
At org.springframework.context.support.AbstractApplicationContext.refresh (AbstractApplicationContext.java:542)
At org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh (EmbeddedWebApplicationContext.java:122)
At org.springframework.boot.SpringApplication.refresh (SpringApplication.java:737)
At org.springframework.boot.SpringApplication.refreshContext (SpringApplication.java:370)
At org.springframework.boot.SpringApplication.run (SpringApplication.java:314)
At org.springframework.boot.web.support.SpringBootServletInitializer.run (SpringBootServletInitializer.java:151)
At org.springframework.boot.web.support.SpringBootServletInitializer.createRootApplicationContext (SpringBootServletInitializer.java:131)
At org.springframework.boot.web.support.SpringBootServletInitializer.onStartup (SpringBootServletInitializer.java:86)
At org.springframework.web.SpringServletContainerInitializer.onStartup (SpringServletContainerInitializer.java:169)
At org.apache.catalina.core.StandardContext.startInternal (StandardContext.java:5623)
At org.apache.catalina.util.LifecycleBase.start (LifecycleBase.java:145)
... more
Caused by: org.flywaydb.core.api.FlywayException: Schema "OHDSI" contains a failed migration to version 1.0.0.9!
At org.flywaydb.core.internal.command.DbMigrate $ 2.doInTransaction (DbMigrate.java:196)
At org.flywaydb.core.internal.command.DbMigrate $ 2.doInTransaction (DbMigrate.java:156)
At org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute (TransactionTemplate.java:72)
At org.flywaydb.core.internal.command.DbMigrate.migrate (DbMigrate.java:156)
At org.flywaydb.core.Flyway $ 1.execute (Flyway.java:972)
At org.flywaydb.core.Flyway $ 1.execute (Flyway.java:919)
At org.flywaydb.core.Flyway.execute (Flyway.java:1320)
At org.flywaydb.core.Flyway.migrate (Flyway.java:919)
At org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet (FlywayMigrationInitializer.java:66)
At org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods (AbstractAutowireCapableBeanFactory.java:1687)
At org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean (AbstractAutowireCapableBeanFactory.java:1624)
... more

April 24, 2017 5:43:14 PM org.apache.catalina.startup.HostConfig deployWAR
Serious: Error deploying web application archive C: \ Program Files \ Apache Soft

**Comment by chrisknoll** [comment]
I see from your other post that you are running Oracle 12c.  I've tested deployment on 11g, but the migration scripts should be compatable.

The error was: failed migration to version 1.0.0.9, which is found in this file:
https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/db/migration/oracle/V1.0.0.9__shiro_security.sql

This is related to the 'shiro' feature (security) in WebAPI.  I don't have enough information from your post to know what the actual error was.

Can you execute the DDL in the above migration script one at a time until you get to the command that fails?

-Chris

**Comment by mircom2** [comment]
Chris As you know, I ran the V1.0.0.9__shiro_security.sql query directly from oracleDB.

Below is the contents of the query that causes an error when executing the query.
CREATE SEQUENCE ohdsi.SEC_USER_ROLE_SEQUENCE START WITH 1000 INCREMENT BY 1 MAXVALUE 9223372036854775807 NO CYCLE;
CREATE TABLE ohdsi.SEC_USER_ROLE (
     ID INTEGER NOT NULL,
     USER_ID INTEGER NOT NULL,
     ROLE_ID INTEGER NOT NULL,
     STATUS VARCHAR2 (255) NULL
);

The following error message occurs when executing the above query.

CREATE SEQUENCE ohdsi.SEC_USER_ROLE_SEQUENCE START WITH 1000 INCREMENT BY 1 MAXVALUE 9223372036854775807 NO CYCLE
Error reporting -
ORA-00933: SQL command not terminated correctly
00933. 00000 - "SQL command not properly ended"
* Cause:
* Action:

Table OHDSI.SEC_USER_ROLE has been created.

Chris, I need your help.

**Comment by chrisknoll** [comment]
If you made any corrections to the V1.0.0.9 file, please let us know so we can fix the errors in the script.

@ganisimov: would you please assist @mircom2 with the issues he is having?

**Comment by mircom2** [comment]
I tried to fix the DB script error with Chris's help, but I still get the error of migration failure when running Tomcat.

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org / springframework / boot / autoconfigure / flyway / FlywayAutoConfiguration $ FlywayConfiguration.class]: Invocation of init method failed; Nested exception is org.flywaydb.core.api.FlywayException: Schema "OHDSI" contains a failed migration to version 1.0.0.9!

What information should be provided to resolve this issue?

Thank you for your help.

**Comment by mircom2** [comment]
INSERT INTO ohdsi.source (source_id, source_name, source_key, source_connection, source_dialect) VALUES (1, 'My Cdm', 'MY_CDM', ' jdbc:oracle:thin:ohdsi/{password}@127.0.0.1:1521/xe', 'oracle');
INSERT INTO ohdsi.source (source_id, source_name, source_key, source_connection, source_dialect) VALUES (2, 'Default vocabulary', 'vocab', 'jdbc:oracle:thin:ohdsi/{password}@127.0.0.1:1521/xe', 'oracle');
INSERT INTO webapi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) VALUES (1,1,0, 'cdm', 0);
INSERT INTO webapi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) VALUES (2,1,1, 'cdm', 0);
INSERT INTO webapi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) VALUES (3,1,2, 'ohdsi', 0);
INSERT INTO webapi.source_daimon (source_daimon_id, source_id, daimon_type, table_qualifier, priority) VALUES (4,2,1, 'cdm', 1);


Is the query below an error?
The above description does not cover the creation of webapi schemas.

Webapi.source_daimon >>> ohdsi.source_daimon, you need to change the schema information to ohdsi.

If you know, please ask for help.

**Comment by chrisknoll** [comment]
It looks like oracle doesn't support DDL transactions, which means that you'll have to do a manual repair.  You can either start with a fresh database schema, or you can follow these instructions:

https://flywaydb.org/documentation/maven/repair

However, it would be good to know what you did to get the V1.0.0.9__shiro_security.sql working.  Did you use the file without modification from git?  Because it's a problem if it works when you execute it directly , but fails when you run via flyway...

**Comment by anthonysena** [comment]
Closing out - old issue
