### ISSUE TITLE
The contents of settings.xml for the issue below.

### ISSUE THREAD

**Issue by mircom2** [OHDSI/WebAPI#201]
- For reference, Oracle version is 12c.
- 
- > <Settings>
- > <Profiles>
- >   <Profile>
- >     <Id> webapi-oracle </ id>
- >     <Properties>
- >       <Datasource.driverClassName> oracle.jdbc.OracleDriver </datasource.driverClassName>
- >      <Datasource.url> jdbc: oracle: thin: @ // 127.0.0.1:1521/orcl </ datasource.url>
- >       <Datasource.username> ohdsi </ datasource.username>
- >       <Datasource.password> snubh </datasource.password>
- >       <Datasource.dialect> oracle </datasource.dialect>
- >       <Datasource.ohdsi.schema> OHDSI </datasource.ohdsi.schema>
- >       <Flyway.datasource.driverClassName> oracle.jdbc.OracleDriver </flyway.datasource.driverClassName>
- >       <Flyway.datasource.url> jdbc: oracle: thin: @ // 127.0.0.1:1521/orcl </flyway.datasource.url>
- >       <Flyway.datasource.username> ohdsi </flyway.datasource.username>
- >       <Flyway.datasource.password> snubh </flyway.datasource.password>
- >       <Flyway.locations> classpath: db / migration / oracle </flyway.locations>
- >       <Security.enabled> false </ security.enabled>
- >       <Security.token.expiration> 43200 </security.token.expiration>
- >       <Security.origin> * </ security.origin>
- >       <Security.ssl.enabled> false </ security.ssl.enabled>
- >       <Security.oauth.callback.ui> http: // localhost / atlas / # / welcome </security.oauth.callback.ui>
- >       <Security.oauth.callback.api> http: // localhost: 8080 / WebAPI / user / oauth / callback </security.oauth.callback.api>
- >       <Security.oauth.google.apiKey> </ security.oauth.google.apiKey>
- >       <Security.oauth.google.apiSecret> </ security.oauth.google.apiSecret>
- >       <Security.oauth.facebook.apiKey> </ security.oauth.facebook.apiKey>
- >       <Security.oauth.facebook.apiSecret> </ security.oauth.facebook.apiSecret>
- >     </ Properties>
- >   </ Profile>
- > </ Profiles>
- > </ Settings>
-

**Comment by chrisknoll** [comment]
Please leave additional information as a comment to the origional issue. Thank you!
