### ISSUE TITLE
pac4j saml library dependency issue

### ISSUE THREAD

**Issue by CyloNox** [OHDSI/WebAPI#2012]
I was not able to build the tool due to a dependency not found. The reason for this is that there is no repo reference for shibboleth where the dependency is found.

This is the portion that causes the failure with this error due to not finding the dependency: "Could not find net.shibboleth.tool:xmlsectool:2.0.0"
https://github.com/OHDSI/WebAPI/blob/e4666bfbcf28397b161f35faf1ca4f34215a7c9f/pom.xml#L919-L921

In order to resolve this you would need to include the shibboleth repo so that it can grab it.  I added this to the pom and it builds correctly after:
```
   <repository>
      <id>shibboleth</id>
      <name>build.shibboleth.net</name>
      <url>https://build.shibboleth.net/nexus/content/groups/public</url>
   </repository>
```

**Comment by leeevans** [comment]
@chrisknoll OK I've added it.

**Comment by chrisknoll** [comment]
@CyloNox , could you please try again.

**Comment by CyloNox** [comment]
Do you have this change tied to the master branch? or a sub-branch?

**Comment by chrisknoll** [comment]
It's not tied to any branch. @leeevans changed the configuration of our nexus repository to fetch from the shibboleth repository.  So, it should properly fetch the dependency the next time you do a build.

**Comment by CyloNox** [comment]
I've tried removing it and fails builds again
![image](https://user-images.githubusercontent.com/47669023/159504549-63e7c46e-4997-415d-b5a2-bfb53c0c9186.png)



Downloading from sonatype-nexus-snapshots: https://oss.sonatype.org/content/repositories/snapshots/net/minidev/json-smart/maven-metadata.xml
[WARNING] Could not transfer metadata net.minidev:json-smart/maven-metadata.xml from/to sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots): Transfer failed for https://oss.sonatype.org/content/repositories/snapshots/net/minidev/json-smart/maven-metadata.xml
Downloading from ohdsi: https://repo.ohdsi.org/nexus/content/groups/public/net/shibboleth/tool/xmlsectool/2.0.0/xmlsectool-2.0.0.pom
Downloading from central: https://repo.maven.apache.org/maven2/net/shibboleth/tool/xmlsectool/2.0.0/xmlsectool-2.0.0.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.397 s
[INFO] Finished at: 2022-03-22T10:24:27-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project WebAPI: Could not resolve dependencies for project org.ohdsi:WebAPI:war:2.11.0-SNAPSHOT: Failed to collect dependencies at org.pac4j:pac4j-saml-opensamlv3:jar:4.0.0 -> net.shibboleth.tool:xmlsectool:jar:2.0.0: Failed to read artifact descriptor for net.shibboleth.tool:x
mlsectool:jar:2.0.0: Could not transfer artifact net.shibboleth.tool:xmlsectool:pom:2.0.0 from/to ohdsi (https://repo.ohdsi.org/nexus/content/groups/public): Transfer failed for https://repo.ohdsi.org/nexus/content/groups/public/net/shibboleth/tool/xmlsectool/2.0.0/xmlsectool-2.0.0.pom: java.lang.RuntimeExcepti
on: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by leeevans** [comment]
@CyloNox I'm now able to download the pom file from the OHDSI repo server in my browser using the below URL:
https://repo.ohdsi.org/nexus/content/groups/public/net/shibboleth/tool/xmlsectool/2.0.0/xmlsectool-2.0.0.pom
and download the jar file using this URL:
https://repo.ohdsi.org/nexus/content/groups/public/net/shibboleth/tool/xmlsectool/2.0.0/xmlsectool-2.0.0.jar

Could you check you can download them from a browser too, and then try running the build again?

**Comment by CyloNox** [comment]
Yes, I'm able to remove that repo reference and build correctly now
