### ISSUE TITLE
Having trouble with building the .war file for the WebAPI program.

### ISSUE THREAD

**Issue by ShiftyBlock** [OHDSI/WebAPI#2014]
### Expected behavior
I should get a .war file after following steps in tutorial (setting up postgresql in pgadmin4, modifying the settings.xml file in WebAPIConfig directory.
### Actual behavior
Gets an error message https://pastebin.com/QMrau1tH
### Steps to reproduce behavior
Follow steps in the tutorial. I use macos monterey (intel), maven 3.8, pgadmin4. Have also tried setting JAVA_HOME to both 11 and 8 sdk.

**Comment by ShiftyBlock** [comment]
Fixed by changing javahome in the maven executable file to java8 (can be checked with mvn -v)

**Comment by chrisknoll** [comment]
Yes, good catch.  Currently we depend on classes in the sun.* package which is something exposed in JDK8 but not in later JDKs.  We will eventually move to a more recent JDK so we should be able to avoid these sort of problems when that happens.
