### ISSUE TITLE
Error: Oracle table/view not found OHDSI.COHORT_TAG, OHDSI.TAG

### ISSUE THREAD

**Issue by mbernauer** [OHDSI/WebAPI#2015]
### Expected behavior
Ability to create/update cohorts in Atlas using Oracle for both CDM and WebApi 

### Actual behavior
Getting "Oracle table/view not found" error when trying to generate cohort

### Steps to reproduce behavior
When trying to create/update concept sets or cohorts in Atlas, I’m getting Oracle table/view not found errors for:

    OHDSI.COHORT_TAG
    OHDSI.TAG

I’m running WebAPI v2.10.1. Not sure if this is related but after digging into the source code and looking at database migrations, I’m seeing migration files for PostgreSQL that don’t exist for Oracle. Specifically, these files are in the `WebAPI-2.10.1/src/main/resources/db/migration/postgresql` directory:

```
    V2.8.1.20210203163300__gis_service_add_check_source_permission.sql
    V2.8.1.20210219100459__evidence_get_permission.sql
    V2.8.1.20210226100460__evidence_get_permission.sql
    V2.9.0.20210423125133__assets_tags.sql
    V2.9.0.20210513111520__versioning.sql
    V2.9.0.20210812164224__assets_tags_renaming.sql
```

The Oracle migration directory contains files up to v2.8.0, but there are no migration files for v2.9.x or v10.1.x corresponding to the PostgreSQL migration files listed above. I’m going to try to manually create the SQL statements from the files above and apply them to my Oracle database. I’m hopeful that will let me run Atlas.

Has anyone experienced similar issues while running the CDM and WebAPI on Oracle? I'm guessing this may be the result WebApi's move away from Oracle...

**Comment by rs21brady** [comment]
@chrisknoll what type of effort would it take in order to keep the Oracle migrations up to date? Is this just making sure that each postgreSQL migration that comes out with each subsequent release gets an equivalent Oracle dialect specific migration file as well? Are these migration files auto-generated, or is this something that a volunteer would just do by hand until it has the same outcome that it has on the PostgreSQL db?

**Comment by chrisknoll** [comment]
It is something that someone would have to volunteer to do, because each dialect would require their own special cases.   Anyone can submit a PR to add it, it's just that we're not going to support it.
