### ISSUE TITLE
I want to log in using Google oauth in ATLAS. Help

### ISSUE THREAD

**Issue by josungha** [OHDSI/WebAPI#2016]
### Steps to reproduce behavior
///////////////////////////////////////////////////////////////////////////////

I want to log in using Google oauth in ATLAS

WebAPI and ATLAS
I've been using it recently. I want to use google oauth, but I'm not sure which part to touch first.

![캡처1](https://user-images.githubusercontent.com/89909850/162375148-4ae6fbc1-d5ea-4c15-b9d6-6a18b768ad94.PNG)
![캡처2](https://user-images.githubusercontent.com/89909850/162375156-e2e9e6f6-62c5-4059-b4e4-2a9db935f5b9.PNG)

**Comment by chrisknoll** [comment]
Did you review this information: https://github.com/OHDSI/WebAPI/wiki/Security-Configuration?

**Comment by josungha** [comment]
I entered the key and secret related to google oauth.

**Comment by josungha** [comment]
> https://github.com/OHDSI/WebAPI/wiki/Security-Configuration 정보를 검토하셨습니까 ?

//////////////////////////////////////////////////////////////////////////////////////////////////////

I entered the key and secret related to google oauth.

I'm not sure what to fix.

**Comment by anthonysena** [comment]
Can you provide more details on any subsequent issues you faced after updating the key/secret related to Google OAuth? Otherwise we'll close this out and presume you were able to complete the configuration.

**Comment by anthonysena** [comment]
Sorry to close this issue - re-opening in the hopes that you can provide an update and then we can close this out.

**Comment by chrisknoll** [comment]
Will Close this since we haven't seen any updates in over a year. Please comment if you have any additional information.
