### ISSUE TITLE
Added a new function to Profile.js to test http communication. But I get a 403 error. What causes the error?

### ISSUE THREAD

**Issue by josungha** [OHDSI/WebAPI#2017]
### Steps to reproduce behavior
////////////////////////////////////////////////////////////////////////////////////////
![캡처](https://user-images.githubusercontent.com/89909850/163347844-2c427642-3293-4e78-aae9-8582148b53c2.PNG)

And the "const response" of the response is Promise - rejected.

**Comment by chrisknoll** [comment]
A response of 403 is an authorization error.

**Comment by anthonysena** [comment]
Closing as this appears to be an authorization issue per https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403. Please let us know if you are still facing any challenges and we can re-open this issue.
