### ISSUE TITLE
cohort count not updating after CDM update due to parsing of design hash count

### ISSUE THREAD

**Issue by andtsouch** [OHDSI/WebAPI#2018]
### Expected/Actual behavior
After a CDM is updated and the records in a table have changes, cohorts that use these records would be expected to change as well. For example our death table has some error and included only 600 deaths instead of 4000 that would be expected. After an update on the ETL and producing a new CDM, we investigate the death table on postgres and it included 4000 as expected.

However, after going back to ATLAS and regenerating the cohort, we could see that the count is still the same (old count). The count would also not change even after creating a copy of that cohort with different cohort_id. After some testing we indetified, that this happens because webAPI is caching the results of the specific design_has of the cohort and is parsing that every time the cohort is generated, without running the query again against the database. 

The solution would be to somehow be able to deactivate this functionality and have WebAPI always computing the results for generation of cohort count against the database. That would allow having always the updated results on ATLAS without having to clean out the cache tables every time the CDM is updated.

### Steps to reproduce behavior
1. Generate cohort counts for a specific cohort with any death and check the count
2. Drop half of the death table, run Achilles etc and regenerate the counts of that cohort again. The cohort count will not change since it is parsing the previous count of this design has
3. Delete the cache results on the caches tables and regenerate the cohort. The cohort should now have the correct results.

**Comment by anthonysena** [comment]
Noting that this would be a useful addition to the WebAPI wiki under data source management.

**Comment by adtsouch** [comment]
Thank you for the suggestion, I will give that a try

**Comment by chrisknoll** [comment]
In conclusion, if you are going to update the CDM, the results.cohort_cache should be truncated so that cached results will not be reused.
