### ISSUE TITLE
Wiki documentation errors

### ISSUE THREAD

**Issue by PRijnbeek** [OHDSI/WebAPI#202]
Hi,

I think this is not correct in the webAPI installation documentation:

INSERT INTO ohdsi.source (source_id, source_name, source_key, source_connection, source_dialect) VALUES (1, 'My Cdm', 'MY_CDM', ' jdbc:oracle:thin:ohdsi/{password}@127.0.0.1:1521/xe', 'oracle');
INSERT INTO ohdsi.source (source_id, source_name, source_key, source_connection, source_dialect) VALUES (2, 'Default vocabulary', 'vocab', 'jdbc:oracle:thin:ohdsi/{password}@127.0.0.1:1521/xe', 'oracle');

This should be webapi.source instead of ohdsi.source

Furthermore, I do not see the screenshots in the wiki that i think should be there in the PostgreSQL Setup Guide.

Thanks

**Comment by anthonysena** [comment]
@PRijnbeek - this has been address in some of recent wiki updates per #999 and so I'm going to close this out. Thanks!
