### ISSUE TITLE
Installing WebAPI on a Windows Machine - Error when  building the WebAPI.war using Maven

### ISSUE THREAD

**Issue by avtaylor** [OHDSI/WebAPI#2023]
I am installing WebAPI on a Windows machine (a VM on Azure) - I went through all the steps explained in the installation guide. The main aim is to install Atlas.

However when building with Maven I get BUILD FAILURE
the top error is:
 "Failed to execute goal org.codehaus.gmaven:gmaven-plugin:1.5:execute (add-git-branch-info) on project WebAPI: Execution add-git-branch-info of goal org.codehaus.gmaven:gmaven-plugin:1.5:execute failed: An API incompatibility was encountered while executing org.codehaus.gmaven:gmaven-plugin:1.5:execute: java.lang.ExceptionInInitializerError: null"

I run "mvn clean package -DskipUnitTests -DskipITtests -s WebAPIConfig/settings.xml -P webapi-postgresql"
The full error file is here: https://drive.google.com/file/d/1aPrYFHItk6a4GbZMKE0T89MhIkpT0DOf/view?usp=sharing 

I have PostgreSQL v12 installed in 2020.
Apache Tomcat was installed recently, also Apache Maven, Git and JDK. 

Could anyone help?
Many thanks
Amelia

**Comment by avtaylor** [comment]
The full error file is attached [https://drive.google.com/file/d/1aPrYFHItk6a4GbZMKE0T89MhIkpT0DOf/view?usp=sharing](https://drive.google.com/file/d/1aPrYFHItk6a4GbZMKE0T89MhIkpT0DOf/view?usp=sharing)

**Comment by chrisknoll** [comment]
can you do a java -version to tell us what version of java you have installed?

**Comment by anthonysena** [comment]
It would be helpful to add to the WebAPI installation guide a step to verify the java version:
```
C:\Users\asena5>java -version
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
```

**Comment by avtaylor** [comment]
Thank you for your help. 
Here are the details:
java 18.0.1 2022-04-19
Java(TM) SE Runtime Environment (build 18.0.1+10-24)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1+10-24, mixed mode, sharing)

**Comment by avtaylor** [comment]
I have installed the old version and rerun Maven. This worked now withour errors.
However, when deploying the WebAPI to the Apache Tomcat Manager I get the following error:
"This site can’t be reachedThe webpage at http://localhost:9090/manager/html/upload?org.apache.catalina.filters.CSRF_NONCE=B846CD1F65EB18D176EF0472C908D769 might be temporarily down or it may have moved permanently to a new web address.
ERR_CONNECTION_ABORTED"
What could the prooblem be?
Kind regards
Amelia
