### ISSUE TITLE
Atlas setup

### ISSUE THREAD

**Issue by Gupr1989** [OHDSI/WebAPI#2025]
Hi Team,

I have followed the below steps. with few changes to pom.xml I was able to generate WebAPI.war file.

https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide

when I try to deploy the war file in tomcat, server crashes without error.
![image](https://user-images.githubusercontent.com/98937606/160409399-917067b4-ade6-4a2d-8b0c-73e7f732d723.png)

Can you please help me with this.

**Comment by anthonysena** [comment]
@Gupr1989 - can you obtain any information from the tomcat log files (in your CATALINA_HOME/logs directory)?

**Comment by Gupr1989** [comment]
@anthonysena 

Thanks for response, I got Atlas and Achilles running now with few data. Can you please help me get the sample data that you are using in demo Atlas.
https://atlas-demo.ohdsi.org/#/datasources/SYNPUF1K/drugera.

I have downloaded the data from the below link, achilles>data>SAMPLE json files has no data for drugera and data in many other reports are missing after running Achilles exportToJson.
http://www.ltscomputingllc.com/downloads/

**Comment by anthonysena** [comment]
@Gupr1989 - a few thoughts: if you have the SYNPUF data downloaded and ready, you may be able to build out the derived tables (i.e. drug_era) using the information on https://ohdsi.github.io/CommonDataModel/cdm53.html#Standardized_Derived_Elements. There are SQL scripts you can run such as https://ohdsi.github.io/CommonDataModel/sqlScripts.html#drug_eras that will build the drug eras for you. You may then need to re-run Achilles to have that information for the ATLAS data sources.

Another option is to try and use the data from the OHDSI on AWS project:

https://github.com/OHDSI/OHDSIonAWS/tree/master/datasources

I have not tried to use this myself but I know that those scripts are used when deploying the OHDSI stack on AWS.

**Comment by Gupr1989** [comment]
@anthonysena 
I am on CDM v5.4
Got the DDL from here - https://github.com/OHDSI/CommonDataModel/tree/main/inst/ddl/5.4/postgresql
and using the below data 
https://caruscloud.uniklinikum-dresden.de/index.php/s/Qog8B5WCTHFHmjW/download

with the above data I can just see person , data density and observation period in both Achilles and Atlas
I see all the csv data that I got online does not have data for concept table, is it something we have to create in atlas ? I am looking to see records in drug era, and add new concepts in atlas (I created sample records in concepts tables and added all constraints, no luck)

I have gone through the link - https://ohdsi.github.io/CommonDataModel/sqlScripts.html#drug_eras
Tried executing sql query in my postgres, sql does not return any record because of where clause concept.vocabulary_id = 'RxNorm', and concept_class_id = 'Ingredient'

when I try to copy --https://github.com/OHDSI/OHDSIonAWS/blob/master/datasources/CMSDESynPUF1kpostgres.sql
--COPY OMOP.CONCEPT FROM '/tmp/tempdata/CONCEPT.csv' WITH DELIMITER E'\t' CSV HEADER QUOTE E'\b';
I get error - No such file or directory.

It will be helpful if I get data in csv for all the tables including concept as we see in atlas demo.

**Comment by chrisknoll** [comment]
Will close this issue since it's related to setup and configuration. Feel free to continue here, but the [forums](https://forums.ohdsi.org/) are a great resource for asking these questions.
