### ISSUE TITLE
Atlas Security

### ISSUE THREAD

**Issue by roger-secure** [OHDSI/WebAPI#2026]
Posting here as there is no active Atlas working group at the moment. 

Could I ask about security?
Can I confirm Log4j2 version 2.17.1 fixes the OHDSI WebAPI Log4j vulnerability?

Is it still the case that Atlas will only run on Tomcat8? Our advice is we **MUST** use Tomcat10 for security reasons.

**Comment by chrisknoll** [comment]
I believe we have addressed the Log4j concerns, and that tomcat10 should work. We have received requests about certifying that things work on Tomcat10, so I think we should make an issue for formal support of Tomcat 10.
