### ISSUE TITLE
Error running http: // localhost: 8080 / WebAPI / source / sources

### ISSUE THREAD

**Issue by mircom2** [OHDSI/WebAPI#203]
Http: // localhost: 8080 / WebAPI / source / sources There is an error in the execution result and I would like help.

This document is written through Google Translator. Thank you for your understanding.

When running http: // localhost: 8080 / WebAPI / source / sources, only the following text is displayed and the value is not displayed as in the manual.

Http: // localhost: 8080 / WebAPI / source / sources Execution result
[]

Nothing is displayed as above.

Thank you for your help.

**Comment by chrisknoll** [comment]
It's possible that the empty result is cached. Can you go to this url:

```
Http: // localhost: 8080 / WebAPI / source / refresh
```

If you still get [], can you please execute the following query on your database you configured for WebAPI:

```
select * from SOURCE
```

You may need to put the webAPI schema before SOURCE (ie: webapi.SOURCE) but I do not know how you have configured your database enviornment.

If the SORUCE table is empty, you need to add records to that table, described here: http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:webapi_installation_guide under the heading "webAPI SOURCE and SOURCE_DAIMON Inserts.

**Comment by mircom2** [comment]
Select * from SOURCE I get the following results when I run the query but still
[] Only empty results.

1 My Cdm MY_CDM jdbc: oracle: thin: ohdsi / snubh@127.0.0.1: 1521 / snuhos oracle
2 Default vocabulary vocab jdbc: oracle: thin: ohdsi / snubh@127.0.0.1: 1521 / snuhos oracle

Thank you for your help.

**Comment by anthonysena** [comment]
Closing out - old issue
