### ISSUE TITLE
SQLException: No suitable driver found - connection to Bigquery through JDBC 4.2

### ISSUE THREAD

**Issue by gabriellopes** [OHDSI/WebAPI#2037]
First, hello everybody!
Thank you for the great job you guys are doing in order to permit improvements in Healthcare according to better visualization and analysis of health data. 

### Expected behavior
So, I'm trying to connect Atlas to Bigquery through WebAPI. At the latter, I've configured both _source_ and _source_daimon_ tables, in order to admit a connection to the BigQuery repository.

By following the steps of [JDBC Data Connector by Google BigQuery](https://storage.googleapis.com/simba-bq-release/jdbc/Simba%20Google%20BigQuery%20JDBC%20Connector%20Install%20and%20Configuration%20Guide.pdf#page=43&zoom=100,106,180), I've created the following _connection String_:

```
jdbc:bigquery://https://www.googleapis.com/bigquery/v2:443;ProjectId=bigquery-public-data.cms_synthetic_patient_data_omop;OAuthType=0;OAuthServiceAcctEmail=xxxxxxxxx-compute@developer.gserviceaccount.com;OAuthPvtKeyPath=~/service-acc_key.json
```

### Actual behavior
And, when I try to, for instance, Generate a given Cohort, I receive the following error message:

```
java.sql.SQLException: No suitable driver found for jdbc:bigquery:...
```

I guess I'm missing something at the server-side, where there are the .jar files from the JDBC and where it is running WebAPI.

### Steps to reproduce behavior

1. Configure the CDM in the WebAPI,
2. Create a JDBC connection string to a Bigquery server,
3. Try to generate a Cohort from Atlas

Thank you in advance!

**Comment by konstjar** [comment]
You need to build the application with "webapi-bigquery" profile. Also you need to specify the path to driver. 
https://github.com/OHDSI/WebAPI/blob/master/pom.xml#L1467

**Comment by gabriellopes** [comment]
Hey @konstjar , thank you so much for your contribution!
It redirected my attention from the connection string toward the .war WebAPI. 

Well, I've tried to generate a new version from WebAPI, but, as it was in the 2.7.8 version, most of the libs related to google and bigquery were deprecated. 

So, I've tried a new version, 2.10.1, but, the WebAPI application is losing connection with the tomcat, so "_curl localhost:8080/WebAPI/info_" is returning 404. 

@konstjar , is it possible to be because I'm using Postgres to store **_configuration schemas_**, while bigquery as a **_data repository_**?

Thank you in advance,

**Comment by konstjar** [comment]
I think you have 2 different issues. 
- Not working WebAPI/info means that application was not started properly and you need to check Catalina logs to see the reason
- BigQuery connection - I'm not sure I got your point. WebAPI does not have BigQuery driver and support of the dialect. You need to specify the path to driver and enable profile in maven commands.

**Comment by alex-odysseus** [comment]
@gabriellopes closing as there are no comments for quite long time and we don't experience issues connecting to a BigQuery instance
