### ISSUE TITLE
V1.0.0.9__shiro_security.sql During the migration, the following error occurs in the last query.

### ISSUE THREAD

**Issue by mircom2** [OHDSI/WebAPI#204]
V1.0.0.9__shiro_security.sql During the migration, the following error occurs in the last query.

Error starting from line 4 of the command:
ALTER TABLE ohdsi.SEC_ROLE_PERMISSION ADD CONSTRAINT FK_ROLE_PERMISSION_TO_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES ohdsi.SEC_PERMISSION (ID)
Error reporting:
SQL error: ORA-00972: length of identifier is too long
00972. 00000 - "identifier is too long"
* Cause: An identifier with more than 30 characters was specified.
* Action: Specify at most 30 characters.

How do I resolve it?
The version of Oracle I'm using is shown below.
Oracle Database 12c Standard Edition Release 12.1.0.2.0 - 64bit Production

Thank you for your help.

**Comment by chrisknoll** [comment]
Looks like migration scripts were added that violate the Oracle constraint of maxlength of 30 characters:
FK_ROLE_PERMISSION_TO_PERMISSION = 32 characters.

**Comment by anthonysena** [comment]
Closed via #211
