### ISSUE TITLE
Anonymous role capability for Data Sources

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#2060]
### Expected behavior
With security enabled, we should be able to still share Data Sources with non-Atlas users. 

### Actual behavior
Data Sources can only be accessed by the "Atlas Users" role. We have people in our organization that do not have Atlas access as they are not hands-on users, but would like to still view the aggregated Data Sources reports.

### Steps to development
1. Add an optional role for Data Sources when security is enabled that still authenticates the user but allows for the reports to be accessed.
2. "Data Sources Viewer" could be the name. It has the same anonymous role behavior, but has the Data Sources permission enabled. 
3. This role isn't something every site needs. Add a config option "dataSourcesRole".

**Comment by chrisknoll** [comment]
Yes, I think that's the proper approach: manage permissions that fits your local environment use-case, in this case grant more permissions to the public role (which all users have).
