### ISSUE TITLE
PHOEBE 2.0 implementation for WebAPI

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#2064]
### Overview

PHOEBE is a concept recommendation tool that assists in creating concept set expressions by suggesting related concepts that may be found through lexical (string), ontological (concept ancestor) or similarity (cosine similarity).  This issue is meant to track the necessary WebAPI updates to support the end-pionts and results schema updates necessary to implement this functionality.

### Endpoints

1. Suggest Concept:  Given an input string with terms related to a concept of interest, this end-point will return a concept that is suggested based on PHOEBE selection algorithm.
2. Recommend Concepts: Given an input of a set of concept IDs, this end-point will return the recommended concepts based on the lexical, ontological and similarity scores of the input concepts.

### Security

This should follow the same vocabulary searching rules as any other vocabulary source.   

### Results Schema

Several (TBD) results tables will be created to provide a mapping between concepts and their recommendations.  Note: some recommendations can be performed on the fly by a concept search, others will use a 'similarity matrix' type of table to perform the lookup, where the table of similarities will be provided through an external process (ie: you load the lookup table as part of an ETL process or when initializing the results schema for a CDM).

### Source Daimons

TBD: should a new source daimon be introduced to represent the PHOEBE tables?

**Comment by alondhe** [comment]
Again, shifting to 2.12 based on convo with @chrisknoll -- hope this is okay.

**Comment by chrisknoll** [comment]
Fixed in #2087.
