### ISSUE TITLE
Executing an Incidence Rate Analysis on an IBM Netezza Data Source fails while creating a temp table

### ISSUE THREAD

**Issue by alex-odysseus** [OHDSI/WebAPI#2124]
### Expected behavior
Successful analysis execution

### Actual behavior
After a minute or so there is an error

java.util.concurrent.CompletionException: org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL [CREATE TEMP TABLE Codesets  (codeset_id int NOT NULL,
...

### Steps to reproduce behavior
- design a new Incidence Rate Analysis
- click on the "Generate" button on the "Generation" tab choosing the respective IBM Netezza Data Source

**Comment by chrisknoll** [comment]
I'm assuming all these temp table creation errors are related on IBM Netezza, so perhaps we need to file 1 issue to cover that?
