### ISSUE TITLE
Cohort Characterization result is ~x2 times more with Visit Detail limitation in Cohort with empty VISIT_DETAIL table

### ISSUE THREAD

**Issue by ttemnikova** [OHDSI/WebAPI#2129]
### Expected behavior
The empty VISIT_DETAIL table does not affect the cohort characterization
### Actual behavior
According to the cohort characterization result, the cohort **with** visit detail limitation has ~2x more people than the cohort without visit detail limitation
![image](https://user-images.githubusercontent.com/95474802/195084078-35190714-3520-40aa-8117-e78eb4a43c49.png)
### Steps to reproduce behavior
Prerequisites: VISIT_DETAIL table is empty
1. Login
2. Create a cohort 
3. Add some entry events
4. Add a visit detail attribute to an initial event
5. Create the same cohort as in # 3
6. Create a cohort characterization with these two cohorts (I used the following features, but I don't think they are so important: Condition Era Long Term, Demographics Age Group, Demographics Gender, Chads 2)
7. Generate the cohort characterization
8. Observe the result
Example cohort characterization: [regress 2.11 vs regress 2.12 withOUT concept sets but WITH visit details.txt](https://github.com/OHDSI/WebAPI/files/9754777/regress.2.11.vs.regress.2.12.withOUT.concept.sets.but.WITH.visit.details.txt)

**Comment by chrisknoll** [comment]
Does this need to be done in the context of a cohort characterization? Wouldn't just generating both cohorts give you the counts that you can compare with each other?

I ask because adding the layer of a characterization may obscure what is actually going on.

**Comment by ttemnikova** [comment]
When I generate these cohorts in the Cohort Definition section, the results are equal (in my case it is 50,103 people). But in Cohort Characterization section, I observe different results for these two cohorts (50,103 for the cohort without visit detail event attribute and 97,392 for the cohort with the visit detail) which is confusing.

**Comment by chrisknoll** [comment]
Ok!  Thanks for the clarification.  I'm relieved that I think the visit detail logic is working (we do have unit tests for that) but worried about what is happening on the characterization side...when we call cohort characterization we load the 'cached results' of a given cohort definition using a 'design hash' of the cohort...is it possible that the with and without cohort hashes to the same 'design hash' thus leading to some kind of duplicate entries being added tot he cache?   We need to investigate further.

**Comment by chrisknoll** [comment]
I'm wondering if this is an anomaly related to the distribtuion statistics, where the column heading says 'people' but in fact it's the total number of records used to make the distribtion (ie, it's not 50k peopel, it's 50k chads2 scores).   Can you show me the other elemetns of the report such as gender, and see if it is also showing 50k people in the cohort or if it looks correct?

**Comment by ttemnikova** [comment]
Cohort definition looks the same
<img width="959" alt="cohort_def" src="https://user-images.githubusercontent.com/95474802/195304189-83ef5d84-2ee6-4f17-8b54-d50e543cc6ee.png">

But in cohort characterization the number of people look differently
<img width="649" alt="Cohort_charact_gender" src="https://user-images.githubusercontent.com/95474802/195304732-6fbd3f2b-33e0-4c15-adb8-d2b721baa6f0.png">

**Comment by chrisknoll** [comment]
But the records look different:   you have 50k records in the cohort, but 97k records in the second cohort. This leads me to believe that you have 'earliest per person' set in one cohort but 'all events per person in the other'. Can you confirm? I haven't had a chance to download your JSON specifications to look locally, so sorry to have to ask you for this detail.

**Comment by alex-odysseus** [comment]
Chris, you are right

Shouldn't we have different visualizations (column naming) then not to confuse users in Characterizations for Cohorts with " Limit qualifying cohort to: all events per person. " and " Limit qualifying cohort to: earliest event per person. "?

As then Count currently means the number of records and not distinct persons, doesn't it? @chrisknoll

**Comment by chrisknoll** [comment]
I think count currently means records, always, but you can assume the count is for person when you know that your cohort definition is 1 event per person.   But if you consider the context of this report: it's a distribution report, so it's giving you IQRs and averages, and the important info there is not how many people, but how many values went into the distribution.

**Comment by ttemnikova** [comment]
Thank you Alex and Chris. Yes, as Alex mentioned, I had 'all events per person' in the cohort with visit detail attribute. But it was in the block of Inclusion criteria and I've never thought that this limitation on an empty block (there are no inclusion criteria in these two cohorts) can affect the result of the cohort characterization analysis.
