### ISSUE TITLE
Basic Security on 2.12 - authorization broke? Unable to set configuration or get execution engine status

### ISSUE THREAD

**Issue by rkboyce** [OHDSI/WebAPI#2143]
Hi, 

I went through all of the steps to get WebAPI Basic security working on my Atlas/WebAPI installation and am able to authenticate but authorization seems broken or misconfigured in my environment. The authenticated user account appears to have appropriate permissions but I can't get to the configuration page to move to the next step.

### Expected behavior

After logging in for the first time with a user assigned the admin role, be able to set configuration within Atlas per https://github.com/OHDSI/WebAPI/wiki/Atlas-Security 

### Actual behavior

logging in with a user assigned the admin role succeeds but there is no way to go to the configuration section of Atlas to set up permissions. All access is blocked. There is no error or warning that indicates an issue.

![image](https://user-images.githubusercontent.com/104793/198018914-ecefac44-988a-4ac6-b877-c5edd9c75add.png)

![image](https://user-images.githubusercontent.com/104793/198018971-c145b7a3-04bb-4f70-9388-109e5b8d4837.png)

![image](https://user-images.githubusercontent.com/104793/198019130-e68f303d-2004-417d-bed6-8b1e8b41941e.png)

### Steps to reproduce behavior

WebAPI info (recently migrated to 2.12 from 2.7):

```
{"version":"2.12.0","buildInfo":{"artifactVersion":"WebAPI 2.12.0","build":"NA","timestamp":"Tue Oct 25 21:13:35 UTC 2022","branch":"*","commitId":"*","atlasRepositoryInfo":{"milestoneId":42,"releaseTag":"*"},"webapiRepositoryInfo":{"milestoneId":43,"releaseTag":"*"}},"configuration":{"security":{"samlActivated":false,"enabled":true,"samlEnabled":false},"vocabulary":{"solrEnabled":false},"person":{"viewDatesPermitted":false},"plugins":{"atlasgisEnabled":false},"heracles":{"smallCellCount":"5"}}}
```

WebAPI settings.xml related to security

```
<security.provider>AtlasRegularSecurity</security.provider>
      <server.port>9090</server.port>
      <security.origin>*</security.origin>
      <security.ssl.enabled>false</security.ssl.enabled>
      <security.cors.enabled>true</security.cors.enabled>
      <security.maxLoginAttempts>3</security.maxLoginAttempts>
      <security.duration.initial>10</security.duration.initial>
      <security.duration.increment>10</security.duration.increment>
      <security.db.datasource.schema>atlas_security</security.db.datasource.schema>
      <datasource.url>jdbc:postgresql://localhost:5432/gsph_pace_security</datasource.url>
      <datasource.username><USER></datasource.username>
      <datasource.password><PWORD></datasource.password>
      <security.db.datasource.authenticationQuery>select password from ${security.db.datasource.schema}.users where lower(email) = lower(?)</security.db.datasource.authenticationQuery>
    </properties> 
```

WebAPI is running on port 9090 of localhost served behind Apache on the same machine but, for institutional security reasons, reached through a different Apache proxy on another server. 

Apache proxy configs:

- host of WebAPI

```
<VirtualHost *:80>
        ServerName localhost
        ServerAlias <host name>
        ServerAlias <host IP>
        DocumentRoot <path to where the Atlas code resides> 
        ...
</VirtualHost>
```

- proxy server
```
        <Location /pace_webapi/>
          ProxyPass  "http://<host server>:9090/WebAPI-GSPH/"
          ProxyPassReverse  "http://<host server>:9090/WebAPI-GSPH/"
          <RequireAny>
            Require all granted
          </RequireAny>
       </Location>

        <Location /pace_atlas/>
          ProxyPass  "http://<host server>/Atlas-GSPH/"
          ProxyPassReverse  "http://<host server>/Atlas-GSPH/"
          <RequireAny>
            Require all granted
          </RequireAny>
       </Location>
```

Atlas info:
 - version 2.12.0
- config-local.js:
```
define([], function () {
	var configLocal = {};
        configLocal.userAuthenticationEnabled = true;
	configLocal.api = {
		name: 'GSPH-PACE',
	        url: 'http://<IP for the proxy server>/pace_webapi/' 
	};
        configLocal.authProviders = [{
		"name": "Local Security Test DB",
		"url": "user/login/db",
		"ajax": true,
		"icon": "fa fa-database",
		"isUseCredentialsForm": true
	}];
	return configLocal;
});
```

Database setups:

Security DB:

![image](https://user-images.githubusercontent.com/104793/198022155-d545e77d-69bf-4661-98cb-a830e9fe92ad.png)

WebAPI DB in the OHDSI schema

![image](https://user-images.githubusercontent.com/104793/198022391-82b3edf9-8a2e-4925-86cc-8a1efde1c277.png)

User permissions

![image](https://user-images.githubusercontent.com/104793/198022483-a941425b-4c0c-4bec-aac0-03c5ef3ad95b.png)

Atlas network behavior:

![image](https://user-images.githubusercontent.com/104793/198022691-89cab4e8-a2a9-45ba-afbc-91869bec4d3b.png)

![image](https://user-images.githubusercontent.com/104793/198022769-7410ff20-6997-472d-9522-81e8ba0af90a.png)

http://130.49.206.139/pace_webapi/user/me 

```
{"id":1000,"login":"rdb20@pitt.edu","name":"rdb20@pitt.edu","permissions":[{"id":616,"permission":"source:daimon:priority:get","description":"Get priority of Source Daimons"},{"id":507,"permission":"user:me:get","description":"Get info about current user (myself)"},{"id":45,"permission":"source:*:get","description":"Read configuration"}]}
```
http://130.49.206.139/pace_atlas/#/configure

![image](https://user-images.githubusercontent.com/104793/198023050-c1eded2f-8920-429e-853e-d31be5e67c79.png)

This is where I am stuck. I did read through all of the github posts mentioned on the wiki but don't see anything that corresponds exactly to this issue. Can you please suggest  next steps?

**Comment by anthonysena** [comment]
@rkboyce - could you also try adding the `Atlas user` role to your user account to see if that helps?

**Comment by rkboyce** [comment]
@anthonysena  - thanks for the suggestion. I see that `Atlas users` (addition of 's' instead of `Atlas user`) is in sec_role as role 10 and that sec_role_permission has a long list of permissions. I tried once to add that role id to my user by adding a row to sec_user_role in addition to the one that grants admin but did not see a change (not sure if a user can have more than one role in t hat table. Can you please suggest how it should work?  I will see if something is off in my setup. I do notice that the 'status' column is null in sec_user_role. Does that matter?

**Comment by anthonysena** [comment]
Hi @rkboyce - yes, you can have more than 1 role in the `sec_user_role` table and I'd suggest you have: admin, Atlas user, public (this should be granted by default) and add in any data source roles you have (for example your vocabulary data source). That should allow you to see the configuration screen but let me know if you still face any challenges.

**Comment by rkboyce** [comment]
Ok - it took me awhile to see this but I did not realize that the WebAPI recreated the entire ohdsi schema in the security database. So, the whole time, I was configuring the sec_* tables in the original ohdsi schema. Once I added the roles to the correct sec_user_role table in the security DB it all worked as expected! I did have to copy a heap of data from old ohdsi schema to the new one (and will probably have to edit some sequences used for row ids soon). All good! Thanks!

**Comment by chrisknoll** [comment]
glad you have it fixed, but it's odd that somehow you have the ohdsi schema in the security schema....causing you to copy data from old schema to new.  I think something may be wrong there, but if you have something that works for you, then that's good.
