### ISSUE TITLE
Mapping AD groups to Atlas/WebAPI roles

### ISSUE THREAD

**Issue by nzurawski** [OHDSI/WebAPI#2153]
### Expected behavior
Ability to search AD for all groups and map the appropriate ones to existing roles in Atlas
### Actual behavior
Can only search for groups that match the OU of the AD service account defined in WebAPI settings.xml
### Steps to reproduce behavior
I have a service account created just for accessing Active Directory defined in the webAPI settings.xml file like this:
<security.ad.system.username>$SAUserName</security.ad.system.username>
<security.ad.system.password>$SAPassword</security.ad.system.password>

and the search base parameters with the matching OU
<security.ad.searchBase>OU=$SaMatch,DC=example,DC=org</security.ad.searchBase>

This allows me and everyone else in the organization to log into Atlas with our AD accounts but we are given no permissions upon log in. I would like to have an AD group specific for each role in Atlas and use the Import AD Group functionality but when searching for AD groups within that functionality I can only find groups that match the OU of the service account and that is not the OU our organization uses for regular user groups like this. Is there a way to define a separate search base and still use the Service account for simply accessing the AD?

**Comment by anthonysena** [comment]
Tagging @konstjar @alondhe for advice on this issue.

**Comment by konstjar** [comment]
1. Remove OU=$SaMatch from "searchBase": <security.ad.searchBase>DC=example,DC=org</security.ad.searchBase>
2. Ensure you are using Global Catalog port for AD

**Comment by konstjar** [comment]
Yes, it's per design. You can limit this huge list by using <security.ad.searchFilter> parameter. Eg, I want to see in the list only users who are in "ATLAS-USERS" group:
(&(sAMAccountName=*)(memberOf=CN=ATLAS-USERS,OU=groups,dc=example,dc=org))

**Comment by konstjar** [comment]
The point of selecting the group and users - to create user records in WebAPI and assign roles in advance.

**Comment by nzurawski** [comment]
Apologies, I was just a little confused by what I was seeing.

So if I was to not change the search filter parameter and just match one group with the admin role and do nothing else, would it only import the users in that group or would it import all users?

**Comment by konstjar** [comment]
The users of selected group will be imported only. If you create scheduled task, new users will be imported too.

**Comment by nzurawski** [comment]
Forgot to close this.
