### ISSUE TITLE
Moderator cannot delete reusable despite reusable:*:delete permission

### ISSUE THREAD

**Issue by ttemnikova** [OHDSI/WebAPI#2158]
### Expected behavior
The asset is deleted
### Actual behavior
The asset is not deleted. The request `DELETE WebAPI/reusable/<reusableid>` returns 403
### Steps to reproduce behavior
**Prerequisites**: Moderator role has reusable:*:delete permission
1. Login as Moderator
2. Go to Reusables
3. Open an asset created by another user
4. Try to delete the asset

**Comment by chrisknoll** [comment]
What is 'Moderator'?  I think we have an understanding of 'admin', 'public' and 'atlas user', but Moderator?
