### ISSUE TITLE
Create a guide how to contribute new localizations 

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#2167]
### Expected behavior
As a developer I would like to contribute and create new localizations. Unfortunately I cannot find any information in Wiki

### Actual behavior
I can find instructions for localization package development

### Steps to reproduce behavior
See wiki and observe nothing :-)

**Comment by anton-abushkevich** [comment]
now we have it! https://github.com/OHDSI/WebAPI/wiki/Localization-Development#contribute-your-localization
