### ISSUE TITLE
Wiki clean up

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#2168]
As Oracle and MS Server are not supported for WebAPI, I would propose to remove these pages from Wiki to avoid confusion:
https://github.com/OHDSI/WebAPI/wiki/Oracle-DB-Setup-Guide
https://github.com/OHDSI/WebAPI/wiki/SQL-Server-Setup-Guide

@anthonysena what do you think?

**Comment by anthonysena** [comment]
Agreed & done. Thanks!
