### ISSUE TITLE
WebAPI works only when Tomcat launched with `sudo`

### ISSUE THREAD

**Issue by scheah92** [OHDSI/WebAPI#2205]
### Expected behavior

When launching Tomcat using a dedicated `tomcat` user with ownership set on the `/tomcat` directory, `./catalina.sh start` should launch the server and deploy the WebAPI and ATLAS webapps successfully.

### Actual behavior

When launching as above, Tomcat shows WebAPI as having 'successfully' deployed, however, querying any of the WebAPI endpoints returns a 404 error.

'Successful' deploy:
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/98944366/218467533-d38996b7-8755-49bb-bd71-41a82d23ae4a.png">

404 error upon querying WebAPI endpoint:
<img width="773" alt="image" src="https://user-images.githubusercontent.com/98944366/218467622-a9d706e2-6e54-4a61-80d5-03d994232dd6.png">

Error logs related to non-`sudo` WebAPI deployment:
```
13-Feb-2023 10:32:11.539 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/WebAPI.war]
13-Feb-2023 10:32:11.564 WARNING [localhost-startStop-1] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'antiJARLocking' to 'true' did not find a matching property.
13-Feb-2023 10:32:12.035 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/tomcat/webapps/WebAPI.war] has finished in [495] ms
```

However, launching Tomcat with `sudo ./catalina.sh start` instead allows the WebAPI endpoints to be queried successfully:
<img width="2178" alt="image" src="https://user-images.githubusercontent.com/98944366/218468490-c01d283f-f500-45f2-a68f-9327ee87c326.png">

Error logs related to `sudo` WebAPI deployment:
```
13-Feb-2023 13:16:51.612 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/opt/tomcat/webapps/WebAPI.war]
13-Feb-2023 13:16:51.653 WARNING [localhost-startStop-1] org.apache.catalina.startup.SetContextPropertiesRule.begin [SetContextPropertiesRule]{Context} Setting property 'antiJARLocking' to 'true' did not find a matching property.
13-Feb-2023 13:17:05.965 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
13-Feb-2023 13:17:58.826 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/opt/tomcat/webapps/WebAPI.war] has finished in [67,214] ms
```

### Steps to reproduce behavior
Launch Tomcat without `sudo` first, take note of the logs, then launch Tomcat again with `sudo` this time.
Note the difference in time taken to deploy WebAPI. With `sudo`, i.e. a successful deploy of WebAPI, startup takes about a minute. Without `sudo`, startup takes less than a second but results in 404 error at the endpoints. There is also an additional INFO line regarding some jasper servlet that does not appear when launching Tomcat without `sudo`, I do not know why.

I suspect permissions must be at the core of the issue, as using `sudo` solves the problem. However, I'm unable to figure out exactly where the issue with permissions lie because the logs do not throw any AccessDenied or PermissionDenied kind of error. I understand this is probably a very niche problem, but I'd appreciate any help nonetheless.

**Comment by chrisknoll** [comment]
I'd look through the other log files for any hints of errors.   Unfortunately, I'm not sure this is an application issue that we can help you with.
