### ISSUE TITLE
Redirect URL not working for OpenID authenticators, WebAPI v2.9.0

### ISSUE THREAD

**Issue by migldasilva** [OHDSI/WebAPI#2211]
### Expected behavior

After a successful authentication using OpenID, the user should be redirected to URL defined in `security.oid.redirectUrl`. 

### Actual behavior

After a successful authentication using OpenID, the user is redirected to `http://localhost/Atlas/#/welcome`. Please observe the capital A in the URL, it's shown like this in the browser.

Besides that, it's worth nothing that OpenID authentication is provided by Azure AD (through an Application Registration). I can confirm that authentication is working fine because after a successful authentication **and** failed redirection, I can access Atlas once I correct the URL in browser's address bar. I.e., I manually change `http://localhost/Atlas/#/welcome` with `http://my-real-url.com/atlas/#/welcome`, and can access the system through an authenticated session.

### Steps to reproduce behavior

1) Install WebAPI 2.9.0
2) Configure OpenID as described in https://github.com/OHDSI/webapi-wiki/blob/master/Security-Configuration.md
3) Access Atlas using valid OpenID credentials

One last comment, such behavior was observed in a different issue: https://github.com/OHDSI/WebAPI/issues/1473#issuecomment-781672821

**Comment by konstjar** [comment]
You should use `security.oauth.callback.ui` value for correct redirect.

**Comment by migldasilva** [comment]
Many thanks @konstjar

Maybe it's a good idea to update this doc: https://github.com/OHDSI/webapi-wiki/blob/master/Security-Configuration.md

It gives the impression that `security.oauth.callback.ui` is not applicable, and redirect will be handled by `security.oid.redirectUrl`.
