### ISSUE TITLE
New Feature: Cohort Characterization

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#222]
**Creating a separate issue for this off of the main topic (#217).**

I'm interested in adding a cohort characterization feature to Atlas.

- A short description of the feature
This feature would allow us to generate characteristics of cohorts designed in Atlas's cohort designer. It would run a version of FeatureExtraction (in a Java wrapper) to obtain a set of patient features that then could be viewable in Atlas.

- The organization or developers that are involved in the implementation
Aside from myself, @chrisknoll , @pbr6cornell , @fdefalco , @anthonysena have expressed interest in working on this.

- Any anticipated impact to current WebAPI/Atlas functionality (if applicable)
This would replace the existing "Reporting" tab in Atlas.

**Comment by gowthamrao** [comment]
@alondhe  wold like to collaborate on this.
