### ISSUE TITLE
New features in cohort analysis

### ISSUE THREAD

**Issue by chen-regen** [OHDSI/WebAPI#223]
**Creating a separate issue for this off of the main topic (#217).**

Those new features are cohort analysis (old Heracles) related.

## 1. Data completeness

**A short description of the feature**
Generate a table with percentages to indicate how complete the person data is for gender, race and ethnicity. For example, for patients age 0~10, 65% has race data, etc.

**The organization or developers that are involved in the implementation**
Chen at Regenstrief

**Any anticipated impact to current WebAPI/Atlas functionality (if applicable)**
Back-end will be in WebAPI cohort analysis
Atlas changes will be under cohort->reporting

## 2. Observation entropy

**A short description of the feature**
Calculate Shannon entropy for column observation.value_as_string per day and show them in a line chart.

**The organization or developers that are involved in the implementation**
Chen at Regenstrief

**Any anticipated impact to current WebAPI/Atlas functionality (if applicable)**
Back-end will be in WebAPI cohort analysis
Atlas changes will be under cohort->reporting

## 3. Timeliness

**A short description of the feature**
Calculate average delay time between observation.observation_date and row_created_db_time each day and show them in chart.

**The organization or developers that are involved in the implementation**
Chen at Regenstrief

**Any anticipated impact to current WebAPI/Atlas functionality (if applicable)**
Back-end will be in WebAPI cohort analysis
Atlas changes will be under cohort->reporting

**Comment by chen-regen** [comment]
@anthonysena Hi Anthony, I have create 2 pull requests for WebAPI and Atlas. Please let me know if there's any issues. Thank you!

**Comment by chen-regen** [comment]
Attaching some of the screenshots for first 2 features:

<img width="1355" alt="screen shot 2017-08-01 at 1 59 57 pm" src="https://user-images.githubusercontent.com/10854641/28933384-de0f8270-784a-11e7-8ff8-9225c8ca4976.png">
![screen shot 2017-08-03 at 12 54 32 pm](https://user-images.githubusercontent.com/10854641/28933402-eddf2a66-784a-11e7-9e82-6c43bc0f3d7d.png)
![screen shot 2017-08-01 at 11 47 53 am](https://user-images.githubusercontent.com/10854641/28933433-0ee4e692-784b-11e7-861a-0b1f16f95112.png)

**Comment by chen-regen** [comment]
Screenshot for entropy:

<img width="1355" alt="screen shot 2017-08-01 at 1 59 57 pm" src="https://user-images.githubusercontent.com/10854641/28933524-57fff8a8-784b-11e7-9c0e-724128a8f365.png">
![screen shot 2017-08-01 at 11 47 53 am](https://user-images.githubusercontent.com/10854641/28933529-5dd8b63e-784b-11e7-9a03-318837455b39.png)

**Comment by chen-regen** [comment]
Another for entropy:

![screen shot 2017-08-01 at 11 47 53 am](https://user-images.githubusercontent.com/10854641/28933545-6cdd2c5a-784b-11e7-8c93-f4f5055966d9.png)

**Comment by anthonysena** [comment]
Thanks! These contributions have been pulled into the V2.1 release branch. Hoping that you can collaborate on the cohort characterization work #222 as well!

**Comment by chen-regen** [comment]
Issue [104 in CDM](https://github.com/OHDSI/CommonDataModel/issues/104) created for feature 3.

**Comment by chrisknoll** [comment]
Maybe we could move feature 3 to it's own issue so that we can mark the completed ones as closed?

**Comment by chen-regen** [comment]
@anthonysena Hi Anthony, I have added "care site" based entropy as we discussed couple of weeks ago for "feature 2". Below please take a look at the screenshots. I created "R21_entropy" branches for both WebAPI and Atlas. I will create pull requests in a minute. 

<img width="1170" alt="screen shot 2017-09-12 at 10 03 38 am" src="https://user-images.githubusercontent.com/10854641/30330687-bac31804-97a3-11e7-8d99-1fe2d41071ba.png">

<img width="1203" alt="screen shot 2017-09-12 at 10 03 21 am" src="https://user-images.githubusercontent.com/10854641/30330696-bf9b079c-97a3-11e7-962d-9e6f9eac94d4.png">

**Comment by anthonysena** [comment]
Closed via #246
