### ISSUE TITLE
CDM and Vocab in same schema

### ISSUE THREAD

**Issue by davidhcar** [OHDSI/WebAPI#2232]
When CDM and Vocabularies are in the same schema what should be the daimon_type in the source_daimon table? Could someone clarify please?

![image](https://user-images.githubusercontent.com/54858404/226682706-a3c0b25a-b14d-4468-a672-432aa7ec0dce.png)

**Comment by chrisknoll** [comment]
It is the normal case that vocab and cdm tables are in the same schema.  The reason that we have a 'vocab' daimon separate from a 'cdm' daimon is that it is possible to set up a source that is only used for vocabulary searching.  

IN your case, just put the same schema for the CDM and Vocabulary Daimon (CDM=0, Vocab=1)

**Comment by chrisknoll** [comment]
`table_qualifier`.  We used that instead of 'shema' because in the early years of buidling the app, different DB platforms had different definitions of what a 'schema' is, so we just called it `table_qualifier` to avoid that.

**Comment by davidhcar** [comment]
Thank you again for the prompt response @chrisknoll. The naming convention of being generic makes sense.
