### ISSUE TITLE
Enable GitHub Actions for unit tests

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#2243]
When new branches are pushed to the repo, we should run the maven tests.

**Comment by chrisknoll** [comment]
Need to look into hooking up gitActions to perform this, and also post codecoverage to codecov.io (if we want badges and such).

About 2 years ago, I did have travis builds (via [travis.yml](https://github.com/OHDSI/circe-be/blob/master/.travis.yml)) in circe-be, but something changed (I think it went to subscription based) and I never cut it over to use gitActions. So, part of this work is finding a gitActions script that can invoke the builds and post the codecov.
