### ISSUE TITLE
Atlas Characterizations, Cohort Pathways & Cohort Reports not working on Spark (Databricks)

### ISSUE THREAD

**Issue by TomWhite-MedStar** [OHDSI/WebAPI#2248]
### Expected behavior
Three Atlas functions that work fine on SQL Server are not working on Spark:  Characterizations, Cohort Pathways, and Cohort Reports (Heracles reports).  Characterizations worked fine in Spark/Databricks in the 2.11 release of Atlas and WebAPI, but do not work in 2.12.1

### Actual behavior
Each of those types of analyses fail - usually after significant runtime.  In each case the root cause appears to be SqlRender error in substituting <START_WITH> and <END_WITH>.  See[ issue # 330 ](https://github.com/OHDSI/SqlRender/issues/330 )in SqlRender for more detail.  There is also discussion on  [this ](https://forums.ohdsi.org/t/atlas-characterizations-error-org-ohdsi-webapi-exception/18639 )forum post.

#### Characterizations
Load the attached json into Chacterizations.  Select Executions and click Generate
[Lipitor Users vs Zocor Users.json.txt](https://github.com/OHDSI/WebAPI/files/11172664/Lipitor.Users.vs.Zocor.Users.json.txt)
There are multiple queries like `show columns in #analysis_ref` where the temporary table names are not substituted to something like `show columns in tmp.analysis_ref`.  However, those queries do not cause the job to fail.
Instead, it fails the first time there is a unprocessed <START_WITH> substitution.  The error file is below.
[Lipitor Users vs Zocor Users.error.txt](https://github.com/OHDSI/WebAPI/files/11172706/Lipitor.Users.vs.Zocor.Users.error.txt)

#### Cohort Pathways
Load the attached json into Cohort Pathways.  Select Executions, and click Generate
[Diabetic Treatment Pathway.json.txt](https://github.com/OHDSI/WebAPI/files/11172360/Diabetic.Treatment.Pathway.json.txt)
The error message generated is attached.
[Diabetic Treatment Pathway.error.txt](https://github.com/OHDSI/WebAPI/files/11172596/Diabetic.Treatment.Pathway.error.txt)

#### Cohort / Heracles Reports.
Load the attached json cohort.  Generate the cohort.  Then, under Cohort Reporting, select that source and choose Quick Analysis
[[COVID HCQ ID62 v1] New users of sulfasazine with prior rheumatoid arthritis.json.txt](https://github.com/OHDSI/WebAPI/files/11172341/COVID.HCQ.ID62.v1.New.users.of.sulfasazine.with.prior.rheumatoid.arthritis.json.txt)
The Heracles reports after a few seconds.  The SQL query that caused the error is attached.
[Cohort-Heracles.error.txt](https://github.com/OHDSI/WebAPI/files/11172633/Cohort-Heracles.error.txt)

**Comment by anthonysena** [comment]
@TomWhite-MedStar - I'm going to close this for now so we can track this work on the SqlRender issue. If needed, we can transfer the SqlRender issue to this repo and re-visit the information you have provided in this issue (which is excellent by the way!).

**Comment by TomWhite-MedStar** [comment]
@anthonysena, we upgraded to Atlas 2.13, and I can confirm that all of the above-listed issues are now fixed.

However, when I ran the Heracles Full Analysis it failed partway through.  Here is the generated Spark SQL that failed:
[Cohort-Heracles-full.sql.error.txt](https://github.com/OHDSI/WebAPI/files/11224445/Cohort-Heracles-full.sql.error.txt)

The error message is:  
[PARSE_SYNTAX_ERROR] Syntax error at or near 'into'.(line 8, pos 0)

Should I continue to track such issue here, or only in the SqlRender thread?

**Comment by anthonysena** [comment]
Excellent - let's track this work here. I'll close out the SqlRender issue that is now linked. Let me see if I can track down the query causing the issue and go from there.

**Comment by TomWhite-MedStar** [comment]
@anthonysena , the INTO statement is hidden in the formatting on  the line before the first FROM statement:

`  COUNT(distinct vo1.person_id) as count_value **into** tmp_v0125_v2.sl527h4fresults_200
`

When I run the code you [linked above ](https://github.com/OHDSI/WebAPI/blob/a1a130a9606c0318ca3b69255b1aee50b39ab56d/src/main/resources/resources/cohortanalysis/heraclesanalyses/sql/200_201.sql) through SqlRender, I get a different output from the above.  

Might it be a SQL splitting issue?  I see from this line above:
`  vo1.visit_CONCEPT_ID --;`
that there is a semi-colon after a comment.  The full SQL I posted above is what was sent to Databricks, so it appears that SQLRender didn't recognize that there are two SQL statements above.  

Which code does the substitutions in sections like this?:
`--{@CDM_version == '4'}?{
vo1.place_of_service_CONCEPT_ID
--}
--{@CDM_version == '5'}?{
vo1.visit_CONCEPT_ID
--}
;
`
Could that be leading to cases like shown on the line with the commented semi-colon?

**Comment by TomWhite-MedStar** [comment]
@chrisknoll , I submitted a pull request before noticing that you may have already fixed query 200_201.sql.

Silly question - where do I find the control file that determines the order in which  those heraclesanalyses are run?  I monitored  the generated queries, and they are not in an obvious order.  If you can let me know what sequence of queries are called for Full Analysis after 200, I can test the remaining ones for potential issues on Databricks / Spark.

**Comment by chrisknoll** [comment]
Sorry, I saw this after I saw the PR, so the PR is approved and merged (the changes looked good to me).

I need to look at the code again and remember how the heracles reports are generated....I'll reply here when I work it out.
