### ISSUE TITLE
Request to replace hyphen(-) with underscore(_) - Property naming conventions

### ISSUE THREAD

**Issue by davidhcar** [OHDSI/WebAPI#2251]
The azure cloud Appservice is not allowing to configure properties with hyphen(-), could this property be updated to use Dot(.) or underscore(_) instead ?
Reference: https://learn.microsoft.com/en-us/answers/questions/767956/why-is-hyphen-not-allowed-in-app-setting-name
Note: Potentially it impacts on other properties who uses hyphen in their name as well.
```

<!-- Logging -->
    <spring.jpa.show-sql>false</spring.jpa.show-sql>
```

**Comment by chrisknoll** [comment]
We don't have control over those property names, I believe they come from spring's set of configuration variables.

@wivern or @ssuvorov-fls would you be able to confirm?

**Comment by RowanErasmus** [comment]
@davidhcar if you set SPRING_JPA_SHOWSQL=true as environment variable it should work.
There is some documentation on this here: https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.relaxed-binding

**Comment by RowanErasmus** [comment]
@davidhcar I'm closing this under the presumption that you managed to solve this particular issue.
