### ISSUE TITLE
How to set a source in the database?

### ISSUE THREAD

**Issue by tstringer-fn** [OHDSI/WebAPI#2278]
Good day! I have setup WebAPI and I'm wondering how to create a source in the database. I see [the documentation](https://github.com/OHDSI/WebAPI/wiki/CDM-Configuration#source-and-source_daimon-table-setup) but this still seems to not be working (verified an empty array when I go to `/WebAPI/source/sources`).

In the documentation it says to INSERT a row into the `webapi.source` table with this connection string: `jdbc:postgresql://server:5432/cdm?user={user}&password={password}`. I understand that "server" should be replaced, as well as "cdm" for the actual CDM database. But what about `user` and `password`? Are those supposed to be literals, and you keep the strings "user" and "password" in that?

Thank you!

**Comment by chrisknoll** [comment]
I think you can leave out the user/pass from the JDBC url, and instead store it in the username/password column in the source table.  This will auto-encrypt when you start webapi.

When you change sources, you will need to refresh the server cache, so you can either restart WebAPI or  access the url /WebAPI/source/refresh.  Hitting that endpoint with browser will trigger the cache to reset.

**Comment by tstringer-fn** [comment]
Thank you for your response! So you're saying that I should be doing an `INSERT` into `webapi.source` with the `username` and `password` columns set in plaintext? While I understand that webapi will auto-encrypt this on startup, there is a non-zero amount of time that the password is stored in plaintext, which isn't ideal.

Is there no other way to get the credentials stored in the database that are encrypted from the start to eliminate this plaintext window?

**Comment by chrisknoll** [comment]
Yes, as opposed to the infinite time that it would be unencrypted if placed into the URL :).

**Comment by tstringer-fn** [comment]
Yes, totally agreed that it shouldn't be unencrypted at all in the URL or otherwise :)

Ah great I didn't know there was part of the UI to create the source! Do you have the URL of that?

**Comment by chrisknoll** [comment]
The admin screen will only show you source management (create/update) if security is enabled.   If you have it enabled, you can go to the 'Configuration' screen and you see something like this:

![image](https://github.com/OHDSI/WebAPI/assets/6818777/28c8fb60-514b-44f0-97d2-b18d4479d338)

Click New Source to add a new source, and specify the different daimons:
![image](https://github.com/OHDSI/WebAPI/assets/6818777/31108747-41de-4fb9-b9da-756270e967fa)

**Comment by tstringer-fn** [comment]
Ah I don't see that `New Source` button. Judging by your comment, it sounds like it's because security isn't enabled if I'm understanding correctly? How do I enable it so I can see that new source button? Thank you!

**Comment by chrisknoll** [comment]
Security configuration is described [here](https://github.com/OHDSI/WebAPI/wiki/Security-Configuration).

Getting security set up is a complicated task because you need to re-build your WebAPI with the AtlasSecurity enabled, and then configure the Atlas configuration to specify which security providers you want to allow.   It's too much to describe in this post.  if you are happy to use Atlas in 'anonymous' mode, then just do the updates to SOURCE table directly and restart webapi to have changes take effect.

**Comment by tstringer-fn** [comment]
Thanks for the help! I really appreciate it!
