### ISSUE TITLE
Importing user information from Azure Active Directory (not the "classic" AD)

### ISSUE THREAD

**Issue by migldasilva** [OHDSI/WebAPI#2283]
I'm working on a project that relies on Azure AD for authentication. This functionality is working as expected, using OpenID. 

According to the documentation, and some discussions available here, WebAPI is able to import groups/roles and users from AD/LDAP. On the other hand, checking the code for importing from AD/LDAP, and trying some configurations, importing groups directly from Azure AD seems not to be supported. 

Thus, for such kind of integration, some code between WebAPI and AAD, together with specific configurations in AAD, seems to be the better way to go. 

Is this kind of deployment already tested?

**Comment by konstjar** [comment]
Azure AD supports "classic" AD. You should be able to use direct AD connection. See Directory Services documentation in AAD: https://azure.microsoft.com/en-us/products/active-directory/ds

**Comment by migldasilva** [comment]
Excellent, that's what I could verify. Actually, the part where I wrote, "together with specific configurations in AAD", I meant exactly the deployment of DS in AAD. 

In this case, the support in WebAPI is already included, and nothing new would be required.

Thanks for the link. It's already bookmarked.
