### ISSUE TITLE
Add embedded DB WebAPI to contain OHDSI schema

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/WebAPI#232]
Add an embedded DB (such as H2) to contain OHDSI schema. This will allow WebAPI to support same functionality as current version but will make WebAPI easier to deploy, configure, update and maintain.

**Comment by anthonysena** [comment]
@t-abdul-basser - I'm going to close this out since we've proposed using PostgreSQL as our standard back end for WebAPI per #585. Please let me know if you have concerns with this. Thanks!
