### ISSUE TITLE
Faulty source leads to inability to use Vocab hooks

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#233]
If a source in the source table has a server name that is unreachable, the default Vocabulary hooks fail. We had this happen when 1 source was on a server that was retired. Ideally, the Vocab WebAPI hooks should still succeed even with a bad source.

**Comment by pavgra** [comment]
@alondhe , could I ask you to clarify what is `default Vocabulary hook`?

**Comment by alondhe** [comment]
Hmm trying to remember :) 

I think what I meant was that if 1 CDM source is unreachable, that shouldn't prevent the Vocabulary service (which uses the Default Vocabulary source) from failing.
