### ISSUE TITLE
First time initialization creates 'ohdsi' schema vs using the existing schema 'webapi'

### ISSUE THREAD

**Issue by davidhcar** [OHDSI/WebAPI#2333]
### Expected behavior
API to setup tables/objects in schema named 'webspi' where the property set datasource.ohdsi.schema = webapi

### Actual behavior
creating new schema named 'ohdsi'

### Steps to reproduce behavior
Initialize 2.13.0 with postgres configurations to initialize schema the first time.

**Comment by davidhcar** [comment]
@chrisknoll @anthonysena Any clue why it would create a new schema?

**Comment by chrisknoll** [comment]
This could come from a few places:

The root is [here](https://github.com/OHDSI/WebAPI/blob/3f9e90c5a62dac4557f34f85b2d0ce70d58b439d/pom.xml#L52), which is referenced [here](https://github.com/OHDSI/WebAPI/blob/3f9e90c5a62dac4557f34f85b2d0ce70d58b439d/pom.xml#L61), but in the webapi-postgresql profile (which is what you're using) it's defined [here](https://github.com/OHDSI/WebAPI/blob/3f9e90c5a62dac4557f34f85b2d0ce70d58b439d/pom.xml#L1283),   This is where I've found the 'ohdsi' schema.

However, in the [setup documentation](https://github.com/OHDSI/WebAPI/wiki/WebAPI-Installation-Guide#configure-the-maven-profile), I don't see it noted that you can change the schema name.   So, I think what's happening is you're not overriding it in your settings.xml, and you need to add this to your settings.xml:

```
<datasource.ohdsi.schema>webapi</datasource.ohdsi.schema>
```

Then rebuild, and re-deploy.

**Comment by davidhcar** [comment]
Thank you @chrisknoll you are spot on. I had a environment variables but without settings.xml. was under impression it is optional and overrides pom.xml from the environment settings. Did rebuild with settings.xml everything works as expected. Thank you once again as always for prompt response!!
