### ISSUE TITLE
Proximal logic for events while designing a Cohort

### ISSUE THREAD

**Issue by alex-odysseus** [OHDSI/WebAPI#2346]
### Business Requirements

There is a need to identify patients with diagnoses, medications, laboratory measurements that are most proximal (before or after) to the index date

### Design Ideas and Functional Requirements

There is an intention to leverage the date adjustment functionality being added to v2.14.0 to design Cohorts accordingly

### Open Questions

N/A

@mrechkem @Sathyaraos

**Comment by anthonysena** [comment]
Closed via https://github.com/OHDSI/circe-be/tree/v1.11.0
