### ISSUE TITLE
Ability to calculate total unique time at risk or exposure for a cohort

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/WebAPI#235]
Given a cohort (subjects with start date and an end date), we need an ability to calculate the total of subject's time at risk (or exposure) in dates. This will be used as an element in cohort characterization  (reporting time-at-risk or person-time metrics.)

**Use in Cohort Characterization:**
1. Report exposure or time at risk
2, Cost per subject per month = ((total cost for all unique events for all subjects during cohort period)/(Time at risk in days))*30.5 days 
3. Events per 1,000 subjects per year:
```
((total unique events for all subjects during cohort period)/(Time at risk in days))*1000*365
```

**Comment by gowthamrao** [comment]
@anthonysena @alondhe is this usable?

[ExposureCalculation.txt](https://github.com/OHDSI/WebAPI/files/1219044/ExposureCalculation.txt)

**Comment by anthonysena** [comment]
@gowthamrao I suspect we'll create a new storage mechanism for the new cohort characterization statistics so we can review analysis IDs as part of defining that specification. For now, the only caution I'd have with the query you provided is the use of common table expressions and insert statements. At first glance, I'm not sure if this will translate to all platforms so we'll need to test.

**Comment by gowthamrao** [comment]
@anthonysena  PR https://github.com/OHDSI/WebAPI/pull/234 merged 
Now its simple as
[ExposureCalculation.txt](https://github.com/OHDSI/WebAPI/files/1261203/ExposureCalculation.txt)

**Comment by gowthamrao** [comment]
@schuemie  how can we help contribute to feature extraction 2?

**Comment by gowthamrao** [comment]
> Given a cohort (subjects with start date and an end date), we need an ability to calculate the total of subject's time at risk (or exposure) in dates. This will be used as an element in cohort characterization (reporting time-at-risk or person-time metrics.)

With the implementation of era-fy collapse strategy implemented, this need is now solved with a simple subject_id, sum(cohort_end_date - cohort_start_date).

Closing this issue.
