### ISSUE TITLE
Priority call causes application hang in initial load for ATLAS

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/WebAPI#2350]
### Expected behavior
WebAPI responds or async handles requests for data source priority during initial application loading.

### Actual behavior
WebAPI will block until a 'select 1' is executed against all data sources configured. This is problematic in cases where database platforms have idle/standby modes where upon receiving a query they take several minutes to initialize before being able to respond to the query. (ie, databricks, redshift serverless, spark serverless)

![image](https://github.com/OHDSI/WebAPI/assets/6586384/badf6c80-e57d-4aa4-ae9a-8fad5b82861d)

This check connection appears to be the cause of the issue:
https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/source/SourceService.java#L108

For responding to priority it might be better to only make use of the data in the daimon tables without performing a connection test.

**Comment by anthonysena** [comment]
Closed via #2374
