### ISSUE TITLE
AtlasRegularSecurity breaks connection to WebAPI

### ISSUE THREAD

**Issue by nzurawski** [OHDSI/WebAPI#2366]
I have an installation of WebAPI and Atlas setup with SSL enabled on WebAPI, and the site loading over a secure connection on port 443. If I leave SSL enabled and set security.provider to DisabledSecurity, the application is able to call the WebAPI succesfully. However, if I set security.provider to AtlasRegularSecurity, the application is no longer able to get a response from WebAPI with a 401 error showing in Chrome's developer tools. The Stdout log file from Apache Tomcat shows no errors.

Why would enabling AtlasRegularSecurity cause the WebAPI to refuse the connection from Atlas?

Copies of WebAPI settings and Atlas Config-local attached here.
[config-local.txt](https://github.com/OHDSI/WebAPI/files/15112942/config-local.txt)
[settings.txt](https://github.com/OHDSI/WebAPI/files/15112943/settings.txt)

**Comment by chrisknoll** [comment]
You also need to configure Atlas to enable security.  When you changed to AtlasRegularSecurity, did you update your config-local.js file to indicate security is enabled?

**Comment by nzurawski** [comment]
HI Chris, yes I did.

Here's what teh config-local looks like:
define([], function () {
	var configLocal = {};
	
	configLocal.UserAuthenticationEnabled = true;

	configLocal.api = {
		name: 'REDACTED',
		url: 'https://atlas-dev.REDACTED.org:8443/WebAPI/'
	};
	
	configLocal.authProviders = [{
		"name": "Local Security Test DB",
		"url": "user/login/db",
		"ajax": true,
		"icon": "fa fa-database",
		"isUseCredentialsForm": true
	  }
	  
	  ];

	return configLocal;
});
 Am I missing something?

**Comment by chrisknoll** [comment]
[It's case sensitive.](https://github.com/OHDSI/Atlas/blob/dd9e49e35073dc48382cd15963351e1dbd4f633e/js/config/app.js#L14C13-L14C39)

```
configLocal.userAuthenticationEnabled = true;
```

Also, you'll know if you are in security enabled mode if you see a 'sign in' button at the top of the UI.

**Comment by nzurawski** [comment]
Well that's embarassing for me. Thanks. I'm in business now.
