### ISSUE TITLE
As "withinQuotes"

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/WebAPI#237]
In the .sql below and many related sql, the select statement is   `select aa1.analysis_name AS "attribute_name"`
why is the quotes used? i.e. why  `AS "attribute_name"` instead of just `AS attribute_name`

Reason: we believe this is causing errors in Netezza DBMS because of the quotes. Would it be ok to remove quotes like below and do a PR?

https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/report/person/population.sql

```
(SELECT
   aa1.analysis_name AS "attribute_name",
   ar1.stratum_1     AS "attribute_value"
 FROM @results_database_schema.ACHILLES_analysis aa1
INNER JOIN
@results_database_schema.ACHILLES_results ar1
ON aa1.analysis_id = ar1.analysis_id
                   WHERE aa1.analysis_id = 0

 .....
```

# change to

```
(SELECT
   aa1.analysis_name AS attribute_name,
   ar1.stratum_1     AS attribute_value
 FROM @results_database_schema.ACHILLES_analysis aa1
INNER JOIN
@results_database_schema.ACHILLES_results ar1
ON aa1.analysis_id = ar1.analysis_id
                   WHERE aa1.analysis_id = 0

 .....
```

**Comment by chrisknoll** [comment]
Agreed, this has come up in other spots, quoting column names means different things on different platforms. We should not be doing this.

**Comment by gowthamrao** [comment]
Thanks @chrisknoll 

@t-abdul-basser or others have any concerns about making changes? Is there any benefits to use quotation marks?

**Comment by anthonysena** [comment]
+1 to remove quotes.

**Comment by t-abdul-basser** [comment]
@gowthamrao No particular benefits that I recall. A similar issue has been noted an fixed in [#183](https://github.com/OHDSI/WebAPI/issues/183). I have no concerns: please feel free to fix across the board and submit PR.

**Comment by gowthamrao** [comment]
@anthonysena  pr at https://github.com/OHDSI/WebAPI/pull/241

**Comment by gowthamrao** [comment]
PR accepted
