### ISSUE TITLE
Fix for compile error seen for Eclipse

### ISSUE THREAD

**Issue by greshje** [OHDSI/WebAPI#2390]
WebAPI fails to compile using Eclipse.  Two errors are given around the use of generics and wild cards (e.g. <V,?>).  The overloading of the initAndBuildList function for the lists and group lists gives one error in ValidatorGroupBuilder and one error in AbstractForEachValidatorBuilder.  

The fix for this is simply to create an exact duplicate of the very small mehtods in each class for initAndBuildList for the group list with a more specific call signature.

**Comment by chrisknoll** [comment]
Can we get more detail around what exactly the error is?  Something like we should add something like `? extends SomeClass` to it?  What is the more specific call signature you're suggesting?
