### ISSUE TITLE
Sample_settings.xml authentication query should better match the Basic Security Configuration wiki page

### ISSUE THREAD

**Issue by amarsan** [OHDSI/WebAPI#2392]
This a companion issue to https://github.com/OHDSI/webapi-wiki/issues/10

### Expected behavior

The [security.db.datasource.schema](https://github.com/OHDSI/WebAPI/blob/master/sample_settings.xml#L64) and  [authentication query](https://github.com/OHDSI/WebAPI/blob/master/sample_settings.xml#L69) should match the schema, table, and column names that are recommended in the [Basic Security Configuration wiki page](https://github.com/OHDSI/webapi-wiki/blob/master/Basic-Security-Configuration.md).

```
<security.db.datasource.schema>atlas-security</security.db.datasource.schema>
```

```
<security.db.datasource.authenticationQuery>select password,firstName,middleName,lastName from ${security.db.datasource.schema}.users where username = ?</security.db.datasource.authenticationQuery>
```

The wiki page recommends that we *do not* put the security table in the `webapi` schema, so the `security.db.datasource.schema` node should be updated accordingly. 

The wiki page recommends naming the table `demo_security`, but I noted in the referenced webapi-wiki issue that the name `users` makes more sense, so I think we should continue to use that here. 

The wiki page recommends having a column called `username`, rather than `email`, so that should be fixed.

### Actual behavior
```
<security.db.datasource.schema>${datasource.ohdsi.schema}</security.db.datasource.schema>
```

```
<security.db.datasource.authenticationQuery>select password from ${security.db.datasource.schema}.users where lower(email) = lower(?)</security.db.datasource.authenticationQuery>
```

### Steps to reproduce behavior
N/A

**Comment by chrisknoll** [comment]
Agreed, we shouldn't put an example settings that conflicts with the documentation recommendation.
