### ISSUE TITLE
Tag cohort generation queries with cohort ID at top

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#240]
To help track down long-running queries on the server, can we add the cohort definition id as the first comment in the generated SQL, like below? On PDW, the console truncates the running queries, so it's hard to know which session is running what cohort Id.

```
/* ** Cohort ID 1234 ** */
CREATE TABLE #Codesets (
  codeset_id int NOT NULL,
  concept_id bigint NOT NULL
)
;

INSERT INTO #Codesets (codeset_id, concept_id)
SELECT 0 as codeset_id, c.concept_id FROM (select distinct I.concept_id FROM
( 
```

**Comment by alondhe** [comment]
Additionally, perhaps the session id of the cohort generation could be tracked in the ohdsi_repository and displayed on screen?

**Comment by chrisknoll** [comment]
Tagging the query with cohort ID is completely doable.

Getting the session ID of the connection...not so much.

**Comment by chrisknoll** [comment]
Also, once security is enabled, maybe we could also tag it with the user who is generating.

**Comment by alondhe** [comment]
@ericaVoss is also on board
