### ISSUE TITLE
Concept record counts bug

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#243]
Came across an issue internally with the concept: 594249 - Measles Vaccine. Internally, for DOD, this concept_id is reported to have 131 records and 262 descendant records. This was not matching another report that I had generated.

This query helped me to identify the bug directly against the source:

```
with concepts AS(
	select c2.*
	from concept c
	INNER JOIN concept_ancestor ca ON ca.ancestor_concept_id = c.concept_id
	INNER JOIN concept c2 ON c2.concept_id = ca.descendant_concept_id
	where c.concept_id = 594249
), exactMatch AS (
	select COUNT(*) rec_cnt, COUNT(DISTINCT person_id) person_cnt
	from drug_exposure de 
	where de.drug_concept_id = 594249
), descMatch AS (
	select COUNT(*) desc_rec_cnt, COUNT(DISTINCT de.person_id) desc_person_count
	from drug_exposure de 
	INNER JOIN concepts c ON de.drug_concept_id = c.concept_id
)
SELECT *
FROM exactMatch, descMatch
```
The query above returns 0 for exact matches for that concept_id and 131 for descendants; Atlas says there are 131 exact record matches and 262 descendants.

I think the join at this section of the record count cache points to the issue whereby we're considering both ancestors and descendants for each concept:

https://github.com/OHDSI/WebAPI/blob/68d9fe2fb9356feb3c620767cfb5f47d961dd333/src/main/resources/resources/cdmresults/sql/loadConceptRecordCountCache.sql#L53

Tagging @fdefalco for assistance on this one.

**Comment by mpozhidaeva** [comment]
@anthonysena, @fdefalco, @pavgra - I spent some time investigation the issue and I guess the reason is in including records from _concept_ancestor_ table with _ancestor_concept_id = descendant_concept_id_.

In odysseus-test environment (master webapi, datasource - synpuf 110k, vocabularies - 05-OCT-18) I see 
![image](https://user-images.githubusercontent.com/31308645/52225429-5fa2a200-28bb-11e9-847c-64fdbf1b8efb.png.
The result count is a sum of the analyzes 701 and 901.
https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cdmresults/sql/getConceptRecordCount.sql

For 901 analysis I get all descendant records only for record ancestor_concept_id = descendant_concept_id (=594249). I think they are incorrect.

 concept_id | record_count | descendant_record_count
------------+--------------+-------------------------
 594249     |           67 |                      67

**Comment by anthonysena** [comment]
@mpozhidaeva - thanks for digging into this item and for the pull request with changes. In reviewing those, I think this would cause a problem for users of ATLAS since we want to include the record count (RC) for the current concept inside of the descendant record count (DRC) so that when users sort by DRC, they are able to get those concepts + descendants with the highest/lowest count of records.

After investing the item above, I problem I surfaced in this issue goes a little deeper. Concept_id == 594249 (Measles Vaccine) is an RxNorm Ingredient which will have results in the [Achilles 401 analysis](https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/401.sql) which summarizes records in the `drug_exposure` table and also the [Achilles 901 analysis](https://github.com/OHDSI/Achilles/blob/master/inst/sql/sql_server/analyses/901.sql) which summarizes the `drug_era` table. Since this concept is an RxNorm ingredient, concept_id == 594249 appears in both analyses it has both a record_count (from analysis 901) and adds to the descendant record counts in analysis 401. 

After spending some time to look through these queries, there is a trade off between getting it perfect and performance. These queries work very well with this edge-case limitation that if a concept is in > 1 achilles analysis, we might have some overflow. We might be able to construct the query to make the counts exact but likely at the expense of making them much slower. Happy to be challenged on this if someone has some ideas but I'm out of ideas on where to further optimize things.

In terms of the record count usage in ATLAS: the counts are utilized more to get a feel for which concepts show up in the data. It isn't always required to have the exact record count but it would be nice.

For now, I'm going to move this item to the 2.8 release to see if we can think on any optimizations we can make here. I'll also close out #803 and note this comment for reference. Thanks!

**Comment by pavgra** [comment]
@anthonysena , so what's the final plan: do we want to re-think it or leave as-is?

**Comment by anthonysena** [comment]
@pavgra I think we can leave this as-is since this issue contains enough information that we can explain differences between the RC/DRC and the values from the individual Achilles analyses. If you agree, we can close this out. Thanks!
