### ISSUE TITLE
Person Location in WebAPI / Atlas

### ISSUE THREAD

**Issue by jduke99** [OHDSI/WebAPI#254]
Any thoughts of adding location as part of demographic criteria in cohort builder?

**Comment by gowthamrao** [comment]
@jduke99  good idea and strongly support. 

Location information currently is represented in text format. There is no standardized representation, not stored as a point(lat/long) or area (shape). We also don't use concept_id's to represent geographic concepts of point or area.

So, current state - I think the best we can do is - how many records have location information vs not have location information. We could use the text fields of city, state, zip -- but absence of standardization, these may not usable?

**Comment by fdefalco** [comment]
Has anyone had an opportunity to discuss this with members of the GIS working group?

**Comment by pavgra** [comment]
Being covered by https://github.com/OHDSI/WebAPI/issues/649
