### ISSUE TITLE
cohort -> explore does not yield patient set

### ISSUE THREAD

**Issue by leenadR** [OHDSI/WebAPI#267]
Hi:

After installation of the current toolstack (fresh pull from github for WebAPI and Atlas), I came across a weird behavior. 
The dataset is the synpuf (but also on other schemas the problem exists). The databases are postgres 10.1 and 9.6 with webapi jdbc and most recent jdbc.

case A)
Cohort definition is just "death from any any death"
"Generate" yields 44 hits
"Explore" shows me 28 people (counting the gender facets)

case B)
Cohort definition is just "death from any any death" and "number of drug exposures<=0"
"Generate" yields 11 hits
"Explore" shows me "cohort has no members, please use generate first"

The problem seems to be that cohorts with empty facets, e.g. drugs, do not show up.

--

It seems that the code around "select count(distinct subject_id) as people, gender, age, conditions, drugs" (taken from the catalina.out upon pressing the explore-button) uses a few joins to collect the data, but yields 0 results. Using a left join, the result looks better.

Perhaps it has to do with the "Correlated subquery fix (#245)"
see: src/main/resources/resources/cohortresults/sql/raw/getCohortBreakdown.sql

--

Is ist a bug? Or is it a feature?

Cheers,
Martin

**Comment by chrisknoll** [comment]
@gowthamrao, 
  Looking at those queries, should those subqueries that join to conditions and drugs be 'left join' in the case that a person doesn't have any conditions or drugs, we should still return he person?  If we do a left join, we could have a NULL returned as the column value, so a coalesce() may also be required to covert a null to 0. (And usual checks for divide by zero should be performed if there is some sort of division involved).

**Comment by leenadR** [comment]
Looking into the SQL, i found that the previous version (at least of) getCohortBreakdown exposed a different result from the current one:

- current version: no result if cohort member has no drugs (probably the same for condition)

- previous version: all members are in the result set (same number as visible in in Atlas), "empty cells" such as column "drugs" are "0", conditions are counted or "0"

- using left join: same as previous version, but "null" where "0" was present

- using left join & coalesce: previous version delivers the identical results.

I notice there are two other files following the same pattern which should be updated as well (Breakdown, BreakdownPeople)

Cheers,
Martin

```
SELECT
  count(DISTINCT subject_id) AS people,
  gender,
  age,
  coalesce(conditions,0), <---------here
  coalesce(drugs,0) <---------here
FROM
  (SELECT
     c.*,
     gc.concept_name                                                                                     AS gender,
     cast(floor((EXTRACT(YEAR FROM cohort_start_date) - year_of_birth) / 10) * 10 AS VARCHAR(5)) || '-' ||
     cast(floor((EXTRACT(YEAR FROM cohort_start_date) - year_of_birth) / 10 + 1) * 10 - 1 AS VARCHAR(5)) AS age,
     conditions,
     drugs
   FROM synpuf_results.cohort c
     LEFT JOIN <---------here
     (SELECT
        person_id,
        ROUND(CAST(count(*) AS NUMERIC),
              cast(-floor(LOG(10, CAST((abs(count(*) + 0.01)) AS NUMERIC))) AS INT)) AS conditions
      FROM synpuf_cdm.condition_occurrence co
      GROUP BY person_id
     ) conditions
       ON c.subject_id = conditions.person_id
     LEFT JOIN <---------here
     (SELECT
        person_id,
        ROUND(CAST(count(*) AS NUMERIC), cast(-floor(LOG(10, CAST((abs(count(*) + 0.01)) AS NUMERIC))) AS INT)) drugs
      FROM synpuf_cdm.drug_exposure de
      GROUP BY person_id
     ) drugs
       ON c.subject_id = drugs.person_id
     JOIN synpuf_cdm.person p ON c.subject_id = p.person_id
     JOIN synpuf_cdm.concept gc ON p.gender_concept_id = gc.concept_id
   WHERE cohort_definition_id = 1514
  ) cohort_people
GROUP BY gender, age, conditions, drugs
ORDER BY 1 DESC;
```

**Comment by chrisknoll** [comment]
Thank you, @leenadR , you've identified the proper fix for this issue.  In the original implementation, the aggregates were being performed directly in the SELECT, which was causing issues with certain dbms. However, moving the work to sub-queries means you have to account for no records being found in the join (hence the left join, as well as the coalesce in the select).

I can create a PR to address this, unless you have something already prepared?

**Comment by leenadR** [comment]
Please go ahead. I had only tested this in postgres, but you are probably more experienced in formulating the SQLRender templates and publishing it.

**Comment by gowthamrao** [comment]
Thank you both for finding this and solving!
