### ISSUE TITLE
Cohort reporting bugs

### ISSUE THREAD

**Issue by mpozhidaeva** [OHDSI/WebAPI#269]
Step for reproduce: create cohort and generate reports.
1)Check reports:
- Conditions by Index
- Drugs by Index
- Procedures by Index

Actual state:
`ERROR: operator does not exist: character varying = integer↵  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.↵  Position: 4512"
nextException:null`

for example: http://www.ohdsi.org/web/atlas/#/cohortdefinition/142003
2) Drilldown reports:
- Condition
- Procedure
- Condition by index

**Comment by anthonysena** [comment]
Closed via #272
