### ISSUE TITLE
Redirecting to HTTPS and failing

### ISSUE THREAD

**Issue by ErezYehuda** [OHDSI/WebAPI#277]
I'm receiving the following error when attempting to access any API route from my browser:
(E.g. http://localhost:8080/WebAPI/source/source)

```
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in method name. HTTP method names must be tokens
	at org.apache.coyote.http11.InternalAprInputBuffer.parseRequestLine(InternalAprInputBuffer.java:185)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1028)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2492)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

It looks like, when attempting to access the routes via HTTP, they get 302 redirected to the same URL and port, but as _HTTPS_, which then fails. The Tomcat manager app does not experience this, nor do other Tomcat sample applications, so it's not Tomcat-wide. Attempting to disable HTTP -> HTTPS redirecting has not helped.

This happens on Tomcat 7, and 8 after changing mssql-jdbc versions as I mentioned in [issue 194](https://github.com/OHDSI/WebAPI/issues/194) (I have not tested Tomcat 6 or below). I only encounter this on Linux; everything works fine (including not encountering issue 194) on OSX El Capitan (tested with Tomcat 8). It seems that the WebAPI startup processes work just fine, as it successfully connects to and interacts with our database (as it had in previous versions). It's just the routes that seem to be failing.

Some env. details:
```
./bin/catalina.sh version

Using CATALINA_BASE:   /usr/local/tomcat
Using CATALINA_HOME:   /usr/local/tomcat
Using CATALINA_TMPDIR: /usr/local/tomcat/temp
Using JRE_HOME:        /Library/Java/JavaVirtualMachines/jdk1.8.0_151
Using CLASSPATH:       /usr/local/tomcat/bin/bootstrap.jar:/usr/local/tomcat/bin/tomcat-juli.jar
Server version: Apache Tomcat/7.0.82
Server built:   Sep 29 2017 12:23:15 UTC
Server number:  7.0.82.0
OS Name:        Linux
OS Version:     4.9.49-moby
Architecture:   amd64
JVM Version:    1.8.0_151-b12
JVM Vendor:     Oracle Corporation
```

**Comment by chrisknoll** [comment]
Does any information in this post help (about an IP tables rule forward to port 80 to port 8443?) 
https://stackoverflow.com/questions/42218237/java-lang-illegalargumentexception-invalid-character-found-in-method-name-http

 I'm sorry I don't have any linux environment to try to reproduce this issue.

**Comment by ErezYehuda** [comment]
@chrisknoll I've looked into that since you posted it, though I haven't spotted anything unusual regarding the IP tables.

I'm actually running this in Docker (from the official Tomcat images) with ports 80, 8080, 8000, 8443, and 443 forwarded to and exposed in the container. The Tomcat manager GUI works fine on the same ports (once remote access is unblocked in its web.xml). I've tested and found that running WebAPI outside of Docker works, though this is less preferable for deployment for us. Would the Dockerfile and setup I'm using be something you'd be interested in looking at?

This previously worked fine with the exact same configuration, so I suspect the change has been something internal to WebAPI.

**Comment by chrisknoll** [comment]
I believe when you have security enabled, it enforces SSL to be enabled.  If I understand correctly, you changing that value to 'false' means disabling security?  In which case it may be disabling the SSL redirect at the same time (enabling security enables SSL redirect).

I may be remembering this implementation detail wrong, however, but if your problem goes away when setting the enabled = false, then that seems to point to the redirection to the SSL port.

**Comment by ErezYehuda** [comment]
Yes, that's what I expect is happening, and in this case, I don't want Tomcat/WebAPI to be handling the security (that's handled by our reverse proxy). The issue now seems to be that the setting I have in the maven settings (which is successfully carried over to application.properties in WEB-INF/classes), security.enabled=false, is being overridden somewhere.

I was able to create a not-horrible crutch by including `-Dsecurity.enabled=false` in `CATALINA_OPTS`. It now uses DisabledSecurity instead of AtlasSecurity and doesn't force the pseudo-HTTPS.

**Comment by chrisknoll** [comment]
Cool! Keep us up to date.  I'm remembering wrong about security forcing SSL: we run on our dev environments with security but without SSL (because we don't have local workstation certificates set up) so I'm wrong about security requiring SSL.  It is strange that it ignores the application properties tho!  

Let us know if you find anything odd.

-Chris
