### ISSUE TITLE
New Authentication providers

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#282]
Authentication providers for LDAP, Active Directory, Kerberos, OpenID, Custom DB.

PR will be created as soon as https://github.com/OHDSI/WebAPI/issues/244 will be resolved (waiting for approval and merge).

**Comment by anthonysena** [comment]
@pavgra as mentioned in #244, I've merged in the vulnerability changes into the rc_2.3 branch. For this issue and the others (#283, #284, #285), please rebase your changes off the rc_2.3 branch so that we can review and merge them with the rest of the work. Thanks!

**Comment by anthonysena** [comment]
Closed
