### ISSUE TITLE
Cohort generation failed on Oracle

### ISSUE THREAD

**Issue by chen-regen** [OHDSI/WebAPI#295]
Current WebAPI/Atlas cohort generation fails with following error:
```
 ORA-00922: missing or invalid option
```
The statements that are causing problems are between "create table kwl9wkboinclusionRuleCohorts" and "CREATE TABLE kwl9wkboincluded_events":
```
create table kwl9wkboinclusionRuleCohorts (inclusion_rule_id NUMBER(19),
	person_id NUMBER(19),
	event_id NUMBER(19)
)

CREATE TABLE kwl9wkboincluded_events

AS
WITH cteIncludedEvents(event_id, person_id, start_date, end_date, op_start_date, op_end_date, ordinal)  AS (SELECT event_id, person_id, start_date, end_date, op_start_date, op_end_date, row_number() over (partition by person_id order by start_date ASC) as ordinal
  FROM (SELECT Q.event_id, Q.person_id, Q.start_date, Q.end_date, Q.op_start_date, Q.op_end_date, SUM(coalesce(POWER(cast(2 as NUMBER(19)), I.inclusion_rule_id), 0)) as inclusion_rule_mask
    FROM kwl9wkboqualified_events Q
    LEFT JOIN kwl9wkboinclusionRuleCohorts I on I.person_id = Q.person_id and I.event_id = Q.event_id
    GROUP BY Q.event_id, Q.person_id, Q.start_date, Q.end_date, Q.op_start_date, Q.op_end_date
   ) MG -- matching groups

 )
 SELECT
event_id, person_id, start_date, end_date, op_start_date, op_end_date

FROM
cteIncludedEvents Results
  WHERE Results.ordinal = 1
 ;
```
It's missing a semicolon between those 2 statements.

@anthonysena  @fdefalco , Anthony and Frank, I am pinging you here to get your attention. Can you forward to whoever is in charge of this? Thank you!

**Comment by chrisknoll** [comment]
I can look into this. The other thing odd-looking about this is that the tables with the hash-like looking prefix are temp tables, and so they should be rendered to crate the table into an 'oracle temp schema'. It's possible that this is missing from the WebAPI sqlRender parameters, so I'll look into this as well.

-Chris

**Comment by chen-regen** [comment]
@chrisknoll Thanks Chris. Have you been able to locate the problem? We would like to deploy the fixes here at Regenstrief because a few projects are waiting on cohort generation to move on.

**Comment by chrisknoll** [comment]
Hi, @chen-regen , sorry for the delay, I've been digging into other related oracle issues related to sql render and Achilles (and Heracles).  But, I think the immediate problem with the missing semicolon can be addressed quickly.  I'll ping back when the new release of the library is fixed.

**Comment by chen-regen** [comment]
@chrisknoll Thanks a lot Chris!

**Comment by chrisknoll** [comment]
hi, @chen-regen,
I think this issue was fixed in the relase of 1.3.1 of Circe-be, however, webAPI hasn't had a release to reference the new library.

If you are working off of a local build, you could reference the new circe-be release by altering your pom.xml:

```
    <dependency>
      <groupId>org.ohdsi</groupId>
      <artifactId>circe</artifactId>
      <version>1.3.1</version>
    </dependency>
```

Current WebAPI has circe reference at 1.3.0.

**Comment by chen-regen** [comment]
@chrisknoll Yeah, let me try that out.

**Comment by chen-regen** [comment]
@chrisknoll  I tried upgrading circe to 1.3.1 and it worked on our end. Thanks for the help! I hope this will work when WebAPI rc_2.3 release is out end of this month so we will not have to maintain the local build difference.
