### ISSUE TITLE
Estimation R code: set fftemp

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#296]
Hi,

It might be good to have a user-defined configuration step in the estimation R code in which the user needs to set fftemp directory. This is a useful prompt because folder permissions can vary from system to system, and disk space strategy can become necessary. I've run into 'cannot set working directory' errors due to the former a few times. If we want to ensure this code is nearly fool-proof, perhaps we can add the following to the top of the script:

```
fftempdir <- "" # Set FF Temp directory to store temporary data files, should be completely writable and have suitable disk space
options(fftempdir = fftempdir)
```

Tagging @anthonysena 

Thanks,
Ajit

**Comment by anthonysena** [comment]
Closed via #620
