### ISSUE TITLE
Building failure of WebAPI

### ISSUE THREAD

**Issue by estone96** [OHDSI/WebAPI#298]
Hello

I am doing the installation of WebAPI for Atlas and Achilles. 
However, there is an error in executing the 'maven' and I cannot complete goal on the project WebAPI.
I'm not sure what is matter.
My systems are windows server 2016 and sql server 2016. The result of executing the 'mvn clean package' is followed.

Thanks 

Yeesuk 

E:\Atlas_v2.2_Install\Atlas_v2.2_Install_Pack\WebAPI-2.2.0>mvn clean package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building WebAPI 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
Downloading: http://repo.maven.apache.org/maven2/org/ohdsi/sql/SqlRender/1.3.0-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.ohdsi.org:8085/nexus/content/repositories/snapshots/org/ohdsi/sql/SqlRender/1.3.0-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.ohdsi.org:8085/nexus/content/repositories/thirdparty/org/ohdsi/sql/SqlRender/1.3.0-SNAPSHOT/maven-metadata.xml
Downloading: http://repo.ohdsi.org:8085/nexus/content/repositories/releases/org/ohdsi/sql/SqlRender/1.3.0-SNAPSHOT/maven-metadata.xml
Downloading: http://redshift-maven-repository.s3-website-us-east-1.amazonaws.com/release/org/ohdsi/sql/SqlRender/1.3.0-SNAPSHOT/maven-metadata.xml
Downloaded: http://repo.ohdsi.org:8085/nexus/content/repositories/snapshots/org/ohdsi/sql/SqlRender/1.3.0-SNAPSHOT/maven-metadata.xml (2 KB at 1.0 KB/sec)
Downloading: http://repo.maven.apache.org/maven2/org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar
Downloading: http://repo.maven.apache.org/maven2/com/microsoft/sqlserver/mssql-jdbc/6.1.0.jre8/mssql-jdbc-6.1.0.jre8.jar
Downloading: http://repo.maven.apache.org/maven2/com/amazon/redshift/redshift-jdbc4-no-awssdk/1.2.8.1005/redshift-jdbc4-no-awssdk-1.2.8.1005.jar
Downloading: http://repo.ohdsi.org:8085/nexus/content/repositories/releases/org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar
Downloading: http://repo.ohdsi.org:8085/nexus/content/repositories/releases/com/microsoft/sqlserver/mssql-jdbc/6.1.0.jre8/mssql-jdbc-6.1.0.jre8.jar
Downloading: http://repo.ohdsi.org:8085/nexus/content/repositories/releases/com/amazon/redshift/redshift-jdbc4-no-awssdk/1.2.8.1005/redshift-jdbc4-no-awssdk-1.2.8.1005.jar
Downloading: http://repo.ohdsi.org:8085/nexus/content/repositories/thirdparty/org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar
Downloading: http://repo.ohdsi.org:8085/nexus/content/repositories/thirdparty/com/microsoft/sqlserver/mssql-jdbc/6.1.0.jre8/mssql-jdbc-6.1.0.jre8.jar
Downloading: http://repo.ohdsi.org:8085/nexus/content/repositories/thirdparty/com/amazon/redshift/redshift-jdbc4-no-awssdk/1.2.8.1005/redshift-jdbc4-no-awssdk-1.2.8.1005.jar
Downloading: http://repo.springsource.org/release/org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar
Downloading: http://repo.springsource.org/release/com/microsoft/sqlserver/mssql-jdbc/6.1.0.jre8/mssql-jdbc-6.1.0.jre8.jar
Downloading: http://repo.springsource.org/release/com/amazon/redshift/redshift-jdbc4-no-awssdk/1.2.8.1005/redshift-jdbc4-no-awssdk-1.2.8.1005.jar
Downloading: http://redshift-maven-repository.s3-website-us-east-1.amazonaws.com/release/org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar
Downloading: http://redshift-maven-repository.s3-website-us-east-1.amazonaws.com/release/com/microsoft/sqlserver/mssql-jdbc/6.1.0.jre8/mssql-jdbc-6.1.0.jre8.jar
Downloading: http://redshift-maven-repository.s3-website-us-east-1.amazonaws.com/release/com/amazon/redshift/redshift-jdbc4-no-awssdk/1.2.8.1005/redshift-jdbc4-no-awssdk-1.2.8.1005.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:01 h
[INFO] Finished at: 2018-01-11T01:04:08+09:00
[INFO] Final Memory: 18M/2118M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project WebAPI: Could not resolve dependencies for project org.ohdsi:WebAPI:war:1.0.0-SNAPSHOT: The following artifacts could not be resolved: org.postgresql:postgresql:jar:9.4-1201-jdbc41, com.microsoft.sqlserver:mssql-jdbc:jar:6.1.0.jre8, com.amazon.redshift:redshift-jdbc4-no-awssdk:jar:1.2.8.1005: Could not transfer artifact org.postgresql:postgresql:jar:9.4-1201-jdbc41 from/to central (http://repo.maven.apache.org/maven2/): GET request of: org/postgresql/postgresql/9.4-1201-jdbc41/postgresql-9.4-1201-jdbc41.jar from central failed: Read timed out -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by anthonysena** [comment]
@estone96 - sorry that there was no follow up on this issue. Please reach out if you are still facing issues and feel free to re-open. I'm going to close it for now since this issue is old.
