### ISSUE TITLE
FeatureExtraction version synchronization

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#307]
Today WebAPI & Atlas use FeatureExtraction package in several places:
- WebAPI itself (https://github.com/OHDSI/WebAPI/blob/master/pom.xml) - version 2.0.2
- PLE analysis -> Utilities -> Code - version 1.2.3
- PLP analysis -> Utilities -> Code - uses PLP package, which depends on FeatureExtraction v2 (https://github.com/OHDSI/PatientLevelPrediction/blob/master/DESCRIPTION)

The first and second versions of FeatureExtraction differs a lot and this brings more complexity into project to maintain both. What is more, it becomes not possible to run both PLE R code and PLP R code, generated by Atlas, in parallel.

So I'd like to propose migrate PLE R code to use FE v2.

**Comment by anthonysena** [comment]
Thanks @pavgra for raising this issue. With the upcoming Atlas/WebAPI release v2.3, we've started to address this inconsistency by making the code all compatible with FE v2. Please see OHDSI/Atlas#509 and checkout the [feature-integration](https://github.com/OHDSI/Atlas/tree/feature-integration) branch on Atlas which is the current release candidate for Atlas v2.3.

The larger issue that you've raised that will need community discussion is ensuring there are well-defined dependencies between Atlas and the methods libraries. We can save that for the OHDSI forums or the future releases of Atlas and for now, I'd propose closing this issue.

**Comment by YuriyKhoma** [comment]
@pavgra, @anthonysena  I do not see any problems to update PLE code for FE v2 compatibility. If no one is against I'll create new R script to solve this issues.

**Comment by anthonysena** [comment]
Hi @YuriyKhoma - I believe we've already addressed this with the code that is currently on the master branch of Atlas/WebAPI. The PLE editor needs some extensions to take advantage of all of the features of FeatureExtraction (and CohortMethod) and that will be planned for the V2.4 release of Atlas/WebAPI.
