### ISSUE TITLE
heracles_results table query performance

### ISSUE THREAD

**Issue by leeevans** [OHDSI/WebAPI#308]
@chrisknoll @anthonysena 

In the OHDSI cloud Atlas database the number of rows in the heracles_results table is growing large and the time to query the table is also increasing.

There are currently 55,435,046 rows in that table in the OHDSI cloud database and the sql below takes 118 seconds (table sequential scan).

For example, this WebAPI endpoint is called by ATLAS and executes the below SQL query:
http://api.ohdsi.org/WebAPI/cohortresults/1PCT/922781/analyses 

```
select distinct analysis_id
FROM  synpuf1pct.heracles_results 
WHERE COHORT_DEFINITION_ID = 922781 
union
SELECT distinct analysis_id
FROM  synpuf1pct.heracles_results_dist 
WHERE COHORT_DEFINITION_ID = 922781
```

Is there some indexing/partitioning approach that can be applied to this table with minimal negative impact on the heracles results generation that inserts rows into it?

Also, the above WebAPI endpoint is immediately called when a cohort is opened in Atlas. If the results are only needed on the Heracles reporting tab, could that endpoint call be deferred so it is only executed when the reporting tab is clicked on by the user?

**Comment by anthonysena** [comment]
Noting this for the 2.8 release to determine if this still an issue. I do not believe ATLAS is automatically requesting this resource upon load.

**Comment by anthonysena** [comment]
@leeevans - I'd like to close this out since 2.8 no longer calls the `WebAPI/cohortresults/<source_key>/<cohort_definition_id>/analyses` endpoint upon opening the cohort. Furthermore, the DDL script from WebAPI does provide some indexes for these tables:

````
CREATE INDEX HRD_IDX_COHORT_DEF_ID ON @results_schema.HERACLES_RESULTS_DIST (cohort_definition_id);

CREATE INDEX HRD_IDX_COHORT_ID_ANALYSIS_ID ON @results_schema.HERACLES_RESULTS_DIST (cohort_definition_id, analysis_id);

CREATE INDEX HRD_IDX_COHORT_DEF_ID_DT ON @results_schema.HERACLES_RESULTS_DIST (cohort_definition_id, last_update_time);

CREATE INDEX HRD_IDX_COHORT_ID_FIRST_RES ON @results_schema.HERACLES_RESULTS_DIST (cohort_definition_id, analysis_id, count_value, stratum_1);

CREATE INDEX HR_IDX_COHORT_DEF_ID ON @results_schema.HERACLES_RESULTS (cohort_definition_id);

CREATE INDEX HR_IDX_COHORT_ID_ANALYSIS_ID ON @results_schema.HERACLES_RESULTS (cohort_definition_id, analysis_id);

CREATE INDEX HR_IDX_COHORT_ANALYSIS_CONCEPT ON @results_schema.HERACLES_RESULTS (cohort_definition_id, analysis_id) WHERE stratum_2 <> '';

CREATE INDEX HR_IDX_COHORT_DEF_ID_DT ON @results_schema.HERACLES_RESULTS (cohort_definition_id, last_update_time);

CREATE INDEX HR_IDX_COHORT_ID_FIRST_RES ON @results_schema.HERACLES_RESULTS (cohort_definition_id, analysis_id, count_value, stratum_1);
````

If we need to revisit this, please let me know and we can re-open the issue.
