### ISSUE TITLE
prevent orphan cohort results data in heracles tables

### ISSUE THREAD

**Issue by leeevans** [OHDSI/WebAPI#309]
@chrisknoll @anthonysena 

I noticed there is some 'orphan' cohort results data in the heracles_results table in the OHDSI cloud ATLAS database where presumably the cohort definition was deleted after a heracles cohort analysis was generated.

One possible solution would be to also delete any existing associated heracles results/visualization data (using cohort_definition_id) from all of the heracles tables when a cohort is deleted in ATLAS.

**Comment by chrisknoll** [comment]
Sounds like we could implement a Tasklet that triggers after cohort delete that would do the necessary cleaning.  This is doable.

**Comment by leeevans** [comment]
Great. 

FYI. I didn't look to see if the cohort table is being cleaned up when a cohort definition is deleted - if not, consider cleaning up that table too.

**Comment by chrisknoll** [comment]
Yep, we'll delete from the set of results tables that has cohort_definition_id on it.
