### ISSUE TITLE
Capture author for all entity types

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#315]
Today WebAPI captures author only for Cohorts and Incidence Rates. The suggestion is log author for Concept sets, Estimations and Predictions too.

**Comment by gowthamrao** [comment]
Thank you @pavgra 

This makes absolute sense. Infact, I think we should at one point plan to design and store user specific definitions and results. E.g. If user A has results, user B can still run incidence rates, but it will not overwrite user B work

**Comment by anthonysena** [comment]
Closed via #320
