### ISSUE TITLE
Informative Application Error Messages

### ISSUE THREAD

**Issue by alexander-ryabokon** [OHDSI/WebAPI#328]
Testing revealed that the application was configured to return informative error messages. This could enable an attacker to understand the cause of the errors and use this information to develop further attack strategies.
An application will often generate the content returned to a user based on specific values it receives. If these values are not supplied in the expected format, they can trigger exceptions in the application’s code. These exceptions can create error messages that include stack traces and other useful debugging information. Although useful to developers, exposing this information to remote users creates the risk of assisting an attacker.
One example of an error message snippet returned when a request was made to the login page with invalid credentials. The URL for the login page is below:

• /WebAPI/user/login/db

The following was the server’s response to receiving invalid credentials:

`HTTP/1.1 500 Internal Server Error
Date: Wed, 07 Feb 2018 18:00:31 GMT
Server: nginx/1.10.3 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains
Content-Type: application/json
Content-Length: 15642
Vary: Accept-Encoding
Connection: close
{
"payload": {
"cause": null,
"stackTrace": [
{
"methodName": "run",
"fileName": "ServerRuntime.java",
"lineNumber": 323,
"className": "org.glassfish.jersey.server.ServerRuntime$2",
"nativeMethod": false
},
{
"methodName": "call",
"fileName": "Errors.java",
"lineNumber": 271,
"className": "org.glassfish.jersey.internal.Errors$1",
"nativeMethod": false
},
{
"methodName": "call",
"fileName": "Errors.java",
"lineNumber": 267,
"className": "org.glassfish.jersey.internal.Errors$1",
"nativeMethod": false
},
<snipped for length>
`

The above error message shows that the application used the “Glassfish Jersey RESTful API” Java library.
Other libraries were found to be in use due to the informative error message, such as the following:

• Apache Catalina
• Apache Tomcat
• Apache Shiro
• Spring Framework

Specific information about the cause of the error can aid an attacker in the development of further attacks, as application layer vulnerabilities often arise from eventualities not anticipated by the developers. Often, it is only possible to construct accurate attacks once the details of errors that have been caused are known.
The presence of verbose error messages also encourages an attacker to continue with a penetration attempt as they highlight that the application code is not correctly handling unexpected input. By contrast, if all error messages returned are standardised and non-informative, an attacker will often not be able to anticipate whether a vulnerability is actually present.

**Comment by anthonysena** [comment]
Tagging @pavgra @gklebanov to understand to what degree that this has already been addressed in the stack.

**Comment by olga-ganina** [comment]
There are GenericExceptionMapper improved, error handling on the UI and some minor changes regarding this issue. Currently we do not have scenario how to get an error page with stacktrace instead of human readable error message
