### ISSUE TITLE
Issue with Integrating google authenticaiton

### ISSUE THREAD

**Issue by Ctvidyak** [OHDSI/WebAPI#332]
I am trying to integrate the Google Authentication with Atlas application . Authentication is working fine. Once authenticated I get redirected to Atlas welcome page. But it shows you are not authorised to view this page. 
However on page reload from browser authorization part works. 
Below are settings i have done is OHDSI Webapi settings.xml

	```
	<security.enabled>true</security.enabled>
			<security.token.expiration>43200</security.token.expiration>
			<security.origin>http://localhost:8088</security.origin>
			<security.ssl.enabled>false</security.ssl.enabled>
			<security.oauth.callback.ui>http://localhost:8088/Atlas/#/welcome</security.oauth.callback.ui>
			<security.oauth.callback.api>http://localhost:8080/WebAPI/user/oauth/callback</security.oauth.callback.api>
			<security.oauth.google.apiKey>[API key from google app]</security.oauth.google.apiKey>
			<security.oauth.google.apiSecret>[secret Key from google app ]</security.oauth.google.apiSecret>
			<security.oauth.facebook.apiKey></security.oauth.facebook.apiKey>

```
And in google app registration

Authorised javascript origin 
http://localhost:8088

Authorised redirect URI
http://localhost:8080/WebAPI/user/oauth/callback?client_name=Google2Client

Am I missing anything in configuration?

**Comment by anthonysena** [comment]
Hi @Ctvidyak - can you confirm which version of WebAPI you are using? I'd highly recommend using what is currently on master (if you are not already) as this contains many improvements around security.

It may be the case that you were not assigned a default role in the system. Can you take a look at the information in the WebAPI DB to confirm that a user account was created for your Google login and then check the roles assigned? Here is a sample query you can use:

```
select * 
from webapi.sec_user u
inner join webapi.sec_user_role ur ON u.id = ur.user_id
inner join webapi.sec_role r ON ur.role_id = r.id
```

If no roles were assigned to your user account, you may need to assign these manually - this is done by inserting records into the sec_user_permission table for the user and role you would like to associate together.

**Comment by anthonysena** [comment]
Closing due to lack of response. Please follow up if you are still facing an issue. Thanks!
