### ISSUE TITLE
Review codebase for potential Spring Data REST security vulnerability

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/WebAPI#342]
Have we reviewed the codebase for exposure to the recently announced  [security vulnerability](https://lgtm.com/blog/spring_data_rest_CVE-2017-8046) associated with our Spring libraries?

**Comment by chrisknoll** [comment]
Possibly. I've quickly scanned the pom.xml for the affected artifacts:
spring-data-rest-core, spring-data-rest-webmvc, spring-data-rest-distribution, spring-data-rest-hal-browser and I didn't find these.

We are using Spring Boot version to prior 2.0.0.M4, but not using the spring boot-startr-data-rest.
We do use Spring Data, I'm not sure which versions fall under 'prior to Kay-RC3', but the vulnerability is related to the use of SpEL, and I don't think we use that in our JPA queries.

So, this should definitely be investigated, we should probably work on upgrading to the latest libraries (I recently updated everything to 1.5..2 early last year), but now there's a 2.0 release we could migrate to.  We should be careful about moving from the 1.5.X to the 2.0.X, i'm sure there's breaking changes we need to account for.

**Comment by t-abdul-basser** [comment]
Agreed. My brief analysis of the POM was also inconclusive. I agree that we should upgrade and would be glad to discuss it and take a stab.

**Comment by anthonysena** [comment]
@pavgra is reviewing this and will determine if it stays in the 2.7 release path or if it should be moved to an upcoming release.

**Comment by ssuvorov-fls** [comment]
5. The main problem is autowiring transactional beans, because default strategy was changed after spring-boot 2.0 and now it s cglib. Using of parameter "proxy-target-class" has no effect.

6. Spring jms has to be included in pom.

**Comment by OdysseusMark** [comment]
As earlier mentioned, vulnerable dependencies are not present in our current project. Any further version upgrades to be considered in separate issues.
