### ISSUE TITLE
Treatment Pathways Integration

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#361]
Extend and test the treatment pathway work done by @chen-regen. Currently this work is located in the following branches:

WebAPI: OHDSI-59 
Atlas: panacea2017

Goals:
- Rebase code off latest master branch in each repository
- Test code is working against MPP platforms (PDW, RedShift)
- Add REST endpoints to the security framework

Targeting to have this as part of the 2.4 release (#346).

**Comment by leeevans** [comment]
@anthonysena as mentioned on previous calls, after you have it working on PDW I would be happy to help test this on Redshift.

**Comment by anthonysena** [comment]
Thanks @leeevans I'll certainly take you up on that offer!

**Comment by anthonysena** [comment]
Closing as we're now tracking this in #522
