### ISSUE TITLE
New IR Analysis endpoint

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WebAPI#366]
We, at The Hyve, have created a new endpoint in the Incidence Rate (IR) Analysis Service: `ir/<analysis_id>/reports/<source_key>`. This returns all IR results for that source and will be used for a new overview of incidence rates in one IR study.
@anthonysena mentioned that it is by design that not all reports are returned currently. Very curious to hear what the reason for this is (security?).

**Comment by anthonysena** [comment]
@MaximMoinat - just going through some old issues. Found this discussion on the forums:

https://forums.ohdsi.org/t/ir-analysis-grid-overview/4211/4

Tagging @pbr6cornell for consideration of having this functionality in the stack. I'm assuming you guys still have the code for this somewhere and would still like to make this contribution. If not, I can close this out with my regrets for not following up sooner.

**Comment by anthonysena** [comment]
Closing due to age.
