### ISSUE TITLE
Heracles - SQL corrections (Persons should be unique subject_id)

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/WebAPI#368]
Number of persons seem to be incorrect in these analysis_id. Person's are people identified by subject_id. In a cohort, a person may have a record more than once with different cohort_start_date and cohort_end_date. In current implementation, we mostly counting records not persons; but the title of the analysis suggests it is unique people. I think, if we report on Persons - we should do summaries of unique subject_id's. In many section `count_big(distinct person_id)` and 'count_big(person_id)` are used; I think we should be consistent with `count_big(person_id)`

In all SQL's below, we should change to
`inner join (select distinct subject_id, cohort_definition_id from #HERACLES_cohort) c1`

some sections that this is important (there are probably 50 of these)

https://github.com/OHDSI/WebAPI/blob/971cc31fe44aa48ed28b57a010ff3e699a0f2cce/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L97

https://github.com/OHDSI/WebAPI/blob/971cc31fe44aa48ed28b57a010ff3e699a0f2cce/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L127

https://github.com/OHDSI/WebAPI/blob/971cc31fe44aa48ed28b57a010ff3e699a0f2cce/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L169

etc.

Should this be fixed?

**Comment by pavgra** [comment]
Should be covered by https://github.com/OHDSI/WebAPI/pull/705
