### ISSUE TITLE
how to insert author info of Concept Set by WebAPI

### ISSUE THREAD

**Issue by chiyuan1126** [OHDSI/WebAPI#373]
May I ask is there any way to call APIs to store author or "createdBy" info? I could get it by "GET" request of "http://54.242.168.196/WebAPI/conceptset/" 

I tried posting some request with that attribute(createdBy) but it doesn't work.

**Comment by pavgra** [comment]
@chiyuan1126, this info is automatically inserted, when application is running in secured mode (authentication enabled).

**Comment by chiyuan1126** [comment]
@pavgra Ok. I see. Thanks!
