### ISSUE TITLE
Concept record counts NumberFormatException

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WebAPI#375]
Why are the concept_ids wrapped into quotes when conceptRecordCounts are retrieved? Is this to prevent code injection?
https://github.com/OHDSI/WebAPI/blob/a4058f5aac8caab2527ca4057eaa1f7f849b0c8f/src/main/java/org/ohdsi/webapi/service/CDMResultsService.java#L81-L85

Downstream this caused an exception for me: `java.lang.NumberFormatException: For input string: "'548378'"`.

**Comment by t-abdul-basser** [comment]
@leenadR We are experiencing the same issue here in Production. We can confirm that the issues appears in some CDMs but not in others.

**Comment by chrisknoll** [comment]
Hi, I'm not sure why the identifiers were quoted, but I think we just need to convert those identifiers to inits and pass them into the 'getConceptRecordCount' function as an array of integers.  I'll work on a PR for that change.

**Comment by mpozhidaeva** [comment]
Sometimes the bug does not occur because result can be taken from the cache (without logic with quotes)
