### ISSUE TITLE
Add DomainMeta to CDMResultsService

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#376]
Currently, the CDMResultsService allows you to consume the Achilles results from a CDM. However, the Domain Meta information is not available.

I'd like to add this, as we have some need to be able to grab this info programmatically.

**Comment by anthonysena** [comment]
Moving this for discussion around 3.0

**Comment by anthonysena** [comment]
Closing this out due to age. If we want to revisit this, we can re-open and prioritize.
