### ISSUE TITLE
set up bug

### ISSUE THREAD

**Issue by Sigfried** [OHDSI/WebAPI#377]
with newest WebAPI from master, I get this at some point:

```
Caused by: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException:
Migration V2.2.5.20180215105415__separate-sequences.sql failed
--------------------------------------------------------------
SQL State  : 42P01
Error Code : 0
Message    : ERROR: relation "webapi.negative_controls_sequence" does not exist
  Position: 15
Location   : db/migration/postgresql/V2.2.5.20180215105415__separate-sequences.sql (/usr/local/Cellar/tomcat/9.0.6/libexec/webapps/WebAPI/WEB-INF/classes/db/migration/postgresql/V2.2.5.20180215105415__separate-sequences.sql)
Line       : 14
Statement  : SELECT setval('webapi.negative_controls_sequence', coalesce(max(id), 1)) FROM webapi.concept_set_negative_controls
```

**Comment by mpozhidaeva** [comment]
@anthonysena - I think it relates with this commit
https://github.com/OHDSI/WebAPI/commit/10eb498ce1192a52e615e38a60ea6576c37f1771

Why did you remove line 13 with creation of the negative_controls_sequence?)

**Comment by anthonysena** [comment]
@mpozhidaeva - The reason I removed that sequence is that it is already created in a previous script:

https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/db/migration/postgresql/V1.0.1.2__conceptset_negative_controls.sql#L3

Upon further review of @Sigfried's bug, I've cleaned up this particular script and will submit a pull request. Could you review it? Thanks!
