### ISSUE TITLE
Store data sources' passwords in encrypted way

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#381]
### Expected behavior
Data sources credentials in database shouldn't be stored in plaintext.

### Solution proposal
Ask user to enter a master password during application startup / in application properties and encrypt data sources credentials entered via UI using the password. Also, double check that decrypted passwords are not printed in logs / UI / elsewhere.

**Comment by gklebanov** [comment]
@gowthamrao - will work with Gowtham and BCBSSC IT team to capture and share requirements

**Comment by anthonysena** [comment]
@gklebanov @pavgra - Some questions regarding the design of this feature:

- What are the requirements around configuring and using private/public keys with respect to encrypting the data sources credentials?
- What are the minimum requirements for encryption strength? Can this be configured as part of the application set up?
- How is the encryption invoked? Presumably this happens as part of the WebAPI start up activities?
- Is the approach here to make this a one-way encryption such that recovery will not be an option? From my previous experience, this is acceptable in the case of connection strings as those should be protected outside of the system configuration.

**Comment by pavgra** [comment]
@anthonysena , regarding the question:

> Is the approach here to make this a one-way encryption such that recovery will not be an option? 

Not sure, whether I got the question. If you have a master password, you are able to decrypt the data
