### ISSUE TITLE
Create cohort through POST request to the WebAPI

### ISSUE THREAD

**Issue by cjamadagni** [OHDSI/WebAPI#383]
I've looked at the webAPI documentation and I can't seem to figure out how one can create a new Cohort by using the available APIs. 

Could someone please provide an example of doing the above?

Thanks in advance.

**Comment by SBylemans** [comment]
@cjamadagni are you still looking into this?

**Comment by chrisknoll** [comment]
The service definition is found here:
https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java#L377

You post a JSON containing the cohort definition following the structure here: https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java#L290 (note how CohortDefinitionDTO contains the fields of CohortDefinitionListItem + an additional field ```expression```.

Also note, expression is a string representation of the cohort expression.  IN the case of CIRCE, you should json-stringify the CohortExpression that is defined here: https://github.com/OHDSI/circe-be/blob/master/src/main/java/org/ohdsi/circe/cohortdefinition/CohortExpression.java#L33.

You can also just go to ohdsi.org/web/atlas and open up a dev console and see how the network traffic interacts with the WebAPI. you will see all the POST/PUTs that are invovled in create/update the cohort.

Closing this as a discussion ticket, but please feel free to discuss.
