### ISSUE TITLE
Split runHeracles.sql into parts and assemble them in Java

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#385]
Today we have a single enormously huge SQL file containing all analyses. The file is processed by SqlRender to cut out all not required analyses, which is absolutely inefficient and takes up to several minutes. What is more, managing and editing of such file is also not convenient.

The proposal is to split the file into partials, one per analysis or analyses group, and assemble them in Java. And only then pass to SqlRender. This would give us a big boost in performance.

**Comment by gowthamrao** [comment]
It was @pbr6cornell original idea to make this beast :)

What I think would be ideal is either
- circe-be like approach - of stitching thru multiple code snippets into a query
- feature extraction like approach - of using hyper parameterized SQL.

In any approach, we need to support
- cohort level characterization (for summary statistics)
- person level characterization (for modeling in PLP, PLE, other including providing an analytic wide data frame with attributes/features selected by analyst for use in an R package)
