### ISSUE TITLE
SAML support for authentication

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#396]

**Comment by anthonysena** [comment]
I believe we can leverage this library which is already part of the project for SAML: http://www.pac4j.org/. It may need an update but I'd suggest looking into this library as part of the design work around a SAML authentication implementation.

**Comment by anthonysena** [comment]
Since we're using Pac4j in the project, is this still an issue that requires resolution @pavgra?

**Comment by olga-ganina** [comment]
Hi @anthonysena  , yes we would like to implement this support, so I'll add this to our queue.

**Comment by ssuvorov-fls** [comment]
VM parameters for saml support
```
-Dsecurity.saml.idpMetadataLocation=classpath:saml/dev/idp-metadata.xml
-Dsecurity.saml.metadataLocation=saml/dev/sp-metadata.xml
-Dsecurity.saml.keyManager.keyStoreFile=classpath:saml/samlKeystore.jks
-Dsecurity.saml.keyManager.storePassword=nalle123
-Dsecurity.saml.keyManager.passwords.arachnenetwork=nalle123
-Dsecurity.saml.keyManager.defaultKey=apollo
-Dsecurity.saml.sloUrl=https://localhost:8443/cas/logout
-Dsecurity.saml.callbackUrl=http://localhost:8080/WebAPI/user/saml/callback
```

**Comment by ssuvorov-fls** [comment]
see also https://bitbucket.org/Odysseus/dockerenv/pull-requests/117/added-parameters-for-atlas-saml
