### ISSUE TITLE
IMPALA: Cohort generation fails

### ISSUE THREAD

**Issue by wivern** [OHDSI/WebAPI#409]
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [DELETE FROM synpuf_50_test_results.cohort_inclusion WHERE cohort_definition_id = ?]; SQL state [HY000]; error code [500051]; [Simba][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AnalysisException: Impala does not support modifying a non-Kudu table: synpuf_50_test_results.cohort_inclusion), Query: DELETE FROM `synpuf_50_test_results`.`cohort_inclusion` WHERE (`cohort_inclusion`.`cohort_definition_id` = 3283).; nested exception is java.sql.SQLException: [Simba][ImpalaJDBCDriver](500051) ERROR processing query/statement. Error Code: 0, SQL state: TStatus(statusCode:ERROR_STATUS, sqlState:HY000, errorMessage:AnalysisException: Impala does not support modifying a non-Kudu table: synpuf_50_test_results.cohort_inclusion), Query: DELETE FROM `synpuf_50_test_results`.`cohort_inclusion` WHERE (`cohort_inclusion`.`cohort_definition_id` = 3283).

**Comment by chrisknoll** [comment]
Right, this was an issue raised multiple times, but I don't think there's a solution for it.  I called it out here: http://forums.ohdsi.org/t/atlas-on-impala/3014/3.  Until that's resolved, I don't think we can call this an issue with WebAPI. I'd open an issue with Impala to support deletes.
