### ISSUE TITLE
USE should not be used

### ISSUE THREAD

**Issue by jduke99** [OHDSI/WebAPI#41]
In runHeraclesAnalyses.sql, line 75, it uses USE, which apparently breaks in Postgres

https://github.com/OHDSI/WebAPI/search?utf8=%E2%9C%93&q=use+select&type=Code

**Comment by chrisknoll** [comment]
Yes, I had to weed these out of the achilles scripts as well.  We just need to make sure that we are prefixing all table references with the appropriate schema.

**Comment by schuemie** [comment]
Sorry, I missed this discussion. Why is it not OK to use `USE`? SqlRender will translate it to `SET SEARCH_PATH TO` for PostgreSQL.

**Comment by jduke99** [comment]
Reportedly a Postgres problem?
