### ISSUE TITLE
PLE name change fails

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#412]
**Steps to reproduce:**
1. Create new PLE and save it
1. Change name
1. Press Save

**Expected results:**
Name updated

**Actual result:**
```
"could not execute statement; SQL n/a; constraint created; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"

ERROR: null value in column "created" violates not-null constraint↵ Detail: Failing row contains (
```

**Comment by chrisknoll** [comment]
From the error, this looks like a constraint violation vs. something related to changing the name.  If the item  is being renamed, it must have already been created, so it's strange that the 'created' field would be null in this case.  It makes me suspicious that there's a deeper problem at play here.
