### ISSUE TITLE
PreparedStatementRender prevents specifying dialect via setDialect()

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#422]
## Expected Behhavior
If you crate a PSR, and later specify the target dialect, you should get the rendered sql for that dialect.

## Actual Behavior
The dialect is pulled from the Source at construction time where the sql is rendered and translated.  If Source is null, it will use the local 'getTargetDialect()', which defaults to 'ms sql'.  Setting target dialect and calling getSql() will not return the sql under the new dialect.

**Comment by pavgra** [comment]
Fixed by https://github.com/OHDSI/WebAPI/pull/423
