### ISSUE TITLE
Unable to "Generate With Features" in ATLAS

### ISSUE THREAD

**Issue by lrasmus** [OHDSI/WebAPI#433]
I am unable to use the "Generate With Features" capability in ATLAS.  I have a cohort definition that will run successfully (via Generate), but will error out when run as "Generate With Features".  In review of the logs, the following exception is coming back:

```
SQL state [S0001]; error code [2714]; There is already an object named '#raw_data' in the database.; nested exception is java.sql.BatchUpdateException: There is already an object named '#raw_data' in the database.
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
    	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
    	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:419)
    	at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:600)
    	at org.ohdsi.webapi.cohortfeatures.GenerateCohortFeaturesTasklet.doTask(GenerateCohortFeaturesTasklet.java:150)
    	... 23 more
    Caused by: java.sql.BatchUpdateException: There is already an object named '#raw_data' in the database.
    	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeBatch(SQLServerStatement.java:1915)
    	at org.springframework.jdbc.core.JdbcTemplate$1BatchUpdateStatementCallback.doInStatement(JdbcTemplate.java:561)
    	at org.springframework.jdbc.core.JdbcTemplate$1BatchUpdateStatementCallback.doInStatement(JdbcTemplate.java:548)
    	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:408)
    	... 25 more
```

I am able to get the full SQL code from the log and see the same error when run directly against the database (no big surprise there).  Our setup is using Broadsea containers for ATLAS and WebAPI, running against a SQL Server 2017 Standard database.

**Comment by anthonysena** [comment]
@lrasmus could you help us understand what version of Atlas/WebAPI you are running on Broadsea? Tagging @leeevans for awareness. It might also be helpful if you can post up the SQL code you mentioned that is causing the issue. I'm sure the script is large so it might be best to attach it to the issue (or we can coorespond via email). Thanks!

**Comment by lrasmus** [comment]
Thanks @anthonysena and @leeevans for any insight!  Looks like the Broadsea containers are always tagged "latest", so it's the "latest" image as of 6 months ago:

REPOSITORY  |  TAG  |   IMAGE ID | CREATED  | SIZE
-------------- | ------ | ----------- | -------- | ----------
docker.io/ohdsi/broadsea-webtools  | latest |   ba21241221a3   |  6 months ago | 934 MB

Here's the SQL that I was able to pull out of the container logs: 
[error-generate-with-features.txt](https://github.com/OHDSI/WebAPI/files/2039658/error-generate-with-features.txt)

**Comment by leeevans** [comment]
@lrasmus  Please try to pull the latest ohdsi/broadsea-webtools image again:
`docker pull ohdsi/broadsea-webtools`

The docker hub automated build log shows it was last built 8 days ago, so it should be the latest version.

https://hub.docker.com/r/ohdsi/broadsea-webtools/builds/

FYI. The dockerfile includes the webapi release version number which was 2.4:
https://hub.docker.com/r/ohdsi/broadsea-webtools/~/dockerfile/

**Comment by lrasmus** [comment]
@leeevans thanks for the info on finding the version number!

Applied the update and restarted, but unfortunately I'm seeing the same error.  Given that the only thing that hasn't changed yet is the database, I'm wondering if there's something I did incorrect in the setup.

**Comment by chrisknoll** [comment]
Ok, so this kind of error could be that we're reusing a temp table name during the generateFeatures, but MSSQL does a full batch statement parse to find out if there's duplicate table names being created (which could be the case here).  We may need to do something about ensuring all temp tables within the script are unique, or do some sort of batch step isolation so that the parser doesn't come up with that error.

I'm surprised we haven't run across this error on MS PDW...it uses the same parser.

**Comment by lrasmus** [comment]
@chrisknoll it seems like it would have come up, which is why I'm wondering if it's something specific to my environment.  Taking that SQL, as expected putting in GO statements after the appropriate DROP commands fixes things up where the script at least executes to completion.

**Comment by chrisknoll** [comment]
Right, the GO statement acts as a partition between statements so the parser doesn't attempt to look for Create #temp .... create #temp ... and then detects the error.  

Let me investigate the script and figure out a way to avoid this situation.

**Comment by t-abdul-basser** [comment]
@lrasmus Just want to chime in here that we are also seeing this in our department-wide deployment.

**Comment by chrisknoll** [comment]
@schuemie , the issue stems from the same temp table being created in the same series of statements, and can be avoided if each query has a dedicated 'rawData' temp table name so that the SQL parser won't falsly identify a table creation being duplicated.

@t-abdul-basser , a short term solution can be to execute the feature SQL statements sequentially instead of using execute batch.

**Comment by lrasmus** [comment]
@t-abdul-basser thanks for letting me know I'm not the only one seeing this.

@chrisknoll thanks for continuing to investigate.  Let me know if this is anything the community could help out with as far as working on an implemented solution (sounds like you may already have a good handle on it though).

**Comment by chrisknoll** [comment]
We have a new release of feature extraction which keeps the temp tables unique. We should be able to make a 2.4.2 release (or we will re-release 2.4.1) with these fixes.

**Comment by shandy79** [comment]
I'm getting this error as well with Atlas/WebAPI 2.4.2 and 2.4.3.  Any updates on when this might be addressed?

**Comment by chrisknoll** [comment]
Hmm, this was something that I think was addressed in feature extraction 2.1.4: https://github.com/OHDSI/FeatureExtraction/commit/7b96c1c4216fa0e43edd95ae6c71f93b1d380d55

But, WebAPI won't use it unless we've updated the reference to feature extraction to be the correct version: https://github.com/OHDSI/WebAPI/blob/v2.4.3/pom.xml#L573.

But it appears pom.xml is pointing to 2.1.4. 

So, I need to do a local debug and look at the generated Feature Extraction sql to verify that the #raw_data temp table is not being duplciated.

@shandy79 , are you certain that you are getting the same error about the duplicate table name?

**Comment by shandy79** [comment]
@chrisknoll, the error message that was given is:
SQL state [S0001]; error code [2714]; There is already an object named '#overall_stats' in the database.

I've attached the SQL code from the logs.
[catalina.out.txt](https://github.com/OHDSI/WebAPI/files/2246118/catalina.out.txt)

**Comment by chrisknoll** [comment]
Aha! Ok, i'll check or that temp table as well.

Thank you!

**Comment by pavgra** [comment]
Closing since there is no more "Generate with features"
