### ISSUE TITLE
Correction runHeraclesAnalyses

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/WebAPI#443]
https://github.com/OHDSI/WebAPI/blob/d28509e7f6e3ee21c9885edaf887bd1a6a434aa4/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L9367
Should say "Distribution of number of visit dates per subject by period_id, by visit_concept_id, by visit_type_concept_id during the cohort period"

https://github.com/OHDSI/WebAPI/blob/d28509e7f6e3ee21c9885edaf887bd1a6a434aa4/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L9542
Should say "Distribution of number of care_site+visit dates per subject by period_id, by visit_concept_id, by visit_type_concept_id during the cohort period"

https://github.com/OHDSI/WebAPI/blob/d28509e7f6e3ee21c9885edaf887bd1a6a434aa4/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L11165
Should say "Distribution of greater than 0 US$ cost per subject by period_id, by visit_concept_id, by visit_type_concept_id, by cost_concept_id, by cost_type_concept_id in the 365d prior to first cohort start date"

https://github.com/OHDSI/WebAPI/blob/d28509e7f6e3ee21c9885edaf887bd1a6a434aa4/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L11587
Should say "Distribution of greater than 0 US$ cost per subject by period_id, by drug_concept_id, by drug_type_concept_id, by cost_concept_id, by cost_type_concept_id in the 365d prior to first cohort start date"

https://github.com/OHDSI/WebAPI/blob/d28509e7f6e3ee21c9885edaf887bd1a6a434aa4/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L11587
Should say "Distribution of greater than 0 US$ cost per subject by period_id, by drug_concept_id, by drug_type_concept_id, by cost_concept_id, by cost_type_concept_id in the 365d prior to first cohort start date"

https://github.com/OHDSI/WebAPI/blob/d28509e7f6e3ee21c9885edaf887bd1a6a434aa4/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L11814
Should say "Distribution of greater than 0 US$ cost per subject by period_id, by drug_concept_id, by drug_type_concept_id, by cost_concept_id, by cost_type_concept_id, by cost_type_concept_id during the cohort period"

@pavgra @chrisknoll

**Comment by gowthamrao** [comment]
https://github.com/OHDSI/WebAPI/blob/d28509e7f6e3ee21c9885edaf887bd1a6a434aa4/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql#L10514

Should say "4016 Number of subjects with Drug Exposure by period_id, by drug_concept_id, by drug_type_concept_id during the cohort period"

**Comment by anthonysena** [comment]
Closed via #454 and #462
