### ISSUE TITLE
FYI API standards for - ONC is seeking volunteers for Data Access Framework

### ISSUE THREAD

**Issue by daniellameeker** [OHDSI/WebAPI#45]
This group may wish to consider participating in "Phase 2" of DAF devoted to research frameworks.

http://wiki.siframework.org/DAF+Standards+Harmonization+and+Implementation

**Comment by chrisknoll** [comment]
I'll close this as not an issue, but marked at is a question if anyone would like to add anything to this topic.

@daniellameeker : this might be something to raise awareness on the ohdsi forums:  
http://forums.ohdsi.org.
