### ISSUE TITLE
WebPI Flyway migration error on Oracle database

### ISSUE THREAD

**Issue by Anaxymenes** [OHDSI/WebAPI#466]
Hello all.
I have a little problem with connecting WebAPI to oracle database. After deploy WebAPI.war on tomcat server, I've got a error " Schema "" contains a failed migration to version 1.0.6.0.1 ! ". I also noticed that the oracle migration files contain commands from postgresql. I am asking for help and thank you in advance.

[https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/db/migration/oracle/V1.0.6.0.1__schema-add-analysis_execution_password.sql](url)

When I replaced any postgresql datatypes and commands, like BYTEA datatype, i can manually run sql commands from V1.0.6.0.1__schema-add-analysis_execution_password.sql with success of response, but migrations still doesn't work.

**Comment by chrisknoll** [comment]
> When I replaced any postgresql datatypes and commands, like BYTEA datatype, i can manually run sql commands from V1.0.6.0.1__schema-add-analysis_execution_password.sql with success of response, but migrations still doesn't work.

Hi, @Anaxymenes :  You shouldn't manually run the SQL because then the migration meta doesn't know that the migration happened (and technically, it didn't).  The solution is to create a hotfix that has the corrected migration script in it, and then you can let the application complete the migration normally.

Could you provide the changes to the migration script you needed in order to get the code to execute correctly?

**Comment by Anaxymenes** [comment]
Many thanks for you reply.
When the migration returned me of error, I only checked if a sql commands are correctly.
Yes, i think this code will be good

[V1.0.6.0.1__schema-add-analysis_execution_password.txt](https://github.com/OHDSI/WebAPI/files/2078738/V1.0.6.0.1__schema-add-analysis_execution_password.txt)

**Comment by chrisknoll** [comment]
@Anaxymenes , I've pushed up a change with your suggested changes, except for the following:

Oracle documentation says not to use VARCHAR, so I updated the script to use VARCHAR2:
http://www.differencebetween.info/difference-between-varchar-and-varchar2

Can you test this change by checking out the branch 'oracle-analysis-execution-migration'
found here: https://github.com/OHDSI/WebAPI/tree/oracle-analysis-execution-migration

If you build webAPI from source, just pull down the repo, and switch to the oracle-analysis-execution-migration branch. Then rebuild, and see if the oracle migration is successful.

Thank you!

**Comment by chrisknoll** [comment]
This Oracle migration script has been merged into master, and verified on Oracle XE.
