### ISSUE TITLE
Users and roles import from AD / LDAP

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#506]
Today a user is added into Atlas database only after he / she logins there for the first time. Therefore there is no ability to assign roles to the user in advance. Moreover, the roles assignment can only be done manually even if the user belongs to a certain AD group which could define a set of roles which he / she transitively gets.

Therefore there is a suggestion to add a new page in Atlas: LDAP import screen with the ability to define DN-role mapping and "Import" button, which would scan the AD for not imported users or users with changed roles, provide the change list to admin for approval and do the import from AD. There is going to be "Import users from LDAP / AD" button available at the Configuration page if the LDAP / AD auth was setup, which will navigate an admin to the import page.

As a further improvement a scheduler for the automatic users import can be added.

**Comment by t-abdul-basser** [comment]
@pavgra This would be very helpful.
