### ISSUE TITLE
SQLException w/Cohort Generation in Atlas

### ISSUE THREAD

**Issue by shandy79** [OHDSI/WebAPI#511]
When attempting to use either the "Generate" or "Generate With Features" function for a Cohort in Atlas, I am consistently encountering a SQLException.  I've attached a file containing the stacktrace, as obtained from the cohort_generation_info.fail_message column.  There is not a full trace in the Tomcat log.

I am running Atlas 2.4.2 and WebAPI at commit d5c7ed3 on CentOS 7.5 w/Tomcat 7.0.76 and JDK 1.8.0_171 against SQL Server 2016 SP2.  The OMOP CDM is version 5.2.2, since I wanted to load the ETL-CMS project's latest CMS SynPUK 100K data set.

Any help would be appreciated!  I don't have the full SQL to troubleshoot with, so I think my only recourse is to pull the latest code for the various projects.  Let me know if there are other standard troubleshooting routes I should pursue.

[atlas_cohort_generation_sqlexception.txt](https://github.com/OHDSI/WebAPI/files/2202975/atlas_cohort_generation_sqlexception.txt)

**Comment by chrisknoll** [comment]
Hi, I'm unable to determine the error from your exception attachment (uncategorized sqlException is not spacific).  Can you grab the entire sql in your log, and execute it in a mssql session to see what the specific error is? Or, is there another error in the log about a specific error? Such as 'table already exists' or something like that?

**Comment by shandy79** [comment]
@chrisknoll, as I mentioned in the original post, there is nothing in the Tomcat logs corresponding to this exception.  I'll look into turning up the logging output and see if I can get something more useful.

**Comment by chrisknoll** [comment]
Hi, @shandy79 , that's why I suggested you grab the SQL from the log, and execute it in a sql server session, to see if it uncovered what the actual error is.  From your attachment, it appears that the sql that generated the error is provided, even if the actual sql exception is not given.

**Comment by shandy79** [comment]
I was originally looking only in /var/log/tomcat/, so after figuring out how to use syslog on CentOS to produce the output I was looking for, I was able to grab the full SQL.  I've attached a file with that excerpt.  The error is near line 21, where there is an empty FROM expression in the generated SQL.

[atlas_cohort_generation_sqlexception-full.txt](https://github.com/OHDSI/WebAPI/files/2206069/atlas_cohort_generation_sqlexception-full.txt)

**Comment by chrisknoll** [comment]
Ah, the complete error shows the actual problem: error code [102]; Incorrect syntax near ')'. That was missing from the original log.

This is the part of the query that involves selecting the 'primary events', which, as you point out, has an empty FROM:
```
with primary_events (event_id, person_id, start_date, end_date, op_start_date, op_end_date, visit_occurrence_id) as
(
-- Begin Primary Events
select row_number() over (PARTITION BY P.person_id order by P.start_date) as event_id, P.person_id, P.start_date, P.end_date, op_start_date, op_end_date, cast(P.visit_occurrence_id as bigint) as visit_occurrence_id
FROM
(
select E.person_id, E.start_date, E.end_date, row_number() OVER (PARTITION BY E.person_id ORDER BY E.start_date ASC) ordinal, OP.observation_period_start_date as op_start_date, OP.observation_period_end_date as op_end_date, cast(E.visit_occurrence_id as bigint) as visit_occurrence_id
FROM
(
) E
JOIN OHDSI.observation_period OP on E.person_id = OP.person_id and E.start_date >=  OP.observation_period_start_date and E.start_date <= op.observation_period_end_date
WHERE DATEADD(day,0,OP.OBSERVATION_PERIOD_START_DATE) <= E.START_DATE AND DATEADD(day,0,E.START_DATE) <= OP.OBSERVATION_PERIOD_END_DATE
) P
WHERE P.ordinal = 1
-- End Primary Events
)
```

Which leads me to believe you don't have any initial event criteria in your cohort definition. Would you be able to post a screenshot of your cohort definition, or export the cohort expression JSON to a file and post that here? I think the simple problem is that you've defined an invlaid cohort definition and so the sql query built from it is also invalid.  We're going to be introducing a feature in the 2.5 release of the tools that will give you some diagnostics about a cohort definition, including missing information that is required to generate.

**Comment by shandy79** [comment]
You are correct!  I should have realized that would be an issue.  Feedback from the UI would also be helpful.  I was able to compare to a cohort from a previous data set that generated properly and confirmed that was the only functional difference.  Thanks for your assistance!
