### ISSUE TITLE
Logging of security-related events

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#530]
The application should be able to log security-related events.

## Events to Log
User account management activity:
- Addition and deletion of user accounts
- Changes in security attributes (new roles / roles change / roles assignment-removal for a user)

Access control related events:
- Successful and failed logon / logoff events
- Account lockout events

Changes to the application configuration settings:
- Changes to data sources (new / deleted / altered)
- Startup/stops of application
- Failed database connection attempts

**Comment by chrisknoll** [comment]
Just want to point out, as I know everyone is aware:  take special care of logging sensitive information in the logs.  Logging things like 'Password updated to 'xxxx' for user 'yyy'' is obviously a bad idea, but even just indicating in the log who user 'yyy' was could be sensitive information that could open an attack vector.

**Comment by pavgra** [comment]
@chrisknoll , the proposed design gives us a good level of abstraction so we'll be able to implement multiple configurations in a flexible way:

![image](https://user-images.githubusercontent.com/10010071/44153571-94fc4302-a076-11e8-8343-a6899a864724.png)

**Comment by pavgra** [comment]
Closed by
https://github.com/OHDSI/WebAPI/pull/591
https://github.com/OHDSI/WebAPI/pull/675
https://github.com/OHDSI/WebAPI/pull/680
