### ISSUE TITLE
error in caching?

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/WebAPI#54]
I'm seeing what I think is an error in the way the heracles visualization data is attempting to be cached.  I'm seeing this on our SQL server platform.

Hibernate: insert into heracles_visualization_data (COHORT_DEFINITION_ID, DATA, DRILLDOWN_ID, END_TIME, SOURCE_ID, VISUALIZATION_KEY) values (?, ?, ?, ?, ?, ?)
2015-09-11 23:28:00.011 WARN http-nio-8080-exec-7 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - SQL Error: 273, SQLState: S0001
2015-09-11 23:28:00.011 ERROR http-nio-8080-exec-7 org.hibernate.engine.jdbc.spi.SqlExceptionHelper -  - Cannot insert an explicit value into a timestamp column. Use INSERT with a column list to exclude the timestamp column, or insert a DEFAULT into the timestamp column.
2015-09-11 23:28:00.011 DEBUG http-nio-8080-exec-7 org.springframework.orm.jpa.JpaTransactionManager -  - Initiating transaction rollback

**Comment by cahilton** [comment]
This works ok on Oracle and Postgres as is. So, we need to make sure those still work.

You can try changing these:
https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/cohortresults/CohortResultsAnalysisRunner.java#L1451
https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/cohortresults/CohortResultsAnalysisRunner.java#L1411

But we still need to make sure the date defaults if we're not setting it.

**Comment by chrisknoll** [comment]
Is this inserting into PDW or MSSQL? That sounds like an error from inserting into PDW.

**Comment by chen-regen** [comment]
The Date is set and is being inserted right into Oracle from my test:
2015-09-18 11:03:59.389 DEBUG http-nio-8080-exec-5 org.springframework.orm.jpa.JpaTransactionManager -  - Committing JPA transaction on EntityManager [org.hibernate.jpa.internal.EntityManagerImpl@417bb69e]
Hibernate: insert into heracles_visualization_data (COHORT_DEFINITION_ID, DATA, DRILLDOWN_ID, END_TIME, SOURCE_ID, VISUALIZATION_KEY, ID) values (?, ?, ?, ?, ?, ?, ?)

Inserted timestamps:
18-SEP-15 11.37.29.021000000 AM
18-SEP-15 11.03.59.186000000 AM

I am wondering if this is a problem with inserting java.util.Date into MSSQL timestamp column. I can try change to java.sql.Timestamp.

Charity, do we have a way to reproduce/test this in RI for MSSQL?

**Comment by cahilton** [comment]
No, we don't have a way. We can hit the synpuf postgres instance, but MS SQL is a challenge for us.

That's traditionally been a problem for these kinds of issues.

**Comment by chen-regen** [comment]
Hmm... I'll try change that to Timestamp and test again to see if it works correctly for Oracle first.

**Comment by chen-regen** [comment]
Charity, I have created a JIRA for this: OHDSI-53. I have tested the changes and it worked for Oracle. I documented details in the JIRA. I will create a OHDSI-53 and commit the code. I still don't know what we can do with MSSQL though.

**Comment by fdefalco** [comment]
There is a public MSSQL instance that @leeevans has as part of the OHDSI infrastructure.  You can work with him to get access to it for testing purposes if that helps.

**Comment by chen-regen** [comment]
Hi @leeevans , could you please send me the log-on info for the public MSSQL server? Or can you give me your email address so we can discuss in emails?

**Comment by leeevans** [comment]
Hi @chen-regen, ask Jon or Charity, they can give you my email address. I needed to do some WebAPI  flyway migration testing with Postgresql and Oracle last week so I took some time to setup a developer OHDSI cloud image that has all three DBMSs and Netbeans configured to debug WebAPI against each one.  I still need to load test data into MSSQL but it should be ready tomorrow if you want to use it. Drop me an email and you can have access to it for a few days.

**Comment by chrisknoll** [comment]
@mav704 identified the fix in #69 and I'll have a fix pushed for this shortly.

**Comment by chrisknoll** [comment]
This is fixed for MSSQL, and redeploying will apply the fixes to the database automatically via flyway.
