### ISSUE TITLE
Add concept_hierarchy optimizations to heracles treemap queries

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#563]
As part of one of the prior releases of WebAPI, the DataSources modules leveraged the concept_hierarchy table that was created as part of the Achilles processing.  This same table can be leveraged for Heracles reports.

I suggest adding the concept_hierarchy to the results DDL service, as well as the initialization script.  People who have WebAPI set up who generate the Achilles statistics into the results schema will disable he option in Achilles to create the concept_hierarchy table.

**Comment by gowthamrao** [comment]
concept_hierarchy . Is this a calculated reference table derived from concept_ancestor and concept_relationship?

**Comment by aklochkova** [comment]
`concept_hierarchy` table is already in results scheme

**Comment by anthonysena** [comment]
Noting this was closed by #564
