### ISSUE TITLE
CAS authentication

### ISSUE THREAD

**Issue by chen-regen** [OHDSI/WebAPI#571]
Anthony @anthonysena suggested that I should start asking the question here. With all the enhanced OHDSI security features, do we have CAS authentication integration? I see buji-pac4j jar in the current pom, but don't see pac4j-cas. Thanks!

**Comment by chen-regen** [comment]
Following changes need to be made for getting CAS integration into WebAPI:

- pac4j-cas needs to be added into pom as a dependency

- set correct security.oauth.callback.ui and security.oauth.callback.api in the pom

- AtlasSecurity: add CasClient with CasConfiguration (set corresponding attributes, like loginUrl, etc.), add casClient into existing cfg, create another SecurityFilter with cfg and add it into filters

In Atlas config, add another authentication method, for example:
`
{
  "name": "CAS",
  "url": "user/oauth/cas",
  "ajax": false,
  "icon": "fa fa-database"
}
`
I tested those changes. Atlas successfully redirects the page to our CAS instance (it's duo factor authentication) and redirects back to Atlas home page with a valid casticket set. However I need some info as of how Atlas handles token/ticket setting in a session after authentication by third party. Right now, what I am experiencing is the application stays at "unauthenticated" stage, although CAS has authenticated the user and a casticket has been validated.

**Comment by chrisknoll** [comment]
tagging @pavgra : he has experience in linking the different authentication schemes together, and would hopefully have recommendations about how the appropriate security headers should be specified.

**Comment by anthonysena** [comment]
Thanks @chen-regen for the update here - if you have a branch with changes for WebAPI/Atlas, feel free to push them up and we can take a look either as part of a pull request or on the branch alone. I think the changes you've detailed make good sense - not sure if @pavgra or @gklebanov have any feedback based on their experience.

As for how Atlas handles token/ticket setting in a session, I think you'll want to take a look at this module:

https://github.com/OHDSI/Atlas/blob/master/js/modules/WebAPIProvider/AuthAPI.js

**Comment by chen-regen** [comment]
Hi Anthony @anthonysena and Chris @chrisknoll thank you for the feedback! I will create a branch when we get everything work against out CAS. I haven't heard anything from Pavel or anybody who re-wrote the security package. Can you guys ping them or let them provide documentation? Thank you!

**Comment by pavgra** [comment]
Hi @chen-regen ,

I haven't explored the CAS authentication protocol, but making an assumption that it works similarly to OAuth, I believe the following is required:
- two filter paths:
  - the first one handles initial auth request and provides the redirect info (redirects a user to CAS)
  - the second one is the path to which the user is redirected by CAS after successful auth, there you grab required info from the request and issue `AuthenticationToken`
- realm which validates `AuthenticationToken` (does authentication) and issues `SimpleAuthenticationInfo` or throws `AuthenticationException`

E.g. you can get a look at `JdbcAuthFilter` and `JdbcAuthRealm`. The only diff from a general perspective is that you'll need one more filter to redirect user to CAS

**Comment by chen-regen** [comment]
@pavgra @anthonysena @chrisknoll  is OAuth still working in master branch? I tried with facebook and got following error in Atlas after facebook logged me in: 

routes.js?_=u3ok29:19 Uncaught ReferenceError: authApi is not defined
    at routes.js?_=u3ok29:19
    at Object.execCb (require.js:29)
    at Z.check (require.js:18)
    at Z.enable (require.js:23)
    at Z.init (require.js:17)
    at require.js:26

Also can you guys advise on the configuration changes regarding OAuth? Is this documentation up to date: http://www.ohdsi.org/web/wiki/doku.php?id=development:security ? I noticed <security.enabled> is gone, and there are new properties like <security.provider> and <security.cors.enabled>.

**Comment by chen-regen** [comment]
Some updates: with Anthony's help, the error is fixed in Atlas: https://github.com/OHDSI/Atlas/issues/896

**Comment by chen-regen** [comment]
Hi Anthony @anthonysena , FYI - I just pushed CAS authenticaton stuff into WebAPI cas_authn branch. One new filter class CasHandleFilter for handling CAS callback. And changes in following files/classes:
- pom.xml: add pac4j-cas dependency and CAS properties
- application.properties: add CAS properties
- AtlasRegularSecurity: add CAS configuration/client/filgers/properties (We are using Pac4jRealm in WebAPI, so there's not need to add add that realm again)
- UpdateAccessTokenFilter: handle get CAS profile through Pac4jPrincipal

I will create a pull request soon. Just wanted to give you a heads up first.

**Comment by chen-regen** [comment]
This has been merged into master. Thank you for all your help @anthonysena @pavgra @chrisknoll
