### ISSUE TITLE
DDLService constraints

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#583]
Hi @chrisknoll:

I don't think PDW can support the constraints in the DDL files for heracles_results and heracles_results_dist:

`An expression cannot be used with a default constraint. Specify only constants for a default constraint. [SQL State=S0001, DB Errorcode=104338]
`
I can remove them manually, but I was wondering if those constraints can be optional based on dialect.

Thanks,
Ajit

**Comment by chrisknoll** [comment]
Hi, good catch, yes, we've disabled constraints  and indexes for specific dialects in sql render.

Basically we translate the constraint statement into a ```-- dialect does not support constraints``` message.  If it's a constraint that's inline, that's a bit trickier, but we could recommend to people that you do not inline create + constraint  commands into single statements.

**Comment by alondhe** [comment]
Not sure I follow. So then the DDL Service is supposed to already disable these constraints if using PDW?

When I hit /WebAPI/ddl/results?schema=scratch&dialect=pdw, the constraints are present.

**Comment by chrisknoll** [comment]
Sorry, i meant to say 'disable indexes', not just constraints. The constraint part would be the thing that needs to be added to the rules, and the examplar can be how we handled indexes.
