### ISSUE TITLE
Restrict official support of RDBMS of WebAPI to Postgresql

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#585]
For WebAPI 3.0, I'd like to propose that we drop official support for mssql and oracle in favor of single support for PostgreSQL (we can decide a minimum version possibly 9.6 or 10).

### Important Note!
This is not a proposal to restrict CDM platforms to only postgresql.  SQL Render has already proven successful in supporting cross platform QUERIES and simple DDL (creating temp tables with specific data types).  That is not the point of this Issue.  SQL Render can not handle the use-cases necessary for the implementation of WebAPI.

### Background

The challenges have been that each platform requires a certain amount of re-writing in order to implement the proper functionality that WebAPI requires, but using platform-specific rules.  

When dealing with foreign keys, sequences, unique constraints, each platform has their own twist on how you create them, rules around modifying them, etc.

Instead, we can officially support postgresql for each release, but leave it to independent contributors to support other platforms of choice.  We do not need to drop the multi-platform capabilities of flyway (so that people who are forced to use oracle have an option), but I am proposing that those people who need this functionality provide the implementation themselves, and contribute back to the source.

**Comment by pavgra** [comment]
@chrisknoll, fully support for the proposal.

**Comment by gklebanov** [comment]
I am assuming you are talking about the database where ATLAS artifacts are being stored (a.k.a. "OHDSI schema"). In this case - yes, total sense.

**Comment by t-abdul-basser** [comment]
Fully support this proposal @chrisknoll. It is long past time that we bundle our own postgres in a docker container (say, as part of BroadSea) and relieved installers of having to worry about the WebAPI DB at all.

**Comment by pavgra** [comment]
Linking to https://github.com/OHDSI/WebAPI/issues/533

**Comment by yradsmikham** [comment]
Is there an update to this issue? Would like to understand the roadmap since this could impact how we plan on using the WebAPI and other OHDSI services.

**Comment by chrisknoll** [comment]
As of 2.8, the only platform supported is Postgres for WebAPI.  We, of course, can accept Pull Requests to add migration scripts for other platforms.
