### ISSUE TITLE
new function to support updating WebAPI test functions for multi-homed WebAPI

### ISSUE THREAD

**Issue by leeevans** [OHDSI/WebAPI#59]
The current WebAPI tests have an endpoint format (e.g. ${baseUri}/vocabulary) which no longer works for mult-homed WebAPI causing the tests to fail. The jenkins CI build job is using skiptests as a workaround.

A source/sourceDaimon function is needed that can be called by the WebAPI test functions to consistently resolve to a single source id for testing. The returned source id can then be included in the test endpoint. (e.g. $(baseUri) + "/" +  sourceID + "/vocabulary").

One approach could be for the new function to return the source id of the daimon with the highest priority, for a given daimon type. Note. In the case of two daimons of the same type with the same assigned priority, the single source id that is returned by this function must be deterministic so that tests are consistently reproducible,

**Comment by leeevans** [comment]
changed issue title to be more specific that this is a request for a new function

**Comment by anthonysena** [comment]
Closing this in favor of #239 which also aims to look at the testing approach for WebAPI.
