### ISSUE TITLE
Missing db/migrations for attribute mode_id of ddl/results/cohort_*

### ISSUE THREAD

**Issue by limadm** [OHDSI/WebAPI#590]
At v2.5.0 (2cda7393), `ddl/results/cohort_*` tables have a new attribute:
`mode_id INT NOT NULL DEFAULT 0;`
This atttribute is not present in `db/migration/*`, causing errors when generating cohorts.

**Comment by chrisknoll** [comment]
db/migration does not touch the webAPI schema. You need to manage the results schema manually.

This change was noted in 2.5.0 release notes under the 'Migration' section:
https://github.com/OHDSI/WebAPI/releases

**Comment by limadm** [comment]
Hello!
My bad, I git-pulled the repository and didn't see the release notes.
There is
`CREATE TABLE ${ohdsiSchema}.cohort_inclusion_result`
(and other result tables) in
`db/migration/postgresql/V1.0.2.0__cohort_feasiblity.sql`
so at first I thought that adding these `ALTER TABLES` in a subsequent migration would be reasonable to ease environment setup while they are still there.

**Comment by chrisknoll** [comment]
> PS: I did a small change in the exception reporting in order to see what was causing this.
> In GenerationJobExecutionListener:85 instead of StringUtils.left(exceptionMessage, 2000), I used StringUtils.abbreviateMiddle(exceptionMessage, "... [truncated] ...", 2000).
> 

That would make an excellent pull request.

Re: the legacy tables in webAPI, yes, it's confusing, we'd like to drop it, but someone may actually be using those so we need to give clear warning before we do that (most likely for a 3.0 release)
