### ISSUE TITLE
For Postgres sources, use OpenSourceSubProtocolOverride

### ISSUE THREAD

**Issue by alondhe** [OHDSI/WebAPI#592]
As discussed here https://github.com/OHDSI/Broadsea/issues/11 (shoutout to @chrisknoll for helping to solve it), when using Postgres sources, the Redshift driver may try to intercept a Postgres connection, resulting in Redshift errors.

We should document this:

If using a Postgres source, append this to your postgresql JDBC url:
`?OpenSourceSubProtocolOverride=true`

**Comment by anthonysena** [comment]
Noting this for #686

**Comment by anthonysena** [comment]
Wiki updated to reflect this information.
