### ISSUE TITLE
Modularize WebAPI

### ISSUE THREAD

**Issue by chen-regen** [OHDSI/WebAPI#594]
Per Anthony @anthonysena , I am filing this issue to open discussion of "modularize WebAPI". Right now, WebAPI is a huge war. We would like to see it separated into different modules so that every module would be easier built/maintained (each module should be built by mvn independently). For example, we can make the main pom as the parent pom and define the modules like:
```
<modules>
        <module>model</module>
        <module>service</module>
        <module>security</module>
        <module>util</module>
        <module>common</module>
......
</modules>
```
It can be more as WebAPI grows. And we need to discuss existing packages' destination.

**Comment by pavgra** [comment]
@chen-regen / @anthonysena , I'd suggest to post the suggestion in https://github.com/OHDSI/WebAPI/issues/533 and close the issue so that we can track all refactoring-related things in one place.
