### ISSUE TITLE
Update to PrintFriendly for Cohorts

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/WebAPI#617]
We would like to be able to leverage the print friendly cohort description from places outside of ATLAS but we think that will require some rework in how the print friendly is generated.

Additional we should use the opportunity to revisit some of the language and presentation of the cohort description. 

Tagging @anthonysena 

THIS IS A POST SYMPOSIUM ITEM IGNORE ME!

**Comment by anthonysena** [comment]
Tagging @chrisknoll so we can discuss this since this is likely an item we can generalize to other entities in the stack that require representations in human readable format.
