### ISSUE TITLE
There is already an object named '#temp_dates' in the database

### ISSUE THREAD

**Issue by mav7014** [OHDSI/WebAPI#62]
In our environment, executing multiple visualization packs in Heracles (e.g. person and observation) results in batch job failure and WebAPI reports the exception and stack trace provided below. We are using MSSQL.

    2015-10-08 14:32:11.756 ERROR taskExecutor-1 org.springframework.batch.core.step.AbstractStep -  - Encountered an error executing step cohortAnalysisStep in job cohortAnalysisJob
    org.springframework.jdbc.UncategorizedSQLException: StatementCallback; uncategorized SQLException for SQL[

    DELETE FROM my_omop.dbo.HERACLES_results
    WHERE cohort_definition_id IN (12) AND analysis_id IN (116, 117, 0, 1, 2, 3, 4, 5, 200, 201, 202, 203, 204, 206, 211);
    DELETE FROM my_omop.dbo.HERACLES_results_dist
    WHERE cohort_definition_id IN (12) AND analysis_id IN (116, 117, 0, 1, 2, 3, 4, 5, 200, 201, 202,
                                                           203, 204, 206, 211);
    IF OBJECT_ID('tempdb..#HERACLES_cohort', 'U') IS NOT NULL
        DROP TABLE #HERACLES_cohort;

    SELECT
      subject_id,
      cohort_definition_id,
      cohort_start_date,
      cohort_end_date
    INTO #HERACLES_cohort
    FROM my_omop.dbo.cohort
    WHERE cohort_definition_id IN (12);
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
      SELECT
        c1.cohort_definition_id,
        0                             AS analysis_id,
        'cumc'                        AS stratum_1,
        COUNT_BIG(DISTINCT person_id) AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
      GROUP BY c1.cohort_definition_id;
    INSERT INTO my_omop.dbo.HERACLES_results_dist (cohort_definition_id, analysis_id, stratum_1, count_value)
      SELECT
        c1.cohort_definition_id,
        0                             AS analysis_id,
        'cumc'                        AS stratum_1,
        COUNT_BIG(DISTINCT person_id) AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
      GROUP BY c1.cohort_definition_id;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, count_value)
      SELECT
        c1.cohort_definition_id,
        1                             AS analysis_id,
        COUNT_BIG(DISTINCT person_id) AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
      GROUP BY c1.cohort_definition_id;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
      SELECT
        c1.cohort_definition_id,
        2                             AS analysis_id,
        gender_concept_id             AS stratum_1,
        COUNT_BIG(DISTINCT person_id) AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
      GROUP BY c1.cohort_definition_id, GENDER_CONCEPT_ID;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
      SELECT
        c1.cohort_definition_id,
        3                             AS analysis_id,
        year_of_birth                 AS stratum_1,
        COUNT_BIG(DISTINCT person_id) AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
      GROUP BY c1.cohort_definition_id, YEAR_OF_BIRTH;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
      SELECT
        c1.cohort_definition_id,
        4                             AS analysis_id,
        RACE_CONCEPT_ID               AS stratum_1,
        COUNT_BIG(DISTINCT person_id) AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
      GROUP BY c1.cohort_definition_id, RACE_CONCEPT_ID;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
      SELECT
        c1.cohort_definition_id,
        5                             AS analysis_id,
        ETHNICITY_CONCEPT_ID          AS stratum_1,
        COUNT_BIG(DISTINCT person_id) AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
      GROUP BY c1.cohort_definition_id, ETHNICITY_CONCEPT_ID;
    IF OBJECT_ID('temp_dates', 'U') IS NOT NULL --This should only do something in Oracle
        DROP TABLE temp_dates;

    SELECT DISTINCT YEAR(observation_period_start_date) AS obs_year
    INTO
        #temp_dates
    FROM my_omop.dbo.PERSON p1
      INNER JOIN (SELECT
                    subject_id,
                    cohort_definition_id,
                    cohort_start_date,
                    cohort_end_date
                  FROM #HERACLES_cohort) c1
        ON p1.person_id = c1.subject_id
      INNER JOIN
      my_omop.dbo.observation_period op1
        ON p1.person_id = op1.person_id;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, stratum_2, stratum_3, count_value)
      SELECT
        c1.cohort_definition_id,
        116                                          AS analysis_id,
        t1.obs_year                                  AS stratum_1,
        p1.gender_concept_id                         AS stratum_2,
        floor((t1.obs_year - p1.year_of_birth) / 10) AS stratum_3,
        COUNT_BIG(DISTINCT p1.PERSON_ID)             AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
        INNER JOIN
        my_omop.dbo.observation_period op1
          ON p1.person_id = op1.person_id
        ,
        #temp_dates t1
      WHERE year(op1.OBSERVATION_PERIOD_START_DATE) <= t1.obs_year
            AND year(op1.OBSERVATION_PERIOD_END_DATE) >= t1.obs_year
      GROUP BY c1.cohort_definition_id,
        t1.obs_year,
        p1.gender_concept_id,
        floor((t1.obs_year - p1.year_of_birth) / 10);
    TRUNCATE TABLE #temp_dates;
    DROP TABLE #temp_dates;
    IF OBJECT_ID('temp_dates', 'U') IS NOT NULL --This should only do something in Oracle
        DROP TABLE temp_dates;

    SELECT DISTINCT YEAR(observation_period_start_date) * 100 + MONTH(observation_period_start_date) AS obs_month
    INTO
        #temp_dates
    FROM my_omop.dbo.PERSON p1
      INNER JOIN (SELECT
                    subject_id,
                    cohort_definition_id,
                    cohort_start_date,
                    cohort_end_date
                  FROM #HERACLES_cohort) c1
        ON p1.person_id = c1.subject_id
      INNER JOIN
      my_omop.dbo.observation_period op1
        ON p1.person_id = op1.person_id;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
      SELECT
        c1.cohort_definition_id,
        117                               AS analysis_id,
        t1.obs_month                      AS stratum_1,
        COUNT_BIG(DISTINCT op1.PERSON_ID) AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
        INNER JOIN
        my_omop.dbo.observation_period op1
          ON p1.person_id = op1.person_id
        ,
        #temp_dates t1
      WHERE YEAR(observation_period_start_date) * 100 + MONTH(observation_period_start_date) <= t1.obs_month
            AND YEAR(observation_period_end_date) * 100 + MONTH(observation_period_end_date) >= t1.obs_month
      GROUP BY c1.cohort_definition_id, t1.obs_month;
    TRUNCATE TABLE #temp_dates;
    DROP TABLE #temp_dates;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
      SELECT
        c1.cohort_definition_id,
        200                               AS analysis_id,
        --
        --
        vo1.visit_CONCEPT_ID              AS stratum_1,
        --
        COUNT_BIG(DISTINCT vo1.PERSON_ID) AS count_value
      FROM
        my_omop.dbo.visit_occurrence vo1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON vo1.person_id = c1.subject_id
      --
      GROUP BY c1.cohort_definition_id,
        --
        --
        vo1.visit_CONCEPT_ID
    --
    ;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, count_value)
      SELECT
        c1.cohort_definition_id,
        201                      AS analysis_id,
        --
        --
        vo1.visit_CONCEPT_ID     AS stratum_1,
        --
        COUNT_BIG(vo1.PERSON_ID) AS count_value
      FROM
        my_omop.dbo.visit_occurrence vo1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON vo1.person_id = c1.subject_id
      --
      GROUP BY c1.cohort_definition_id,
        --
        --
        vo1.visit_CONCEPT_ID
    --
    ;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, stratum_2, count_value)
      SELECT
        c1.cohort_definition_id,
        202                                                    AS analysis_id,
        --
        --
        vo1.visit_CONCEPT_ID                                   AS stratum_1,
        --
        YEAR(visit_start_date) * 100 + month(visit_start_date) AS stratum_2,
        COUNT_BIG(DISTINCT PERSON_ID)                          AS count_value
      FROM
        my_omop.dbo.visit_occurrence vo1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON vo1.person_id = c1.subject_id
      --
      GROUP BY c1.cohort_definition_id,
        --
        --
        vo1.visit_CONCEPT_ID,
        --
        YEAR(visit_start_date) * 100 + month(visit_start_date);
    INSERT INTO my_omop.dbo.HERACLES_results_dist (cohort_definition_id, analysis_id, count_value, min_value, max_value, avg_value, stdev_value, median_value, p10_value, p25_value, p75_value, p90_value)
      SELECT
        cohort_definition_id,
        203                    AS analysis_id,
        COUNT_BIG(count_value) AS count_value,
        min(count_value)       AS min_value,
        max(count_value)       AS max_value,
        avg(1.0 * count_value) AS avg_value,
        stdev(count_value)     AS stdev_value,
        max(CASE WHEN p1 <= 0.50
          THEN count_value
            ELSE -9999 END)    AS median_value,
        max(CASE WHEN p1 <= 0.10
          THEN count_value
            ELSE -9999 END)    AS p10_value,
        max(CASE WHEN p1 <= 0.25
          THEN count_value
            ELSE -9999 END)    AS p25_value,
        max(CASE WHEN p1 <= 0.75
          THEN count_value
            ELSE -9999 END)    AS p75_value,
        max(CASE WHEN p1 <= 0.90
          THEN count_value
            ELSE -9999 END)    AS p90_value
      FROM
        (
          SELECT
            cohort_definition_id,
            num_visits                                                               AS count_value,
            1.0 * (row_number()
            OVER (PARTITION BY cohort_definition_id
              ORDER BY num_visits)) / (COUNT_BIG(num_visits)
                                       OVER (PARTITION BY cohort_definition_id) + 1) AS p1
          FROM
            (
              SELECT
                c1.cohort_definition_id,
                vo1.person_id,
                --
                --
                COUNT_BIG(DISTINCT vo1.visit_concept_id) AS num_visits
              --
              FROM
                my_omop.dbo.visit_occurrence vo1
                INNER JOIN (SELECT
                              subject_id,
                              cohort_definition_id,
                              cohort_start_date,
                              cohort_end_date
                            FROM #HERACLES_cohort) c1
                  ON vo1.person_id = c1.subject_id
              --
              GROUP BY c1.cohort_definition_id, vo1.person_id
            ) t0
        ) t1
      GROUP BY cohort_definition_id;
    INSERT INTO my_omop.dbo.HERACLES_results (cohort_definition_id, analysis_id, stratum_1, stratum_2, stratum_3, stratum_4, count_value)
      SELECT
        c1.cohort_definition_id,
        204                                                     AS analysis_id,
        --
        --
        vo1.visit_CONCEPT_ID                                    AS stratum_1,
        --
        YEAR(visit_start_date)                                  AS stratum_2,
        p1.gender_concept_id                                    AS stratum_3,
        floor((year(visit_start_date) - p1.year_of_birth) / 10) AS stratum_4,
        COUNT_BIG(DISTINCT p1.PERSON_ID)                        AS count_value
      FROM my_omop.dbo.PERSON p1
        INNER JOIN (SELECT
                      subject_id,
                      cohort_definition_id,
                      cohort_start_date,
                      cohort_end_date
                    FROM #HERACLES_cohort) c1
          ON p1.person_id = c1.subject_id
        INNER JOIN
        my_omop.dbo.visit_occurrence vo1
          ON p1.person_id = vo1.person_id
      --
      GROUP BY c1.cohort_definition_id,
        --
        --
        vo1.visit_CONCEPT_ID,
        --
        YEAR(visit_start_date),
        p1.gender_concept_id,
        floor((year(visit_start_date) - p1.year_of_birth) / 10);
    INSERT INTO my_omop.dbo.HERACLES_results_dist (cohort_definition_id, analysis_id, stratum_1, stratum_2, count_value, min_value, max_value, avg_value, stdev_value, median_value, p10_value, p25_value, p75_value, p90_value)
      SELECT
        cohort_definition_id,
        206                    AS analysis_id,
        visit_CONCEPT_ID       AS stratum_1,
        gender_concept_id      AS stratum_2,
        COUNT_BIG(count_value) AS count_value,
        min(count_value)       AS min_value,
        max(count_value)       AS max_value,
        avg(1.0 * count_value) AS avg_value,
        stdev(count_value)     AS stdev_value,
        max(CASE WHEN p1 <= 0.50
          THEN count_value
            ELSE -9999 END)    AS median_value,
        max(CASE WHEN p1 <= 0.10
          THEN count_value
            ELSE -9999 END)    AS p10_value,
        max(CASE WHEN p1 <= 0.25
          THEN count_value
            ELSE -9999 END)    AS p25_value,
        max(CASE WHEN p1 <= 0.75
          THEN count_value
            ELSE -9999 END)    AS p75_value,
        max(CASE WHEN p1 <= 0.90
          THEN count_value
            ELSE -9999 END)    AS p90_value
      FROM
        (
          SELECT
            c1.cohort_definition_id,
            --
            --
            vo1.visit_CONCEPT_ID,
            --
            p1.gender_concept_id,
            vo1.visit_start_year - p1.year_of_birth                      AS count_value,
            1.0 * (row_number()
            OVER (PARTITION BY c1.cohort_definition_id, vo1.visit_CONCEPT_ID, p1.gender_concept_id
              ORDER BY vo1.visit_start_year - p1.year_of_birth)) / (COUNT_BIG(vo1.visit_start_year - p1.year_of_birth)
                                                                    OVER (PARTITION BY c1.cohort_definition_id, vo1.visit_CONCEPT_ID, p1.gender_concept_id)
                                                                    + 1) AS p1
          FROM my_omop.dbo.PERSON p1
            INNER JOIN (SELECT
                          subject_id,
                          cohort_definition_id,
                          cohort_start_date,
                          cohort_end_date
                        FROM #HERACLES_cohort) c1
              ON p1.person_id = c1.subject_id
            INNER JOIN
            (SELECT
               vo0.person_id,
               --
               --
               vo0.visit_CONCEPT_ID,
               --
               min(year(vo0.visit_start_date)) AS visit_start_year
             FROM my_omop.dbo.visit_occurrence vo0
               INNER JOIN (SELECT
                             subject_id,
                             cohort_definition_id,
                             cohort_start_date,
                             cohort_end_date
                           FROM #HERACLES_cohort) c1
                 ON vo0.person_id = c1.subject_id
             --
             GROUP BY person_id,
               --
               --
               vo0.visit_CONCEPT_ID
              --place_of_service_concept_id
            ) vo1
              ON p1.person_id = vo1.person_id
        ) t1
      GROUP BY cohort_definition_id,
        visit_CONCEPT_ID,
        gender_concept_id;
    INSERT INTO my_omop.dbo.HERACLES_results_dist (cohort_definition_id, analysis_id, stratum_1, count_value, min_value, max_value, avg_value, stdev_value, median_value, p10_value, p25_value, p75_value, p90_value)
      SELECT
        cohort_definition_id,
        211                    AS analysis_id,
        --
        --
        visit_CONCEPT_ID
          --
                               AS stratum_1,
        COUNT_BIG(count_value) AS count_value,
        min(count_value)       AS min_value,
        max(count_value)       AS max_value,
        avg(1.0 * count_value) AS avg_value,
        stdev(count_value)     AS stdev_value,
        max(CASE WHEN p1 <= 0.50
          THEN count_value
            ELSE -9999 END)    AS median_value,
        max(CASE WHEN p1 <= 0.10
          THEN count_value
            ELSE -9999 END)    AS p10_value,
        max(CASE WHEN p1 <= 0.25
          THEN count_value
            ELSE -9999 END)    AS p25_value,
        max(CASE WHEN p1 <= 0.75
          THEN count_value
            ELSE -9999 END)    AS p75_value,
        max(CASE WHEN p1 <= 0.90
          THEN count_value
            ELSE -9999 END)    AS p90_value
      FROM
        (
          SELECT
            c1.cohort_definition_id,
            --
            --
            vo1.visit_CONCEPT_ID,
            --
            datediff(DD, visit_start_date, visit_end_date)                          AS count_value,
            1.0 * (row_number()
            OVER (PARTITION BY c1.cohort_definition_id, vo1.visit_CONCEPT_ID
              ORDER BY datediff(DD, visit_start_date, visit_end_date))) /
            (COUNT_BIG(datediff(DD, visit_start_date, visit_end_date))
             OVER (PARTITION BY c1.cohort_definition_id, vo1.visit_CONCEPT_ID) + 1) AS p1
          FROM my_omop.dbo.visit_occurrence vo1
            INNER JOIN (SELECT
                          subject_id,
                          cohort_definition_id,
                          cohort_start_date,
                          cohort_end_date
                        FROM #HERACLES_cohort) c1
              ON vo1.person_id = c1.subject_id
          --
        ) t1
      GROUP BY cohort_definition_id,
        --
        --
        visit_CONCEPT_ID
    --
    ;
    TRUNCATE TABLE #HERACLES_cohort;
    DROP TABLE #HERACLES_cohort;
    DELETE FROM my_omop.dbo.HERACLES_results
    WHERE count_value <= 10;
    DELETE FROM my_omop.dbo.HERACLES_results_dist
    WHERE count_value <= 10

    ]; SQL state [S0001]; error code [2714]; There is already an object named '#temp_dates' in the database.; nested exception is java.sql.BatchUpdateException: There is already an object named '#temp_dates' in the database.
            at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:84)
            at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
            at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
            at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:416)
            at org.springframework.jdbc.core.JdbcTemplate.batchUpdate(JdbcTemplate.java:611)
            at org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet$1.doInTransaction(CohortAnalysisTasklet.java:61)
            at org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet$1.doInTransaction(CohortAnalysisTasklet.java:44)
            at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
            at org.ohdsi.webapi.cohortanalysis.CohortAnalysisTasklet.execute(CohortAnalysisTasklet.java:44)
            at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:406)
            at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:330)
            at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
            at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
            at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
            at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
            at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
            at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
            at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
            at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:198)
            at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
            at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:386)
            at org.springframework.batch.core.job.SimpleJob.doExecute(SimpleJob.java:135)
            at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:304)
            at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:135)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
            at java.lang.Thread.run(Thread.java:745)
    Caused by: java.sql.BatchUpdateException: There is already an object named '#temp_dates' in the database.
            at net.sourceforge.jtds.jdbc.JtdsStatement.executeBatch(JtdsStatement.java:1069)
            at org.springframework.jdbc.core.JdbcTemplate$1BatchUpdateStatementCallback.doInStatement(JdbcTemplate.java:572)
            at org.springframework.jdbc.core.JdbcTemplate$1BatchUpdateStatementCallback.doInStatement(JdbcTemplate.java:559)
            at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:405)
            ... 23 more

**Comment by mav7014** [comment]
I noticed that multiple analyses are using the same name `#temp_dates` for temp tables. As a quick fix, I changed the name within each analysis. It seems to me to work- does this break anything?

**Comment by pbr6cornell** [comment]
In the code, the temp tables should be getting dropped after each use,
before they are recreated.   the drops are honored if you are running
through the app.  however, if you are running from sql server IDE, you may
be getting the error, unless you put a 'go' statement in between the
segments.  this is not a fix for the script, which is tested to work in sql
server, but may be something to test if you are running local.

**Comment by fdefalco** [comment]
I would need @cahilton or @alexfranken to weigh in on if changing that name in the script would break any of the heracles analyses.  It is odd that this issue is occurring since it is my understanding that the scope of the #temp tables on MSSQL is limited to the current connection.  Can you provide a few additional details about your environment including the version of MSSQL?

**Comment by cahilton** [comment]
?


Charity Hilton
Systems Engineer
Regenstrief Institute, Inc.<https://www.exchange.iu.edu/owa/redir.aspx?C=QpN1M_FrLkCMdQU7vhG1XOmSJbv_g88Iohbv4VNXWD3HztRi34vHhNPYC7LdSs-qadvCWGUGeTk.&URL=http%3a%2f%2fwww.regenstrief.org%2f>

cahilton@regenstrief.org<https://www.exchange.iu.edu/owa/redir.aspx?C=QpN1M_FrLkCMdQU7vhG1XOmSJbv_g88Iohbv4VNXWD3HztRi34vHhNPYC7LdSs-qadvCWGUGeTk.&URL=mailto%3acahilton%40regenstrief.org>

Confidentiality Notice:
The contents of this message and any files transmitted with it may contain confidential and/or privileged information and are intended solely for the use of the named addressee(s). Additionally, the information contained herein may have been disclosed to you from medical records with confidentiality protected by federal and state laws. Federal regulations and State laws prohibit you from making further disclosure of such information without the specific written consent of the person to whom the information pertains or as otherwise permitted by such regulations. A general authorization for the release of medical or other information is not sufficient for this purpose. If you have received this message in error, please notify the sender by return e-mail and delete the original message. Any retention, disclosure, copying, distribution or use of this information by anyone other than the intended recipient is strictly prohibited.
________________________________

**Comment by cahilton** [comment]
I would defer to you guys (Frank and Patrick), but the file should run fine in the app, however, if you're running command line, they'll be some tweaks you'll have to make.

I wouldn't think these would break the application, but couldn't say for sure without testing.

**Comment by mvelez1984** [comment]
@pbr6cornell @cahilton This is from WebAPI, but thanks for the GO tip.

@fdefalco We use SQL Server 2012 Enterprise; JDK 1.8; jTDS JDBC driver 1.3.1.

Does this output suggest that the SQL blocks are not being split properly? Thanks OHDSI for the responsiveness.

**Comment by chrisknoll** [comment]
Yes, in that SQL you sent us, it looks like multiple statements are included in 1 sql query. But this 1 block of SQL should be split by the ';' and then executed in batch (using the Java batch execute function).

That would explain why the parser things that you are trying to create a table that already exists.

**Comment by mav7014** [comment]
We've also been seeing the seemingly related exception below logged in `BATCH_STEP_EXECUTION.EXIT_MESSAGE`. This also seems to relate to [this topic](http://forums.ohdsi.org/t/transaction-vs-session-scope-for-global-temp-tables-statements/333/2) in the OHDSI forums.

I did a trace and found that 72 statements were passed to [batchUpdate](https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/cohortanalysis/CohortAnalysisTasklet.java#L61) which @chrisknoll referred to. In MSSQL I monitored the queries associated with the job and found that statements were all joined into a single query. I'm not familiar enough with Spring Batch to determine if it might be pooling these into the same transaction or session nor what to do about this. I appreciate any advice. 

    org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Transaction marked as rollbackOnly
      at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:526)
      at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:757)
      at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:726)
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      at java.lang.reflect.Method.invoke(Method.java:483)
      at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
      at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127)
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
      at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
      at com.sun.proxy.$Proxy102.commit(Unknown Source)
      at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:150)
      at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:271)
      at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:77)
      at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:368)
      at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215)
      at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:144)
      at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:257)
      at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:198)
      at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
      at org.springframework.ba

**Comment by chrisknoll** [comment]
I'm not sure about this later error message: exceptions in JPA means that one of the entities failed to save to the database (related to a transaction). There may be inner exceptions being raised that we aren't seeing here, but the 'table already exists' errors from the prior messages isn't the same as the 'transaction could not be committed'.

@mvelez1984:   This is what I've been doing in my cohort definition code, not sure if it's different where the code is executing for you:


~~~ java
      String expressionSql = expressionQueryBuilder.buildExpressionQuery(expression, options);
      String translatedSql = SqlTranslate.translateSql(expressionSql, "sql server", jobParams.get("target_dialect").toString(), SessionUtils.sessionId(), null);
      String[] sqlStatements = SqlSplit.splitSql(translatedSql);
      result = GenerateCohortTasklet.this.jdbcTemplate.batchUpdate(sqlStatements);
~~~

The array of sql statements should be executed separately and if an exception is throw with SQL in it, it should just have the executing query.  But that's a bit of an assumption on my side, but I haven't seen these types of errors.

-Chris

**Comment by mav7014** [comment]
I was able to resolve the issue by using the Microsoft JDBC driver. I suppose (have not confirmed) the jTDS driver supports batch updates whereas the MS driver doesn't- and so [JdbcTemplate.batchUpdate](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/jdbc/core/JdbcTemplate.html#batchUpdate-java.lang.String...-) behaves differently. If this is the case, should we consider running these explicitly as separate updates?

**Comment by fdefalco** [comment]
Would the intent be to do that to support the jTDS driver?

**Comment by mav7014** [comment]
@fdefalco The intent would be to prevent this error when using a JDBC driver that supports batch update. I'm not sure which do, but I suspect jTDS does. Support might also be added in future versions of other drivers and this error would be hard to spot (that is, if my understanding of the issue is even correct). I think I understand the benefit of using batch update when it is supported, but it would seem that flows are possible to `CohortAnalysisTasklet` where steps should not be batched. What do you think?
