### ISSUE TITLE
CC "temp" tables issue

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#621]
Thank you @chrisknoll for discovering the issue

There are permanent ‘temp tables’ used in cohort characterization. These ‘permenant-temporary tables’ are running up against rules of our db accounts to only be able to create temp tables in the results schema, but no create permeant tables.

If we’re wanting this to work like oracle: there is a parameter for sqlrender for ‘temp schema’ which is specifically for cases where we want to create these ‘permenant-temp tables’…it allows DBAs to grant full permission on a temp schema without compromising the results schema.  Could you update your generation code to leverage the ‘temp schema’ in your sql render calls so that those temp tables are created off in the temporary schema?  You’ll have to look at the sql render code to see how those tokens are replaced (I’m not sure how that is exposed) or we can introduce a new token to sql render called ‘@tempschema’ that we use in cases where we are creating a temporary table that is permanent.

This has the advantage of any temp talbes that are not cleaned up can be easily identified by being stored in the temp schema without polluting the results schema.  Hopefully, this makes sense and is something you can easily change.

**Comment by pavgra** [comment]
Since we don't have temp table diamon yet, we'll need to coalesce it to RESULTS schema. @chrisknoll , any objections or better ideas?

**Comment by chrisknoll** [comment]
No, if a temp schema daimon isn't specified, falling-back to results schema is a good option.  but, we should define the new daimon type in the enum and try to use it if we find the source has a 'temp' daimon registered.

**Comment by pavgra** [comment]
Ok, so overall plan then is:
- define the new daimon type for TEMP schema (reflect in admin panel UI as well)
- create "permenant-temp" tables used in CC in the temp schema if it is defined, otherwise - fallback to results schema

**Comment by chrisknoll** [comment]
Agreed.

**Comment by pavgra** [comment]
Closed by
https://github.com/OHDSI/WebAPI/pull/629
https://github.com/OHDSI/Atlas/pull/1020
