### ISSUE TITLE
Owner of an entity should be able to grant permissions for the entity update / delete / etc to others

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#639]
- Entity owner field should be introduced (I propose to put it into CommonEntity)
- There should be an additional button for Permissions management for each entity next to the entity's Save / Close / Delete button (let's move the button block to common component)
- The button should open permissions management popup, where:
  - Current owner should be displayed and the ownership can be transferred
  - Entity permissions (update / delete / execute / etc) can be granted to any Atlas user or Role. The block should consist of autocomplete for users, select for available entity-level permissions and list of permissions granted to users. Similarly to following Arachne popup (but with permission selector):
![image](https://user-images.githubusercontent.com/10010071/46640598-07d97180-cb3b-11e8-94f9-a253539fad4a.png)

**Comment by fdefalco** [comment]
Bumping to 2.8 after discussion with @anthonysena - this is a feature that will be necessary for collaboration to be feasible in our environment
