### ISSUE TITLE
Export IR analysis SQL

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#655]
Would be very useful to be able to export IR analysis SQL

**Comment by gowthamrao** [comment]
@pavgra are you talking about the rendered code be available in SQL. If yes, YES!!

**Comment by pavgra** [comment]
@gowthamrao , exactly about it

**Comment by aostropolets** [comment]
Yey! I'm all for that stuff. Right now you can't modify IR outside Atlas, which limits the possibility to customize it.

**Comment by anthonysena** [comment]
Re-opening since this is still unresolved in terms of the ATLAS changes.
