### ISSUE TITLE
Compatibility with Postgres <9.6

### ISSUE THREAD

**Issue by MaximMoinat** [OHDSI/WebAPI#676]
The sql syntax `ADD COLUMN IF NOT EXISTS` is only supported since Postgres 9.6:
https://github.com/OHDSI/WebAPI/blob/4a2f11708bde260ab7abbf37e156590518cd5a8b/src/main/resources/db/migration/postgresql/V2.5.0.20180730192730__schema-add-kerberos-to-source.sql#L1

Getting the same behaviour for e.g. Postgres 9.5 is not trivial, see the following thread on Stackoverflow: https://stackoverflow.com/questions/12597465/how-to-add-column-if-not-exists-on-postgresql

So do we want to drop support for Postgres 9.5 and earlier?

**Comment by anthonysena** [comment]
Closing since this was fixed via changes in #1486.
