### ISSUE TITLE
WebAPI Wiki

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#686]
I'd like to propose that we move the content from our [current wiki](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi) to GitHub to keep it closer to the code. 

We also need help to update it to reflect the new options for configuration, setup, etc. Putting this out here to see who may be interested in helping with this effort.

**Comment by konstjar** [comment]
@anthonysena I'm with you on this

**Comment by anthonysena** [comment]
Per our Atlas/WebAPI call, we should also aim to have a list of SQL "templates" for flyway migrations for the various dialects.

**Comment by anthonysena** [comment]
Closing this as it was done as part of the 2.7.2 release.
