### ISSUE TITLE
Heracles: Cannot insert an explicit value into a timestamp column

### ISSUE THREAD

**Issue by mav7014** [OHDSI/WebAPI#69]
We are using SQL Server 2012 and the Microsoft JDBC driver. When we open the Heracles runner UI, we encounter the WebAPI exception "Cannot insert an explicit value into a timestamp column." The culprit was [heracles_visualization_data.end_time](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/db/migration/sqlserver/V1.0.0.8__heracles_data.sql#L10). Changing the type from `timestamp` to `datetime` seems to resolve the issue.

**Comment by chrisknoll** [comment]
Yes, thank you, @mav7014. Finding this issue along with others. I'll have a new push shortly.

**Comment by evillalonNY** [comment]
Yes this is already resolved.

**Comment by cahilton** [comment]
Sounds like this issue has been resolved for SQL Server
