### ISSUE TITLE
Generated Results DDL is incorrect for Impala

### ISSUE THREAD

**Issue by konstjar** [OHDSI/WebAPI#694]
There are few issues with generated DDL for Impala
http://<host>/WebAPI/ddl/results?schema=cdm_results&dialect=impala

1. There is no IF EXISTS statement for 'CREATE TABLE @results_database_schema.concept_hierarchy' or 'CREATE TABLE cdm_results.cc_results' or 'CREATE TABLE cdm_results.pathway_analysis_stats'
2. There is no translation for @results_database_schema and @vocab_database_schema in few places
3. 'CREATE TABLE jan11s5ktemp_period ' - This part is causing issues in some environments. This code assumes we have permissions to write in default database, while in most enterprise environments it's prohibited. Suggestion - add @results_database_schema to create temporary table in results schema.
4. "mode_id INT DEFAULT 0" - Impala does not allow DEFAULT statement
5. Met few CAST issues for "Populate the hierarchy lookup table per treemap"

**Comment by chrisknoll** [comment]
The issue with `@results_database_schema` is going to be addressed in #692.

The issue with @vocab_database_schema is that the interface to the results DDL schema does not accept a parameter for the vocabulary schema...I think the assumption there is that the caller needs to do their own find-replace on that token when using the script (or we add a new method to the results schema that lets you pass in the additional parameter.

For the 'permanent temp tables' there should be an 'oracle_temp_schema' param in sqlrender which will prefix the temp schema to temp tables.  But where do we read this value from?  Does it become another parameter?

The lack of default values in impala is disappointing.  I think this brings up, again, the notion of 'minimum required functionality' to be supported on a CDM.

For the CAST issues, could you contribute commits to the pdw-ddl branch (which #692 is based on) and I can check the cast fixes against PDW?

**Comment by mpozhidaeva** [comment]
1. fix for **concept_hierarchy** here - https://github.com/OHDSI/WebAPI/pull/692/files#diff-5b86cac7b3e2e0683182dc6543db2b74
2. https://github.com/OHDSI/WebAPI/pull/723/files
3. 
4. https://github.com/OHDSI/SqlRender/pull/144
5.

**Comment by mpozhidaeva** [comment]
I would like to remind I need https://github.com/OHDSI/WebAPI/pull/692/files#diff-5b86cac7b3e2e0683182dc6543db2b74 for the current issue.
