### ISSUE TITLE
Heracles: Cannot set id to null in table heracles_visualization_data

### ISSUE THREAD

**Issue by mav7014** [OHDSI/WebAPI#71]
We are using SQL Server 2012 and the Microsoft JDBC driver. When we open the Heracles runner UI, we encounter a WebAPI exception associated with [getCohortSummaryData](https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/service/CohortResultsService.java#L1201) (sorry, I no longer have the stack trace). The generated SQL was attempting to insert into `heracles_visualization_data` with `id=null`. I discovered the problem was due to the annotations on [VisualizationData.id](https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/cohortresults/VisualizationData.java#L21) being inconsistent with the [DDL](https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/db/migration/sqlserver/V1.0.0.8__heracles_data.sql#L4); the DDL does not set `id` to autoincrement. Setting `heracles_visualization_data.id` to autoincrement (see below) appears to have resolved the issue.

```sql
ALTER TABLE [HERACLES_VISUALIZATION_DATA] DROP COLUMN id
ALTER TABLE [HERACLES_VISUALIZATION_DATA] ADD id integer IDENTITY(1,1)
```

**Comment by chen-regen** [comment]
I have committed into OHDSI-58 branch and created merge request. Please review and merge. I can merge too if you guys want me to.
