### ISSUE TITLE
Failed to import cohort characterization design

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#724]
When importing a CharacterizationDesign from a 2.6 instance into latest master, the import failed:

```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'criteriaType' that is to contain type id  (for class org.ohdsi.webapi.feanalysis.dto.BaseFeAnalysisCriteriaDTO)
 at [Source: N/A; line: -1, column: -1] (through reference chain: org.ohdsi.webapi.cohortcharacterization.dto.CcExportDTO["featureAnalyses"]->java.util.ArrayList[6])

```

We should have compatibility between 2.6 and the next release with respect to importing. Anything that is newly added should have a default value coming from 2.6.

**Comment by aklochkova** [comment]
@chrisknoll Could you please provide this Characterization? I can't reproduce.

**Comment by chrisknoll** [comment]
[CC_with_CriteriaFeature.txt](https://github.com/OHDSI/WebAPI/files/2737647/CC_with_CriteriaFeature.txt)

The attached export was created in the 2.6 release version of webapi.  When you attempt to import this design into an instance running from latest master in WebAPI, you get this error in the console:
![image](https://user-images.githubusercontent.com/6818777/50845412-ca9f9e00-133a-11e9-9c0f-a352767e0b01.png)

![image](https://user-images.githubusercontent.com/6818777/50845420-d12e1580-133a-11e9-8caf-57781cb2ed1f.png)
