### ISSUE TITLE
Color mismatch on cohort inclusion rule attrition report

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#732]
The ``scaleQuantize`` is leading to the wrong color result in the color scale:

```
// from FeasibilityAttritionReport.js, line 53
self.color = d3.scaleQuantize()
		.domain([1.0, .75, .5, .25, .10])
		.range(["#7BB209", "#95B90A", "#C9C40D", "#E77F13", "#FF3D19"]);
```

Instead, this should be switched to use ``scaleThreshold`` to associate the continuous domain to the categorical colors.

**Comment by anthonysena** [comment]
Closed via OHDSI/Atlas#1207
