### ISSUE TITLE
Atlas/WebAPI Setup Failing

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#739]
Per our discussion on http://forums.ohdsi.org/t/atlas-setup-failing/5858/21, creating an issue here to continue the troubleshooting.

**Comment by ambuj369** [comment]
@anthonysena 
I am also unable to view the vocabulary version under configuration section within Atlas, However, the query 

select VOCABULARY_VERSION from omop_cdm.vocabulary where VOCABULARY_ID = 'None';

returned : "v5.0 27-FEB-19"

please suggest.

As well as I am unable to view data in Atlas. All the sections shows as NO DATA within.
![Atlas1](https://user-images.githubusercontent.com/47858365/55149070-79e85600-516f-11e9-8896-c85c1e8f5ec4.png)
![Atlas2](https://user-images.githubusercontent.com/47858365/55149071-7a80ec80-516f-11e9-88e7-406440118ba0.png)
