### ISSUE TITLE
Broken build v2.6.0 due to change in standardized-analysis-api v1.0.0

### ISSUE THREAD

**Issue by SBylemans** [OHDSI/WebAPI#740]
The version 2.6.0 of WebAPI does not compile now due to change in standardized-analysis-api version 1.0.0. This version changed yesterday (14/01/2019 or 01/14/2019 for the Americans). This a real troubling issue, seeing as a released version should not change. What should change then is the version itself. Any of you have access to revert the version 1.0.0 and release a new version instead of standardized-analysis-api?

**Comment by anthonysena** [comment]
@SBylemans are you using WebAPI 2.6.0 off of the v2.6.0 tag or off master? If using the tag, it should work. If you are running it off master, you will also need to compile the StandardizedAnalysisAPI off of master at this time. 

I'm working through cleaning up some of the versioning - v1.0.0 of the StandardizedAnalysisAPI repo was released at the OHDSI symposium and is a dependency for v2.6.0 of WebAPI. 

If you are facing another issue, please post up the error(s) along with any relevant information (such as the release/commit you are on) and we'll do our best to help. Thanks!

**Comment by SBylemans** [comment]
We are using WebAPI 2.6.0 off of the tag. @anthonysena When was this symposium? Because the repo for the [standardized-analysis-api](http://repo.ohdsi.org:8085/nexus/content/repositories/releases/org/ohdsi/standardized-analysis-api/) changed yesterday...

The error that we are encountering is the following:

```
...
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/service/SparqlService.java: Some input files use or override a deprecated API.
[WARNING] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/service/SparqlService.java: Recompile with -Xlint:deprecation for details.
[WARNING] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/feanalysis/domain/FeAnalysisEntity.java: Some input files use unchecked or unsafe operations.
[WARNING] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/feanalysis/domain/FeAnalysisEntity.java: Recompile with -Xlint:unchecked for details.
[INFO] 4 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/domain/CohortCharacterizationEntity.java:[7,56] cannot find symbol
  symbol:   class CohortCharacterizationStrata
  location: package org.ohdsi.analysis.cohortcharacterization.design
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/domain/CohortCharacterizationEntity.java:[58,33] cannot find symbol
  symbol:   class CohortCharacterizationStrata
  location: class org.ohdsi.webapi.cohortcharacterization.domain.CohortCharacterizationEntity
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/dto/CcExportDTO.java:[4,56] cannot find symbol
  symbol:   class CohortCharacterizationStrata
  location: package org.ohdsi.analysis.cohortcharacterization.design
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/dto/CcExportDTO.java:[13,33] cannot find symbol
  symbol:   class CohortCharacterizationStrata
  location: class org.ohdsi.webapi.cohortcharacterization.dto.CcExportDTO
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/domain/CohortCharacterizationEntity.java:[57,5] method does not override or implement a method from a supertype
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/dto/CcExportDTO.java:[12,5] method does not override or implement a method from a supertype
[INFO] 6 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.687 s
[INFO] Finished at: 2019-01-15T10:01:09Z
[INFO] Final Memory: 46M/376M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project WebAPI: Compilation failure: Compilation failure: 
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/domain/CohortCharacterizationEntity.java:[7,56] cannot find symbol
[ERROR]   symbol:   class CohortCharacterizationStrata
[ERROR]   location: package org.ohdsi.analysis.cohortcharacterization.design
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/domain/CohortCharacterizationEntity.java:[58,33] cannot find symbol
[ERROR]   symbol:   class CohortCharacterizationStrata
[ERROR]   location: class org.ohdsi.webapi.cohortcharacterization.domain.CohortCharacterizationEntity
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/dto/CcExportDTO.java:[4,56] cannot find symbol
[ERROR]   symbol:   class CohortCharacterizationStrata
[ERROR]   location: package org.ohdsi.analysis.cohortcharacterization.design
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/dto/CcExportDTO.java:[13,33] cannot find symbol
[ERROR]   symbol:   class CohortCharacterizationStrata
[ERROR]   location: class org.ohdsi.webapi.cohortcharacterization.dto.CcExportDTO
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/domain/CohortCharacterizationEntity.java:[57,5] method does not override or implement a method from a supertype
[ERROR] /home/ec2-user/workspace/4-HONEUR-WebAPI-remote/src/main/java/org/ohdsi/webapi/cohortcharacterization/dto/CcExportDTO.java:[12,5] method does not override or implement a method from a supertype
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
...
```

**Comment by anthonysena** [comment]
Hi @SBylemans - yes, the repository for the StandardizedAnalysisAPI changed yesterday in an effort to tidy up the versioning that was missed after Symposium (Oct. 2018). I applied the v1.0.0 tag to https://github.com/OHDSI/StandardizedAnalysisAPI/tree/v1.0.0 to reflect the work that was done at that time. Subsequent commits were made to the master branch after that point to support new work that will go into WebAPI 2.7 and StandardizedAnalysisAPI 1.1. 

I have tested this against WebAPI v2.6.0 and looking at the error above, my guess is that you may not be on the v2.6.0 tag since it is encountering an error on the CohortCharacterizationStrata which was added after the v2.6.0 release. Could you confirm that you've checked out the code at the tag using the following git command:

`git checkout tags/v2.6.0`

Thanks!

**Comment by SBylemans** [comment]
Ok @anthonysena we found the cause, we had some issues before and solved them manually, now that the code has been cleaned up these resolutions are not necessary anymore. Thanks!

**Comment by chrisknoll** [comment]
> Ok @anthonysena we found the cause, we had some issues before and solved them manually, now that the code has been cleaned up these resolutions are not necessary anymore. Thanks!

@SBylemans : Could you provide details on what your issues were and how you solved them?

**Comment by SBylemans** [comment]
In [CohortCharacterizationEntity.java](https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/cohortcharacterization/domain/CohortCharacterizationEntity.java) and [CcExportDTO.java](https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/cohortcharacterization/dto/CcExportDTO.java) we had issues prior to the clean up.

Due to these classes implementing `CohortCharacterization`, they needed to override `public Collection<? extends CohortCharacterizationStrata> getStratas()`. Somehow, this method was present in the standardized-analysis-api version 1.0.0 while not accounted for in WebAPI version 2.6.0. We solved it by returning an empty list.

As stated, this is solved by the new release. Thanks @anthonysena !
