### ISSUE TITLE
Update Basic Security Configuration in OHDSI Wiki so that it works for recent release(s)

### ISSUE THREAD

**Issue by t-abdul-basser** [OHDSI/WebAPI#751]
### Expected Behavior

When attempting to configure a WebAPI deployment to support Atlas with security features, following the [Basic Security Configuration](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:basic_security) tutorial in the OHDSI Wiki results in a successful deployment.

### Actual Behavior

As per #571, security is not configured in resulting deployment. Authentication fails with 
* error message in Atlas login form ("Bad Credentials") and 
* console errors raised for the `/login` service .

### Steps to Reproduce

1. Follow tutorial

**Comment by t-abdul-basser** [comment]
Updated [Basic Security Configuration](http://www.ohdsi.org/web/wiki/doku.php?id=documentation:software:webapi:basic_security) so that 
    `- security.enabled=true`
 is replaced with
    `- security.provider=AtlasRegularSecurity`

**Comment by anthonysena** [comment]
@t-abdul-basser - thanks again for making these edits to the WebAPI wiki. Recently I ported over the documentation to here: https://github.com/OHDSI/WebAPI/wiki/Basic-Security-Configuration and also expanded the [security documentation on the wiki](https://github.com/OHDSI/WebAPI/wiki/Security-Configuration). I think we should be set but please re-open if you see any issues in the documentation. Thanks!
