### ISSUE TITLE
Atlas security - clone and modify roles

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/WebAPI#752]
Nice to have functionalities

- copy existing role to new role
- modify roles
- export/import role as JSON from one atlas instance to another
- over ride current role with imported JSON
- create new role with imported JSON
- rename existing roles

Related issue: https://github.com/OHDSI/WebAPI/issues/506
Tagging @pavgra

**Comment by pavgra** [comment]
The following features are already presented:
- copy existing role to new role
- modify roles
- export/import role as JSON from one atlas instance to another
- create new role with imported JSON

So, just two from the list need to be implemented:
- over ride current role with imported JSON
- rename existing roles <-- currently not available to admin, but available to the role creator

**Comment by pavgra** [comment]
Proposed solution:
- Grant access for the Admin role to modify any role names
- Add `Utilities` tab with `Export` / `Import` section similar to other entities to be able to overwrite current role / export current role
