### ISSUE TITLE
(treatment) pathways produces some unanticipated values

### ISSUE THREAD

**Issue by mick-iqvia** [OHDSI/WebAPI#779]
We are looking at the behaviour of treatment pathways in order to implement a version running against a spark cluster.

There are a number of results that we are not sure are what was intended.

These are outlined in the image below, where 100, 200 etc are person ids.

![pathwaysanomolies](https://user-images.githubusercontent.com/47112987/51849191-18466f80-2317-11e9-9028-40dbd8197ad9.png)

The columns are: 
1. Input events - event cohorts - assume all these events fall within target
2. Current output - these are current pathways
3. Required output - these are the results we expected
4. Henry has modified runPathways SQL and these are the outputs following his changes. He can comment on this.

I'll add the test data in a follow up comment

**Comment by mick-iqvia** [comment]
Here is some test data that has been copied from a test fixture we have in a scala file. Hopefully it is straightforward to understand. The tests from "Overlapping" on are not producing expected outputs.

`case class PathwaysTestExample(name: String, comboWindow: Int, allowRepeats: Boolean, maxDepth: Int,
                               targetCohortIds: Seq[Int], eventsCohortIds: Seq[Int],
                               inputCohorts: String, expectedEvents: String, expectedStats: String) {
  val inputTable = TTable(inputCohorts)
  val expectedEventTable = TTable(expectedEvents)
  val expectedStatsTable = TTable(expectedStats)
}

object PathwaysTestExamples {
  val examples: Seq[PathwaysTestExample] = Seq(
    PathwaysTestExample("Filtered events", 0, allowRepeats = false, 5, Seq(1), Seq(2, 3, 4, 5),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |1                   |999       |2017-01-18       |2017-01-18
          |2                   |999       |2017-01-18       |2017-01-18
          |3                   |999       |2017-01-17       |2017-01-19
          |4                   |999       |2017-01-18       |2017-01-19
          |5                   |999       |2017-01-17       |2017-01-18""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |1                |1        |999        |1       |2017-01-18        |2017-01-18""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |1                |1                   |1"""),

    PathwaysTestExample("Repeated events", 0, allowRepeats = true, 5, Seq(1), Seq(2, 3),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |1                   |999       |2017-01-18       |2018-01-18
          |2                   |999       |2017-01-18       |2017-01-18
          |3                   |999       |2017-06-18       |2017-06-18
          |2                   |999       |2018-01-18       |2018-01-18""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |1                |1        |999        |1       |2017-01-18        |2017-01-18
          |1                              |1                |2        |999        |2       |2017-06-18        |2017-06-18
          |1                              |1                |1        |999        |3       |2018-01-18        |2018-01-18""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |1                |1                   |1"""),

    PathwaysTestExample("No repeated events", 0, allowRepeats = false, 5, Seq(1), Seq(2, 3),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |1                   |999       |2017-01-18       |2018-01-18
          |2                   |999       |2017-01-18       |2017-01-18
          |3                   |999       |2017-06-18       |2017-06-18
          |2                   |999       |2018-01-18       |2018-01-18""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |1                |1        |999        |1       |2017-01-18        |2017-01-18
          |1                              |1                |2        |999        |2       |2017-06-18        |2017-06-18""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |1                |1                   |1"""),

    PathwaysTestExample("Removal of repeated events", 0, allowRepeats = false, 5, Seq(1), Seq(2),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |1                   |999       |2017-01-18       |2018-01-18
          |2                   |999       |2017-01-18       |2017-01-18
          |2                   |999       |2018-01-18       |2018-01-18""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |1                |1        |999        |1       |2017-01-18        |2017-01-18""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |1                |1                   |1"""),

    PathwaysTestExample("Max depth", 0, allowRepeats = true, 2, Seq(1), Seq(2, 3, 4, 5),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |1                   |999       |2017-01-18       |2017-01-21
          |2                   |999       |2017-01-18       |2017-01-18
          |3                   |999       |2017-01-19       |2017-01-19
          |4                   |999       |2017-01-20       |2017-01-20
          |5                   |999       |2017-01-21       |2017-01-21""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |1                |1        |999        |1       |2017-01-18        |2017-01-18
          |1                              |1                |2        |999        |2       |2017-01-19        |2017-01-19""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |1                |1                   |1"""),

    PathwaysTestExample("Matching", 0, allowRepeats = true, 5, Seq(9), Seq(1, 2),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |9                   |100       |2015-01-01       |2021-01-01
          |1                   |100       |2016-01-01       |2017-01-01
          |2                   |100       |2018-01-01       |2019-01-01""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |9                |1        |100        |1       |2016-01-01        |2017-01-01
          |1                              |9                |2        |100        |2       |2018-01-01        |2019-01-01""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |9                |1                   |1"""),

    PathwaysTestExample("Overlapping", 0, allowRepeats = true, 5, Seq(9), Seq(1, 2),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |9                   |200       |2015-01-01       |2021-01-01
          |1                   |200       |2016-01-01       |2017-01-01
          |2                   |200       |2016-07-01       |2017-07-01""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |9                |1        |200        |1       |2016-01-01        |2016-06-30
          |1                              |9                |3        |200        |2       |2016-07-01        |2017-01-01
          |1                              |9                |2        |200        |3       |2017-01-02        |2017-07-01""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |9                |1                   |1"""),

    PathwaysTestExample("Subsumed", 0, allowRepeats = true, 5, Seq(9), Seq(1, 2),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |9                   |300       |2015-01-01       |2021-01-01
          |1                   |300       |2016-01-01       |2018-01-01
          |2                   |300       |2016-07-01       |2017-07-01""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |9                |1        |300        |1       |2016-01-01        |2016-06-30
          |1                              |9                |3        |300        |2       |2016-07-01        |2017-07-01
          |1                              |9                |1        |300        |3       |2017-07-02        |2018-01-01""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |9                |1                   |1"""),

    PathwaysTestExample("Ends aligned", 0, allowRepeats = true, 5, Seq(9), Seq(1, 2),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |9                   |400       |2015-01-01       |2021-01-01
          |1                   |400       |2016-01-01       |2018-01-01
          |2                   |400       |2017-01-01       |2018-01-01""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |9                |1        |400        |1       |2016-01-01        |2016-12-31
          |1                              |9                |3        |400        |2       |2017-01-01        |2018-01-01""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |9                |1                   |1"""),


    PathwaysTestExample("Starts aligned", 0, allowRepeats = true, 5, Seq(9), Seq(1, 2),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |9                   |500       |2015-01-01       |2021-01-01
          |1                   |500       |2016-01-01       |2018-01-01
          |2                   |500       |2016-01-01       |2017-01-01""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |9                |3        |500        |1       |2016-01-01        |2017-01-01
          |1                              |9                |1        |500        |2       |2017-01-02        |2018-01-01""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |9                |1                   |1"""),

    PathwaysTestExample("3 way overlap", 0, allowRepeats = false, 5, Seq(9), Seq(1, 2, 3),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |9                   |600       |2015-01-01       |2021-01-01
          |1                   |600       |2016-01-01       |2018-01-01
          |2                   |600       |2017-01-01       |2019-01-01
          |3                   |600       |2017-07-01       |2020-01-01""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |9                |1        |600        |1       |2016-01-01        |2016-12-31
          |1                              |9                |3        |600        |2       |2017-01-01        |2017-06-30
          |1                              |9                |7        |600        |3       |2017-07-01        |2018-01-01
          |1                              |9                |6        |600        |4       |2018-01-02        |2019-01-01
          |1                              |9                |4        |600        |5       |2019-01-02        |2020-01-01""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |9                |1                   |1"""),


    // some examples that are not handled as expected in current implementation in synpuf 1k
    PathwaysTestExample("Synpuf1k person 80", 0, allowRepeats = true, 5, Seq(3), Seq(6, 7, 8, 10),
      inputCohorts =
        """cohort_definition_id|subject_id|cohort_start_date|cohort_end_date
          |int                 |bigint    |date             |date
          |3                   |80        |2008-05-04       |2011-05-04
          |6                   |80        |2010-06-14       |2010-06-15
          |7                   |80        |2008-05-04       |2008-05-05
          |8                   |80        |2009-05-19       |2009-05-20
          |10                  |80        |2009-05-20       |2009-05-21""",
      expectedEvents =
        """pathway_analysis_generation_id |target_cohort_id |combo_id |subject_id |ordinal |cohort_start_date |cohort_end_date
          |bigint                         |int              |bigint   |bigint     |int     |date              |date
          |1                              |3                |2        |80         |1       |2008-05-04        |2008-05-05
          |1                              |3                |4        |80         |2       |2009-05-19        |2009-05-19
          |1                              |3                |12       |80         |3       |2009-05-20        |2009-05-20
          |1                              |3                |8        |80         |4       |2009-05-21        |2009-05-21
          |1                              |3                |1        |80         |5       |2010-06-14        |2010-06-15""",
      expectedStats =
        """pathway_analysis_generation_id |target_cohort_id |target_cohort_count |pathways_count
          |bigint                         |int              |int                 |int
          |1                              |3                |1                   |1""")
  )
}
`

**Comment by hms1** [comment]
To get to the output shown above, I made some changes to the original runPathwayAnalysis.sql. Hopefully the approach is more robust with respect to different types of event overlap.

I replaced lines 91:145 with the following:

```
IF OBJECT_ID('tempdb..#combo_events', 'U') IS NOT NULL
DROP TABLE #combo_events;

WITH 
cohort_dates AS (
	SELECT DISTINCT subject_id, cohort_date 
	FROM (
		  SELECT subject_id, cohort_start_date cohort_date FROM #collapsed_dates_events 
		  UNION 
		  SELECT subject_id, DATEADD(day, 1, cohort_end_date) cohort_date FROM #collapsed_dates_events
		  )
	ORDER BY subject_id, cohort_date
),
time_periods AS (
	SELECT subject_id, cohort_date, DATEADD(day, -1, LEAD(cohort_date,1) over (PARTITION BY subject_id ORDER BY cohort_date ASC)) next_cohort_date
	FROM cohort_dates 
	GROUP BY subject_id, cohort_date
),
events AS (
	SELECT tp.subject_id, event_cohort_index, cohort_date cohort_start_date, next_cohort_date cohort_end_date  
	FROM time_periods tp
	LEFT JOIN #collapsed_dates_events e ON e.subject_id = tp.subject_id
	WHERE (e.cohort_start_date <= tp.next_cohort_date AND e.cohort_end_date >= tp.cohort_date) 
	OR (e.cohort_start_date = tp.cohort_date AND e.cohort_end_date = tp.cohort_date)
) 
```

More than happy to discuss, and/or make a PR containing the change.

**Comment by chrisknoll** [comment]
Excellent work, @hms1 and @mick-iqvia !

Considering the efforts you put in to creating the test cases, and presenting the before-after view of the split event-cohort episodes, I'm inclined to support a PR with these changes.

Could you provide the following to further support the code changes you suggest:

1. What was the logical error with the original code that led to the incorrect results
2. How is your code change implementing the correct logic?
3. As original author of the split logic, @pavgra should review this as well and share any concerns.

**Comment by chrisknoll** [comment]
No, this is excellent explanation, and will be helpful to people wanting to understand how this analysis splits overlaps.

@pavgra : can you provide your feedback?

**Comment by mick-iqvia** [comment]
Perhaps we could use this issue to discuss the behaviour of the combo window setting also, in particular w.r.t. to short lived events.

Also @cgreich has suggested that it would be nice to get some segment duration stats from the graphic. I.e. when hovering over a segment you see stats related to average duration, 99 percentile duration etc. It is probably better that this be added as a separate enhancement request.

**Comment by chrisknoll** [comment]
@mick-iqvia, I'd prefer it if we focused this issue on the problem of handling overlaps across multiple cohort events properly. We can open a new issue to discuss new features such as combination window settings and other statistics.

**Comment by chrisknoll** [comment]
@mick-iqvia, could you provide a PR with the changes you suggested so that we can begin formal review and testing of the changes?

**Comment by mick-iqvia** [comment]
@chrisknoll  Yes - I'll speak to Henry and we'll get it created

**Comment by anthonysena** [comment]
PR filed with #808
