### ISSUE TITLE
add button for cache load on creation of new source

### ISSUE THREAD

**Issue by fdefalco** [OHDSI/WebAPI#798]
After creating a source in the configuration under administrative privileges there needs to be a feature to load the results cache.  

Additionally perhaps a feature to refresh a cache for a particular data source or all data sources.

The ATLAS UI would have to be added for these features as well.

**Comment by ssuvorov-fls** [comment]
is it the same functionality as described in https://github.com/OHDSI/WebAPI/issues/726?

**Comment by pavgra** [comment]
Closing as duplicate
