### ISSUE TITLE
Can not find symbol for SqlTranslate class

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/WebAPI#831]
![screenshot from 2019-02-15 11-58-11](https://user-images.githubusercontent.com/16149781/52831890-ad1fda00-3119-11e9-8d08-cb7ffcc43e73.png)

An error stating that methods of the SqlTranslate class can not be found when the maven build progresses

**Comment by anthonysena** [comment]
Can you verify that your pom.xml is referencing `SqlRender 1.6.0-SNAPSHOT`? That method was recently added to SqlRender.

**Comment by NEONKID** [comment]
It works well Thanks.
