### ISSUE TITLE
'Fix it' button returns empty list

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/WebAPI#833]
Steps to reproduce:
1. Create cohort definition
2. Add concept set to it on 'Concept Sets' tab
3. Save
4. Go to 'Messages' tab
5. Press 'Fix it' in the line with your concept set

ER:
List with other messages is returned

AR:
List is empty

**Comment by pavgra** [comment]
+
![image](https://user-images.githubusercontent.com/10010071/52862076-3fb47f00-3102-11e9-9e6a-ba6834dbd3cc.png)
