### ISSUE TITLE
/vocbulary/lookup/mapped is using invalid concept relationships

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/WebAPI#85]
The query loaded in the vocabulary service to resolved mapped concepts is using this source file:
/resources/vocabulary/sql/getMappedSourcecodes.sql

In this file, the query used is:
~~~sql
select CONCEPT_ID, CONCEPT_NAME, ISNULL(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, ISNULL(c.INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, VOCABULARY_ID
from @CDM_schema.concept_relationship cr
join @CDM_schema.concept c on c.concept_id = cr.concept_id_1
where cr.concept_id_2 in (@identifiers)
and relationship_id in ('Maps to')
and standard_concept IS NULL
order by domain_id, vocabulary_id
~~~~

The problem is that concept relationships that are invalid are pulling in the invalid relationships, and there is no way to filter this on the UI. The 'Valid' filter on the UI is referring to the returned concepts, but there's no way to control the concept_relationship rows.

**Comment by cgreich** [comment]
Wait, Chris. standard_concept should be 'S' for concept_id_2 concepts.

**Comment by chrisknoll** [comment]
Yeah, that's probably another problem with this query.

**Comment by cgreich** [comment]
So, simply delete all invalid concept_relationship records. I can't think of any useful query other than building or QAing the vocabulary. 

delete from concept_relationship where invalid_reason is not null -- or whatever the notation in SQL Server is

**Comment by fdefalco** [comment]
I would look for @pbr6cornell to comment on this as the current query was what was desired at the time of its development.  

Is the desire to change it so you can filter based on valid/invalid concept relationships in the UI or always ignore invalid concept relationships?

Its my understanding that we are trying to return the non-standard mapped concepts with this query, which is why we are looking for standard_concept IS null instead of standard_concept = 'S'.

**Comment by chrisknoll** [comment]
If I had a vote, i'd say to always ignore invalid concepts (which is effectively what Christian is suggesting by deleting all invalid concept_relationships).  The problem with the UI is that there's no way to know if a mapped concept came from an invalid relationship.  This makes tools like hermes and atlas effectively useless for determining what source codes were mapped to standard concepts.

As to the purpose of the query: from the URL it looks like it is trying to tell you what concepts are mapped to the list of target concepts.  The filters on the front end do allow users to filter out standard vs. non-standard concepts, so there'd be no harm returning any mapped concept.  If the user is interested in only seeing a source vocabulary that concepts mapped from, they can also filter that on the UI.  But this is a bit off topic from the original issue report which focuses on the use of invalid concept_relationships in the query.

**Comment by cgreich** [comment]
Friends:

Again, there is no use case for having invalid relationships in there, or non-standard concepts returned. Those still happen, but we are working on automating forwarding of the mapping or manual reviews of those situations. All source concepts (no matter valid or not, standard or not) should map to a standard concept by definition. So, I wouldn't build UIs for those situations.

**Comment by chrisknoll** [comment]
@cgreich , I'm in 100% agreement with you.
