### ISSUE TITLE
Calypso, Feasibility tables don't exist

### ISSUE THREAD

**Issue by tnovo** [OHDSI/WebAPI#88]
I know this is related to Calypso, but i believe the problem is related to WebAPI.

When running a feasibility study on Calypso, i get this error (actually a 500- server error) on http://127.0.0.1:8080/WebAPI/feasibility/1/info 
 
"ERROR: relation \"ohdsi.feas_study_index_stats\" does not exist\n  Position: 39"

i checked my database, and i believe the error comes because I have my CDM datasource in a different database / schema of the web api database.

**Comment by chrisknoll** [comment]
Yes, having separate databases is an advanced setup, but supported. The required tables are created in the webapi database so you could simply migrate the tables from your WebAPI install database out to your external database.  

It appears from your error message that you specified the schema as 'ohdsi' so I'd suggest copying tables from the WebAPI install database to the ohdsi schema on your CDM server. (or script those tables as DDL and execute them on your CDM server into the ohdsi schema).

You should pull the following tables from your WebAPI install database to your CDM server's ohdsi schema:
cohort(*)
feas_study_inclusion_stats
feas_study_index_stats
feas_study_result
heracles_heel_results
heracles_results
heracles_results_dist

(*) note: this cohort table in the ohdsi schema is separate from the CDM's cohort table.

-Chris
