### ISSUE TITLE
Cohort pathway analysis - Target Cohort vs Event Cohort

### ISSUE THREAD

**Issue by byr0sxj** [OHDSI/WebAPI#883]
Hi Smart peeps,

I posted this issue on the OHDSI Forum, and Chris suggested to open an issue here, becuase it seems like there is a bug on the tool. Here is the issue I faced:

When I read through the results that were generated from the cohort treatment pathway analysis, it looks like the number of target cohort looks different from that of the event cohort. However, I already restricted the target cohort with the events specified in the event cohort, so the number should be exactly the same. Could you pleae look further into this?

Please let me know if you need further info on this!

Mariana

**Comment by chrisknoll** [comment]
One thing we would ask is that if you go to the Pathways analysis UI, you can go to utilities-> export, and export the design of your pathway analysis as a JSON file, and attach that file here.  We can then import it and look at the specific case (and the export includes all cohort definitions, so don't worry about exporting each individual cohort def).

**Comment by byr0sxj** [comment]
Hi Chris,

Thanks for your reply!
I tried to export the file, but it surprisingly does not work.
However, I copied the codes and pasted here (I hope it is okay!And thank you in advance!!):

{
  "name": "AF_Shinyoung_Mariana",
  "targetCohorts": [
    {
      "id": 3898,
      "name": "[1401] Stroke prevention AF",
      "expression": {
        "PrimaryCriteria": {
          "CriteriaList": [
            {
              "DrugExposure": {
                "CodesetId": 7,
                "DrugTypeExclude": false
              }
            },
            {
              "DrugExposure": {
                "CodesetId": 8,
                "DrugTypeExclude": false
              }
            },
            {
              "DrugExposure": {
                "CodesetId": 9,
                "DrugTypeExclude": false
              }
            }
          ],
          "ObservationWindow": {
            "PriorDays": 365,
            "PostDays": 0
          },
          "PrimaryCriteriaLimit": {
            "Type": "First"
          }
        },
        "ConceptSets": [
          {
            "id": 7,
            "name": "[1401] B01AF - Factor Xa",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 43534760,
                    "CONCEPT_NAME": "Direct factor Xa inhibitors",
                    "STANDARD_CONCEPT": "C",
                    "STANDARD_CONCEPT_CAPTION": "Classification",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "B01AF",
                    "DOMAIN_ID": "Drug",
                    "VOCABULARY_ID": "ATC",
                    "CONCEPT_CLASS_ID": "ATC 4th"
                  },
                  "isExcluded": false,
                  "includeDescendants": true,
                  "includeMapped": false
                }
              ]
            }
          },
          {
            "id": 8,
            "name": "[1401] B01AE - Direct Thrombin",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 21601019,
                    "CONCEPT_NAME": "Direct thrombin inhibitors",
                    "STANDARD_CONCEPT": "C",
                    "STANDARD_CONCEPT_CAPTION": "Classification",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "B01AE",
                    "DOMAIN_ID": "Drug",
                    "VOCABULARY_ID": "ATC",
                    "CONCEPT_CLASS_ID": "ATC 4th"
                  },
                  "isExcluded": false,
                  "includeDescendants": true,
                  "includeMapped": false
                }
              ]
            }
          },
          {
            "id": 9,
            "name": "[1401] B01AA - Vitamin K antagonists",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 21600962,
                    "CONCEPT_NAME": "Vitamin K antagonists",
                    "STANDARD_CONCEPT": "C",
                    "STANDARD_CONCEPT_CAPTION": "Classification",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "B01AA",
                    "DOMAIN_ID": "Drug",
                    "VOCABULARY_ID": "ATC",
                    "CONCEPT_CLASS_ID": "ATC 4th"
                  },
                  "isExcluded": false,
                  "includeDescendants": true,
                  "includeMapped": false
                }
              ]
            }
          },
          {
            "id": 10,
            "name": "[1401] Atrial Fibrillation",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 313217,
                    "CONCEPT_NAME": "Atrial fibrillation",
                    "STANDARD_CONCEPT": "S",
                    "STANDARD_CONCEPT_CAPTION": "Standard",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "49436004",
                    "DOMAIN_ID": "Condition",
                    "VOCABULARY_ID": "SNOMED",
                    "CONCEPT_CLASS_ID": "Clinical Finding"
                  },
                  "isExcluded": false,
                  "includeDescendants": true,
                  "includeMapped": false
                }
              ]
            }
          },
          {
            "id": 11,
            "name": "christians list from known codes",
            "expression": {
              "items": []
            }
          }
        ],
        "QualifiedLimit": {
          "Type": "First"
        },
        "ExpressionLimit": {
          "Type": "First"
        },
        "InclusionRules": [
          {
            "name": "Diagnosis of AF",
            "expression": {
              "Type": "ALL",
              "CriteriaList": [
                {
                  "Criteria": {
                    "ConditionOccurrence": {
                      "CodesetId": 10,
                      "ConditionTypeExclude": false
                    }
                  },
                  "StartWindow": {
                    "Start": {
                      "Coeff": -1
                    },
                    "End": {
                      "Days": 0,
                      "Coeff": 1
                    },
                    "UseEventEnd": false
                  },
                  "Occurrence": {
                    "Type": 2,
                    "Count": 1,
                    "IsDistinct": false
                  },
                  "RestrictVisit": false
                }
              ],
              "DemographicCriteriaList": [],
              "Groups": []
            }
          },
          {
            "name": "Age>=18",
            "expression": {
              "Type": "ALL",
              "CriteriaList": [],
              "DemographicCriteriaList": [
                {
                  "Age": {
                    "Value": 18,
                    "Op": "gte"
                  }
                }
              ],
              "Groups": []
            }
          }
        ],
        "CensoringCriteria": [],
        "CollapseSettings": {
          "CollapseType": "ERA",
          "EraPad": 0
        },
        "CensorWindow": {}
      }
    }
  ],
  "eventCohorts": [
    {
      "id": 3899,
      "name": "[1401] Factor Xa",
      "expression": {
        "PrimaryCriteria": {
          "CriteriaList": [
            {
              "DrugExposure": {
                "CodesetId": 2,
                "DrugTypeExclude": false
              }
            }
          ],
          "ObservationWindow": {
            "PriorDays": 0,
            "PostDays": 0
          },
          "PrimaryCriteriaLimit": {
            "Type": "First"
          }
        },
        "ConceptSets": [
          {
            "id": 0,
            "name": "[1401] B01AA - Vitamin K",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 21600962,
                    "CONCEPT_NAME": "Vitamin K antagonists",
                    "STANDARD_CONCEPT": "C",
                    "STANDARD_CONCEPT_CAPTION": "Classification",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "B01AA",
                    "DOMAIN_ID": "Drug",
                    "VOCABULARY_ID": "ATC",
                    "CONCEPT_CLASS_ID": "ATC 4th"
                  },
                  "isExcluded": false,
                  "includeDescendants": true,
                  "includeMapped": false
                }
              ]
            }
          },
          {
            "id": 1,
            "name": "[1401] B01AE - Direct Thrombin",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 21601019,
                    "CONCEPT_NAME": "Direct thrombin inhibitors",
                    "STANDARD_CONCEPT": "C",
                    "STANDARD_CONCEPT_CAPTION": "Classification",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "B01AE",
                    "DOMAIN_ID": "Drug",
                    "VOCABULARY_ID": "ATC",
                    "CONCEPT_CLASS_ID": "ATC 4th"
                  },
                  "isExcluded": false,
                  "includeDescendants": true,
                  "includeMapped": false
                }
              ]
            }
          },
          {
            "id": 2,
            "name": "[1401] B01AF - Factor Xa",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 43534760,
                    "CONCEPT_NAME": "Direct factor Xa inhibitors",
                    "STANDARD_CONCEPT": "C",
                    "STANDARD_CONCEPT_CAPTION": "Classification",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "B01AF",
                    "DOMAIN_ID": "Drug",
                    "VOCABULARY_ID": "ATC",
                    "CONCEPT_CLASS_ID": "ATC 4th"
                  },
                  "isExcluded": false,
                  "includeDescendants": true,
                  "includeMapped": false
                }
              ]
            }
          }
        ],
        "QualifiedLimit": {
          "Type": "First"
        },
        "ExpressionLimit": {
          "Type": "First"
        },
        "InclusionRules": [],
        "CensoringCriteria": [],
        "CollapseSettings": {
          "CollapseType": "ERA",
          "EraPad": 0
        },
        "CensorWindow": {}
      }
    },
    {
      "id": 3900,
      "name": "[1401] Direct Thrombin",
      "expression": {
        "PrimaryCriteria": {
          "CriteriaList": [
            {
              "DrugExposure": {
                "CodesetId": 1,
                "DrugTypeExclude": false
              }
            }
          ],
          "ObservationWindow": {
            "PriorDays": 0,
            "PostDays": 0
          },
          "PrimaryCriteriaLimit": {
            "Type": "First"
          }
        },
        "ConceptSets": [
          {
            "id": 1,
            "name": "[1401] B01AE - Direct Thrombin",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 21601019,
                    "CONCEPT_NAME": "Direct thrombin inhibitors",
                    "STANDARD_CONCEPT": "C",
                    "STANDARD_CONCEPT_CAPTION": "Classification",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "B01AE",
                    "DOMAIN_ID": "Drug",
                    "VOCABULARY_ID": "ATC",
                    "CONCEPT_CLASS_ID": "ATC 4th"
                  },
                  "isExcluded": false,
                  "includeDescendants": true,
                  "includeMapped": false
                }
              ]
            }
          }
        ],
        "QualifiedLimit": {
          "Type": "First"
        },
        "ExpressionLimit": {
          "Type": "First"
        },
        "InclusionRules": [],
        "CensoringCriteria": [],
        "CollapseSettings": {
          "CollapseType": "ERA",
          "EraPad": 0
        },
        "CensorWindow": {}
      }
    },
    {
      "id": 3901,
      "name": "[1401] Vitamin K",
      "expression": {
        "PrimaryCriteria": {
          "CriteriaList": [
            {
              "DrugExposure": {
                "CodesetId": 0,
                "DrugTypeExclude": false
              }
            }
          ],
          "ObservationWindow": {
            "PriorDays": 0,
            "PostDays": 0
          },
          "PrimaryCriteriaLimit": {
            "Type": "First"
          }
        },
        "ConceptSets": [
          {
            "id": 0,
            "name": "[1401] B01AA - Vitamin K",
            "expression": {
              "items": [
                {
                  "concept": {
                    "CONCEPT_ID": 21600962,
                    "CONCEPT_NAME": "Vitamin K antagonists",
                    "STANDARD_CONCEPT": "C",
                    "STANDARD_CONCEPT_CAPTION": "Classification",
                    "INVALID_REASON": "V",
                    "INVALID_REASON_CAPTION": "Valid",
                    "CONCEPT_CODE": "B01AA",
                    "DOMAIN_ID": "Drug",
                    "VOCABULARY_ID": "ATC",
                    "CONCEPT_CLASS_ID": "ATC 4th"
                  },
                  "isExcluded": false,
                  "includeDescendants": true,
                  "includeMapped": false
                }
              ]
            }
          }
        ],
        "QualifiedLimit": {
          "Type": "First"
        },
        "ExpressionLimit": {
          "Type": "First"
        },
        "InclusionRules": [],
        "CensoringCriteria": [],
        "CollapseSettings": {
          "CollapseType": "ERA",
          "EraPad": 0
        },
        "CensorWindow": {}
      }
    }
  ],
  "combinationWindow": 0,
  "minCellCount": 0,
  "maxDepth": 5,
  "allowRepeats": false
}

**Comment by chrisknoll** [comment]
Sorry for the late response (very late, 18 months, yikes) but after doing a lot of refinement on pathway analsyis since this was reported, I thought it time to look back at the open issues and I found this one:

I do not believe that this is a bug:  the logic of your Target cohort looks for any of those 3 exposures, but you also have to have 365d prior observation in addition to other prior conditions, while your event cohorts only look for the the specific exposure, with zero continuous observation (or prior condition).

This means that, in a patient timeline, you only allow cohort entry after 365d of continuous observation, but any of your event cohorts could occur before day 365 of the patient timeline.  Therefore, those event cohorts will not appear in the pathway analysis because they occur prior to cohort entry (pathway analysis only shows those cohort events that happen within the target cohort's start and end date.

The way to get your event cohorts to match, is that you have to add logic to your event cohort that assert your target cohort's logic occurs prior to your event cohort's entry.  That way, all your event cohorts will guarantee that your target cohort's population is covered.
