### ISSUE TITLE
Can't cancel generation of cohort definition

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/WebAPI#889]
Returns 403 error - http://localhost:8080/WebAPI/cohortdefinition/4/cancel/110k

**Comment by pavgra** [comment]
Seems like `cohortdefinition:*:cancel:%s:get` from `WebAPI\src\main\resources\db\migration\postgresql\V2.7.0.20190214145000__permissions-fixes-3.sql` wasn't reflected in `AtlasSecurity` -> `sourcePermissionTemplates`
