### ISSUE TITLE
Concept record count fails to load

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/WebAPI#901]
This appears to be related to #892 since I've found that calls to retrieve the concept record count for sources with a priorty == 0 fails initially. Once the value is then added to the cache, the service call works properly.

**Comment by chrisknoll** [comment]
Can you describe "fails initially"?

**Comment by anthonysena** [comment]
The first time this endpoint is called:

`WebAPI/cdmresults/<source>/conceptRecordCount`

with payload: `["1503297"]`

This is the error: [conceptRecordCount.txt](https://github.com/OHDSI/WebAPI/files/2927640/conceptRecordCount.txt). 

The next call using the same payload returns the expected result of the RC/DRC for the concept in that source. 

I haven't had an opportunity to debug but suspect the problem is here: https://github.com/OHDSI/WebAPI/blob/master/src/main/java/org/ohdsi/webapi/service/CDMResultsService.java#L73

**Comment by anthonysena** [comment]
Also, this only seems to happen to sources that do not have the cache warmed so that's where I thought it could be related to #892.

**Comment by chrisknoll** [comment]
> Also, this only seems to happen to sources that do not have the cache warmed so that's where I thought it could be related to #892.

Reasonable assumption, but I wonder if this would happen if you went to the service directly when the app started up before warmcache jobs could finish?  This definitely was brought to the surface when we selectively warmed caches where priority > 0.  But , in that case, in our env where it was trying to warm 47 source caches, it was just hammering our sever (which I think the spring jobs let 10 jobs go at a time...so it was downloading the full recordcounts for the entire vocabularies 10-at-a-time in parallel...was just destroying the GC.

I was wondering if non-priority caches could be warmed sequentially (so only 1 at a time in a single job) while the priority ones get warmed in parallel jobs?
