### ISSUE TITLE
CCL_execution sql migration error in SQL Server

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/WebAPI#913]
![screenshot from 2019-03-06 13-26-44](https://user-images.githubusercontent.com/16149781/53856283-a13a8000-4014-11e9-97be-fe77bf5fe9f7.png)
The above constraint error occurs when migrating WebAPI tables

**Comment by chrisknoll** [comment]
Hi, @NEONKID , 
  This worries me because we run locally on SQLServer and did not experience this error.  What version of SqlServer are you running?

**Comment by NEONKID** [comment]
I am using SQL Server 2016. Detailed version information is as follows.
```
Microsoft SQL Server 2016 (RTM-GDR) (KB3210111) - 13.0.1728.2 (X64) Enterprise Edition
```

**Comment by chrisknoll** [comment]
Thank you.  I'm very worried that we didn't see this error before getting it merged into master. Thank you for providing a fix. I have a few backups on my local env at different schema version points, and I'll restore those old copies and try to apply the migrations to it to see if any errors arise.
