### ISSUE TITLE
heracles_vis_data_sequence not working in SQL Server

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/WebAPI#915]
When performing Heracles function in Cohort Definition, error that heracles_vis_data_sequence is wrong occurred.

**Comment by anthonysena** [comment]
From review on the WebAPI call: seems like only the Oracle flyway script contains the `heracles_vis_data_sequence`. However, the other DB platforms appear to have this sequence with a different name:

${ohdsiSchema}.heracles_visualization_data_sequence
SQL Server:
https://github.com/OHDSI/WebAPI/pull/791/files#diff-b1a203c15a8e75fcd7b6e35d768937c2R92
PostgreSQL:
https://github.com/OHDSI/WebAPI/pull/791/files#diff-6855c70dd24f5904f16ae05822915047R11

**Comment by chrisknoll** [comment]
For postgresql, there is a alter sequence to rename:

PostgreSQL: https://www.postgresql.org/docs/9.1/sql-altersequence.html
``` ALTER SEQUENCE name RENAME TO new_name ``` (it's not clear if you include the schema name here)

MSSQL actually doesn't seem to have a simple way to rename, so the approach here should be:
1. create new sequence 'heracles_vis_data_sequence' with the current value of the existing sequence 'heracles_visualization_data_sequence'
2. drop sequence 'heracles_visualization_data_sequence'

**Comment by anthonysena** [comment]
@NEONKID this is now fixed via #924 so I'm going to close this out. Thanks!
