### ISSUE TITLE
Heracles baseline reporting permission denied

### ISSUE THREAD

**Issue by NEONKID** [OHDSI/WebAPI#941]
![Screenshot from 2019-03-11 14-45-25](https://user-images.githubusercontent.com/16149781/54103122-8d28c100-440e-11e9-997d-aaab03c34178.png)

After cohort definition in Cohort Definition, full analysis was performed. I then click on the visualized result in the baseline, but I get an error saying that I do not have permission.

![Screenshot from 2019-03-11 14-47-46](https://user-images.githubusercontent.com/16149781/54103151-b2b5ca80-440e-11e9-92ac-fb4668370063.png)

The current permissions are as above.

**Comment by anthonysena** [comment]
Closed via #959.
