### ISSUE TITLE
Vocabulary search is not protected

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#945]
![image](https://user-images.githubusercontent.com/10010071/54134280-124fae00-43ee-11e9-91e6-d665a0a625c9.png)

\+

AtlasSecurity:
```
this.sourcePermissionTemplates.put("vocabulary:%s:search:post", "Search vocab on Source with SourceKey = %s");
```

**Comment by anthonysena** [comment]
Closed via #946
