### ISSUE TITLE
Error isn't sent while creating Incidence Rate

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/WebAPI#948]
Steps to reproduce:

1. Create new Incidence Rate
2. Press 'Save'
3. Return to Incidence Rates' list and ensure that yours IR wasn't created (probably due to issue with sequences in database)

ER:
error is sent to frontend

AR:
error isn't sent
![image](https://user-images.githubusercontent.com/38942654/54195343-7ac28c00-44cf-11e9-962c-cb9dab984389.png)

**Comment by anthonysena** [comment]
Closed via #953

**Comment by aklochkova** [comment]
https://github.com/OHDSI/WebAPI/pull/953 actually doesn't fix this problem.
The wrong behavior is when entity of IR wasn't created but we got "200" response from backend.

1. we receive from frontend a request to create a new IR
2. this entity is successfully created and the response is written with code "200" in servlet's output stream after which **this stream closes**
3. when we try to add permissions to newly created IR's entity we catch an error (due to problem with sequences, for example) but output stream is already closed (and successful code from p.2 lies in it) and it can't be reopened. So we got incorrect response code

I have no ideas how to fix it with current architecture

**Comment by aklochkova** [comment]
#953 actually doesn't fix this problem.
The wrong behavior is when entity of IR wasn't created but we got "200" response from backend.

we receive from frontend a request to create a new IR
this entity is successfully created and the response is written with code "200" in servlet's output stream after which this stream closes
when we try to add permissions to newly created IR's entity we catch an error (due to problem with sequences, for example) but output stream is already closed (and successful code from p.2 lies in it) and it can't be reopened. So we got incorrect response code
I have no ideas how to fix it with current architecture
