### ISSUE TITLE
Record Counts tab isn't shown

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/WebAPI#950]
If user doesn't have permissions for one of available datasources then RC tab is permanently showing 'loading'
![image](https://user-images.githubusercontent.com/38942654/54201659-41921800-44df-11e9-8db8-9b3f08eb5cc7.png)

Steps to reproduce:

1. open 'Search' tab
2. enter 'Aspirin' and open any concept (i.g. https://qaatlas.arachnenetwork.com/index.html#/concept/19082433)
3. go to 'Record Counts' tab

ER:
record counts are shown
AR:
there is a 403 error
![image](https://user-images.githubusercontent.com/38942654/54201170-08a57380-44de-11e9-98c7-fc8556540726.png)

**Comment by anthonysena** [comment]
Closed via #1492
