### ISSUE TITLE
Characterization failed on BigQuery

### ISSUE THREAD

**Issue by spbima** [OHDSI/WebAPI#951]
Characterization failed when executed on BigQuery with uncategorized SQLException

![bg-test-characterization](https://user-images.githubusercontent.com/804934/54201775-8d44c180-44df-11e9-964a-5fc77c65eed7.png)

Error text
[bq_execution_error.txt](https://github.com/OHDSI/WebAPI/files/2956907/bq_execution_error.txt)

**Comment by anthonysena** [comment]
Can you post the design for this characterization?

**Comment by spbima** [comment]
yes, sure - [bq_characterization_desing.txt](https://github.com/OHDSI/WebAPI/files/2957239/bq_characterization_desing.txt)

**Comment by anthonysena** [comment]
Thanks! I ran this same design in our environment against SQL Server PDW and did not encounter an error so seems isolated to BigQuery as you originally stated.
