### ISSUE TITLE
Cohort characterization - unable to import json code

### ISSUE THREAD

**Issue by jhardin29** [OHDSI/WebAPI#954]
### Expected behavior
Navigate to utilities in existing characterization, click export button, navigate to new characterization, utilities page, select import button (the one below the other one); json code should import and populate the characterization.
### Actual behavior
Json code is not imported and attached error appears. 
### Steps to reproduce behavior
Navigate to utilities in existing characterization, click export button, navigate to new characterization, utilities page, select import button (the one below the other one); in prod was trying to import characterization #222 into beta. 
### Related Issue
#1460 

![image](https://user-images.githubusercontent.com/11822115/54202132-c102f580-44a5-11e9-8d53-5e44373ff349.png)

**Comment by anthonysena** [comment]
@pavgra it also appears that there is a problem when generating a CC that contains a criteria_set statType. I'll dig into the details but also wanted to mention it here since it could be a related issue.
