### ISSUE TITLE
display a full user name instead of a login ID

### ISSUE THREAD

**Issue by johnSamilin** [OHDSI/WebAPI#963]
https://github.com/OHDSI/Atlas/issues/1289

### Proposal
Add a field `fullname` to `/me` endpoint response JSON.
Fill it for those A&A providers that can return a full user name, assing a value `null` otherwise.

**Comment by pavgra** [comment]
At least, we need to do this for AD, LDAP, custom DB and IAP authentication providers.

**Comment by ssuvorov-fls** [comment]
existing field "name" is now returned by server

**Comment by anemniugin** [comment]
In DB in table with users  you need to add new columns:
firstname (character varying)
middlename (character varying)
lastname (character varying)

**Comment by anemniugin** [comment]
test passed
