### ISSUE TITLE
Wrong name of sequence for heracles_visualization_data

### ISSUE THREAD

**Issue by ssuvorov-fls** [OHDSI/WebAPI#964]
Sequence "heracles_vis_data_sequence" in VisualizationData class must be renamed to "heracles_visualization_data_sequence". Now the sequence used in class differs from the sequence that is created by postgresql and ms sql scripts. Oracle script also must be changed

**Comment by chrisknoll** [comment]
You have it backwards: the sequence must be named 'hearacles_vis_data_sequence' because the value `heracles_visualization_data_sequence` is too long for oracle.   Oracle had the shorter name, and we recently renamed those sequences to `hearacles_vis_data_sequence` for postgresql and MSSQL to match.

**Comment by ssuvorov-fls** [comment]
could you give me a link to issue where these sequence were renamed?

**Comment by ssuvorov-fls** [comment]
sorry, found it

**Comment by ssuvorov-fls** [comment]
could you close my issue and pr, please
