### ISSUE TITLE
Problem with IAP authentication

### ISSUE THREAD

**Issue by spbima** [OHDSI/WebAPI#968]
For authentication is using IAP

The logging in window did not provide me with the option of entering email. I had to go to an incognito window to be able to enter my email. As seen on the screenshot below, I am asked to sign in, but I am unable to enter or select anything. 

![iap1](https://user-images.githubusercontent.com/804934/54372882-53192280-468d-11e9-8422-f532a1db9484.jpg)

For logging out, I am not sure if the option is supposed to exist, but I am not seeing it at the moment: 

![iap2](https://user-images.githubusercontent.com/804934/54372889-56aca980-468d-11e9-87f0-cb67af5a506d.jpg)

**Comment by pavgra** [comment]
Seems like the session is not automatically updated:
https://cloud.google.com/iap/docs/sessions-howto

### Clearing user login

The following URL clears the Cloud IAP login cookie:
YOUR_APP_URL/_gcp_iap/clear_login_cookie

**Comment by spbima** [comment]
fixed in 2.7.0 version
