### ISSUE TITLE
Check method for cohort defenition is returning 500 status

### ISSUE THREAD

**Issue by spbima** [OHDSI/WebAPI#973]
Using 2.5.3 version

![cohort-error2](https://user-images.githubusercontent.com/804934/54432449-44d51000-473a-11e9-98ba-76fc498d1415.jpg)

[cohort-error.txt](https://github.com/OHDSI/WebAPI/files/2971125/cohort-error.txt)

**Comment by wivern** [comment]
@spbima Could you attach design of Cohort? 
That would be very helpful to reproduce an error.

**Comment by aklochkova** [comment]
design of cohort: [cohort.txt](https://github.com/OHDSI/WebAPI/files/2978035/cohort.txt)

**Comment by anthonysena** [comment]
Closed via OHDSI/Atlas#1562
