### ISSUE TITLE
Pathways results take a long time to load

### ISSUE THREAD

**Issue by spbima** [OHDSI/WebAPI#984]
Pathways results take a long time to load (approximately 1 minute)

![pathway-long-time](https://user-images.githubusercontent.com/804934/54821532-7c503900-4cb3-11e9-89ab-f15457db9b16.jpg)

[pathway-long-time.txt](https://github.com/OHDSI/WebAPI/files/2996360/pathway-long-time.txt)

**Comment by chrisknoll** [comment]
Agreed. this is a 2.8 issue.  The core of the issue is that we are pulling patent-level pathways out of the database and procesisng pathways in memory. This needs to be summarized and stored in the DB and the report needs to just query a result table.
