### ISSUE TITLE
[2.5.3] Can't delete Incidence Rate

### ISSUE THREAD

**Issue by aklochkova** [OHDSI/WebAPI#987]
Steps to reproduce:
Create new Incidence Rate and save it

ER:
Delete button is active

AR:
Delete button is disabled

**Comment by anthonysena** [comment]
@aklochkova - could you confirm that this is fixed in the v2.7.2 release and if so, close this issue? Thank you!

**Comment by aklochkova** [comment]
it doesn't reproduce in v.2.7.2
