### ISSUE TITLE
After restart Atlas trying to connect to someone else's Postgres

### ISSUE THREAD

**Issue by spbima** [OHDSI/WebAPI#994]
After restart Atlas docker container trying to connect to someone else's Postgres 54.209.111.128:5432

I can see in the Atlas log:
019-03-27 17:54:55.552 ERROR localhost-startStop-1 org.ohdsi.webapi.AuthDataSource -  - Failed to initialize connection to DB used for authentication: Failed to initialize pool: Connection to 54.209.111.128:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

After that, everything works, but it seems to me that this is wrong.

I found this IP in pom.xml
https://github.com/OHDSI/WebAPI/search?q=54.209.111.128&unscoped_q=54.209.111.128

Atlas version is 2.5.3

**Comment by leeevans** [comment]
@spbima are you using the broadsea-webtools docker container and docker compose?

The below docker-compose.yml file is an example of overriding the datasource_url environment variable (and other db connection vars) with your own database connection info:

https://github.com/OHDSI/Broadsea/blob/master/postgresql/docker-compose.yml

If you are using docker-compose and do a "docker stop" and "docker start" I would have expected the container to remember the values of the environment variables from your docker-compose.yml file.

**Comment by anthonysena** [comment]
@spbima I'm going to assume this is closed but if the problem persists, please re-open and provide the information requested by @leeevans. Thanks!
