### ISSUE TITLE
Source diamon priority fixes

### ISSUE THREAD

**Issue by pavgra** [OHDSI/WebAPI#997]
### Actual
1. Create source in freshly deployed Atlas
2. Observe that priority checkbox for the source is selected in Configuration screen while its actual priority is 0 (in database)

### Expected
- First source should get priority = 1
- Source diamon with priority = 0 should never be shown as selected in Configuration screen

**Comment by pavgra** [comment]
@ssuvorov-fls , what about UI changes for the second item in the Expected section?

**Comment by ssuvorov-fls** [comment]
If source daimon with priority == 0 wil be hided, the we won't be able to edit it. Is it correct behavior?

**Comment by pavgra** [comment]
Where have you found the requirement for diamon to be _hidden_?
